### ISSUE TITLE
[BUG]JSONObject.to(Clazz) 格式化出错

### ISSUE THREAD

**Issue by kanyways** [alibaba/fastjson2#1001]
### 问题描述
```js
{"name":"hello","values":{"score":[111,222,333],"classes":["语文","数学","英语"]}}
```
目前有个这样的数据结构，需要转换成Java对象。
采用JSONObject.to()方法，报错`com.alibaba.fastjson2.reader.ObjectReaderImplObject`
但是采用 `JSONObject.parseObject(text,Clazz)` 却正常。
会解析成：
![解析结果](https://user-images.githubusercontent.com/9895669/206176668-65c866a9-6708-43d2-b2bc-30a4510fa62b.png)

### 环境信息
 - OS信息：  Windows 10 专业版 21H2
 - JDK信息： Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
 - 版本信息：Fastjson2 2.0.19
 

### 重现步骤
```java
public class User {
        private String name;
        private Map<String, Object> values;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Map<String, Object> getValues() {
            return values;
        }

        public void setValues(Map<String, Object> values) {
            this.values = values;
        }
    }

    @Test
    public void TestFastjson2() {
        User user = new User();
        user.setName("hello");
        Map<String, Object> map = new HashMap<>();
        map.put("score", Arrays.asList(111, 222, 333));
        map.put("classes", Arrays.asList("语文", "数学", "英语"));
        user.setValues(map);

        String values = JSONObject.toJSONString(user);
        log.info(values);
        JSONObject jsonObject = JSONObject.parseObject(values);
        User temp = jsonObject.to(User.class, JSONReader.Feature.SupportAutoType);
    }
```

### 相关日志输出
```bash
{"name":"hello","values":{"score":[111,222,333],"classes":["语文","数学","英语"]}}

java.lang.UnsupportedOperationException: com.alibaba.fastjson2.reader.ObjectReaderImplObject

	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:37)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.createInstance(ObjectReaderImplMapTyped.java:91)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1153)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:107)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1201)
	at cn.com.donson.project.doss.webservice.services.TestCRMService.TestFastjson2(TestCRMService.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.21-SNAPSHOT/
问题已经修复，请用最新快照版本2.0.21-SNAPSHOT版本帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.21
问题已修复，请用新版本
