### ISSUE TITLE
在安卓7.0下运行，发生找不到LocalTime异常，1.2.83版本无此问题

### ISSUE THREAD

**Issue by flyinmind** [alibaba/fastjson2#1005]
### 问题描述
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalTime;
at com.alibaba.fastjson2.writer.ObjectWriterProvider.<clinit>(ObjectWriterProvider.java:252)
at com.alibaba.fastjson2.JSONFactory.<clinit>(JSONFactory.java:354)
at com.alibaba.fastjson2.util.Fnv.hashCode64(Fnv.java:71)
at com.alibaba.fastjson2.JSONReader.<clinit>(JSONReader.java:32)
at com.alibaba.fastjson2.JSONReader.of(JSONReader.java:2796)
at com.alibaba.fastjson2.JSON.parseObject(JSON.java:216)

### 环境信息
 - OS信息：  Android 7.0
 - JDK信息：AndroidStudio/jdk1.8
 - 版本信息：fastjson2-2.0.20.android.jar
 

### 重现步骤
*如何操作可以重现该问题：*
```java
 JSON.parseObject(jsonStr, JSONReader.Feature.AllowUnQuotedFieldNames, JSONReader.Feature.UseNativeObject);
```

### 期待的正确结果
不发生异常

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
2.0.x目前只支持Android 8+
