### ISSUE TITLE
【BUG】json转Object日期格式yyyyMMddhhmmss出错

### ISSUE THREAD

**Issue by sadboy-cn** [alibaba/fastjson2#1015]
## 问题描述

```java
{"birthday":"20201028110419"}
```
将如上json转对象时，如果format=yyyyMMddhhmmss会报错，将hh改成HH时正常，大概是fastjson2的bug。

## 环境信息

* OS信息：Microsoft Windows 10 专业版
* JDK信息：1.8.0_261
* 版本信息：Fastjson2  2.0.21

## 重现步骤
正常情况：
```java
    @Test
    public void test(){
        String dateStr = "{\"birthday\":\"20201028110419\"}";
        Student student = com.alibaba.fastjson.JSON.parseObject(dateStr, Student.class);
        System.out.println(student.getBirthday());
    }
    @Data
    public static class Student{
        @com.alibaba.fastjson.annotation.JSONField(format = "yyyyMMddHHmmss")
        private Date birthday;
    }
```
结果：
![image](https://user-images.githubusercontent.com/34757726/207485813-cc2c2b35-9f06-4ea3-ba91-5072b20e369d.png)

【**异常情况**】将日期格式从yyyyMMddHHmmss修改为yyyyMMddhhmmss后出现错误：

```java
    @Test
    public void test(){
        String dateStr = "{\"birthday\":\"20201028110419\"}";
        Student student = com.alibaba.fastjson.JSON.parseObject(dateStr, Student.class);
        System.out.println(student.getBirthday());
    }
    @Data
    public static class Student{
        @com.alibaba.fastjson.annotation.JSONField(format = "yyyyMMddhhmmss")
        private Date birthday;
    }
```
结果：
![image](https://user-images.githubusercontent.com/34757726/207486254-ae79457f-3757-45c9-a8b9-5a7a73b9d6e5.png)

【**异常情况**】同样，将包名从com.alibaba.fastjson切换到com.alibaba.fastjson2也是一样的错误：

```java
    @Test
    public void test(){
        String dateStr = "{\"birthday\":\"20201028110419\"}";
        Student student = com.alibaba.fastjson2.JSON.parseObject(dateStr, Student.class);
        System.out.println(student.getBirthday());
    }
    @Data
    public static class Student{
        @com.alibaba.fastjson2.annotation.JSONField(format = "yyyyMMddhhmmss")
        private Date birthday;
    }
```
结果：
![image](https://user-images.githubusercontent.com/34757726/207486363-b53da57d-cd34-4f76-bd9e-5deb98dbbdfe.png)

## 期待的正确结果
根据查文档[自定义日期和时间格式字符串](https://learn.microsoft.com/zh-cn/dotnet/standard/base-types/custom-date-and-time-format-strings)，hh和HH分别代表12小时制和24小时制。测试fastjson1（1.2.83）支持这两种格式，希望fastjson2也支持hh格式。

## 相关日志输出
```
java.time.format.DateTimeParseException: Text '20201028110419' could not be parsed: Unable to obtain LocalDateTime from TemporalAccessor: {MicroOfSecond=0, MilliOfSecond=0, HourOfAmPm=11, SecondOfMinute=19, NanoOfSecond=0, MinuteOfHour=4},ISO resolved to 2020-10-28 of type java.time.format.Parsed

	at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:1920)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1855)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readDate(ObjectReaderImplDate.java:131)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readObject(ObjectReaderImplDate.java:69)
	at com.alibaba.fastjson2.reader.ObjectReader_4.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:601)
	at net.polyv.live.v1.service.chat.LiveChatRoomServiceImplTest.test(LiveChatRoomServiceImplTest.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.time.DateTimeException: Unable to obtain LocalDateTime from TemporalAccessor: {MicroOfSecond=0, MilliOfSecond=0, HourOfAmPm=11, SecondOfMinute=19, NanoOfSecond=0, MinuteOfHour=4},ISO resolved to 2020-10-28 of type java.time.format.Parsed
	at java.time.LocalDateTime.from(LocalDateTime.java:461)
	at java.time.format.Parsed.query(Parsed.java:226)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	... 28 more
Caused by: java.time.DateTimeException: Unable to obtain LocalTime from TemporalAccessor: {MicroOfSecond=0, MilliOfSecond=0, HourOfAmPm=11, SecondOfMinute=19, NanoOfSecond=0, MinuteOfHour=4},ISO resolved to 2020-10-28 of type java.time.format.Parsed
	at java.time.LocalTime.from(LocalTime.java:409)
	at java.time.LocalDateTime.from(LocalDateTime.java:457)
	... 30 more
```

**Comment by wenshao** [comment]
12小时制要提供AM/PM信息才能正确读取，什么场景？

**Comment by sadboy-cn** [comment]
> 12小时制要提供AM/PM信息才能正确读取，fastsjon1使用SimpleDateFormat实现，SimpleDateFormat不严谨，所以不报错。java.time.DateTimeFormatter是严谨的，所以报错了。你这个什么场景？

了解。我们的使用场景是将API封装成SDK提供出去，我们使用上没有问题，改成yyyy-MM-dd HH:mm:ss就行。

如果要使用yyyy-MM-dd hh:mm:ss接收，如何去标识上午下午？
以下午1点为例，2022-12-14 13:00:00，api返回的字符串应该为2022-12-14 01:00:00PM?formate应该为yyyy-MM-dd hh:mm:sstt?
还是API返回必须是2022-12-14 13:00:00，然后formate为yyyy-MM-dd HH:mm:ss接收？

**Comment by wenshao** [comment]
```
Dec 17, 2022 10:55:19 AM
```
如上的日期，需要配置的format是
```
MMM dd, yyyy hh:mm:ss a
```
H12的format要和a搭配使用

**Comment by sadboy-cn** [comment]
> ```
> Dec 17, 2022 10:55:19 AM
> ```
> 
> 如上的日期，需要配置的format是
> 
> ```
> MMM dd, yyyy hh:mm:ss a
> ```
> 
> H12的format要和a搭配使用，hh如果不搭配a，可以认为是个不合法的日期格式

我使用如下代码能测试跑通，理解了，感谢回复！！！
```java
    @Test
    public void test(){
        String dateStr = "{\"birthday\":\"20201028010419PM\"}";
        Student student = com.alibaba.fastjson.JSON.parseObject(dateStr, Student.class);
        System.out.println(student.getBirthday());
    }
    
    @Data
    public static class Student{
        @com.alibaba.fastjson.annotation.JSONField(format = "yyyyMMddhhmmssa")
        private Date birthday;
    } 
```

**Comment by Pruney-Che-Che** [comment]
``java
    @Data
    public static class Student{
        @com.alibaba.fastjson.annotation.JSONField(format = "yyyyMMddhhmmssa")
        private Date birthday;
    } 
这里包是不是引错了，换成2还兼容吗

**Comment by sadboy-cn** [comment]
> ``java @DaTa public static class Student{ @com.alibaba.fastjson.annotation.JSONField(format = "yyyyMMddhhmmssa") private Date birthday; } 这里包是不是引错了，换成2还兼容吗

看起来当时是使用fastjson1版本测试的示例代码。由于过了几年不太记得当时的场景了

我重新跑了下fastjson 2.0.53 和当时记录的 2.0.21 版本，都出现异常（fastjson包改成了fastjson2）。通过查询文档，应该是中文环境下不能使用PM，而应该使用下午进行表示。跑通示例如下：

`import java.util.Date;

public class Main {
    public static void main(String[] args) {
        String dateStr = "{\"birthday\":\"20201028010419下午\"}";
        Student student = com.alibaba.fastjson2.JSON.parseObject(dateStr, Student.class);
        System.out.println(student.getBirthday());
        System.out.println("Hello world!");
    }
   
    public static class Student{
        @com.alibaba.fastjson2.annotation.JSONField(format = "yyyyMMddhhmmssa")
        private Date birthday;
        
        public Date getBirthday() {
            return birthday;
        }
        
        public void setBirthday(Date birthday) {
            this.birthday = birthday;
        }
    }
}
`

根据【[wenshao](https://github.com/wenshao)】回复中的提示，使用 DateTimeFormatter 测试，确实可以指定语言环境。查询文档未找到 fastjson2 中如何指定语言，如果找到，可以同步下。DateTimeFormatter 测试代码如下：

`
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

public class Main2 {
    
    public static void main(String[] args) {
        DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss a");
        String dateTimeStr1 = "2020-10-28 01:04:19 下午";
        LocalDateTime dateTime1 = LocalDateTime.parse(dateTimeStr1, formatter1);
        System.out.println(dateTime1);
        
        DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss a", Locale.ENGLISH);
        String dateTimeStr2 = "2020-10-28 01:04:19 PM";
        LocalDateTime dateTime2 = LocalDateTime.parse(dateTimeStr2, formatter2);
        System.out.println(dateTime2);
    }
}
`
