### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yangxudong** [alibaba/fastjson2#1018]
### 问题描述
*简要描述您碰到的问题。*
JSONPath.eval(jsonStr, "$.data.plan.targets[*].set_points[0]") 在阿里云flink平台上执行报错，如下：

Caused by: com.alibaba.fastjson2.JSONException: TODO
  at com.alibaba.fastjson2.JSONPathSegment$AllSegment.accept(JSONPathSegment.java:962)
  at com.alibaba.fastjson2.JSONPathMulti.extract(JSONPathMulti.java:298)
  at com.alibaba.fastjson2.JSONPath.extract(JSONPath.java:50)
  at com.alibaba.fastjson2.JSONPath.eval(JSONPath.java:60)

在本地执行是ok的。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.21]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSONPath.eval` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/
问题已修复，请帮忙用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
