### ISSUE TITLE
[BUG]通过将包含枚举值的JSONObject转为Bean，抛出异常

### ISSUE THREAD

**Issue by yhl452493373** [alibaba/fastjson2#1031]
### 问题描述
通过将包含枚举值的JSONObject转为Bean，抛出异常

### 环境信息
*请填写以下信息：*

 - OS信息：  macOS 13.1，64G，i9 10980HK
 - JDK信息： 1.8
 - 版本信息：2.0.21
 

### 重现步骤
执行以下代码，使用JSON.parseObject没问题，serializeUsing和deserializeUsing也都执行了。
但是，先将实体转为JSON字符串，然后将其转为JSONObject，最后调用该JSONObject的toJavaObject会抛异常，同时deserializeUsing也并未执行

```java
import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.reader.ObjectReader;
import com.alibaba.fastjson2.writer.ObjectWriter;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Type;

/**
 * @author yanghuanglin
 * @since 2022/12/22
 */
public class FastJsonTest {
    static class TestBean {
        @JSONField(serializeUsing = TestEnum.Writer.class, deserializeUsing = TestEnum.Reader.class)
        private TestEnum testEnum;

        public TestEnum getTestEnum() {
            return testEnum;
        }

        public void setTestEnum(TestEnum testEnum) {
            this.testEnum = testEnum;
        }
    }

    enum TestEnum {
        ENUM_ONE("枚举1", 3),
        ENUM_TWO("枚举2", 2),
        ENUM_THREE("枚举3", 1);
        private String name;
        private Integer value;

        TestEnum(String name, Integer value) {
            this.name = name;
            this.value = value;
        }

        public String getName() {
            return name;
        }

        public Integer getValue() {
            return value;
        }

        public static TestEnum ofValue(Integer value) {
            for (TestEnum enumConstant : TestEnum.class.getEnumConstants()) {
                if (enumConstant.getValue().equals(value))
                    return enumConstant;
            }
            return null;
        }

        public static class Writer implements ObjectWriter<TestEnum> {

            @Override
            public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
                TestEnum testEnum = (TestEnum) object;
                jsonWriter.writeInt32(testEnum.getValue());
            }
        }

        public static class Reader implements ObjectReader<TestEnum> {
            @Override
            public TestEnum readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
                Integer value = jsonReader.readInt32();
                return TestEnum.ofValue(value);
            }
        }
    }

    @Test
    public void fastjsonTest() {
        TestBean testBean = new TestBean();
        testBean.setTestEnum(TestEnum.ENUM_ONE);
        String testBeanString = JSON.toJSONString(testBean);

        //正常
        TestBean testBeanFromString = JSON.parseObject(testBeanString, TestBean.class);

        JSONObject testBeanJSON = JSON.parseObject(testBeanString);

        //异常
        TestBean testBeanFromJSONObject = testBeanJSON.toJavaObject(TestBean.class);
    }
}

```

### 期待的正确结果
不抛错，且枚举序列化和反序列化的结果正常

### 相关日志输出
```
com.alibaba.fastjson2.JSONException: No enum ordinal com.cdhncy.cemis.screen.FastJsonTest.TestEnum.3

	at com.alibaba.fastjson2.reader.ObjectReaderImplEnum.getEnumByOrdinal(ObjectReaderImplEnum.java:69)
	at com.alibaba.fastjson2.util.TypeUtils.cast(TypeUtils.java:1268)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:117)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1210)
	at com.alibaba.fastjson2.JSONObject.toJavaObject(JSONObject.java:1220)
	at com.cdhncy.cemis.screen.FastJsonTest.fastjsonTest(FastJsonTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)log
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/
问题已经修复，请用2.0.22-SNAPSHOT版本验证，2.0.22版本在元旦期间发布

**Comment by yhl452493373** [comment]
OK了，感谢
