### ISSUE TITLE
[BUG]使用JSONObject反序列化为对象时，属性中的JSONArray未能正确反序列化

### ISSUE THREAD

**Issue by cnscoo** [alibaba/fastjson2#1038]
### 环境信息
 - OS信息：  Windows11 Home
 - JDK信息： OracleJDK 17.0.5
 - 版本信息：Fastjson2 2.0.21
 

### 重现步骤

目标对象

```kotlin
class AuthUser : Serializable {
    var username: String? = null
    var password: String? = null
    var avatar: String? = null
    var nickname: String? = null
    var gender: Int? = null
    var mobile: String? = null
    var email: String? = null
    var status: Int? = null
    var deleted: Boolean = false
    var roles: Set<String>? = null
    var auths: Set<String>? = null
    var setting: JSONObject? = null
}
```

执行代码，报错

```kotlin
val json = "{\"id\":1,\"username\":\"user\",\"password\":\"123\",\"nickname\":\"用户\",\"gender\":1,\"mobile\":\"13000000000\",\"email\":\"abc@qq.com\",\"status\":1,\"deleted\":false,\"create_time\":\"2020-11-30 22:12:58.0\",\"update_time\":\"2020-11-30 22:13:01.0\",\"roles\":[\"ADMIN\"]}"
val user = JSONObject.parseObject(json).to<AuthUser>()  // 错误: set roles error
```

堆栈信息

```
Request processing failed: com.alibaba.fastjson2.JSONException: set roles error

java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at com.alibaba.fastjson2.reader.FieldReaderObject.accept(FieldReaderObject.java:264) ~[fastjson2-2.0.21.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstructor.createInstance(ObjectReaderNoneDefaultConstructor.java:450) ~[fastjson2-2.0.21.jar:na]
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1210) ~[fastjson2-2.0.21.jar:na]
```

但如果直接从json字符串反序列化，则不会有任何问题

```kotlin
val json = "{\"id\":1,\"username\":\"user\",\"password\":\"123\",\"nickname\":\"用户\",\"gender\":1,\"mobile\":\"13000000000\",\"email\":\"abc@qq.com\",\"status\":1,\"deleted\":false,\"create_time\":\"2020-11-30 22:12:58.0\",\"update_time\":\"2020-11-30 22:13:01.0\",\"roles\":[\"ADMIN\"]}"
val user = json.to<AuthUser>()   // 成功
```

### 期待结果

JSONObject 对象中的 JSONArray 属性能正确反序列化为相关对象。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/

问题已经修复，请用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
