### ISSUE TITLE
[BUG] Map的value为Path类型，调用JSONObject的toJSONString时报错StackOverflowError

### ISSUE THREAD

**Issue by mayu1991** [alibaba/fastjson2#1040]
### 问题描述
*简要描述您碰到的问题。*
发现Map里的对象如果是Path类型，调用JSONObject的toJSONString时会报错StackOverflowError

### 环境信息
*请填写以下信息：*

 - OS信息：  centos 7.5，其实本机window测试也出现
 - JDK信息： [e.g.：Openjdk 11.0.5]
 - 版本信息：[e.g.：Fastjson2 2.0.21]
 

### 重现步骤
本地测试可以重现
```java
    Map<String, Object> ext = new HashMap<>();
    ext.put("test1", Path.of("/usr/bin"));
    System.out.println(JSONObject.toJSONString(ext));
```

### 期待的正确结果
升级fastjson2之后才出现的问题。
当然把path toString一下就可以解决了，只是确认下这个是不是问题。

### 相关日志输出
报错日志：
java.lang.StackOverflowError
	at java.base/java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:73)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.alibaba.fastjson2.writer.FieldWriterObjectMethod.getFieldValue(FieldWriterObjectMethod.java:27)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:156)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
	at com.alibaba.fastjson2.writer.ObjectWriter6.write(ObjectWriter6.java:90)
.....

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
是BUG，请帮忙看下这个Path是哪个package下的？我好尽快修复

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/

问题已经修复，请用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
