### ISSUE TITLE
[BUG]fastjson2 将日期格式的String(yyyy-MM-dd HH:mm:ss)反序列化成Long类型出错（但是fastjson1可以）

### ISSUE THREAD

**Issue by ligoudaner** [alibaba/fastjson2#1060]
### 问题描述
fastjson2 将日期格式的String(yyyy-MM-dd HH:mm:ss)反序列化成Long类型出错（但是fastjson1可以）

### 环境信息
*请填写以下信息：*

 - OS信息：  macOS
 - JDK信息： jdk8
 - 版本信息：2.0.22
 

### 重现步骤
*如何操作可以重现该问题：*

运行下述代码即可
```java
import com.alibaba.fastjson.JSON;
import lombok.Data;

import java.io.Serializable;

public class DemoApplication {

    public static void main(String[] args) {
        String str = "{\"createTime\":\"2023-01-09 15:38:13\"}";
        BizDTO bizDTO = JSON.parseObject(str, BizDTO.class);
        System.err.println("createTime=" + bizDTO.getCreateTime());
    }

    @Data
    public static class BizDTO implements Serializable {
        private Long createTime;
    }
}
```

### 期待的正确结果
createTime=1673249893000

### 相关日志输出
Exception in thread "main" com.alibaba.fastjson.JSONException: parseLong error, value : -01-09 15:38:13
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:517)
	at com.fintek.mx.market.user.DemoApplication.main(DemoApplication.java:12)
Caused by: com.alibaba.fastjson2.JSONException: parseLong error, value : -01-09 15:38:13
	at com.alibaba.fastjson2.JSONReader.toInt64(JSONReader.java:2504)
	at com.alibaba.fastjson2.JSONReader.getInt64(JSONReader.java:650)
	at com.alibaba.fastjson2.JSONReaderUTF16.readInt64(JSONReaderUTF16.java:2835)
	at com.alibaba.fastjson2.reader.ORG_1_1_BizDTO.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:507)
	... 1 more

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/
问题已修复，请用2.0.23版本帮忙验证，2.0.23版本预计在1月14日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
问题已经修复，请用新版本
