### ISSUE TITLE
[BUG]fastjson2序列化然后再反序列化出错

### ISSUE THREAD

**Issue by nadazero** [alibaba/fastjson2#1069]
### 问题描述
fastjson2序列化然后再反序列化出错，但类似的代码在fastjson1上运行正常

### 环境信息
*请填写以下信息：*
 - OS信息：  [e.g.：Redhat]
 - JDK信息： [e.g.：jdk 1.8.0_281]
 - 版本信息：[e.g.：Fastjson2 2.0.22]
 
### 重现步骤

代码如下，可以直接运行，运行到最后会出错
```java
import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class Main {
    public static void main(String[] args) {
        UserAttrActionInfo userAttrActionInfo1 = new UserAttrActionInfo();
        Map<Integer, List<Long>> map = new LinkedHashMap<>();
        List<Long> list = new ArrayList<>();
        list.add(1L);
        list.add(2L);
        list.add(3L);
        list.add(4L);
        map.put(1234, list);
        userAttrActionInfo1.tagInfos = map;

        //序列化然后再反序列化会出错，但类似的代码在fastjson1上运行正常
        String strJson = JSON.toJSONString(userAttrActionInfo1, JSONWriter.Feature.WriteClassName);
        System.out.println("strJson=" + strJson);
        UserAttrActionInfo UserAttrActionInfo2 = JSON.parseObject(strJson, UserAttrActionInfo.class, JSONReader.Feature.SupportAutoType);

    }

    private static class UserAttrActionInfo {
        public Map<Integer, List<Long>> tagInfos;
        public UserAttrActionInfo() {}
    }
}
```
### 相关日志输出
Exception in thread "main" com.alibaba.fastjson2.JSONException: parseInt error, value : @type
	at com.alibaba.fastjson2.JSONReader.toInt32(JSONReader.java:2497)
	at com.alibaba.fastjson2.JSONReader.getInt32Value(JSONReader.java:565)
	at com.alibaba.fastjson2.JSONReaderUTF16.readInt32(JSONReaderUTF16.java:2575)
	at com.alibaba.fastjson2.reader.ObjectReaderImplInteger.readObject(ObjectReaderImplInteger.java:22)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1363)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:298)
	at com.alibaba.fastjson2.reader.ORG_1_1_UserAttrActionInfo.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:808)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/
问题已修复，请用2.0.23版本帮忙验证，2.0.23版本预计在1月14日前发布

**Comment by nadazero** [comment]
[fastjson2-2.0.23-20230112.011113-45.jar](https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/fastjson2-2.0.23-20230112.011113-45.jar)

验证此bug在以上2.0.23-SNAPSHOT版本上已修正

等2.0.23正式版本出了再做验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
问题已经修复，请用新版本
