### ISSUE TITLE
[BUG]mvn install -DskipTests出现编译错误

### ISSUE THREAD

**Issue by Tom-python0121** [alibaba/fastjson2#1077]
### 问题描述
*简要描述您碰到的问题。*
mvn install -DskipTests出现编译错误

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.23]
 

### 重现步骤
*如何操作可以重现该问题：*

mvn install -DskipTests
```java
//可在此输入示例代码
[root@bigdata spack-src]# java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.191-b12, mixed mode)
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
编译成功

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
```console
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] fastjson2                                                          [jar]
[INFO] fastjson2-extension                                                [jar]
[INFO] adapter                                                            [jar]
[INFO] fastjson2-benchmark                                                [jar]
[INFO] fastjson2-extension-spring5                                        [jar]
[INFO] example-spring-test                                                [jar]
[INFO] fastjson1-compatible                                               [jar]
[INFO] fastjson2-kotlin                                                   [jar]
[INFO] fastjson2-parent                                                   [pom]
[INFO]
[INFO] ------------------< com.alibaba.fastjson2:fastjson2 >-------------------
[INFO] Building fastjson2 2.0.23                                          [1/9]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-checkstyle-plugin:3.2.0:check (checkstyle) @ fastjson2 ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] fastjson2 2.0.23 ................................... FAILURE [  1.561 s]
[INFO] fastjson2-extension 2.0.23 ......................... SKIPPED
[INFO] adapter 2.0.23 ..................................... SKIPPED
[INFO] fastjson2-benchmark 2.0.23 ......................... SKIPPED
[INFO] fastjson2-extension-spring5 2.0.23 ................. SKIPPED
[INFO] example-spring-test 2.0.23 ......................... SKIPPED
[INFO] fastjson1-compatible 2.0.23 ........................ SKIPPED
[INFO] fastjson2-kotlin 2.0.23 ............................ SKIPPED
[INFO] fastjson2-parent 2.0.23-SNAPSHOT ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.946 s
[INFO] Finished at: 2023-01-16T11:16:53+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:check (checkstyle) on project fastjson2: Failed during checkstyle execution: Unable to find configuration file at location: src/checkstyle/fastjson2-checks.xml: Could not find resource 'src/checkstyle/fastjson2-checks.xml'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by Tom-python0121** [comment]
我在相关路径下可以找到相应配置文件呀
[root@bigdata checkstyle]# ls
fastjson2-checks.xml  presto-checks.xml

**Comment by wenshao** [comment]
```
./mvnw clean install
```
这样试试看

**Comment by Tom-python0121** [comment]
[root@bigdata spack-src]# ./mvnw clean install
Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:90)
        at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:76)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:72)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
