### ISSUE TITLE
[BUG]kotlin:2.0.23解析时NullPointerException

### ISSUE THREAD

**Issue by summersrest** [alibaba/fastjson2#1088]
### 问题描述
*简要描述您碰到的问题。*
kotlin1.8，使用fastjson2-kotlin:2.0.23解析Json字符串报空指针异常。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Android 11]
 - JDK信息： [e.g.：Openjdk 11.0.15]
 - 版本信息：[e.g.：kotlin:2.0.23]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `text.to<User>()` 方法
2. 输入 `"{\"id\":1,\"name\":\"李雷\"}"`  数据
3. 出现 `java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference` 错误
```java
val text = "{\"id\":1,\"name\":\"李雷\"}"
val data = text.to<User>()       //NullPointerException
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
 Process: com.sum.myapplication, PID: 28907
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.alibaba.fastjson2.util.Fnv.hashCode64(Fnv.java:101)
        at com.alibaba.fastjson2.reader.FieldReader.<init>(FieldReader.java:77)
        at com.alibaba.fastjson2.reader.FieldReaderObject.<init>(FieldReaderObject.java:38)
        at com.alibaba.fastjson2.reader.FieldReaderObjectParam.<init>(FieldReaderObjectParam.java:27)
        at com.alibaba.fastjson2.reader.FieldReaderInt32Param.<init>(FieldReaderInt32Param.java:11)
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaderParam(ObjectReaderCreator.java:1803)
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createObjectReaderWithCreator(ObjectReaderCreator.java:485)
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createObjectReader(ObjectReaderCreator.java:888)
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:950)
        at com.alibaba.fastjson2.JSON.parseObject(JSON.java:601)
        at com.sum.myapplication.MainActivity.onCreate$lambda$0(MainActivity.kt:25)
        at com.sum.myapplication.MainActivity.$r8$lambda$NwyEH9HlGk-y4Gyd_rUHsj64nLM(Unknown Source:0)
        at com.sum.myapplication.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:0)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

#### 附加信息
![image](https://user-images.githubusercontent.com/7820570/216007053-b0321bf4-bed9-4766-9556-0437e22f764d.png)

![image](https://user-images.githubusercontent.com/7820570/216006928-fe882d41-892c-49c2-b342-e8e6b01d23a4.png)

**Comment by summersrest** [comment]
低版本的fastjson是可以的，比如com.alibaba:fastjson:1.2.73，是可以正确解析的。

**Comment by wenshao** [comment]
User类的代码提供下？

**Comment by summersrest** [comment]
> 

在最后的截图有一起解出来
data class User(
       var id: Int,
       var name: String
)

**Comment by summersrest** [comment]
有了解决办法，导入kotlin-reflect以后不会报错了。
    implementation 'org.jetbrains.kotlin:kotlin-reflect:1.7.21'
这个是不是写文档的时候可以考虑标注强调一下，没用过这个库的人可能不知道这个情况。

**Comment by bingoIsCoder** [comment]
> 有了解决办法，导入kotlin-reflect以后不会报错了。 implementation 'org.jetbrains.kotlin:kotlin-reflect:1.7.21' 这个是不是写文档的时候可以考虑标注强调一下，没用过这个库的人可能不知道这个情况。

谢谢大佬，解决了我遇到的同样的问题

**Comment by l619534951** [comment]
> 有了解决办法，导入kotlin-reflect以后不会报错了。 implementation 'org.jetbrains.kotlin:kotlin-reflect:1.7.21' 这个是不是写文档的时候可以考虑标注强调一下，没用过这个库的人可能不知道这个情况。

兄弟你开了混淆优化吗？我一开混淆优化在真机上就会报这个错，在虚拟机上就没事，我换成jackson又正常

**Comment by philwu** [comment]
java也遇到这个问题怎么办？

**Comment by wenshao** [comment]
@philwu 加上kotlin-reflect依赖试试看

**Comment by philwu** [comment]
> @philwu 加上kotlin-reflect依赖试试看

不可以哦，一样的错误。

**Comment by kuaikaiyun** [comment]
【已解决】补一个洛阳铲
Kotlin下，有kotlin-reflect依赖，依然会报错误

我是加的有kotlin-reflect依赖，但是依然会报这个错误
但是我发现我的ProRes基类不会有问题
我对比发现，还有一种情况会出现这个问题：
当类有构造方法，但没有指定主构造方法，会出现这个错误

```
// 能够能够正常反序列化
public open class ProRes(
  var code: Int = 0,
  var msg: String = "",
  var showType: ShowTypeEnum = ShowTypeEnum.SILENT
):Serializable
```

```
// 会报错 Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
public open class ProDataRes<T:Any> : ProRes {

    constructor()
    constructor(...)
    ...

}
```

以上
供参考
