### ISSUE TITLE
[BUG] Fastjson2 2.0.23 在项目打包成 native-image 后进行反序列化JSON异常

### ISSUE THREAD

**Issue by wssy001** [alibaba/fastjson2#1093]
### 问题描述
升级 Fastjson2 至 2.0.23 后，使用 GraalVM 构建 Native-Image 后将 JSON 反序列化成 Java Bean 报错，提示 com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public xxxx.xxxx.xxxx.vo.LoginVO()

将 Fastjson2 降级至 2.0.21.graal 则正常。

### 环境信息
*请填写以下信息：*

 - OS信息：     Ubuntu 20.4.5 LTS under WSL2
 - JDK信息：    GraalVM 22.3.1 with  OpenJDK 19.0.2
 - 版本信息：  Fastjson2 2.0.23
 - Web 框架： SpringBoot 3.0.2
 

### 背景
项目中引入了Spring Security，需要自定义一个Filter用于登录，期间用到了一个反序列化操作

### 重现步骤

1. 启动项目
2. 调用 getFromBody() 方法

```java
private LoginVO getFromBody(HttpServletRequest request) {
        try {
            BufferedReader reader = request.getReader();
            StringBuilder builder = new StringBuilder();
            String line = reader.readLine();
            while (line != null) {
                builder.append(line);
                line = reader.readLine();
            }
            reader.close();
            String string = builder.toString();
            log.info("******UsernamePasswordLogInFilter.getFromBody：{}", string);
            return JSON.parseObject(string, LoginVO.class);
        } catch (Exception e) {
            e.printStackTrace();
            throw new AuthenticationServiceException("无法获取body中的用户登录信息");
        }
    }
```

### 期待的正确结果
getFromBody() 执行无报错 ，Fastjson2 反序列化正常

### 相关日志输出
2023-02-04T02:03:09.425+08:00  INFO 3816 --- [io-38080-exec-1] c.w.p.f.UsernamePasswordLogInFilter      : ******UsernamePasswordLogInFilter.getFromBody：{"login":"test1","password":"91a7adde5b0919d53ffb7dc7253f9f345c3c902a759fe5a2493c70abb7e25095"}
com.alibaba.fastjson2.JSONException: create instance error
        at com.alibaba.fastjson2.reader.ConstructorSupplier.get(ConstructorSupplier.java:37)
        at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance0(ObjectReaderAdapter.java:277)
        at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:324)
        at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:305)
        at com.alibaba.fastjson2.JSON.parseObject(JSON.java:603)
        at xxxx.xxxx.xxxx.filter.UsernamePasswordLogInFilter.getFromBody(UsernamePasswordLogInFilter.java:61)
        at xxxx.xxxx.xxxx.filter.UsernamePasswordLogInFilter.attemptAuthentication(UsernamePasswordLogInFilter.java:37)        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:351)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base@19.0.2/java.lang.Thread.run(Thread.java:1589)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public xxxx.xxxx.xxxx.vo.LoginVO()
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@19.0.2/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:73)
        at java.base@19.0.2/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:497)
        at java.base@19.0.2/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base@19.0.2/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:306)
        at java.base@19.0.2/java.lang.Class.newInstance(DynamicHub.java:684)
        at com.alibaba.fastjson2.reader.ConstructorSupplier.get(ConstructorSupplier.java:28)
        ... 64 more

#### 附加信息
暂无

**Comment by wssy001** [comment]
这个问题算是解决了，自从FastJson2把graalvm版本合到一起后，就出现了一些小问题，即便使用了tracing agent，仍然需要手动使用@RegisterReflectionForBinding标注
附一个解决示例：
```java
import org.springframework.aot.hint.annotation.RegisterReflectionForBinding;

@RegisterReflectionForBinding(LoginVO.class)
private LoginVO getFromBody(HttpServletRequest request) {
        try {
            BufferedReader reader = request.getReader();
            StringBuilder builder = new StringBuilder();
            String line = reader.readLine();
            while (line != null) {
                builder.append(line);
                line = reader.readLine();
            }
            reader.close();
            String string = builder.toString();
            log.info("******UsernamePasswordLogInFilter.getFromBody：{}", string);
            return JSON.parseObject(string, LoginVO.class);
        } catch (Exception e) {
            e.printStackTrace();
            throw new AuthenticationServiceException("无法获取body中的用户登录信息");
        }
    }
```
