### ISSUE TITLE
[QUESTION]带微秒的时间字符串反序列化失败

### ISSUE THREAD

**Issue by lylyxxg** [alibaba/fastjson2#1098]
java中，秒后小数点大于3位的字符串，如“**2023-02-07T00:02:15.1234+08:00**”，用JSON.parseObject反序列化成Date类型时，
1.1.15版本不报错可正常转换，1.2.83报错，如下：
_Exception in thread "main" com.alibaba.fastjson.JSONException: For input string: "2023-02-07T00:02:15.1234+08:00"
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:710)_
请问大佬，这个怎么解决

**Comment by wenshao** [comment]
可以帮忙用2.0.23验证下么？

**Comment by lylyxxg** [comment]
2.0.23转换也报错，错误信息：
_Exception in thread "main" java.time.format.DateTimeParseException: Text '2023-02-07T00:02:15.1234+08:00' could not be parsed at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readDate(ObjectReaderImplDate.java:135)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readObject(ObjectReaderImplDate.java:70)
	at com.alibaba.fastjson2.reader.ORG_1_1_Stu.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:507)
	at test.Test.main(Test.java:140)_

**Comment by lylyxxg** [comment]
2.0.23不报错，上面报错是因为加了 format = "yyyy-MM-dd HH:mm:ss.SSSS"
