### ISSUE TITLE
[BUG]从V1.2.76升级到V2.0.24提交带有Date类型(值为long类型)的数据报错date only support string input

### ISSUE THREAD

**Issue by Skqing** [alibaba/fastjson2#1125]
### 问题描述
*简要描述您碰到的问题。*
[BUG]从V1.2.76升级到V2.0.24提交带有Date类型(值为long类型)的数据报错date only support string input

### 环境信息
*请填写以下信息：*

 - OS信息：  windows10
 - JDK信息： Openjdk 1.8.0_301
 - 版本信息：Fastjson2 2.0.24，fastjson2-extension-spring5 2.0.24
 

### 重现步骤
使用android端提交的数据，android端并没有修改任何相关代码，服务端升级到2.0.24后客户端只要提交的对象包含Date类型的参数都提交失败

我尝试用代码去复现，但无法复现，因为客户端HTTP框架用的是第三方的，里面使用的是android里独有的org.json.JSONObject，目前只能在服务端捕捉到异常信息，

### 期待的正确结果
希望能1.0一样正常解析客户端提交的数据

### 相关日志输出

```java
rg.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: date only support string input; nested exception is com.alibaba.fastjson2.JSONException: date only support string input
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.readType(FastJsonHttpMessageConverter.java:110) ~[fastjson2-extension-spring5-2.0.23.jar:?]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.read(FastJsonHttpMessageConverter.java:77) ~[fastjson2-extension-spring5-2.0.23.jar:?]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:185) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:160) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.15.jar:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-embed-core-9.0.56.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.15.jar:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.56.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [spring-boot-actuator-2.6.3.jar:2.6.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.15.jar:5.3.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.15.jar:5.3.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: com.alibaba.fastjson2.JSONException: date only support string input
	at com.alibaba.fastjson2.JSONReaderUTF8.getStringLength(JSONReaderUTF8.java:4495) ~[fastjson2-2.0.24.jar:?]
	at com.alibaba.fastjson2.JSONReader.readMillisFromString(JSONReader.java:1151) ~[fastjson2-2.0.24.jar:?]
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readDate(ObjectReaderImplDate.java:164) ~[fastjson2-2.0.24.jar:?]
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readObject(ObjectReaderImplDate.java:70) ~[fastjson2-2.0.24.jar:?]
	at com.alibaba.fastjson2.reader.ORG_2_44_TravelNotes.readObject(Unknown Source) ~[?:?]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1280) ~[fastjson2-2.0.24.jar:?]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.readType(FastJsonHttpMessageConverter.java:108) ~[fastjson2-extension-spring5-2.0.23.jar:?]
	... 44 more
2023-02-19 16:40:40.314 [http-nio-8281-exec-4] DEBUG [org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters: 268] - Using 'application/json', given [*/*] and supported [application/json]
2023-02-19 16:40:40.314 [http-nio-8281-exec-4] DEBUG [org.springframework.core.log.LogFormatUtils.traceDebug: 119] - Writing [BaseResult(result=false, code=100, msg=参数格式错误：请检查参数格式, data=null)]
2023-02-19 16:40:40.315 [http-nio-8281-exec-4] DEBUG [org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException: 146] - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: date only support string input; nested exception is com.alibaba.fastjson2.JSONException: date only support string input]
```

#### 附加信息
实体类的赋值
![image](https://user-images.githubusercontent.com/1713001/219938305-dbcbd7ff-1989-42d3-939c-5d73b9ac5525.png)

**Comment by wenshao** [comment]
有办法看到输入的字符串是怎样的么？这个信息不是很方便诊断问题

**Comment by Skqing** [comment]
> 有办法看到输入的字符串是怎样的么？这个信息不够完整不好诊断问题所在

我想想办法

**Comment by wenshao** [comment]
能文本贴一下么，我手打一次如果输入错误就不好了

**Comment by wenshao** [comment]
还有就是：TravelNotes这个类的代码可以贴一下么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本帮忙验证，2.0.25版本预计在3月中旬发布。

**Comment by Skqing** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/ 问题已修复，请帮忙用2.0.25-SNAPSHOT版本帮忙验证，2.0.25版本预计在3月中旬发布。

目前测试还是不行，关键问题前端设置的日期值，在后台的interceptor里拿到的竟然是空的对象这个原因暂时还没找到，有可能是前端框架的问题，我还在找原因。

**Comment by Skqing** [comment]
客户端值的原因找到了，android里的序列化使用了org.json包里面的类，替换为fastjson2后得到了正确的值：
![image](https://user-images.githubusercontent.com/1713001/220004771-f81d29ad-2d34-4658-a728-f67e629467f9.png)

"locationTime":"2023-02-20 11:42:03.314"
能够正常提交了，所以问题是难道是因为两个JSON框架序列化不兼容导致的？

**Comment by Skqing** [comment]
https://github.com/getActivity/EasyHttp/issues/158
