### ISSUE TITLE
[BUG]DateTimeParseException: Text '2023-02-20 16:03:25' could not be parsed at index 2

### ISSUE THREAD

**Issue by sly-APalmCat** [alibaba/fastjson2#1138]
### 问题描述
*简要描述您碰到的问题。*
DateTimeParseException: Text '2023-02-20 16:03:25' could not be parsed at index 2
java.time.format.DateTimeParseException: Text '2023-02-20 16:03:25' could not be parsed at index 2
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[na:1.8.0_112]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_112]
	at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[na:1.8.0_112]
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readDate(ObjectReaderImplDate.java:135) ~[fastjson2-2.0.24.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readObject(ObjectReaderImplDate.java:70) ~[fastjson2-2.0.24.jar:na]

Date、LocalDateTime 数据类型返回反序列化时报的错，序列化未能执行

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson 2.0.24]
 

### 重现步骤
*如何操作可以重现该问题：*
![image](https://user-images.githubusercontent.com/70318337/220852765-668a31be-4075-4cb0-bbd9-cc7f0909bffa.png)

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
@Data
public class DateVO implements Serializable {

	@JSONField(format = "HH:mm:ss")
	private Date dateCus;

}

```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*![image](https://user-images.githubusercontent.com/70318337/220852680-28c06a02-a14d-4f09-be4c-bb0019104d5d.png)*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by sly-APalmCat** [comment]
希望可以根据 @JSONFeild 注解中format的优先执行，正确执行

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.25-SNAPSHOT/
问题已修复，请用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
