### ISSUE TITLE
[BUG] fastjson2 2.0.22序列化oom

### ISSUE THREAD

**Issue by yamikaze0** [alibaba/fastjson2#1165]
### 问题描述
序列化大对象 大小11k左右，偶发出现OOM，堆栈如下：
java.lang.OutOfMemoryError: null
	at com.alibaba.fastjson2.JSONWriterUTF16.writeChar(JSONWriterUTF16.java:852)
	at com.alibaba.fastjson2.writer.ObjectWriterImplCharacter.write(ObjectWriterImplCharacter.java:32)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:231)
	at com.alibaba.fastjson2.writer.OWG_7_12_Node.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:231)
	at com.alibaba.fastjson2.writer.OWG_3_5_G6Result.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_1_5_Result.write(Unknown Source)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1473)

### 环境信息
 - OS信息：  MacOS  Monterey 12.5.1
 - JDK信息： jdk1.8
 - 版本信息：fastjson2 2.0.22
 

### 重现步骤
序列化大对象即可

### 期待的正确结果
// 64M or 1G
maxArraySize = (context.features & LargeObject.mask) != 0 ? 1073741824 : 67108864;

期待能够正常序列化

### 相关日志输出
见前面堆栈

#### 附加信息
附加writeChar附加容量方法
```java
@Override
public void writeChar(char ch) {
    int minCapacity = chars.length + 8;
    if (minCapacity - chars.length > 0) {
        int oldCapacity = chars.length;
        int newCapacity = oldCapacity + (oldCapacity >> 1);
        if (newCapacity - minCapacity < 0) {
            newCapacity = minCapacity;
        }
        if (newCapacity - maxArraySize > 0) {
            throw new OutOfMemoryError();
        }

        // minCapacity is usually close to size, so this is a win:
        chars = Arrays.copyOf(chars, newCapacity);
    }
}
```

**Comment by yamikaze0** [comment]
int minCapacity = chars.length + 8; 
应修正为：
int minCapacity = this.off + 8;

**Comment by wenshao** [comment]
你可以帮忙提交Pull Request来修复这个问题么？

**Comment by yamikaze0** [comment]
> 你可以帮忙提交Pull Request来修复这个问题么？
已提交 https://github.com/alibaba/fastjson2/pull/1166

**Comment by wenshao** [comment]
JSONWriterUTF8#writeChar方法有同样的问题，你也帮忙一并提交PR解了吧？

同时建议补上单测，比如这种：
```java
public class Issue1165 {
    @Test
    public void testUTF16() {
        JSONWriter jsonWriter = JSONWriter.ofUTF16();
        for (int i = 0; i < 1_000_000; i++) {
            jsonWriter.writeChar(' ');
        }
        jsonWriter.close();
    }

    @Test
    public void testUTF8() {
        JSONWriter jsonWriter = JSONWriter.ofUTF8();
        for (int i = 0; i < 1_000_000; i++) {
            jsonWriter.writeChar(' ');
        }
        jsonWriter.close();
    }
}

```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
