### ISSUE TITLE
[BUG]JSONPath.extract解析异常

### ISSUE THREAD

**Issue by pysenic** [alibaba/fastjson2#1215]
scala 2.11
fastjson 2.0.23

测试代码
``` scala
object Test {

  def main(args: Array[String]): Unit = {

    val r =
      """
        |{"x":{},"message":"1"}
        |""".stripMargin

    println(JSONPath.extract(r, "$.x.y"))

  }
}

```
期望结果：null

Exception in thread "main" com.alibaba.fastjson2.JSONException: illegal fieldName input,, offset 9, character ,, line 2, column 10, fastjson-version 2.0.23

{"x":{},"message":"1"}

	at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:1053)
	at com.alibaba.fastjson2.JSONPathSegmentName.accept(JSONPathSegmentName.java:539)
	at com.alibaba.fastjson2.JSONPathTwoSegment.extract(JSONPathTwoSegment.java:188)
	at com.alibaba.fastjson.JSONPath.extract(JSONPath.java:73)
	at Test$.main(Test.scala:22)
	at Test.main(Test.scala)

以下写法结果都是null
```scala
object Test {

  def main(args: Array[String]): Unit = {

    val r =
      """
        |{"x":{},"message":"1"}
        |""".stripMargin

    println(JSONPath.eval(JSON.parseObject(r), "$.x.y"))

  }
}
```

```scala
object Test {

  def main(args: Array[String]): Unit = {

    val r =
      """
        |{"x":{},"message":"1"}
        |""".stripMargin

    println(JSONPath.eval(r, "$.x.y"))

  }
}

```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
