### ISSUE TITLE
[BUG] JSON.register(java.util.Date.class, ObjectReader<java.util.Date>); 无法生效

### ISSUE THREAD

**Issue by codefan** [alibaba/fastjson2#1225]
### 问题描述
 JSON.register(java.util.Date.class, ObjectReader<java.util.Date>) 无法生效 ； JSON.register(java.util.Date.class, ObjectWriter<java.util.Date>) 是可以生效的。

在做日期格式的到json转换时，需要添加时区信息，java.util.Date 用“"yyyy-MM-dd HH:mm:ss zzz"”格式导出时 默认的时区是 CST， fastjson2 读取时 报CST 时区找不大; 于是想用JSON.register 注册自己的读取类，但是不能成功。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows 11  4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_301]
 - 版本信息：[e.g.：Fastjson2 2.0.24]
 

### 重现步骤
`        // 自定义了 日期 类型的ObjectReader 和 ObjectWriter  发现下面的注册， 除了第一行 其他的都生效了
        JSON.register(java.util.Date.class, UtilDateSerializer.instance);
        JSON.register(java.sql.Date.class, SqlDateSerializer.instance);
        JSON.register(java.sql.Timestamp.class, SqlTimestampSerializer.instance);
        
        JSON.register(java.util.Date.class, UtilDateDeserializer.instance);
        JSON.register(java.sql.Date.class, SqlDateDeserializer.instance);
        JSON.register(java.sql.Timestamp.class, SqlTimestampDeserializer.instance);
`
 public static class JsonWithDateField implements Serializable {
        private java.util.Date  utilDate;
        private java.sql.Date  sqlDate;
        private java.sql.Timestamp  timestamp;
}

       JsonWithDateField jsonDate = new JsonWithDateField();

        String s = JSON.toJSONString(jsonDate);
        System.out.println(s);

        JsonWithDateField jsonDate2 = JSON.parseObject(s, JsonWithDateField.class);

        System.out.println(JSON.toJSONString(jsonDate2));

### 期待的正确结果

日期的 反序列化（ JSON.register(java.util.Date.class,） 能够生效。

### 相关日志输出
*Exception in thread "main" java.time.zone.ZoneRulesException: Unknown time-zone ID: CST
	at java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:272)
	at java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:227)
	at java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.time.ZoneId.of(ZoneId.java:411)
	at java.time.ZoneId.of(ZoneId.java:359)
	at com.alibaba.fastjson2.util.DateUtils.getZoneId(DateUtils.java:3275)
	at com.alibaba.fastjson2.JSONReaderUTF16.readZonedDateTimeX(JSONReaderUTF16.java:6425)
	at com.alibaba.fastjson2.JSONReader.readMillisFromString(JSONReader.java:1221)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readDate(ObjectReaderImplDate.java:164)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readObject(ObjectReaderImplDate.java:70)
	at com.alibaba.fastjson2.reader.ORG_1_3_JsonWithDateField.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:642)
	at com.centit.support.test.TestJsonIO.main(TestJsonIO.java:60)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
能提供下报错的日期输入文本么？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本，不需要注册自定义ObjectReader，内置直接支持CST时区

**Comment by codefan** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.25
> 问题已修复，请用新版本，不需要注册自定义ObjectReader，内置直接支持CST时区

非常感谢，如此之快的修复这个问题。 问题是注册自定义java.utilsDate.class 类型的 ObjectReader 能生效吗？
