### ISSUE TITLE
[BUG] 使用FastJsonHttpMessageConverter返回对象Response序列化报错

### ISSUE THREAD

**Issue by winson52u** [alibaba/fastjson2#1226]
### 问题描述
*简要描述您碰到的问题。*
configureMessageConverters添加FastJsonHttpMessageConverter输出包含实体对象为Null时出错。
WriterFeatures配置WriteNulls或者WriteMapNullValue时，NameFilter使用了SnakeCase会出现Could not write JSON: JSON#writeTo cannot serialize 'xxxxxx' to 'OutputStream'，
使用WriteNulls或者WriteMapNullValue时，不使用SnakeCase的NameFilter可正常输出。同时配置WriteNulls与SnakeCase的NameFilter时报错。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows 10 专业版 19045.2604 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 19.0.2]
 - 版本信息：[e.g.：Fastjson2 2.0.24] [fastjson2-extension-spring6 2.0.24][ springboot 3.0.3]
 
### 重现步骤
```
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        super.configureMessageConverters(converters);
        //使用fastJson来序列化
        converters.add(this.fastJsonConverter());
    }
public FastJsonHttpMessageConverter fastJsonConverter() {
        FastJsonHttpMessageConverter rtn = new FastJsonHttpMessageConverter();
        FastJsonConfig fastJsonConfig = new FastJsonConfig();
        fastJsonConfig.setWriterFeatures(JSONWriter.Feature.WriteNulls,JSONWriter.Feature.WriteMapNullValue,JSONWriter.Feature.WriteLongAsString);
        NameFilter snakeCaseNameFilter = NameFilter.of(PropertyNamingStrategy.SnakeCase);
        fastJsonConfig.setWriterFilters(snakeCaseNameFilter);
        fastJsonConfig.setReaderFeatures(SupportSmartMatch);
        fastJsonConfig.setDateFormat(null);
        rtn.setFastJsonConfig(fastJsonConfig);
        rtn.setDefaultCharset(StandardCharsets.UTF_8);
        List<MediaType> fastMediaTypes = new ArrayList<>();
        fastMediaTypes.add(MediaType.APPLICATION_JSON);
        rtn.setSupportedMediaTypes(fastMediaTypes);
        return rtn;
    }
--------Controller--------
 @RequestMapping("/test3")
    public CreateShortcutResponse test3() {
        CreateShortcutResponse response = new CreateShortcutResponse();
       response.setResultCode(1);
        return response;
    }
----Bean-----
public class BaseResponse {
    protected Integer resultCode;
    protected String resultMessage;
    public Integer getResultCode() {
        return this.resultCode;
    }

    public void setResultCode(Integer resultCode) {
        this.resultCode = resultCode;
    }
  public String getResultMessage() {
        return this.resultMessage;
    }

    public void setResultMessage(String resultMessage) {
        this.resultMessage = resultMessage;
    }
}

public class CreateShortcutResponse extends BaseResponse {
    private ShortcutModel shortcut;

    public ShortcutModel getShortcut() {
        return shortcut;
    }

    public CreateShortcutResponse setShortcut(ShortcutModel shortcut) {
        this.shortcut = shortcut;
        return this;
    }
}

public class ShortcutModel {
    private Long shortcutId;
    private Byte shortcutTypeId;
    private String shortcutName;
    public Long getShortcutId() {
        return shortcutId;
    }

    public ShortcutModel setShortcutId(Long shortcutId) {
        this.shortcutId = shortcutId;
        return this;
    }

    public Byte getShortcutTypeId() {
        return shortcutTypeId;
    }

    public ShortcutModel setShortcutTypeId(Byte shortcutTypeId) {
        this.shortcutTypeId = shortcutTypeId;
        return this;
    }

    public String getShortcutName() {
        return shortcutName;
    }

    public ShortcutModel setShortcutName(String shortcutName) {
        this.shortcutName = shortcutName;
        return this;
    }
}
```
### 期待的正确结果
```json
{"result_code":1,"result_message":null,"shortcut":null"}
```

### 相关日志输出
```
org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: JSON#writeTo cannot serialize 'BaseResponse{resultCode=1, resultMessage='null'}' to 'OutputStream'
	at com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:139) ~[fastjson2-extension-spring6-2.0.24.jar:na]
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:226) ~[spring-web-6.0.5.jar:6.0.5]
	at com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:83) ~[fastjson2-extension-spring6-2.0.24.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:297) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:194) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[tomcat-embed-core-10.1.5.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.5.jar:6.0.5]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.5.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.5.jar:6.0.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.5.jar:6.0.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
Caused by: com.alibaba.fastjson2.JSONException: JSON#writeTo cannot serialize 'BaseResponse{resultCode=1, resultMessage='null'}' to 'OutputStream'
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:2720) ~[fastjson2-2.0.24.jar:na]
	at com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:127) ~[fastjson2-extension-spring6-2.0.24.jar:na]
	... 41 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:201) ~[na:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
	at com.alibaba.fastjson2.writer.FieldWriterStringMethod.getFieldValue(FieldWriterStringMethod.java:25) ~[fastjson2-2.0.24.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:527) ~[fastjson2-2.0.24.jar:na]
	at com.alibaba.fastjson2.writer.OWG_3_8_ShortcutModel.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:622) ~[fastjson2-2.0.24.jar:na]
	at com.alibaba.fastjson2.writer.OWG_2_4_CreateShortcutResponse.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:2715) ~[fastjson2-2.0.24.jar:na]
	... 42 common frames omitted

```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
