### ISSUE TITLE
[BUG] JSON字符串无法解析 unclosed.str.lit u bug

### ISSUE THREAD

**Issue by toohandsome** [alibaba/fastjson2#1235]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息： win11
 - JDK信息： 1.8
 - 版本信息：2.0.25
 

### 重现步骤
 
```java

@Data
public class Traffic {
    private String key;
    private long cost;
    private long reqDate;
    private long respDate;
    private String direction;
    private String host;
    private String url;
    private int reqBodyLength;
    private int respBodyLength;
    private String method;
    private Map<String, String> requestHeaders= new HashMap<>();
    private Map<String, String> responseHeaders = new HashMap<>();
    private String requestBody;
    private String responseBody;
}


String body = "{"respDate":1678811192058,"reqBodyLength":19825,"direction":"down","responseBody":"<!DOCTYPE html>\r\n<!--STATUS OK-->\r\n<html>\r\n<head>\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n    <meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\r\n    <meta content=\"always\" name=\"referrer\">\r\n    <script src=\"https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/nocache/imgdata/seErrorRec.js\"></script>\r\n    <title>页面不存在_百度搜索</title>\r\n    <style data-for=\"result\">\r\n        body {color: #333; background: #fff; padding: 0; margin: 0; position: relative; min-width: 700px; font-family: Arial, 'Microsoft YaHei'; font-size: 12px }\r\n        p, form, ol, ul, li, dl, dt, dd, h3 {margin: 0; padding: 0; list-style: none }\r\n        input {padding-top: 0; padding-bottom: 0; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box } img {border: none; }\r\n        .logo {width: 117px; height: 38px; cursor: pointer }\r\n         #wrapper {_zoom: 1 }\r\n        #head {padding-left: 35px; margin-bottom: 20px; width: 900px }\r\n        .fm {clear: both; position: relative; z-index: 297 }\r\n        .btn, #more {font-size: 14px } \r\n        .s_btn {width: 95px; height: 32px; padding-top: 2px\9; font-size: 14px; padding: 0; background-color: #ddd; background-position: 0 -48px; border: 0; cursor: pointer }\r\n        .s_btn_h {background-position: -240px -48px }\r\n        .s_btn_wr {width: 97px; height: 34px; display: inline-block; background-position: -120px -48px; *position: relative; z-index: 0; vertical-align: top }\r\n        #foot {}\r\n        #foot span {color: #666 }\r\n        .s_ipt_wr {height: 32px }\r\n        .s_form:after, .s_tab:after {content: \".\"; display: block; height: 0; clear: both; visibility: hidden }\r\n        .s_form {zoom: 1; height: 55px; padding: 0 0 0 10px }\r\n        #result_logo {float: left; margin: 7px 0 0 }\r\n        #result_logo img {width: 101px }\r\n        #head {padding: 0; margin: 0; width: 100%; position: absolute; z-index: 301; min-width: 1000px; background: #fff; border-bottom: 1px solid #ebebeb; position: fixed; _position: absolute; -webkit-transform: translateZ(0) }\r\n        #head .head_wrapper {_width: 1000px }\r\n        #head.s_down {box-shadow: 0 0 5px #888 }\r\n        .fm {clear: none; float: left; margin: 11px 0 0 10px }\r\n        #s_tab {background: #f8f8f8; line-height: 36px; height: 38px; padding: 55px 0 0 121px; float: none; zoom: 1 }\r\n        #s_tab a, #s_tab b {display: inline-block; text-decoration: none; text-align: center; color: #666; font-size: 14px }\r\n        #s_tab b {border-bottom: 2px solid #4E6EF2; color: #222 }\r\n        #s_tab a:hover {color: #323232 }\r\n        #content_left {width: 540px; padding-left: 149px;padding-top: 2px;}\r\n        .to_tieba, .to_zhidao_bottom {margin: 10px 0 0 121px }\r\n        #help {background: #f5f6f5; zoom: 1; padding: 0 0 0 50px; float: right }\r\n        #help a {color: #9195a3; padding-right: 21px; text-decoration: none }\r\n        #help a:hover {color: #333 }\r\n        #foot {position: fixed; bottom:0; width: 100%; background: #f5f6f5; border-top: 1px solid #ebebeb; text-align: left; height: 42px; line-height: 42px; margin-top: 40px; *margin-top: 0; _position:absolute; _bottom:auto; _top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0))); }\r\n\r\n        .content_none {padding: 45px 0 25px 121px } .s_ipt_wr.bg,\r\n        .s_btn_wr.bg, #su.bg {background-image: none }\r\n        .s_ipt_wr.bg {background: 0 }\r\n        .s_btn_wr {width: auto; height: auto; border-bottom: 1px solid transparent; *border-bottom: 0 }\r\n        .s_btn {width: 100px; height: 34px; color: white; letter-spacing: 1px; background: #3385ff; border-bottom: 1px solid #2d78f4; outline: medium; *border-bottom: 0; -webkit-appearance: none; -webkit-border-radius: 0 }\r\n        .s_btn:hover {background: #317ef3; border-bottom: 1px solid #2868c8; *border-bottom: 0; box-shadow: 1px 1px 1px #ccc }\r\n        .s_btn:active {background: #3075dc; box-shadow: inset 1px 1px 3px #2964bb; -webkit-box-shadow: inset 1px 1px 3px #2964bb; -moz-box-shadow: inset 1px 1px 3px #2964bb; -o-box-shadow: inset 1px 1px 3px #2964bb }\r\n        #lg {display: none }\r\n        #head .headBlock {margin: -5px 0 6px 121px }\r\n        #content_left .leftBlock {margin-bottom: 14px; padding-bottom: 5px; border-bottom: 1px solid #f3f3f3 }\r\n        .s_ipt_wr {border: 1px solid #b6b6b6; border-color: #7b7b7b #b6b6b6 #b6b6b6 #7b7b7b; background: #fff; display: inline-block; vertical-align: top; width: 592px; margin-right: 0; border-right-width: 0; border-color: #b8b8b8 transparent #ccc #b8b8b8; overflow: hidden }\r\n        .s_ipt_wr.ip_short {width: 439px; }\r\n        .s_ipt_wr:hover, .s_ipt_wr.ipthover {border-color: #999 transparent #b3b3b3 #999 }\r\n        .s_ipt_wr.iptfocus {border-color: #4e6ef2 transparent #4e6ef2 #4e6ef2 }\r\n        .s_ipt_tip {color: #aaa; position: absolute; z-index: -10; font: 16px/22px arial; height: 32px; line-height: 32px; padding-left: 7px; overflow: hidden; width: 526px }\r\n        .s_ipt {width: 526px; height: 22px; font: 16px/18px arial; line-height: 22px\9; margin: 6px 0 0 7px; padding: 0; background: transparent; border: 0; outline: 0; -webkit-appearance: none }\r\n        #kw {position: relative;display: inline-block;}\r\n        input::-ms-clear {display: none }\r\n        /*Error page css*/\r\n        .norsSuggest {display: inline-block; color: #333; font-family: arial; font-size: 13px; position: relative; } \r\n        .norsTitle {font-size: 22px;font-weight: normal; color: #333; margin: 29px 0 25px 0; }\r\n        .norsTitle2 {font-family: arial; font-size: 13px; color: #666; }\r\n        .norsSuggest ol {margin-left: 47px; }\r\n        .norsSuggest li {margin: 13px 0; }\r\n        #content_right {\r\n    border-left: 1px solid #e1e1e1;\r\n    width: 384px;\r\n    margin-top: 20px;\r\n    float: right;\r\n    padding-left: 17px;\r\n}\r\n#wrapper_wrapper {\r\n    width: 1235px;\r\n    margin-top: 50px;\r\n}\r\n.cr-content {\r\n    width: 351px;\r\n    font-size: 13px;\r\n    line-height: 1.54em;\r\n    color: #333;\r\n    margin-top: 8px;\r\n    margin-left: 19px;\r\n    word-wrap: break-word;\r\n    word-break: normal;\r\n}\r\n@media screen and (max-width: 1217px) {\r\n    #wrapper_wrapper {\r\n        width: 1002px;\r\n    }\r\n    #wrapper_wrapper #content_right {\r\n        width: 271px;\r\n    }\r\n    #wrapper_wrapper .cr-content {\r\n        width: 259px;\r\n    }\r\n}\r\n.opr-toplist-title {\r\n    position: relative;\r\n    font-size: 14px;\r\n    line-height: 1.29em;\r\n    font-weight: 700;\r\n    margin-bottom: 3px;\r\n    font: 14px/22px Arial,sans-serif;\r\n    color: #222;\r\n    font-weight: 400;\r\n}\r\n.opr-toplist-table {\r\n    width: 100%;\r\n    border-collapse: collapse;\r\n    border-spacing: 0;\r\n    font-size: 13px;\r\n}\r\n.opr-toplist-table th,td {\r\n    line-height: 1.54;\r\n    border-bottom: 1px solid #f3f3f3;\r\n    text-align: left;\r\n}\r\n.opr-toplist-table thead th {\r\n    padding-top: 4px;\r\n    padding-bottom: 4px;\r\n    font-weight: 400;\r\n    color: #666;\r\n    white-space: nowrap;\r\n    background-color: #fafafa;  \r\n}\r\n.opr-toplist-table .opr-toplist-right {\r\n    text-align: right;\r\n    white-space: nowrap;\r\n}\r\n.opr-toplist-table td {\r\n    width: 100%;\r\n    font-size: 13px;\r\n    padding-top: 5.5px;\r\n    padding-bottom: 5.5px;\r\n    vertical-align: top;\r\n}\r\n.opr-toplist-table a:hover {\r\n    color: #315EFB;\r\n    text-decoration: underline;\r\n}\r\n.opr-toplist-table td{\r\n    padding-top: 5px 0;\r\n    border: none!important;\r\n    height: 20px;\r\n    line-height: 20px!important;\r\n}\r\n.opr-item-text{\r\n    font: 14px/22px Arial,sans-serif;\r\n    color: #2440B3;\r\n}\r\n.opr-index-item {\r\n    display: inline-block;\r\n    padding:1px 0;\r\n    color: #9195A3;\r\n    width: 20px;\r\n    height: 16px;\r\n    line-height: 100%;\r\n    font-size: 15px;\r\n    margin-right: 1px;\r\n    text-align: left;\r\n}\r\n.opr-index-hot1 {\r\n    color: #f54545;\r\n}\r\n\r\n.opr-index-hot2 {\r\n    color: #ff8547;\r\n}\r\n.opr-index-hot3 {\r\n    color: #ffac38;\r\n}\r\n.opr-item-text {\r\n    text-decoration: none;  \r\n}\r\n.opr-toplist-info {\r\n    color: #666;\r\n    text-align: right;\r\n    margin-top: 5px;\r\n}\r\n.opr-toplist-info>a {\r\n    color: #666;\r\n}\r\n/* 新加 */\r\n@font-face {\r\n  font-family: 'cIconfont';\r\n  src: url('./font/iconfont.eot');\r\n  src: url('./font/iconfont.eot?#iefix') format('embedded-opentype'),\r\n    url('./font/iconfont.woff2') format('woff2'),\r\n    url('./font/iconfont.woff') format('woff'),\r\n    url('./font/iconfont.ttf') format('truetype'),\r\n    url('./font/iconfont.svg#iconfont') format('svg');\r\n}\r\n.s_form {\r\n    zoom: 1;\r\n    padding: 15px 0 4px 16px;\r\n    height: 40px;\r\n    font-size: 0;\r\n}\r\n#result_logo{\r\n    margin-top: 2px;\r\n}\r\n#result_logo img {\r\n    width: 101px;\r\n    height: 33px;\r\n}\r\n.fm {\r\n    margin-left: 19px;\r\n}\r\n.s_ipt_wr{\r\n    box-sizing: border-box;\r\n    height:40px;\r\n    line-height: 40px;\r\n    border: 2px solid #c4c7ce;\r\n    border-radius: 10px 0 0 10px;\r\n    border-right: 0;\r\n    overflow: visible;\r\n}\r\n.s_btn_wr .s_btn{\r\n    cursor: pointer;\r\n    width: 112px;\r\n    height: 40px;\r\n    line-height: 41px;\r\n    line-height: 40px\9;\r\n    background-color: #4e6ef2;\r\n    border-radius: 0 10px 10px 0;\r\n    font-size: 17px;\r\n    box-shadow: none;\r\n    font-weight: 400;\r\n    border: 0;\r\n    outline: 0;\r\n    letter-spacing: normal;\r\n}\r\n.s_btn_wr .s_btn:hover{\r\n    background: #4662d9;\r\n}\r\n.s_ipt_wr.ip_short{\r\n    width: 480px;\r\n}\r\n#kw{\r\n    width: 465px;\r\n    height: 38px;\r\n    font: 16px/18px arial;\r\n    padding: 10px 0 10px 14px;\r\n    margin: 0;\r\n    background: transparent;\r\n    border: 0;\r\n}\r\n.fm{\r\n    margin: 0 0 15px 16px;\r\n    clear: none;\r\n    float: left;\r\n    position: relative;\r\n}\r\n#head{\r\n    border-bottom: none;\r\n    position: relative;\r\n}\r\n#u {\r\n    height: 40px;\r\n    line-height: 40px;\r\n    padding-right: 30px;\r\n    z-index: 301;\r\n    display: inline-block;\r\n    float: right;\r\n    color: #999;\r\n}\r\n#u .toindex{\r\n    font-family: Arial, 'Microsoft YaHei';\r\n    font-size: 13px;\r\n    color: #222222;\r\n    text-align: right;\r\n    text-decoration: none;\r\n}\r\n#u .toindex:hover{\r\n    color: #2640b3;\r\n}\r\n.s-tab-item:hover::before{\r\n    color: #222 !important;\r\n}\r\n#s_tab {\r\n    position: absolute;\r\n    left: 0;\r\n    background: none;\r\n    line-height: 36px;\r\n    height: 38px;\r\n    padding: 2px 0 0 150px;\r\n    float: none;\r\n    zoom: 1;\r\n    color: #626675;\r\n    overflow: hidden;\r\n}\r\n#s_tab a, #s_tab b {\r\n    display: inline-block;\r\n    margin-right: 24px;\r\n    min-width: 44px;\r\n    text-decoration: none;\r\n    font-size: 14px;\r\n    text-align: left;\r\n    line-height: 28px;\r\n    color: #222222;\r\n    font-weight: normal;\r\n}\r\n#s_tab a{\r\n    color: #626675;\r\n}\r\n#s_tab .s-tab-item:before {\r\n    display: inline-block;\r\n    margin-right: 2px;\r\n    width: 14px;\r\n    font-family: 'cIconfont'!important;\r\n    font-style: normal;\r\n    -webkit-font-smoothing: antialiased;\r\n    background: initial;\r\n    color: #c0c2c8;\r\n}\r\n#s_tab .cur-tab:before {\r\n    font-family: 'cIconfont'!important;\r\n    color: #626675;\r\n    margin-right: 2px;\r\n    content: '\e608';\r\n}\r\n#s_tab .s-tab-news:before {\r\n    content: '\e606';\r\n}\r\n#s_tab .s-tab-video:before {\r\n    content: '\e604';\r\n}\r\n#s_tab .s-tab-pic:before {\r\n    content: '\e607';\r\n}\r\n#s_tab .s-tab-zhidao:before {\r\n    content: '\e633';\r\n}\r\n#s_tab .s-tab-wenku:before {\r\n    content: '\e605';\r\n}\r\n#s_tab .s-tab-tieba:before {\r\n    content: '\e609';\r\n}\r\n#s_tab .s-tab-map:before {\r\n    content: '\e630';\r\n}\r\n#s_tab .s-tab-b2b:before {\r\n    content: '\e603';\r\n}\r\n#content_right{\r\n    border-left: none;\r\n}\r\n.norsTitle{\r\n    font-family: Arial, 'Microsoft YaHei';\r\n    font-size: 18px;\r\n    color: #222222;\r\n    text-align: justify;\r\n    line-height: 18px;\r\n}\r\n.norsTitle{\r\n    margin-bottom: 28px;\r\n}\r\n.norsTitle2{\r\n    font-family: Arial, 'Microsoft YaHei';\r\n    font-size: 14px;\r\n    color: #333333;\r\n    text-align: justify;\r\n    line-height: 14px;\r\n    margin-bottom: 12px;\r\n}\r\n.norsSuggest a{\r\n    color: #2440b3;\r\n    text-decoration: none;\r\n}\r\n.norsSuggest a:hover{\r\n    color: #315efb;\r\n    text-decoration: underline;\r\n}\r\n#foot{\r\n    background: #f5f5f6;\r\n    color: #9195a3;\r\n    border-top: none;\r\n}\r\n#help{\r\n    float:left;\r\n    padding-left:150px\r\n}\r\n    </style>\r\n</head>\r\n\r\n<body link=\"#0000cc\">\r\n    <div id=\"wrapper\" class=\"wrapper_l\">\r\n        <div id=\"head\">\r\n            <div class=\"head_wrapper\">\r\n                <div class=\"s_form\">\r\n                    <div class=\"s_form_wrapper\">\r\n                        <a href=\"//www.baidu.com/\" id=\"result_logo\"><img src=\"//www.baidu.com/img/flexible/logo/pc/result@2.png\" alt=\"到百度首页\" title=\"到百度首页\"></a>\r\n                        <form id=\"form\" name=\"f\" action=\"//www.baidu.com/s\" class=\"fm\">\r\n                            <input type=\"hidden\" name=\"ie\" value=\"utf-8\">\r\n                            <input type=\"hidden\" name=\"f\" value=\"8\">\r\n                            <input type=\"hidden\" name=\"rsv_bp\" value=\"1\">\r\n                            <input type=\"hidden\" name=\"ch\" value=\"\">\r\n                            <input type=\"hidden\" name=\"tn\" value=\"baiduerr\">\r\n                            <input type=\"hidden\" name=\"bar\" value=\"\">\r\n                            <span class=\"bg s_ipt_wr iptfocus\">\r\n                                <input id=\"kw\" name=\"wd\" class=\"s_ipt\" value=\"\" maxlength=\"255\" autocomplete=\"off\" autofocus>\r\n                            </span><span class=\"bg s_btn_wr\">\r\n                                <input type=\"submit\" id=\"su\" value=\"百度一下\" class=\"bg s_btn\">\r\n                            </span>\r\n                        </form>\r\n                    </div>\r\n                    <div id=\"u\">\r\n                        <a class=\"toindex\" href=\"//www.baidu.com/\">百度首页</a>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    <div class=\"s_tab\" id=\"s_tab\">\r\n        <b class=\"cur-tab\">网页</b>\r\n        <a href=\"//www.baidu.com/?tn=news\" class=\"s-tab-item s-tab-news\" wdfield=\"kw\">资讯</a>\r\n        <a href=\"//v.baidu.com/\" class=\"s-tab-item s-tab-video\">视频</a>\r\n        <a href=\"//image.baidu.com/\" class=\"s-tab-item s-tab-pic\">图片</a>\r\n        <a href=\"//zhidao.baidu.com/\" class=\"s-tab-item s-tab-zhidao\">知道</a>\r\n        <a href=\"//wenku.baidu.com/\" class=\"s-tab-item s-tab-wenku\">文库</a>\r\n        <a href=\"//tieba.baidu.com/index.html\" class=\"s-tab-item s-tab-tieba\">贴吧</a>\r\n        <a href=\"//map.baidu.com/\" class=\"s-tab-item s-tab-map\">地图</a>\r\n        <a href=\"//b2b.baidu.com/s?fr=wwwt\" class=\"s-tab-item s-tab-b2b\">采购</a>\r\n        <a href=\"//www.baidu.com/more/\" class=\"s-tab-item s-tab-more\">更多</a>\r\n    </div>\r\n    <div id=\"wrapper_wrapper\">\r\n        <div id=\"content_left\">\r\n            <div class=\"nors\">\r\n                <div class=\"norsSuggest\">\r\n                    <h3 class=\"norsTitle\">很抱歉，您要访问的页面不存在！</h3>\r\n                    <p class=\"norsTitle2\">温馨提示 :</p>\r\n                    <p class=\"norsTitle2\">请检查您访问的网址是否正确</p>\r\n                    <p class=\"norsTitle2\">如果您不能确认访问的网址，请浏览<a href=\"//www.baidu.com/more/index.html\">百度更多</a>页面查看更多网址。</p>\r\n                    <p class=\"norsTitle2\">回到顶部重新发起搜索</p>\r\n                    <p class=\"norsTitle2\">如有任何意见或建议，请及时<a href=\"http://qingting.baidu.com/index\">反馈给我们</a>。</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div id=\"foot\">\r\n        <span id=\"help\">\r\n            <a href=\"http://help.baidu.com/question\" target=\"_blank\">帮助</a>\r\n            <a href=\"http://www.baidu.com/search/jubao.html\" target=\"_blank\">举报</a>\r\n            <a href=\"http://jianyi.baidu.com\" target=\"_blank\">用户反馈</a>\r\n        </span>\r\n    </div>\r\n</body>\r\n<script>\r\n(function () {\r\n        var LOGURL = 'https://sp1.baidu.com/5b1ZeDe5KgQFm2e88IuM_a/cm.gif';\r\n        var params = 'type=wwwerror&terminal=www';\r\n        var img = new Image();\r\n        img.src = LOGURL + '?' + params;\r\n    })();\r\n    (function () {\r\n        if(window.recommend && window.recommend.query && window.recommend.query.length > 0) {\r\n            var recommendWrapper = document.createElement('div');\r\n            var recommendHtml = '<div class=\"cr-content\"><div class=\"opr-toplist-title\">' + window.recommend.title + '</div><table class=\"opr-toplist-table\">';\r\n            var queryArray = window.recommend.query;\r\n            var itemUrl = '';\r\n            for(var i = 1; i < (queryArray.length+1); i++) {\r\n                itemUrl = '//www.baidu.com/s?word=' + encodeURIComponent(queryArray[i-1].word) + '&sa=' + queryArray[i-1].sa + '&tn=' + queryArray[i-1].tn;\r\n                if (queryArray[i-1].rsv_dl) {\r\n                    itemUrl += \"&rsv_dl=\" + queryArray[i-1].rsv_dl;\r\n                }\r\n                \r\n                if (i < 4) {\r\n                    recommendHtml += '<tr><td><span class=\"opr-index-hot' + i + ' opr-index-item\">' + i + '</span><a target=\"_blank\" href=\"' + itemUrl +'\" class=\"opr-item-text\">' + queryArray[i-1].word + '</a></td></tr>';\r\n                } else {\r\n                    recommendHtml += '<tr><td><span class=\"opr-index-item\">' + i + '</span><a target=\"_blank\" href=\"' + itemUrl +'\" class=\"opr-item-text\">' + queryArray[i-1].word + '</a></td></tr>';\r\n                }\r\n            }\r\n            recommendHtml += '</tbody></table></div>';\r\n            recommendWrapper.setAttribute('id', 'content_right');\r\n            document.getElementById('wrapper_wrapper').insertBefore(recommendWrapper, document.getElementById('content_left'));\r\n            var recommend = document.getElementById('content_right');\r\n            recommend.innerHTML = recommendHtml;\r\n        }\r\n})();\r\n(function(){\r\n    var bds = {\r\n        util: {}\r\n    };\r\n    var c = document.getElementById('kw').parentNode;\r\n\r\n    bds.util.getWinWidth = function(){\r\n        return window.document.documentElement.clientWidth;\r\n    };\r\n\r\n    bds.util.setFormWidth = function(){\r\n        var width = bds.util.getWinWidth();\r\n        if(width < 1217)    {bds.util.setClass(c, 'ip_short', 'add')}\r\n        else                {bds.util.setClass(c, 'ip_short', 'remove')};\r\n    };\r\n\r\n    bds.util.setClass = function(obj, class_name, set) {\r\n        var ori_class = obj.className,\r\n            has_class_p = -1,\r\n            ori_class_arr = [],\r\n            new_class = '';\r\n\r\n        if(ori_class.length) ori_class_arr = ori_class.split(' ');\r\n\r\n        for( i in ori_class_arr) {\r\n            if(ori_class_arr[i] == class_name) has_class_p = i;\r\n        }\r\n\r\n        if( set == 'remove' && has_class_p >= 0) {\r\n            ori_class_arr.splice(has_class_p, 1);\r\n            new_class = ori_class_arr.join(' ');\r\n            obj.className = new_class;\r\n        } else if( set == 'add' && has_class_p < 0) {\r\n            ori_class_arr.push(class_name);\r\n            new_class = ori_class_arr.join(' ');\r\n            obj.className = new_class;\r\n        }\r\n    }\r\n    bds.util.setFormWidth();\r\n\r\n    if (typeof document.addEventListener != \"undefined\") {\r\n        window.addEventListener('resize', bds.util.setFormWidth, false);\r\n        document.getElementById('kw').addEventListener('focus', function(){bds.util.setClass(c,'iptfocus', 'add');}, false);\r\n        document.getElementById('kw').addEventListener('blur', function(){bds.util.setClass(c,'iptfocus', 'remove');}, false);\r\n    } else {\r\n        window.attachEvent('onresize', bds.util.setFormWidth, false);\r\n        document.getElementById('kw').attachEvent('onfocus', function(){bds.util.setClass(c,'iptfocus', 'add');}, false);\r\n        document.getElementById('kw').attachEvent('onblur', function(){bds.util.setClass(c,'iptfocus', 'remove');}, false);\r\n    } \r\n\r\n})();\r\n\r\n\r\n</script>\r\n\r\n</html>\r\n","requestHeaders":{},"responseHeaders":{"null":"HTTP/1.1 200 OK","Server":"Apache","Last-Modified":"Wed, 10 Mar 2021 06:27:44 GMT","P3p":"CP=\" OTI DSP COR IVA OUR IND COM \"","Date":"Tue, 14 Mar 2023 16:26:34 GMT","Accept-Ranges":"bytes","Cache-Control":"max-age=86400","Etag":"\"4d71-5bd28c3bf7800\"","Set-Cookie":"BAIDUID=29D5FB2F2C63A88CF938AC2C19499108:FG=1; expires=Wed, 13-Mar-24 16:26:34 GMT; max-age=31536000; path=/; domain=.baidu.com; version=1","Vary":"Accept-Encoding,User-Agent","Expires":"Wed, 15 Mar 2023 16:26:34 GMT","Content-Length":"19825","Content-Type":"text/html"},"key":"1015961004"}";
 Traffic traffic = JSON.parseObject(body, Traffic.class);
```

 

### 相关日志输出
```
com.alibaba.fastjson2.JSONException: unclosed.str.lit 9
	at com.alibaba.fastjson2.JSONReader.char1(JSONReader.java:330)
	at com.alibaba.fastjson2.JSONReaderUTF16.readString(JSONReaderUTF16.java:3735)
	at com.alibaba.fastjson2.reader.ORG_3_14_Traffic.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:642)
```

 
![image](https://user-images.githubusercontent.com/46422252/225075880-6d4ca515-a041-45d3-a777-c1c8a5febce5.png)

**Comment by wenshao** [comment]
这个不是合法JSON格式，jackson/gson也 不支持。
```
\9
```

应该写成如下的格式：
```
\u0009
```
