### ISSUE TITLE
fastjson1支持返回的泛型的DTO转成List，但是fastjson2会转换失败

### ISSUE THREAD

**Issue by hcxxiaomo** [alibaba/fastjson2#1240]
### fastjson1和2兼容性问题
对应数据：
{"date":"2023-03-10 11:55:42","errorCode":"202004","errorMessage":"人员不存在或获取失败","obj":{"deptCode":"755H,"scheduleCode":"03D","scheduleEndTime":1330,"scheduleName":"755H03D10311330","scheduleStartTime":1031,"scheduleTime":"10:31-13:30","scheduleType":2,"status":0,"unitCode":"755H013"},"success":false}

fastjson1版本：com.alibaba:fastjson:1.2.83
fastjson2版本：com.alibaba:fastjson:2.0.24

反序列化的代码

` 

String info = "{\"date\":\"2023-03-10 11:55:42\",\"errorCode\":\"202004\",\"errorMessage\":\"人员不存在或获取失败\",\"obj\":{\"deptCode\":\"755H,\"scheduleCode\":\"03D\",\"scheduleEndTime\":1330,\"scheduleName\":\"755H03D10311330\",\"scheduleStartTime\":1031,\"scheduleTime\":\"10:31-13:30\",\"scheduleType\":2,\"status\":0,\"unitCode\":\"755H013\"},\"success\":false}";
 Result<List<String>> listResult = JSONObject.parseObject(info, new TypeReference<Result<List<String>>>() {
        });
`

用fastjson1没有问题，能正常解析兼容。用fastjson2就会报下面错误：
` 

Caused by: com.alibaba.fastjson.JSONException: offset 86, character {, line 1, column 87, fastjson-version 2.0.24 {"date":"2023-03-10 11:56:07","errorCode":"202001","errorMessage":"人员不存在或获取失败","obj":{"status":0,"unitCode":"755H013"},"success":false}
at com.alibaba.fastjson.JSON.parseObject(JSON.java:573)
at com.sf.pbs.http.convertor.DefaultResponseGeneratorConvertor.generate(DefaultResponseGeneratorConvertor.java:100)
... 60 more
Caused by: com.alibaba.fastjson2.JSONException: offset 86, character {, line 1, column 87, fastjson-version 2.0.24 {"date":"2023-03-10 11:56:07","errorCode":"202001","errorMessage":"人员不存在或获取失败","obj":{"status":0,"unitCode":"755H013"},"success":false}
at com.alibaba.fastjson2.reader.ObjectReaderImplListStr.readObject(ObjectReaderImplListStr.java:181)
at com.alibaba.fastjson2.reader.ORG_9_9_Result.readObject(Unknown Source)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:563)
... 61 more
`

查了下代码，fastjson2在这里处理的时候，只能处理列表数据：
` 

com.alibaba.fastjson2.reader.ObjectReaderImplListStr#readObject 的177行
`

而fastjson1在这里处理的时候，是会特别兼容的：
` 

com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer#parseArray 的 202 行 最后的 else 里面兼容了
     else {
            if (itemTypeDeser == null) {
                itemTypeDeser = deserializer = parser.getConfig().getDeserializer(itemType);
            }
            Object val = itemTypeDeser.deserialze(parser, itemType, 0);
            array.add(val);
            parser.checkListResolve(array);
        }
`

看看这个是否要跟fastjson1一样，兼容List存储单个dto对象

**Comment by wenshao** [comment]
Result 这个类的代码可以提供下面么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
问题已修复，请用新版本
