### ISSUE TITLE
[BUG]自定义反序列化异常

### ISSUE THREAD

**Issue by SummerDream-z** [alibaba/fastjson2#1249]
### 问题描述

自定义反序列化，偶尔成功一次，大部分情况执行时异常：
```java
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.fastjson2.reader.FieldReaderObject.accept(FieldReaderObject.java:264)
```

### 环境信息

java sdk: OpenJDK 1.8.0_281
fastjson: 2.0.21
 

### 重现步骤

**定义**
```java
@Data
public class CallInfo {

    private String phoneNum;

    @JSONField(deserializeUsing = JsonDeserializer.class)
    private Map<String, Object> varDefine;

    @JSONField(deserializeUsing = TagDeserializer.class)
    private List<Tag> tagSession;
}
```

```java
@Data
public class Tag {
    private String tagId;
    private String tagName;
}
```

```java
public class JsonDeserializer implements ObjectReader<Map<String, Object>> {
    @Override
    public Map<String, Object> readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
        String value = jsonReader.readString();
        return JSONObject.parseObject(value);
    }
}
```

```java
public class TagDeserializer implements ObjectReader<List<Tag>> {
    @Override
    public List<Tag> readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
        String value = jsonReader.readString();
        return JSON.parseArray(value, Tag.class);
    }
}
```

**使用**

```java
public static void main(String[] args) {
        Map<String, String> map = new HashMap<>();
        map.put("phoneNum", "1");
        map.put("varDefine", "{\"success\":\"yes\"}");
        map.put("tagSession", "[{\"tagId\":\"6908494829\",\"tagName\":\"不是本人\"}]");
        CallInfo callInfo = JSON.parseObject(JSON.toJSONString(map), CallInfo.class);
    }
```

### 相关日志输出

```java
Exception in thread "main" com.alibaba.fastjson2.JSONException: read field 'CallInfo.getVarDefine, offset 117, character }, line 1, column 118, fastjson-version 2.0.21 {"phoneNum":"1","tagSession":"[{\"tagId\":\"6908494829\",\"tagName\":\"不是本人\"}]","varDefine":"{\"success\":\"yes\"}"}
	at com.alibaba.fastjson2.reader.FieldReaderObject.readFieldValue(FieldReaderObject.java:162)
	at com.alibaba.fastjson2.reader.ObjectReader3.readObject(ObjectReader3.java:337)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:601)
	at Test.main(Test.java:20)
Caused by: com.alibaba.fastjson2.JSONException: set varDefine error
	at com.alibaba.fastjson2.reader.FieldReaderObject.accept(FieldReaderObject.java:268)
	at com.alibaba.fastjson2.reader.FieldReaderObject.readFieldValue(FieldReaderObject.java:147)
	... 3 more
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.fastjson2.reader.FieldReaderObject.accept(FieldReaderObject.java:264)
	... 4 more
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
问题已修复，请用新版本
