### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pysenic** [alibaba/fastjson2#1251]
scala 2.11
fastjson 2.0.23

测试代码
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val s =
      """
        |[fd listen socket: /tmp/dev_dc1_pubvsnutlog2v1.2.23.sock]
        |""".stripMargin
    println(JSON.isValidArray(s))
    val validator = JSONValidator.from(s)
    println(validator.getType)
    JSON.parseArray(s)
  }
}
```

结果：
true
Array
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error : s
	at com.alibaba.fastjson.JSON.parseArray(JSON.java:1976)
	at Test$.main(Test.scala:22)
	at Test.main(Test.scala)
Caused by: com.alibaba.fastjson2.JSONException: syntax error : s
	at com.alibaba.fastjson2.JSONReader.readBoolValue(JSONReader.java:1773)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:275)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1376)
	at com.alibaba.fastjson.JSON.parseArray(JSON.java:1967)
	... 2 more

Process finished with exit code 1

两种判断方式都有问题

**Comment by wenshao** [comment]
问题无法重现，是否可以帮忙用 2.0.26版本验证下是否问题还存在
