### ISSUE TITLE
[BUG] 兼容性反馈：fastjson2（v2.0.26） 不支持//注释符，而fastjson1支持

### ISSUE THREAD

**Issue by xseruer** [alibaba/fastjson2#1270]
### 问题描述
无法处理/开头的注释内容.

### 重现步骤
```java
    public static void main(String[] args) {
        String policy = "{\n" +
                "  \"Version\": \"1\",\n" +
                "  \"Statement\": [\n" +
                "    {\n" +
                "      \"Action\": [\n" +
                "        \"log:PostLogStoreLogs\" \n" +
                "      ],\n" +
                "      \"Resource\": [\n" +
                "        //请务必完整填写到Logstore，否则会造成越权漏洞\n" +
                "        \"*\"\n" +
                "      ],\n" +
                "      \"Effect\": \"Allow\"\n" +
                "    }\n" +
                "  ]\n" +
                "}";
        com.alibaba.fastjson.JSONObject.parseObject(policy);  // 1.2.75 正常
        com.alibaba.fastjson2.JSON.parseObject(policy); // 2.0.26 版本抛异常
    }
```

### 期待的正确结果
和fastjson1保持一致

### 相关日志输出
```
com.alibaba.fastjson2.JSONException: TODO : /

	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2062)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1702)
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2030)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1529)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:215)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by xseruer** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/ 问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

测试了[fastjson2-2.0.27-20230326.172629-40.jar](https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/fastjson2-2.0.27-20230326.172629-40.jar) 工作正常，期待尽快打正式包。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
请用新版本
