### ISSUE TITLE
[BUG] 2.0.26使用 SupportAutoType 反序列化时，如果存在使用枚举类为 key 的 map 则总会失败

### ISSUE THREAD

**Issue by huangluyu** [alibaba/fastjson2#1324]
### 问题描述
使用 SupportAutoType 反序列化时，如果存在使用枚举类为 key 的 map 则总会失败
2.0.17 没有这个问题，2.0.26 会有，没有深究具体出现的版本

### 重现步骤
```java
import com.alibaba.fastjson2.JSON
import com.alibaba.fastjson2.JSONReader

enum TestEnum {
    x1,
    x2
}

class Test {

    Map<TestEnum, Integer> map;
}


String json = "{\"map\": {\"x1\": 1}}"
JSON.parseObject(json, Test.class, JSONReader.Feature.SupportAutoType)
```

### 相关日志输出
```
com.alibaba.fastjson2.JSONException: not support name x1
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:315)
	at com.alibaba.fastjson2.reader.ORG_1_2_Test.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:848)
```

**Comment by lorna1** [comment]
使用boolean值作为map key 也会出现同样问题，例如   
"cases": {
        "true": "node119",
        "false": "node120"
    }  

报错：  not support name true

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
