### ISSUE TITLE
[BUG]2.0.27 Feature.SupportAutoType map反序列化失败

### ISSUE THREAD

**Issue by lorna1** [alibaba/fastjson2#1344]
### 问题描述
Exception in thread "main" com.alibaba.fastjson.JSONException: not support name true
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:546)
	at com.lorna.fastjson2.EnumJsonTest.main(EnumJsonTest.java:23)
Caused by: com.alibaba.fastjson2.JSONException: not support name true
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:325)
	at com.alibaba.fastjson2.reader.ORG_2_1_Test2.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:536)
	... 1 more

### 环境信息

 - OS信息：  [e.g.：mac os 14.2]
 - JDK信息： [e.g.：jdk 1.8.0_212]
 - 版本信息：[e.g.：Fastjson2 2.0.27]
 

### 重现步骤
    public static void main(String[] args) {
    
        String json2  = "{\"maps\":{\"true\":\"1\",\"false\":\"2\"}}";
        Test2 test2 = JSON.parseObject(json2, Test2.class, Feature.SupportAutoType);

        System.out.println(1);
    }

    private static class Test2 implements Serializable {
        private Map<Boolean, String> maps;

        public Map<Boolean, String> getMaps() {
            return maps;
        }

        public void setMaps(Map<Boolean, String> maps) {
            this.maps = maps;
        }
    }

### 期待的正确结果
序列化成功

### 相关日志输出
Exception in thread "main" com.alibaba.fastjson.JSONException: not support name true
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:546)
	at com.lorna.fastjson2.EnumJsonTest.main(EnumJsonTest.java:23)
Caused by: com.alibaba.fastjson2.JSONException: not support name true
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:325)
	at com.alibaba.fastjson2.reader.ORG_2_1_Test2.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:536)
	... 1 more

**Comment by lorna1** [comment]
JSON.parseObject(json2, Test2.class) 不带Feature的情况下可以正确序列哈
