### ISSUE TITLE
[QUESTION]反序列化失败

### ISSUE THREAD

**Issue by bai0004** [alibaba/fastjson2#1345]
调用JSON.parseObject、JSONObject.toJavaObject等方法统一提示如下信息，java类继承了Serializable，并且不论是否增加@JSONField注解，提示都是这个，其中使用的的JSONstring是从文件中读取的，fastjson1可以正常反序列化，网上也没找到类似的问题，请问这个问题要怎么处理
java.lang.UnsupportedOperationException: can't load this type of class file
                                                                                                    	at java.lang.ClassLoader.defineClass(ClassLoader.java:591)
                                                                                                    	at com.alibaba.fastjson2.util.DynamicClassLoader.defineClassPublic(DynamicClassLoader.java:138)
                                                                                                    	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:570)
                                                                                                    	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:808)
                                                                                                    	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1195)
                                                                                                    	at com.alibaba.fastjson2.JSONObject.toJavaObject(JSONObject.java:1208)

**Comment by wenshao** [comment]
什么JDK版本啊
