### ISSUE TITLE
org.apache.dubbo.remoting.RemotingException: com.alibaba.fastjson2.JSONException: TODO : INT32 56

### ISSUE THREAD

**Issue by HelloToGithub** [alibaba/fastjson2#1366]
### 问题描述
*简要描述您碰到的问题。*
Fastjson2：2 0.27
Dubbo：3.1.9

org.apache.dubbo.remoting.RemotingException: com.alibaba.fastjson2.JSONException: TODO : INT32 56
com.alibaba.fastjson2.JSONException: TODO : INT32 56
	at com.alibaba.fastjson2.JSONReaderJSONB.getString(JSONReaderJSONB.java:106)
	at com.alibaba.fastjson2.JSONReaderJSONB.checkAutoType(JSONReaderJSONB.java:1186)

去掉projectGoodsSkuDTOMap对象则正常

此时JSONB.toJSONString(bytes) 结果：
```
{
	"@type":"vip.joinsun.dto.PageResult",
	"current":1,
	"records":[
		{
			"@type":"vip.joinsun.dto.order.ThirdOrderResponseBO",
			"afterSaleFlag":0,
			"afterSaleNum":0,
			"afterSaleSuccessAmount":0,
			"apartOrderResponseList":[
				{
					"apartOrderId":null,
					"enterpriseExpressId":null,
					"orderStatus":null,
					"source":null,
					"thirdSubOrderList":[
						{
							"addResult":"成功添加",
							"afterSaleGoodsNum":0,
							"afterSaleStatus":0,
							"afterSaleSuccessAmount":0,
							"afterSaleSuccessGoodsNum":0,
							"apartOrderId":null,
							"apartOrderSource":null,
							"categoryFourId":0,
							"categoryOneId":20005,
							"categoryThreeId":0,
							"categoryTwoId":20182,
							"costDistributionAmount":3.90,
							"costExpenditureAmount":0.00,
							"createTime":1681452929,
							"currentDeliveryNum":null,
							"delFlag":0,
							"deliveryNum":0,
							"distributionFreight":0.00,
							"distributionPrice":3.90,
							"enterpriseId":null,
							"externalCode":"KCVIWERK214564",
							"giftFlag":0,
							"goodsCode":"GCP1508340227327508482",
							"goodsId":15083402274155888661508340227415588866,
							"goodsMainImage":"https://img-1.joinsun.vip/upload/06f1f663b5f6c2126e73d02ef175b025.jpg",
							"goodsNum":1,
							"goodsSource":0,
							"goodsSourceName":"总部自营",
							"goodsTitle":"多-抽绳垃圾袋家用手提式加厚厨房卫生间自动收口塑料袋大号实惠装",
							"memberId":null,
							"originalFlag":1,
							"originalThirdSubOrderId":null,
							"pickNum":null,
							"preDeliveryNum":0,
							"productCode":"158689-001",
							"productDistributorName":"",
							"productFreight":0.00,
							"productId":"1750789743771728",
							"productName":"2022民族汉服甜美女生",
							"productNum":1,
							"productPayAmount":2.00,
							"productPic":"https://p3-aio.ecombdimg.com/obj/ecom-shop-material/opPdqLIP_m_fec62ce22295eaa8392ae4eb00a7db80_sx_337823_www800-800",
							"productPrice":2.00,
							"productSkuDetail":"颜色:白色;",
							"profitAmount":2.00,
							"profitRate":100.00,
							"remainPickNum":null,
							"rowKey":null,
							"salesAttributeType":1,
							"sellerWordsTagFlag":null,
							"skuDetail":"颜色:1卷15只;",
							"skuFlag":1,
							"skuId":15083402286025769011508340228602576901,
							"splitOrderType":1,
							"stopNum":0,
							"subExternalOrderNo":"5056684646606142903",
							"supplierId":null,
							"supplierType":null,
							"supplyFreight":0.00,
							"supplyPrice":0.00,
							"supportFullQueryFlag":0,
							"systemRoleType":null,
							"thirdOrderGiftId":null,
							"thirdOrderId":16467590587697848341646759058769784834,
							"thirdPlatformCreateTime":1681452923,
							"thirdPlatformUpdateTime":1681452927,
							"thirdSubOrderId":16467590588914196491646759058891419649,
							"updateTime":1681453932,
							"warehouseId":null
						}
					],
					"totalGoodsNum":1,
					"warehouseId":null
				}
			],
			"buyerWords":"",
			"changeReceiverStatus":90,
			"children":null,
			"consigneeDetailAddress":"",
			"costAndProfitWords":"采购金额:0.00,毛利:2.00",
			"costDistributionAmount":0,
			"costExpenditureAmount":0.00,
			"createTime":1681452929,
			"currency":"RMB",
			"customerAddress":"******",
			"customerCityCode":"350200",
			"customerDistrictCode":"350206",
			"customerName":"******",
			"customerPhone":"******",
			"customerProvinceCode":"350000",
			"customerStreetCode":"350206005",
			"desensitisePostReceiver":"果*",
			"desensitisePostTel":"1********82",
			"distributionFreight":null,
			"encryptReceiveFlag":1,
			"enterpriseId":11459700241162936331145970024116293633,
			"exceptionTypeList":[],
			"expShipTime":1681574399,
			"externalOrderNo":"5056684646606142903",
			"externalShopOrderNo":"5056684646606142903",
			"giftOrders":[],
			"goodsNum":1,
			"isCanSplitOrderBtn":0,
			"isCanSplitOrderBtnTips":"至少2种商品才可拆单",
			"isShowDeleteOrReSyncBtn":1,
			"isShowDeliverBtn":0,
			"isShowUndoOrderBtn":0,
			"mergeType":1,
			"numberType":0,
			"orderAmount":2.00,
			"orderGoodsAmount":2.00,
			"orderLogList":null,
			"orderType":1,
			"packageNum":0,
			"payTime":1681452925,
			"payType":2,
			"platformOrderStatus":1,
			"platformType":1,
			"postAmount":0.00,
			"postCity":"",
			"postCityCode":"",
			"postDetail":"******",
			"postProvince":"",
			"postProvinceCode":"35",
			"postReceiver":"*",
			"postStreet":"",
			"postStreetCode":"",
			"postTel":"1********82",
			"postTown":"湖里区",
			"postTownCode":"350206",
			"profitAmount":2.00,
			"profitRate":100.00,
			"projectGoodsSkuDTOMap":{
				1508340227415588866:[
					{
						"@type":"vip.joinsun.dto.goods.ProjectGoodsSkuDTO",
						"abroadDistributeDeliveryTemplateId":null,
						"bomId":null,
						"delFlag":0,
						"deliveryTemplateId":15293439993268183061529343999326818306,
						"distributeDeliveryTemplateId":15289915444832542741528991544483254274,
						"distributePrice":3.90,
						"enterpriseId":11459700241162936331145970024116293633,
						"externalCode":"KCVIWERK214564",
						"goodsBarCode":"53452345232373",
						"goodsId":15083402274155888661508340227415588866,
						"goodsNum":null,
						"goodsSource":null,
						"goodsType":null,
						"imageUrl":"https://img-1.joinsun.vip/upload/06f1f663b5f6c2126e73d02ef175b025.jpg",
						"memberPrice":3.90,
						"orderNum":null,
						"postFeeType":null,
						"price":3.90,
						"remainStock":null,
						"salesAttributeType":1,
						"scribingPrice":7.80,
						"size":13.300000,
						"skuCode":"1508340228602576902",
						"skuDetail":"颜色:1卷15只;",
						"skuId":15083402286025769011508340228602576901,
						"specimenPrice":3.90,
						"stock":null,
						"stockInUse":null,
						"supplierId":null,
						"supplierSkuId":null,
						"supplyAllianceAssociateSkuId":null,
						"supplyAllianceMaxWholesalePrice":10.90,
						"supplyAllianceMinWholesalePrice":10.90,
						"supplyAlliancePrice":9.90,
						"supplyAllianceRetailDeliveryTemplateId":15413087642949509141541308764294950914,
						"supplyAllianceSellMaxPrice":16.90,
						"supplyAllianceSellMinPrice":16.90,
						"supplyAllianceWholesaleDeliveryTemplateId":13392046248282357771339204624828235777,
						"supplyPrice":3.90,
						"templateDetailsId":null,
						"updateTime":1675736462,
						"weight":12.000,
						"wholesaleDeliveryTemplateId":15293439993268183061529343999326818306,
						"wholesalePrice":80.00
					},
					{
						"@type":"vip.joinsun.dto.goods.ProjectGoodsSkuDTO",
						"abroadDistributeDeliveryTemplateId":null,
						"bomId":null,
						"delFlag":0,
						"deliveryTemplateId":15413077354719805461541307735471980546,
						"distributeDeliveryTemplateId":15224288260767252501522428826076725250,
						"distributePrice":5.90,
						"enterpriseId":11459700241162936331145970024116293633,
						"externalCode":"EWG35451798456",
						"goodsBarCode":"53452345232373",
						"goodsId":15083402274155888661508340227415588866,
						"goodsNum":null,
						"goodsSource":null,
						"goodsType":null,
						"imageUrl":"https://img-1.joinsun.vip/upload/cf770d47e3ff845f9cbb0266fd720cc9.jpg",
						"memberPrice":5.90,
						"orderNum":null,
						"postFeeType":null,
						"price":6.90,
						"remainStock":null,
						"salesAttributeType":1,
						"scribingPrice":11.80,
						"size":15.800000,
						"skuCode":"1508340228602576904",
						"skuDetail":"颜色:2卷45只;",
						"skuId":15083402286025769031508340228602576903,
						"specimenPrice":5.90,
						"stock":null,
						"stockInUse":null,
						"supplierId":null,
						"supplierSkuId":null,
						"supplyAllianceAssociateSkuId":null,
						"supplyAllianceMaxWholesalePrice":10.90,
						"supplyAllianceMinWholesalePrice":10.90,
						"supplyAlliancePrice":9.90,
						"supplyAllianceRetailDeliveryTemplateId":15553643733970288651555364373397028865,
						"supplyAllianceSellMaxPrice":16.90,
						"supplyAllianceSellMinPrice":16.90,
						"supplyAllianceWholesaleDeliveryTemplateId":15293651830043770891529365183004377089,
						"supplyPrice":5.90,
						"templateDetailsId":null,
						"updateTime":1675736462,
						"weight":31.000,
						"wholesaleDeliveryTemplateId":15413077354719805461541307735471980546,
						"wholesalePrice":80.00
					}
				]
			},
			"remainExpShipTime":118107692,
			"roleType":4,
			"roleTypeBusinessId":11459700241162936331145970024116293633,
			"sellerWords":"，我是自动备注信息",
			"sellerWordsTagFlag":2,
			"shopId":"7733776",
			"shopName":"众项云店",
			"shopType":2,
			"splitOrderType":1,
			"stepPayAll":1,
			"syncStatus":-1,
			"syncTime":1681452930,
			"systemCancelTime":null,
			"systemCompleteTime":null,
			"systemCreateTime":null,
			"systemDeliveryTime":null,
			"systemPayTime":null,
			"systemReceivedTime":null,
			"tagType":1,
			"taxAmount":null,
			"thirdOrderId":16467590587697848341646759058769784834,
			"thirdOrderSteps":null,
			"thirdPlatformCreateTime":1681452923,
			"totalGoodsNum":1,
			"totalPaymentAmount":null,
			"updateTime":null,
			"waitPlatformMsgFlag":0,
			"wrongType":0
		}
	],
	"size":10,
	"total":1,
	"totalPage":null
}

```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
问题已修复，请帮忙有2.0.28-SNAPSHOT版本验证，2.0.28版本预计在明天发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本

**Comment by HelloToGithub** [comment]
@wenshao 麻烦再帮忙看下

**Comment by wenshao** [comment]
2.0.28的报错信息还是一样么？

**Comment by HelloToGithub** [comment]
> 2.0.28的报错信息还是一样么？

是的 一样式：com.alibaba.fastjson2.JSONException: TODO : INT32 56 
![image](https://user-images.githubusercontent.com/15622677/232942046-09409ee4-79bc-499b-9dc1-8287b339373f.png)

**Comment by wenshao** [comment]
是否可以直接联系我，我需要你帮我看下上下文信息，我的微信 wenshaojin

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.29
问题已修复，请用新版本
