### ISSUE TITLE
[BUG]Bean对象反序列化失败

### ISSUE THREAD

**Issue by zacat** [alibaba/fastjson2#1370]
调置JSONReader.Feature.InitStringFieldAsEmpty的Feature情况下，执行了不该执行的字段。

 - OS信息：  Windows 10
 - JDK信息：JDK17
 - 版本信息：Fastjson 2.28
 ```java

    @Data
    @NoArgsConstructor
    static class TokenModel {
        String id;
        long createTime;
        Map<String, Object> dataMap = new ConcurrentHashMap<>();
        List<TokenSign> tokenSignList = new Vector<>();
    }

    public static void main(String[] args) {
        TokenModel tokenModel = new TokenModel();
        tokenModel.setId("token:login:session:10001");
        tokenModel.setCreateTime(1681578793249L);
        String str = JSON.toJSONString(tokenModel);
        System.out.println(str);
        tokenModel = JSON.parseObject(str, TokenModel.class, JSONReader.Feature.InitStringFieldAsEmpty);
        System.out.println(tokenModel);
    }
```

```
com.alibaba.fastjson2.JSONException: set dataMap error, not support type class java.lang.String
	at com.alibaba.fastjson2.reader.FieldReaderObjectField.accept(FieldReaderObjectField.java:228) ~[fastjson2-2.0.28.jar:?]
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.initStringFieldAsEmpty(ObjectReaderAdapter.java:536) ~[fastjson2-2.0.28.jar:?]

```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.29-SNAPSHOT/
问题已经修复，请帮忙用2.0.29-SNAPSHOT版本验证。2.0.29版本预计在5月3日发布

**Comment by zacat** [comment]
谢谢。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.29
请用新版本
