### ISSUE TITLE
[BUG] IOUtils 2.0.27 与 2.0.28 对于 Decimal 的处理

### ISSUE THREAD

**Issue by feelinglin** [alibaba/fastjson2#1377]
### 问题描述
*简要描述您碰到的问题。*

从2.0.27升级到2.0.28后，对于同一批数据，2.0.28 报 java.lang.ArrayIndexOutOfBoundsException

### 环境信息
*请填写以下信息：*

 - OS信息：  MacOS 13.3.1 
 - JDK信息：Jdk 1.8
 - 版本信息：2.0.28
 

### 重现步骤
*如何操作可以重现该问题：*

在调用 JSONObject.toString() 时触发

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

正确输出 JSON 字符串

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

2023-04-18 13:45:49.277 [ERROR][http-nio-8080-exec-2] c.k.o.c.b.h.GlobalExceptionHandler:61 - java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.alibaba.fastjson2.util.IOUtils.getDecimalChars(IOUtils.java:348)
	at com.alibaba.fastjson2.util.IOUtils.getDecimalChars(IOUtils.java:248)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeDecimal(JSONWriterUTF16.java:1150)
	at com.alibaba.fastjson2.JSONWriterUTF16.write(JSONWriterUTF16.java:2535)
	at com.alibaba.fastjson2.JSONWriterUTF16.write(JSONWriterUTF16.java:2663)
	at com.alibaba.fastjson2.JSONWriterUTF16.write(JSONWriterUTF16.java:2540)
	at com.alibaba.fastjson2.JSONWriterUTF16.write(JSONWriterUTF16.java:2545)
	at com.alibaba.fastjson2.JSONObject.toString(JSONObject.java:1116)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.29-SNAPSHOT/
问题已修复，请帮忙用2.0.29-SNAPSHOT版本验证，2.0.29版本预计在5月9日前发布。

**Comment by feelinglin** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.29-SNAPSHOT/ 问题已修复，请帮忙用2.0.29-SNAPSHOT版本验证，2.0.29版本预计在5月9日前发布。

2.0.29-SNAPSHOT 已测，PASS

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.29
请用新版本
