### ISSUE TITLE
[BUG] 序列化对象时出现：java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by terminux** [alibaba/fastjson2#1394]
### 问题描述

项目中使用 [Apache的CSV工具库](https://github.com/apache/commons-csv) 读取了一个 `CSV` 文件后得到一个集合，需要使用 `fastjson` 打印这个集合里的对象，伪代码如下：

```java
List<CSVRecord> csvRecordList= readCsvFile("/csvFilePath");
CSVRecord csvRecord = csvRecordList.get(0);
System.out.println(JSON.toJSONString(csvRecord));
```

此时需要序列化 [CSVRecord](https://github.com/apache/commons-csv/blob/master/src/main/java/org/apache/commons/csv/CSVRecord.java) 对象

原来项目中使用的 `fastjson` 版本是：`1.2.11`，上述代码运行正常。当 `1.2.83` 发布时说修复了安全漏洞需要尽快升级，于是我们升级到了 `1.2.83` ，结果上述代码出现了异常：

```java
Exception in thread "main" com.alibaba.fastjson.JSONException: Stream closed
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:314)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:793)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:731)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:688)
	at xxx.util.CsvUtil.main(CsvUtil.java:123)
Caused by: java.io.IOException: Stream closed
	at sun.nio.cs.StreamDecoder.ensureOpen(StreamDecoder.java:46)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:148)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read(BufferedReader.java:182)
	at org.apache.commons.csv.ExtendedBufferedReader.read(ExtendedBufferedReader.java:58)
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:95)
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:664)
	at org.apache.commons.csv.CSVParser.getRecords(CSVParser.java:618)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_CSVParser.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_CSVRecord.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
	... 4 more
```

于是将 `fastjson` 版本升级到 `2.x` ，即最新版：`2.0.28`，依然出现该异常，使用任意 `CSV` 文件均可复现

**Comment by terminux** [comment]
`2.0.28` 中异常的堆栈信息为：

```java
Exception in thread "main" java.io.IOException: Stream closed
	at java.io.BufferedReader.ensureOpen(BufferedReader.java:122)
	at java.io.BufferedReader.read(BufferedReader.java:179)
	at org.apache.commons.csv.ExtendedBufferedReader.read(ExtendedBufferedReader.java:58)
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:95)
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:664)
	at org.apache.commons.csv.CSVParser.getRecords(CSVParser.java:618)
	at com.alibaba.fastjson2.writer.OWG_2_7_CSVParser.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_1_5_CSVRecord.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2334)
	at xxx.util.CsvUtil.main(CsvUtil.java: 123)
```

**Comment by justToBeGood** [comment]
这边复现不了的，能成功打印数据
------------------------------实例代码------------------------------
String[]  headers=new String[]{"a","b","c","d"};
List<CSVRecord> csvRecordList = CSVUtil.read(filePath, headers);
CSVRecord csvRecord = csvRecordList.get(0);
System.out.println(com.alibaba.fastjson.JSON.toJSONString(csvRecord));


---------------------------------------工具类------------------------
public class CSVUtil {
    /**
     *
     * @param csvFile    CSV文件
     * @param fileHeader  CSV文件头
     * @param skipHeader  是否跳过文件头
     * @return 				CSV记录链表
     * @throws IOException
     */
    public static List<CSVRecord> read(final String csvFile, final String[] fileHeader, boolean skipHeader)
            throws IOException {
        CSVFormat format;

        if (skipHeader) {
            // 这里显式地配置一下CSV文件的Header，然后设置跳过Header（要不然读的时候会把头也当成一条记录）
            format = CSVFormat.DEFAULT.withHeader(fileHeader).withFirstRecordAsHeader().withIgnoreHeaderCase()
                    .withTrim();
            // format = CSVFormat.DEFAULT.withHeader(fileHeader)
            // .withIgnoreHeaderCase().withTrim().withSkipHeaderRecord();
        } else {
            format = CSVFormat.DEFAULT.withHeader(fileHeader).withIgnoreHeaderCase().withTrim();
        }
        Reader reader = Files.newBufferedReader(Paths.get(csvFile));

        CSVParser csvParser = new CSVParser(reader, format);
        return csvParser.getRecords();
    }

    /**
     * 读取CSV文件，默认跳过文件头
     * @param csvFile    CSV文件
     * @param fileHeader  CSV文件头
     * @return			CSV记录链表
     * @throws IOException
     */
    public static List<CSVRecord> read(final String csvFile, final String[] fileHeader)
            throws IOException {
        return read(csvFile, fileHeader, true);
    }

-----------------------测试数据---------------------
![image](https://user-images.githubusercontent.com/50023670/236615465-76d29976-b0a7-4ee1-bc4a-19de68e08b85.png)

**Comment by terminux** [comment]
@justToBeGood 这个问题应该只存在于新版本中，请问你的`fastjson`版本是多少呢，可以使用`1.2.83`或者`2.x`试一下

**Comment by terminux** [comment]
* 应该是我在 `finally` 块中关闭了流，然后新版本中的 `fastjson` 再去尝试关闭流，才会出现 `Stream closed`

*  如果`commons-csv`的版本大于 `1.7` 就复现不了了，在新版本中，[`CSVRecord`的`CSVParser`属性增加了`transient`修饰](https://github.com/apache/commons-csv/blob/4ca0556f6b8259bc274bcf11318e0fa005e936aa/src/main/java/org/apache/commons/csv/CSVRecord.java#L57)

* @justToBeGood 如果你的 `commons-csv`的版本小于等于 `1.7` 也复现不了的话，大概率是你的示例代码中没有关闭流的操作，可以增加一下试一下：

```java
finally {
    if (reader != null) {
        reader.close();
    }
}
```

这是我的 `read` 方法：

```java
public static List<CSVRecord> readCsvFile2(final String filePath) throws IOException {
    InputStreamReader reader = null;
    FileInputStream input = null;
    try {
        input = new FileInputStream(filePath);
        reader = new InputStreamReader(input, "GBK");
        CSVParser csvParser = new CSVParser(reader, CSVFormat.DEFAULT);
        return csvParser.getRecords();
    } finally {
        if (input != null) {
            input.close();
        }
        if (reader != null) {
            reader.close();
        }
    }
}
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/blob/main/docs/csv_cn.md

@terminux 你看下fastjson2的CSV API，性能要比commons-csv的性能好。

**Comment by terminux** [comment]
@wenshao 好的，谢谢，不过我们的项目在线上运行很多年了，可能这一时半会不会迁移，后续有机会会考虑`fastjson2`的CSV API
