### ISSUE TITLE
[BUG] 发现一处必现的空指针

### ISSUE THREAD

**Issue by seker** [alibaba/fastjson2#1409]
### 问题描述
*简要描述您碰到的问题。*

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at com.alibaba.fastjson2.util.Fnv.hashCode64(Fnv.java:117)
	at com.alibaba.fastjson2.reader.FieldReader.<init>(FieldReader.java:62)
	at com.alibaba.fastjson2.reader.FieldReaderObject.<init>(FieldReaderObject.java:38)
	at com.alibaba.fastjson2.reader.FieldReaderObjectParam.<init>(FieldReaderObjectParam.java:27)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaderParam(ObjectReaderCreator.java:1995)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createObjectReaderWithCreator(ObjectReaderCreator.java:552)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createObjectReader(ObjectReaderCreator.java:957)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:992)
	at com.alibaba.fastjson2.JSONReader.getObjectReader(JSONReader.java:247)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:507)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
能提供下错误的FASTJSON版本么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.30-SNAPSHOT/
请帮忙用2.0.30-SNAPSHOT版本验证，2.0.30版本预计在5月9日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.30
请用新版本
