### ISSUE TITLE
[BUG] SupportAutoType 出现问题

### ISSUE THREAD

**Issue by changeAtLater** [alibaba/fastjson2#1411]
```java
    public static void main(String[] args) {
        String text = "{\"@type\":\"java.util.concurrent.ConcurrentHashMap\"}";
        System.out.println(JSON.parse(text, JSONReader.Feature.SupportAutoType));
    }
```
```
Exception in thread "main" com.alibaba.fastjson2.JSONException: expect '{', but '[', offset 50, character }, line 1, column 51, fastjson-version 2.0.27 {"@type":"java.util.concurrent.ConcurrentHashMap"}
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:245)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:125)
	at com.alibaba.fastjson2.JSON.parse(JSON.java:168)
	at com.jabqus.sltp.datacollect.utils.CheckpointUtil.main(CheckpointUtil.java:133)
```

我试了一下HashMap是可以的, 请问怎么解决?

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.30
请用新版本
