### ISSUE TITLE
[BUG] JSON string value with whitespace at the end fails to parse

### ISSUE THREAD

**Issue by blutorange** [alibaba/fastjson2#1413]
Tested with latest version 2.0.29

The following should parse as the string `foo`, but it fails with an exception (it worked with fastson-1):

```java
com.alibaba.fastjson2.JSON.parse("  \"foo\"  ")
```

Stacktrace is:

```
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at com.alibaba.fastjson2.JSONReaderASCII.readString(JSONReaderASCII.java:1432)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:271)
	at com.alibaba.fastjson2.JSON.parse(JSON.java:74)
	at de.xima.fc.workflow.DefaultFastJsonConverterTest.testBroken(DefaultFastJsonConverterTest.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

Note: `  " foo"  ` is a valid JSON element according to https://www.json.org/json-en.html

```
json
  element

element
  ws value ws

value
  object
  array
  string
  number
  "true"
  "false"
  "null"

ws
  ""
  '0020' ws
  '000A' ws
  '000D' ws
  '0009' ws

string
  '"' characters '"'
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.30
请用新版本
