### ISSUE TITLE
[BUG]FastJsonHttpMessageConverter将接受信息格式化为JSONObject时出错

### ISSUE THREAD

**Issue by zzs007** [alibaba/fastjson2#1447]
### 问题描述
*简要描述您碰到的问题。*
FastJsonHttpMessageConverter将接受信息格式化为JSONObject时出错

### 环境信息
*请填写以下信息：*

 - OS信息： win11
 - JDK信息： jdk1.8
 - 版本信息：Fastjson2 2.0.28
 

### 重现步骤
*如何操作可以重现该问题：*

1. springMvc配置：
`//final WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter webMvcAutoConfigurationAdapter;
List<HttpMessageConverter<?>> messageConverters = adapter.getMessageConverters();
messageConverters.removeIf(x -> x instanceof FastJsonHttpMessageConverter);
FastJsonHttpMessageConverter jsonConverter = new FastJsonHttpMessageConverter();
FastJsonConfig config = new FastJsonConfig();
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
        config.setWriterFeatures(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat);
        List<MediaType> mediaTypes=new ArrayList<>();
        mediaTypes.add(MediaType.APPLICATION_JSON);
        mediaTypes.add(MediaType.APPLICATION_FORM_URLENCODED);
        jsonConverter.setSupportedMediaTypes(mediaTypes);
        jsonConverter.setDefaultCharset(StandardCharsets.UTF_8);
        jsonConverter.canRead(JSONObject.class,MediaType.APPLICATION_FORM_URLENCODED);
        jsonConverter.setFastJsonConfig(config);
messageConverters.add(jsonConverter);
`
controller:
`
@RestController
@RequestMapping("account")
@RequiredArgsConstructor
public class AccountController {
    
    final AccountService accountService;
    
    @RequestMapping("getList")
    public Map<String, Object> getList(JSONObject paramMap){
//省略业务代码
return new HashMap<>(String, Object);
}
`
2. 输入 `...`  数据
(1)：httpheader:
`application/x-www-form-urlencoded`
(2):数据：{abc={"studentNo":"00000"}}
3. 出现 `...` 错误
`java.lang.IllegalStateException: argument type mismatch
Controller [***.controller.AccountController]
Method [public java.util.Map<java.lang.String, java.lang.Object> ***.controller.AccountController.getList(com.alibaba.fastjson2.JSONObject)] with argument values:
 [0] [type=java.util.LinkedHashMap] [value={abc={\"studentNo\":\"00000\"}}] `

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
{abc:{"studentNo":"00000"}}

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
java.lang.IllegalStateException: argument type mismatch
Controller [***.controller.AccountController]
Method [public java.util.Map<java.lang.String, java.lang.Object> ***.controller.AccountController.getList(com.alibaba.fastjson2.JSONObject)] with argument values:
 [0] [type=java.util.LinkedHashMap] [value={abc={\"studentNo\":\"00000\"}}] 
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:210)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
	Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	... 53 more
	
    argument type mismatch
	Controller [***.controller.AccountController]
	Method [public java.util.Map<java.lang.String, java.lang.Object> ***.controller.AccountController.getList(com.alibaba.fastjson2.JSONObject)] with argument values:
	[0] [type=java.util.LinkedHashMap] [value={abc={\"studentNo\":\"00000\"}}] 

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by zzs007** [comment]
另外同样是httpheader:
application/x-www-form-urlencoded时
如果在注解@RequestBody的情况下，会出现因为没有进行urldecode而无法转化数据

**Comment by CodePlayer** [comment]
感觉你这个不是 fastjson 的bug，而是你自己的用法有问题。
如果想用 JSON 作为请求数据格式，那就不要用 `application/x-www-form-urlencoded` 这种 Content-Type，而应该使用 `application/json`，并且添加 `@RequestBody` 注解 。
你现在这个错误都不是 fastjson 触发的，而是因为你的配置有问题，Spring MVC 自动报错 type mismtach。

**Comment by kraity** [comment]
首先该错误是因`getList(JSONObject paramMap)` 
缺少注解 `@RequestBody` or ` @RequestParam` 等等

由于数据格式为application/x-www-form-urlencoded, 
即使在mediatypes追加`MediaType.APPLICATION_FORM_URLENCODED` , `{abc:{"studentNo":"00000"}}`不是一个json格式会导致解析错误

可以这样手动转换
```java
    @RequestMapping("getList")
    public Map<String, Object> getList(
        @RequestParam(value = "abc") String paramMap
    ) {
        JSONObject obj = JSONObject.parseObject(paramMap);
        return obj;
    }
```

**Comment by zzs007** [comment]
@CodePlayer 你说得对，但是你没法和客户讲理，如果是不同外部项目请求作为服务提供的接口，并且这些外部项目不是受我们控制的，势必需要考虑兼容问题

**Comment by zzs007** [comment]
@kraity 加了@RequestParam 错误是一样的，另外加@requestbody错误就是我的补充评论，并且作为一个非常流行的json后端框架，在Converter中JSONObject可以将数据格式化为除了自身之外的任何序列形式还是有些奇怪了（至少试了实体类和map这样的）（而且还要自己写代码额外转化）

**Comment by zzs007** [comment]
总之就是希望寻找一个通过配置能够同时解决httpheader为application/x-www-form-urlencoded和application/json时能够通过一个接口兼容提供服务的解决方案

**Comment by CodePlayer** [comment]
> @CodePlayer 你说得对，但是你没法和客户讲理，如果是不同外部项目请求作为服务提供的接口，并且这些外部项目不是受我们控制的，势必需要考虑兼容问题

这种来源于客户的奇葩定制需求，是不可能全部指望第三方软件就帮你全部解决的。
因为第三方软件提供的都是通用解决方案，追求最大公约数，再给开发者预留一定的 选项控制 和 自定义扩展空间。
否则，你有这个特殊需求，但是我没有，我引入了第三方软件，反而会出现一些莫名其妙的问题。

你这种情况，其实只需要自定义一个 `org.springframework.web.method.support.HandlerMethodArgumentResolver` 的实现即可，自己想要怎么实现就可以怎么实现。我们项目中也有些特殊的参数解析规则，就是自己去实现的。

**Comment by zzs007** [comment]
> > @CodePlayer 你说得对，但是你没法和客户讲理，如果是不同外部项目请求作为服务提供的接口，并且这些外部项目不是受我们控制的，势必需要考虑兼容问题
> 
> 这种来源于客户的奇葩定制需求，是不可能全部指望第三方软件就帮你全部解决的。 因为第三方软件提供的都是通用解决方案，追求最大公约数，遵守行业规范，再给开发者预留一定的 选项控制 和 自定义扩展空间。 否则，你有这个特殊需求，但是我没有，我引入了第三方软件，反而会出现一些莫名其妙的问题。
> 
> 你这种情况，其实只需要自定义一个 `org.springframework.web.method.support.HandlerMethodArgumentResolver` 的实现即可，自己想要怎么实现就可以怎么实现。我们项目中也有些特殊的参数解析规则，就是自己去实现的。

@CodePlayer 对，所以你看看我的整个issue,自始至终首先JSONObject转换出错才是bug，解决不了的问题才是补充评论，还是有个主次的哈

**Comment by wenshao** [comment]
@zzs007 你建议怎样修改呢？

**Comment by zzs007** [comment]
@wenshao 谢谢您！
我希望第一点：在我提供web接口参数为`@RequestParam JSONObject request`的时候并且httpheader为`application/x-www-form-urlencoded`时传入的web参数能够正确序列化为JSONObject，而不是需要做二次手工转换，即如我最初提的bug描述的那样
第二点：希望寻求一个解决同一个web接口支持两种httpheader为`application/x-www-form-urlencoded`和`application/json`时的请求，这时web接口参数为`@RequestBody JSONObject request`，而这时如果httpheader为`application/x-www-form-urlencoded`，错误是表现为数据就会因为没有进行urldecode而转换失败，不能正确格式化为JSONObject
再次感谢！
