### ISSUE TITLE
[BUG] 泛型反序列化失败，出现 NPE 异常

### ISSUE THREAD

**Issue by CodePlayer** [alibaba/fastjson2#1450]
### 问题描述
目前 Dubbo 3.2.0 已经使用 fastjson 2 作为默认序列化工具。这是个好消息。
然而当我们将从 hessian2 切换到 fastjson2 时，却出现了以下异常 （ 使用 hessian2 时是 OK 的）。

### 环境信息

 - OS信息： Windows 10 或 Linux （ 都必现 ）
 - JDK信息：OpenJDK 17.0.6
 - 版本信息：fastjson 2.0.31
 

### 重现步骤

以下代码可以直接复制到 单元测试 中并执行 `test()` 方法。

```java
public static interface Bean<K extends Serializable> extends Serializable {

    K getId();

}

public static interface Member extends Bean<Long> {

}

@Getter
@Setter
public static class AbstractEntity implements Bean<Long> {

    protected Long id;

}

@Getter
@Setter
public static class AbstractMember extends AbstractEntity implements Member {

    protected String name;

}

@Getter
@Setter
public static class Student extends AbstractMember {

    Integer age;

}

@Test
public void test() throws Exception {
    final Student obj = new Student();
    obj.setId(1L);
    obj.setName("Jim");
    obj.setAge(18);

    byte[] bytes = JSONB.toBytes(obj, JSONWriter.Feature.WriteClassName,
            JSONWriter.Feature.FieldBased,
            JSONWriter.Feature.ErrorOnNoneSerializable,
            JSONWriter.Feature.ReferenceDetection,
            JSONWriter.Feature.WriteNulls,
            JSONWriter.Feature.NotWriteDefaultValue,
            JSONWriter.Feature.NotWriteHashMapArrayListClassName,
            JSONWriter.Feature.WriteNameAsSymbol);

    System.out.println(new String(bytes));

    Object result = JSONB.parseObject(bytes, Member.class, (Filter) null,
            JSONReader.Feature.UseDefaultConstructorAsPossible,
            JSONReader.Feature.ErrorOnNoneSerializable,
            JSONReader.Feature.SupportAutoType,
            JSONReader.Feature.IgnoreAutoTypeNotMatch,
            JSONReader.Feature.UseNativeObject,
            JSONReader.Feature.FieldBased);

    System.out.println(result);
}
```

### 期待的正确结果

希望能够正确反序列化

### 相关日志输出
```
java.lang.NullPointerException
	at com.alibaba.fastjson2.TypeReference.<init>(TypeReference.java:58)
	at com.alibaba.fastjson2.TypeReference.<init>(TypeReference.java:34)
	at com.alibaba.fastjson2.TypeReference$1.<init>(TypeReference.java:229)
	at com.alibaba.fastjson2.TypeReference.get(TypeReference.java:229)
	at com.alibaba.fastjson2.util.BeanUtils.getFieldType(BeanUtils.java:1634)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaderMethod(ObjectReaderCreator.java:2200)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReader(ObjectReaderCreator.java:1392)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.lambda$createFieldReaders$6(ObjectReaderCreator.java:1575)
	at com.alibaba.fastjson2.util.BeanUtils.getters(BeanUtils.java:1055)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaders(ObjectReaderCreator.java:1572)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createObjectReader(ObjectReaderCreator.java:951)
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:259)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:992)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:546)
	at cn.example.JavaTest.test(JavaTest.java:76)
```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/ 问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证

**Comment by CodePlayer** [comment]
目前在 开发环境 验证了1天多，暂未接到任何异常反馈。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.32
请用新版本
