### ISSUE TITLE
[BUG]2.0.31 Feature.SupportAutoType map反序列化失败

### ISSUE THREAD

**Issue by bytew021** [alibaba/fastjson2#1457]
### 问题描述
*简要描述您碰到的问题。*
```shell
Exception in thread "main" com.alibaba.fastjson2.JSONException: not support name 1
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:329)
	at com.alibaba.fastjson2.reader.ORG_1_1_Test2.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:888)
	at MianTestJson.main(MianTestJson.java:19)
```

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：window 10]
 - JDK信息： [e.g.：jdk-17.0.6]
 - 版本信息：[e.g.：Fastjson2 2.0.31]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
    public static void main(String[] args) {

        String jsonStr = "{\"maps\":{\"1\":{\"id\":1}}}"; //失败
//        String jsonStr = "{\"maps\":{1:{\"id\":1}}}"; //成功
        Test2 test3 = JSON.parseObject(jsonStr, Test2.class, JSONReader.Feature.SupportAutoType);
        System.out.println(test3);
    }
    static class Test2 implements Serializable {
        public Map<Integer, MapItem> maps = new HashMap<>();
    }
    static class MapItem {
        public int id;
    }
```

### 期待的正确结果
序列化成功

### 相关日志输出
```shell
Exception in thread "main" com.alibaba.fastjson2.JSONException: not support name 1
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:329)
	at com.alibaba.fastjson2.reader.ORG_1_1_Test2.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:888)
	at MianTestJson.main(MianTestJson.java:19)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/ 
问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证。
