### ISSUE TITLE
[QUESTION]序列化对象的构造函数问题

### ISSUE THREAD

**Issue by TsukasaHwan** [alibaba/fastjson2#1486]
### 请描述您的问题
序列化对象的构造函数包含不存在的类会报ClassNotFound，比如说我封装了一个通用jar和通用对象，但是这个通用jar中的通用对象构造函数依赖了一个<optional>true</optional>的类库，序列化时报ClassNotFound，使用时没有用这个包含不存在类的构造函数，请问一下有何方法避免ClassNotFound

**Comment by TsukasaHwan** [comment]
> 能提供报错信息么？

Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/search/SearchHits
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at com.alibaba.fastjson2.util.BeanUtils.getters(BeanUtils.java:923)
	at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.createObjectWriter(ObjectWriterCreatorASM.java:256)
	at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:369)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2673)
	at com.dangyang.mini.service.impl.OrderServiceImpl.main(OrderServiceImpl.java:476)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.search.SearchHits
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 9 more

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/
问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

**Comment by TsukasaHwan** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/ 问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

不得行，序列化的时候出现的是空json对象


```
public static void main(String[] args) {
    Query query = new Query();
    query.setSize(10);
    query.setCurrent(1);
    QueryResult<Object> objectQueryResult = QueryResult.newEmptyQueryResult(query);
    objectQueryResult.setRecords(Collections.singletonList(1));
    String s = JSON.toJSONString(objectQueryResult);
    System.out.println(s);
}
```
输出为{}

**Comment by vilean2024** [comment]
我们也是服务中自己通过Urlclassloader 进行加载jar包，动态安装和卸载 。
在jar包中使用parseObject ，需要对象中嵌套对象的时候，就会出现java.lang.NoClassDefFoundError
因为DynamicClassLoader ,只能加载主服务的类加载器中的。希望修复这个问题

<img width="752" height="357" alt="Image" src="https://github.com/user-attachments/assets/697a4c45-50de-4423-976f-fc3ecfa6f488" />
