### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RobertHan215** [alibaba/fastjson2#1496]
### 问题描述
用Fastjson 2.0.8序列化了一个JSONArray，然后用Fastjson2 2.0.25进行反序列化时报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [Openjdk 1.8.0_312]
 - 版本信息：[Fastjson2 2.0.25]
 

### 重现步骤
1. 用Fastjson 2.0.8序列化一个JSONArray到文件
2. 用Fastjson 2.0.8反序列化成功
3. 升级到Fastjson 2.0.25之后反序列化失败

### 期待的正确结果
希望能够跨版本反序列化

### 相关日志输出
java.io.InvalidClassException: com.alibaba.fastjson.JSONArray; local class incompatible: stream classdesc serialVersionUID = -2661077227301049955, local class serialVersionUID = 3642856726642946224
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at FastJsonTest.main(FastJsonTest.java:24)

**Comment by wenshao** [comment]
这个没什么办法，很抱歉

**Comment by RobertHan215** [comment]
> 这个没什么办法，很抱歉

我看fastjson2的api没有这个问题，是因为fastjson2更改了写法对吗？

**Comment by yanxutao89** [comment]
> > 这个没什么办法，很抱歉
> 
> 我看fastjson2的api没有这个问题，是因为fastjson2更改了写法对吗？

这应该是因为你class的serialVersionUID不一致导致的

**Comment by telzhou618** [comment]
需要序列化反序列化的对象，显示声明一下 serialVersionUID

**Comment by MNILHX** [comment]
看最新版本com.alibaba.fastjson.JSONArray 这个类下还是没有显示声明serialVersionUID，什么时候可以加上啊？
