### ISSUE TITLE
number too large

### ISSUE THREAD

**Issue by louisjiang** [alibaba/fastjson2#15]
`com.alibaba.fastjson2.JSONException: number too large : 0.784018486000000000000000000000000000000
	at com.alibaba.fastjson2.JSONReader.bigInt(JSONReader.java:1620)
	at com.alibaba.fastjson2.JSONReaderUTF16.readNumber0(JSONReaderUTF16.java:1527)
	at com.alibaba.fastjson2.JSONReader.readNumber(JSONReader.java:605)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:380)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:108)
`

`
{"a":0.784018486000000000000000000000000000000}
`

**Comment by wenshao** [comment]
为了防御DOS攻击，目前做了小数位数最长38的限制，这个可以适当改大，你是什么场景，需要这么长的小数位？

**Comment by louisjiang** [comment]
区块链的计算，建议加上一个配置。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
