### ISSUE TITLE
[BUG]枚举反序列化异常 2.0.32

### ISSUE THREAD

**Issue by kaizen84** [alibaba/fastjson2#1500]
复现代码
```java
import com.alibaba.fastjson2.*;
import com.alibaba.fastjson2.util.ParameterizedTypeImpl;
import org.junit.Test;

import java.util.List;

/**
 * @author 张治保
 * date 2023/5/8
 */
public class FastjsonTest {
    @Test
    public void test() {
        List<TestEnum> enums = List.of(TestEnum.A, TestEnum.B);
        JSONArray array = JSON.parseArray(JSON.toJSONString(enums));
        List<TestEnum> result = array.to(new ParameterizedTypeImpl(new Class[]{TestEnum.class}, null, List.class));
    }

    enum TestEnum {
        A,
        B
    }


}

```

异常
```log
com.alibaba.fastjson2.JSONException: can not convert from class java.lang.String to class top.rows.dubbo.test.consumer.FastjsonTest$TestEnum

	at com.alibaba.fastjson2.reader.ObjectReaderImplList.createInstance(ObjectReaderImplList.java:251)
	at com.alibaba.fastjson2.JSONArray.to(JSONArray.java:983)
	at top.rows.dubbo.test.consumer.FastjsonTest.test(FastjsonTest.java:18)
```

**Comment by kaizen84** [comment]
![image](https://github.com/alibaba/fastjson2/assets/49264728/a1b2188a-6d63-4102-b7c3-14b5886e3431)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/
问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.33
请用新版本
