### ISSUE TITLE
[BUG] fastjson2 遍历输出每个key不报错，当直接tostring时候，Array index out of range: 1024

### ISSUE THREAD

**Issue by zck573693104** [alibaba/fastjson2#1504]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
fastjson2 遍历输出每个key不报错，当直接tostring时候，Array index out of range: 1024
fastjson2:2.0.32
jdk:1.8

**Comment by wenshao** [comment]
请提供报错信息堆栈

**Comment by zck573693104** [comment]
> 请提供报错信息堆栈

好迅速呀 稍等

**Comment by zck573693104** [comment]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 7776
	at com.alibaba.fastjson2.JSONWriterUTF16JDK8.writeString(JSONWriterUTF16JDK8.java:136)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401)
	at com.alibaba.fastjson2.JSONObject.toString(JSONObject.java:1046)
	at java.lang.String.valueOf(String.java:3466)
	at java.io.PrintStream.println(PrintStream.java:821)

**Comment by zck573693104** [comment]
并且 
System.out.println(jsonObject);
出现了
\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000
好神奇，不是每个字段都出现，我检查了自己数据，是不会出现这个情况的，但是

System.out.println(jsonObject);
出现了

**Comment by zck573693104** [comment]
sorry  抱歉，我在家的代码还是
  <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.7</version>
            
        </dependency>
换成
 <dependency>
        <groupId>com.alibaba.fastjson2</groupId>
        <artifactId>fastjson2</artifactId>
        <version>2.0.32</version>
    </dependency>
都解决了，抱歉  我没有再次确认版本
