### ISSUE TITLE
[BUG]JSONPath过滤表达式 && 符号不支持多个

### ISSUE THREAD

**Issue by lukoou3** [alibaba/fastjson2#1516]
### 问题描述
JSONPath过滤表达式 && 符号不支持多个

带解析的json示例：[{"name":"小花","age":18,"city":"扬州"},{"name":"小花","age":20,"city":"扬州"},{"name":"小明","age":18,"city":"扬州"},{"name":"小花","age":18,"city":"苏州"}]
不能解析的JSONPath：$[?( @.name=='小花' && @.age==18 && @.city=='扬州' )]
能解析的JSONPath：$[?( @.name=='小花' && @.age==18)][?( @.city=='扬州' )]

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：windows]
 - JDK信息： [e.g.：jdk1.8.0_181]
 - 版本信息：[e.g.：Fastjson2 2.0.32]
 

### 重现步骤

```java
    @Test
    public void testFastjson2(){
        String jsonArray = "[{\"name\":\"小花\",\"age\":18,\"city\":\"扬州\"},{\"name\":\"小花\",\"age\":20,\"city\":\"扬州\"},{\"name\":\"小明\",\"age\":18,\"city\":\"扬州\"},{\"name\":\"小花\",\"age\":18,\"city\":\"苏州\"}]";
        // 报错
        String path = "$[?( @.name=='小花' && @.age==18 && @.city=='扬州' )]";
        // 没问题
        //String path = "$[?( @.name=='小花' && @.age==18)][?( @.city=='扬州' )]";
        Object rst = JSONPath.of(path).extract(JSONReader.of(jsonArray));;
        System.out.println(rst);
    }
```

### 期待的正确结果
能解析JSONPath

### 相关日志输出
```
java.lang.ClassCastException: com.alibaba.fastjson2.JSONPathFilter$GroupFilter cannot be cast to com.alibaba.fastjson2.JSONPathFilter

	at com.alibaba.fastjson2.JSONPathParser.parseFilterRest(JSONPathParser.java:475)
	at com.alibaba.fastjson2.JSONPathParser.parseFilter(JSONPathParser.java:911)
	at com.alibaba.fastjson2.JSONPathParser.parseArrayAccess(JSONPathParser.java:255)
	at com.alibaba.fastjson2.JSONPathParser.parse(JSONPathParser.java:96)
	at com.alibaba.fastjson2.JSONPath.of(JSONPath.java:434)
	at com.test.JsonPathParseTest.testFastjson2(JsonPathParseTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by lukoou3** [comment]
不好意思，|| 也是不行的，最好一起改了。

```java
    @Test
    public void testFastjson2(){
        String jsonArray = "[{\"name\":\"小花\",\"age\":18,\"city\":\"扬州\"},{\"name\":\"小花\",\"age\":20,\"city\":\"扬州\"},{\"name\":\"小明\",\"age\":18,\"city\":\"扬州\"},{\"name\":\"小花\",\"age\":18,\"city\":\"苏州\"}]";
        // 报错
        String path = "$[?( @.name=='小花' || @.age==18 || @.city=='扬州' )]";
        // 没问题
        //String path = "$[?( @.name=='小花' || @.age==18  )]";
        Object rst = JSONPath.of(path).extract(JSONReader.of(jsonArray));;
        System.out.println(rst);
    }
```

异常：
```
java.lang.ClassCastException: com.alibaba.fastjson2.JSONPathFilter$GroupFilter cannot be cast to com.alibaba.fastjson2.JSONPathFilter

	at com.alibaba.fastjson2.JSONPathParser.parseFilterRest(JSONPathParser.java:475)
	at com.alibaba.fastjson2.JSONPathParser.parseFilter(JSONPathParser.java:911)
	at com.alibaba.fastjson2.JSONPathParser.parseArrayAccess(JSONPathParser.java:255)
	at com.alibaba.fastjson2.JSONPathParser.parse(JSONPathParser.java:96)
	at com.alibaba.fastjson2.JSONPath.of(JSONPath.java:434)
	at com.test.JsonPathParseTest.testFastjson2(JsonPathParseTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.34-SNAPSHOT/
已发布快照版本

**Comment by lukoou3** [comment]
简单的表达式 == > < 等已支持多个 &&或者|| 逻辑表达式，但是对正则匹配和in范围匹配支持的不好，希望能对正则匹配和in范围匹配支持的更好：
```java
    @Test
    public void testFastjson2JSONPathComplie(){
        // yes
        String path = "$[?( @.name=='aa' && @.age==18 && @.city=='beijing' && @.province=='beijing' )]";
        System.out.println(JSONPath.of(path));
        // yes
        path = "$[?( @.name=='aa' || @.age==16 || @.city=='beijing' || @.province=='beijing')]";
        System.out.println(JSONPath.of(path));
        // yes
        path = "$[?( @.name =~ /aa/ )]";
        System.out.println(JSONPath.of(path));
        // yes
        path = "$[?( @.age==18 && (@.name =~ /aa/)  )]";
        System.out.println(JSONPath.of(path));
        // error
        path = "$[?( @.name =~ /aa/ && @.age==18 )]";
        System.out.println(JSONPath.of(path));
        // error
        path = "$[?( (@.name =~ /aa/) && @.age==18 )]";
        System.out.println(JSONPath.of(path));
        // yes
        path = "$[?( @.age==18 && (@.name in ('aa', 'aa2') )  )]";
        System.out.println(JSONPath.of(path));
        // error
        path = "$[?( (@.name in ('aa', 'aa2')) && @.age==18 )]";
        System.out.println(JSONPath.of(path));
    }
```

**Comment by yanxutao89** [comment]
May I continue to undertake this issue ? @wenshao

**Comment by wenshao** [comment]
> May I continue to undertake this issue ? @wenshao

welcome!

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.34
问题已修复，请用新版本
