### ISSUE TITLE
[BUG] Kotlin的 kotlin.collections.EmptyList不能序列化

### ISSUE THREAD

**Issue by qinsss** [alibaba/fastjson2#1540]
### 问题描述
*简要描述您碰到的问题。*
Kotlin的类不能序列化

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
Caused by: org.apache.dubbo.remoting.RemotingException: com.alibaba.fastjson2.JSONException: create instance error class kotlin.collections.EmptyList, offset 32
com.alibaba.fastjson2.JSONException: create instance error class kotlin.collections.EmptyList, offset 32
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.readJSONBObject(ObjectReaderImplList.java:400)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:535)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:149)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.handleValue(DecodeableRpcResult.java:161)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:106)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:138)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:62)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:141)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:70)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:202)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:286)

....
Caused by: java.lang.IllegalAccessException: class com.alibaba.fastjson2.reader.ObjectReaderImplList cannot access a member of class kotlin.collections.EmptyList with modifiers "private"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.34
问题已修复，请用新版本
