### ISSUE TITLE
[BUG] JSON.isValid 错误返回值

### ISSUE THREAD

**Issue by MisakaTAT** [alibaba/fastjson2#1542]
### 问题描述
`JSON.isValid("11111")` 结果为 `true`

### 环境信息
*请填写以下信息：*

 - OS信息：  `Windows 11 Pro WorkStation 22H2 22631.1825`
 - JDK信息： `Azul-17.0.2`
 - 版本信息：`Fastjson2 2.0.33`
 

### 重现步骤
```java
@Test
void test(){
    assertFalse(JSON.isValid("测试"));            // pass
    assertFalse(JSON.isValid("123abc"));         // pass
    assertFalse(JSON.isValid("11111"));          // fail
    assertTrue(JSON.isValid("{\"k\": \"v\"}"));  // pass
}
```

### 期待的正确结果
`JSON.isValid("11111")` 结果为 `false`

### 相关日志输出
```
com.alibaba.fastjson2.JSONException: syntax error : 1, offset 1, character 1, line 1, column 2, fastjson-version 2.0.29 111
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:1930) ~[fastjson2-2.0.29.jar:na]
	at com.alibaba.fastjson2.JSON.parseArray(JSON.java:2071) ~[fastjson2-2.0.29.jar:na]
	at com.mikuac.shiro.common.utils.ShiroUtils.rawToArrayMsg(ShiroUtils.java:217) ~[shiro-2.0.4.jar:na]
	at com.mikuac.shiro.common.utils.EventUtils.pushAnyMessageEvent(EventUtils.java:99) ~[shiro-2.0.4.jar:na]
	at com.mikuac.shiro.common.utils.EventUtils.setAnyMessageEvent(EventUtils.java:120) ~[shiro-2.0.4.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.process(MessageEvent.java:85) ~[shiro-2.0.4.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.group(MessageEvent.java:123) ~[shiro-2.0.4.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.handler(MessageEvent.java:56) ~[shiro-2.0.4.jar:na]
	at com.mikuac.shiro.handler.EventHandler.handler(EventHandler.java:115) ~[shiro-2.0.4.jar:na]
	at com.mikuac.shiro.task.ShiroAsyncTask.execHandlerMsg(ShiroAsyncTask.java:38) ~[shiro-2.0.4.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-6.0.9.jar:6.0.9]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by MisakaTAT** [comment]
#1541

**Comment by yanxutao89** [comment]
A JSON value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested. So, JSON.isValid("11111") should return TRUE

**Comment by MisakaTAT** [comment]
> A JSON value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested. So, JSON.isValid("11111") should return TRUE

Thank you for your reply. So, to check if a value is a valid JSON object, just need to use `JSON.isValidObject`.

**Comment by yanxutao89** [comment]
> > A JSON value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested. So, JSON.isValid("11111") should return TRUE
> 
> Thank you for your reply. So, to check if a value is a valid JSON object, just need to use `JSON.isValidObject`.

You are right. There is also JSON.isValidArray for array input.
