### ISSUE TITLE
[BUG]  Decode rpc result failed: auotype not support 

### ISSUE THREAD

**Issue by rickiehsu** [alibaba/fastjson2#1561]
**问题描述**
Decode rpc result failed: auotype not support : com.example.model.sys.PortalModel, dubbo version: 3.2.2
at com.alibaba.fastjson2.JSONReaderJSONB.autoTypeError(JSONReaderJSONB.java:1223) ~[fastjson2-2.0.33.jar:?]
at com.alibaba.fastjson2.JSONReaderJSONB.checkAutoType(JSONReaderJSONB.java:1192) ~[fastjson2-2.0.33.jar:?]
at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readJSONBObject(ObjectReaderImplObject.java:310) ~[fastjson2-2.0.33.jar:?]
at com.alibaba.fastjson2.reader.ORG_3_5_Pagination.readJSONBObject(Unknown Source) ~[?:?]
at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:547) ~[fastjson2-2.0.33.jar:?]
at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:149) ~[dubbo-3.2.2.jar:3.2.2]

**测试例子**
```
public class Pagination<T> implements Serializable {  
    private int recordsTotal;
    private List<T> data;

    public int getRecordsTotal() {
        return recordsTotal;
    }

    public void setRecordsTotal(int recordsTotal) {
        this.recordsTotal = recordsTotal;
    }

    public List<T> getData() {
        return data;
    }

    public void setData(List<T> data) {
        this.data = data;
    }
}

public class PortalModel implements Serializable {
    private String id;

    private String title;

    private String bizId;

    private String content;

    private Date creatTime;

    private Date dueTime;

    private String state;

    private Integer closeType;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBizId() {
        return bizId;
    }

    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    public Date getDueTime() {
        return dueTime;
    }

    public void setDueTime(Date dueTime) {
        this.dueTime = dueTime;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Integer getCloseType() {
        return closeType;
    }

    public void setCloseType(Integer closeType) {
        this.closeType = closeType;
    }
}

//返回的对象

public Pagination listBulletins(User user) {
        Pagination page = new Pagination();
        page.setRecordsTotal(100);
        List<PortalModel> models = new ArrayList<>();
        Date now = new Date();
        Iterator<SyBulletin> it = bulletins.iterator();
        while (it.hasNext()) {
            SyBulletin bulletin = it.next();
            Integer pkid = bulletin.getPkid();
            Date expireDate = bulletin.getExpireDate();
            PortalModel pmodel = new PortalModel();
            pmodel.setId(pkid.toString());
            pmodel.setBizId(bulletin.getPkid().toString());
            pmodel.setTitle(bulletin.getTopic());
            pmodel.setContent(bulletin.getBltDesc());
            pmodel.setCreatTime(bulletin.getCreateTime());
            pmodel.setDueTime(expireDate);
            models.add(pmodel);
        }
        page.setData(models);
        return page;
    }

```

**Comment by wenshao** [comment]
com.example.model.sys.PortalModel 这个没加入到反序列化白名单？

**Comment by rickiehsu** [comment]
> com.example.model.sys.PortalModel 这个没加入到反序列化白名单？

thanks！ 通过增加security/serialize.allowlist解决问题。
