### ISSUE TITLE
[BUG] 使用openapi_3 ，fastjson2-extension-spring6   : 2.0.34 时，访问文档接口报错

### ISSUE THREAD

**Issue by OnceCrazyer** [alibaba/fastjson2#1601]
开发环境: spring boot  :3.1.1
                 jdk   : 17
                fastjson2-extension-spring6   : 2.0.34
**### 使用FastJsonHttpMessageConverter作为整个项目序列化方案时，报如下错误，但是使用 2.0.32是正常的**

Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson2.JSONPObject
	at com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:134) ~[fastjson2-extension-spring6-2.0.34.jar:?]
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:225) ~[spring-web-6.0.10.jar:6.0.10]
	at com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:86) ~[fastjson2-extension-spring6-2.0.34.jar:?]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:297) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:245) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:136) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.10.jar:6.0.10]
	... 41 more

**Comment by wenshao** [comment]
是不是存在fastjson2低版本了？

**Comment by OnceCrazyer** [comment]
> 是不是存在fastjson2低版本了？
换成2.0.36 最新版本，问题已不存在
