### ISSUE TITLE
[BUG] 对多层嵌套的List进行toJSONString时发生异常：HV000116: getParameterIndex() may only be invoked for nodes of type ElementKind.PARAMETER

### ISSUE THREAD

**Issue by missyou1** [alibaba/fastjson2#1608]
### 问题描述
![image](https://github.com/alibaba/fastjson2/assets/30522042/6a964ea4-2823-43fc-83c2-f853c0229d90)
![image](https://github.com/alibaba/fastjson2/assets/30522042/58709ca1-0147-4958-ae2e-a95e6b43ecaa)

这一样一个正常的List进行JSONObject.toJSONString时发生异常：Exception in thread "main" java.lang.IllegalArgumentException: HV000116: getParameterIndex() may only be invoked for nodes of type ElementKind.PARAMETER

### 环境信息
*请填写以下信息：*

 - OS信息： windows10
 - JDK信息：
 - 
![image](https://github.com/alibaba/fastjson2/assets/30522042/433bb1ac-05c1-41e1-bae1-c71664123c8b)

 - 版本信息： 
 -    <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.31</version>
        </dependency>
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
Exception in thread "main" java.lang.IllegalArgumentException: HV000116: getParameterIndex() may only be invoked for nodes of type ElementKind.PARAMETER.
	at org.hibernate.validator.internal.util.Contracts.assertTrue(Contracts.java:67)
	at org.hibernate.validator.internal.engine.path.NodeImpl.getParameterIndex(NodeImpl.java:366)
	at com.alibaba.fastjson2.writer.OWG_2_12_NodeImpl.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_1_3_PathImpl.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:550)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:373)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:550)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:373)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2453)
	at com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1142)
	at com.k1k.wonderland.common.util.ValidUtil.validChecker(ValidUtil.java:37)
	at com.k1k.wonderland.ybd.secure_checker.SecureChecker.main(SecureChecker.java:51)
Disconnected from the target VM, address: '127.0.0.1:52957', transport: 'socket'

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by missyou1** [comment]
[{"className":"com.k1k.wonderland.ybd.dto.YbdOrderPushCmd","errMsg":[{"className":{"nodeList":[{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},{"name":"pushSecureKey","parent":{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"hashCode":693373453,"asString":"pushSecureKey"}],"nodeListRequiresCopy":true,"currentLeafNode":{"name":"pushSecureKey","parent":{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"hashCode":693373453,"asString":"pushSecureKey"},"hashCode":-93656284},"errMsg":"pushSecureKey不能为空"},{"className":{"nodeList":[{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},{"name":"goods","parent":{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"value":{"goodsId":"2222","goodsUrl":["http://xx.cn/1.jpg","http://xx.cn/2.jpg"],"goodsPrice":232323,"goodsSpecs":"xxxx","goodsNum":1},"hashCode":776772597,"asString":"goods"},{"name":"goodsName","parent":{"name":"goods","parent":{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"value":{"goodsId":"2222","goodsUrl":["http://xx.cn/1.jpg","http://xx.cn/2.jpg"],"goodsPrice":232323,"goodsSpecs":"xxxx","goodsNum":1},"hashCode":776772597,"asString":"goods"},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"hashCode":806494752,"asString":"goodsName"}],"nodeListRequiresCopy":true,"currentLeafNode":{"name":"goodsName","parent":{"name":"goods","parent":{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"value":{"goodsId":"2222","goodsUrl":["http://xx.cn/1.jpg","http://xx.cn/2.jpg"],"goodsPrice":232323,"goodsSpecs":"xxxx","goodsNum":1},"hashCode":776772597,"asString":"goods"},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"hashCode":806494752,"asString":"goodsName"},"hashCode":488522482},"errMsg":"goodsName不能为空"}]},{"className":"com.k1k.wonderland.ybd.dto.Goods","errMsg":[{"className":{"nodeList":[{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},{"name":"goodsName","parent":{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"hashCode":806494752,"asString":"goodsName"}],"nodeListRequiresCopy":true,"currentLeafNode":{"name":"goodsName","parent":{"isIterable":false,"kind":"BEAN","parameterTypes":[],"hashCode":1082990569},"isIterable":false,"kind":"PROPERTY","parameterTypes":[],"hashCode":806494752,"asString":"goodsName"},"hashCode":19465015},"errMsg":"goodsName不能为空"}]}]



这是用gson 转String的数据

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/blob/main/docs/features_cn.md
看下这里的JSONWriter.Feature.IgnoreErrorGetter

**Comment by ReduckProject** [comment]
> https://github.com/alibaba/fastjson2/blob/main/docs/features_cn.md



IgnoreErrorGetter | 忽略setter方法的错误
这里文档描述有误，应该是`忽略getter方法的错误`
-- | --

**Comment by ReduckProject** [comment]
> https://github.com/alibaba/fastjson2/blob/main/docs/features_cn.md 看下这里的JSONWriter.Feature.IgnoreErrorGetter



IgnoreErrorGetter | 忽略setter方法的错误
这里文档描述有误，应该是`忽略getter方法的错误`
