### ISSUE TITLE
[BUG] JSONArray.toJSONString() 出现 StackOverflowException

### ISSUE THREAD

**Issue by liungkejin** [alibaba/fastjson2#1612]
### 问题描述
在使用 `JSONArray.toJSONString()` 方法时出现 `StackOverflowException`，出现了无限递归导致的堆栈溢出问题，

### 环境信息

 - OS信息： OnePlus LE2120  Android 13
 - JDK信息：Open JDK 11.0.15
 - 版本信息：2.0.34.1.android4   / 2.0.21.android 均出现
 

### 重现步骤

```java
    public static String toJsonString(android.net.Uri uri) {
        JSONArray array = new JSONArray();
        JSONObject object = new JSONObject();
        object.put("bbb", uri);
        array.add(object);
        return array.toJSONString();
    }
```

调用此方法即可复现

### 期待的正确结果

正确输出 Json String

### 相关日志输出

```log
at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
at com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:353)
at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
at com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:353)
at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
at com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:353)
at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:269)
at com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:353)
at com.alibaba.fastjson2.JSONWriterUTF16.write(JSONWriterUTF16.java:2138)
at com.alibaba.fastjson2.JSONWriterUTF16.write(JSONWriterUTF16.java:2251)
at com.alibaba.fastjson2.JSONArray.toString(JSONArray.java:901)
at com.alibaba.fastjson2.JSONArray.toJSONString(JSONArray.java:920)
at com.kjin.zapp.AlbumActivity.toJsonString(AlbumActivity.java:156)
at com.kjin.zapp.AlbumActivity.access$200(AlbumActivity.java:45)
at com.kjin.zapp.AlbumActivity$AlbumItemListAdapter$1.onClick(AlbumActivity.java:220)
```

**Comment by wenshao** [comment]
有循环引用的场景，需要加上这个 JSONWriter.Feature.ReferenceDetection

**Comment by liungkejin** [comment]
> 有循环引用的场景，需要加上这个 JSONWriter.Feature.ReferenceDetection

```java
    public static String toJsonString(android.net.Uri uri) {
        JSONArray array = new JSONArray();
        JSONObject object = new JSONObject();
        object.put("bbb", uri);
        array.add(object);
        return array.toJSONString();
    }
```
这个代码没有循环引用吧，只是将一个 uri 塞进了 JSONObject 中

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.38
请用新版本
