### ISSUE TITLE
[BUG] 当类中有get方法且返回值为void时会报ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by slatonwu** [alibaba/fastjson2#1613]
### 问题描述
*简要描述您碰到的问题。*
当类中有get方法且返回值为void时，序列化对象会报ArrayIndexOutOfBoundsException

### 环境信息
windows 11
*请填写以下信息：*

 - OS信息： windows 11
 - JDK信息：oracle jdk 1.8.0_212
 - 版本信息：Fastjson2 2.0.34
 

### 重现步骤
*如何操作可以重现该问题：*
新建类：
package com.example.test;

public class CustomerDTO  {

    public void getApp() {
        System.out.println("2222222222222");

    }
}

CustomerDTO customerDTO = new CustomerDTO();
    String content = JSON.toJSONString(customerDTO);
    System.out.println(content);

```



### 相关日志输出
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.alibaba.fastjson2.internal.asm.Frame.getConcreteOutputType(Frame.java:1062)
	at com.alibaba.fastjson2.internal.asm.Frame.merge(Frame.java:1095)
	at com.alibaba.fastjson2.internal.asm.MethodWriter.visitMaxs(MethodWriter.java:554)
	at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.genMethodWriteJSONB(ObjectWriterCreatorASM.java:840)
	at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.createObjectWriter(ObjectWriterCreatorASM.java:566)
	at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:369)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2673)
	at com.example.test.TestApplication.main(TestApplication.java:42)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.35
问题已修复，请用新版本
