### ISSUE TITLE
[BUG] 序列化Exception时在ContextValueFilter获取Field为null

### ISSUE THREAD

**Issue by zoze0** [alibaba/fastjson2#1709]
### 问题描述
序列化Exception时在ContextValueFilter获取Field为null

### 环境信息

 - OS信息：  any
 - JDK信息： JDK1.8
 - 版本信息：Fastjson2 2.0.38
 

### 重现步骤

```java
// Filter
public class Myfilter implements ContextValueFilter {
    @Override
    public Object process(BeanContext context, Object object, String name, Object value) {
        final Field field = context.getField();
        final Class<?> type = field.getType();
        return value;
    }
}
```

```java
// main
public static void main(String[] args) {
        try {
            int i = 5 / 0;
        } catch (Exception e) {
            System.out.println(JSON.toJSONString(e, new Myfilter()));
        }
    }
```
### 期待的正确结果
Exception 序列化正常

### 相关日志输出
```java
Exception in thread "main" java.lang.NullPointerException
	at com.example.teststack.Myfilter.process(Myfilter.java:12)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:544)
	at com.alibaba.fastjson2.writer.ObjectWriter.writeWithFilter(ObjectWriter.java:138)
	at com.alibaba.fastjson2.writer.ObjectWriterException.write(ObjectWriterException.java:35)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2844)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
