### ISSUE TITLE
[BUG] 序列化"00000000" Date 空指针

### ISSUE THREAD

**Issue by zoze0** [alibaba/fastjson2#1711]
### 环境信息

 - JDK信息：JDK1.8
 - 版本信息：Fastjson2 2.0.38
 

### 重现步骤

```java
// Bean
public class MyBean {
    private Date now;

    public Date getNow() {
        return now;
    }

    public void setNow(Date now) {
        this.now = now;
    }

    @Override
    public String toString() {
        return "MyBean{" +
                "now=" + now +
                '}';
    }
}

```

```java
// main
public static void main(String[] args) {
        Map map = new HashMap();
        map.put("now", "00000000");
       // Hutool BeanUtil
        final MyBean bean = BeanUtil.mapToBean(map, MyBean.class, false, null);
        SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        System.out.println(fmt.format(bean.getNow()));
        System.out.println(JSON.toJSONString(bean));
    }

```

### 相关日志输出
```java
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.writer.FieldWriterDate.writeDate(FieldWriterDate.java:298)
	at com.alibaba.fastjson2.writer.OWG_1_1_MyBean.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2756)
	... 1 more
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
