### ISSUE TITLE
JSON.parseArray(String text, Class<T> type)方法指定Integer类型解析字符串导致OOM[BUG]

### ISSUE THREAD

**Issue by gbhello** [alibaba/fastjson2#1717]
### 问题描述
使用JSON.parseArray(String text, Class<T> type)方法解析字符串时，指定解析类型，在字符串是非指定类型数组时，会导致OOM

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：WINDOWS10 4Core 2.3GHz 12 GB]
 - JDK信息： [e.g.： HotSpot "1.8.0_152"]
 - 版本信息：[e.g.：Fastjson2 2.0.38]
 

### 重现步骤
如下：
```java
    public static void main(String args[]) {
        JSON.parseArray("[jia]", Integer.class);
    }
```

### 期待的正确结果
如之前的版本一样抛出解析异常，这个bug是新引入的，之前某个版本是可用的

### 相关日志输出
```shell
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2389)
	at com.alibaba.fastjson2.JSON.parseArray(JSON.java:2497)
	at com.box.Main1.main(Main1.java:27)
```

#### 附加信息
fighting💪

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本

**Comment by wendao8469759** [comment]
.... 真棒
