### ISSUE TITLE
[BUG] 反序列化嵌套异常时异常

### ISSUE THREAD

**Issue by Mr95ninefive** [alibaba/fastjson2#1724]
### 问题描述
嵌套的异常反序列化会报错

### 环境信息
 - OS信息：  macos
 - JDK信息： oraclejdk 17
 - 版本信息：Fastjson2: 2.0.38
 

### 重现步骤
* 随便写个带异常类型字段的类
  ```java
  public class MyObj {
  
      private Throwable throwable;
  
      public MyObj() {
      }
  
      public MyObj(Throwable throwable) {
          this.throwable = throwable;
      }
  
      public Throwable getThrowable() {
          return throwable;
      }
  
      public void setThrowable(Throwable throwable) {
          this.throwable = throwable;
      }
  }
  ```

* 随便序列化一个实例再反序列
  ```java
  MyObj obj = new MyObj(new Exception("异常信息2", new Exception("异常信息1")));
  String json = JSON.toJSONString(obj, JSONWriter.Feature.WriteClassName, JSONWriter.Feature.NotWriteRootClassName);
  JSON.parseObject(json, MyObj.class, JSONReader.Feature.SupportAutoType);
  ```
  * 上述这种```new Exception("异常信息2", new Exception("异常信息1"))```会出现下面的异常
  * 没嵌套的```new Exception("异常信息")```可以正常反序列化不会异常

### 期待的正确结果
能正常反序列化回去

### 相关日志输出
```shell
Exception in thread "main" com.alibaba.fastjson2.JSONException: illegal fieldName input,, offset 369, character ,, line 1, column 370, fastjson-version 2.0.38 {"throwable":{"@type":"Exception","cause":{"@type":"Exception","localizedMessage":"异常信息1","message":"异常信息1","stackTrace":[{"@type":"StackTraceElement","fileName":"Test.java","lineNumber":10,"className":"my.exp.Test","methodName":"test"},{"@type":"StackTraceElement","fileName":"Main.java","lineNumber":6,"className":"my.exp.Main","methodName":"main"}],"suppressed":[]},"localizedMessage":"异常信息2","message":"异常信息2","stackTrace":[{"@type":"StackTraceElement","fileName":"Test.java","lineNumber":10,"className":"my.exp.Test","methodName":"test"},{"@type":"StackTraceElement","fileName":"Main.java","lineNumber":6,"className":"my.exp.Main","methodName":"main"}],"suppressed":[]}}
	at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:1340)
	at com.alibaba.fastjson2.reader.ObjectReaderException.readObject(ObjectReaderException.java:151)
	at com.alibaba.fastjson2.reader.ObjectReader.readObject(ObjectReader.java:266)
	at com.alibaba.fastjson2.reader.ObjectReaderException.readObject(ObjectReaderException.java:171)
	at com.alibaba.fastjson2.reader.ORG_1_1_MyObj.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1002)
	at my.exp.Test.test(Test.java:12)
	at my.exp.Main.main(Main.java:6)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
