### ISSUE TITLE
[BUG] @JSONField注解设置字段不进行序列化失效

### ISSUE THREAD

**Issue by mrhegit** [alibaba/fastjson2#1728]
### 问题描述
@JSONField注解设置字段不进行反序列化失效；在我的特殊使用场景下，由于我需要序列化的对象中含有默认不支持自动序列化的类型，因此我使用@JSONField注解设置不进行序列化`@JSONField(serialize = false)`，但是在我使用的过程中出现失效的情况，我不知道原因；而且在一些情况下`@JSONField(serialize = false)`可以生效，详细见重现步骤。

### 环境信息

 - OS信息：   Windows 10
 - JDK信息： Oracle JDK 11
 - 版本信息：Fastjson2 2.0.38
 

### 重现步骤
我在使用redis保存Spring Security框架中的UserDetails信息，redis设置的序列化器如下：
```java
@Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory connectionFactory)
    {
        RedisTemplate<String, Object> template = new RedisTemplate<>();
        template.setConnectionFactory(connectionFactory);

        GenericFastJsonRedisSerializer serializer = new GenericFastJsonRedisSerializer();

        // 使用StringRedisSerializer来序列化和反序列化redis的key值
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(serializer);

        // Hash的key也采用StringRedisSerializer的序列化方式
        template.setHashKeySerializer(new StringRedisSerializer());
        template.setHashValueSerializer(serializer);

        template.afterPropertiesSet();
        return template;
    }
```
我使用的序列化对象如下：
```java
@Data
@NoArgsConstructor
@AllArgsConstructor
public class LoginUser implements UserDetails {

    private User user;
    //存储权限信息
    private List<String> permissions;

    //存储SpringSecurity所需要的权限信息的集合
    @JSONField(serialize = false)
    private List<GrantedAuthority> myAuthorities;

    public LoginUser(User user, List<String> permissions) {
        this.user = user;
        this.permissions = permissions;
    }


    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        if(myAuthorities !=null){
            return myAuthorities;
        }
        //把permissions中字符串类型的权限信息转换成GrantedAuthority对象存入authorities中
        myAuthorities = permissions.stream().
                map(SimpleGrantedAuthority::new)
                .collect(Collectors.toList());
        return myAuthorities;
    }

    @Override
    public String getPassword() {
        return user.getPassword();
    }

    @Override
    public String getUsername() {
        return user.getUserName();
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}
```
在使用redis反序列化的过程中，出现了序列化错误的报错，说明`List<GrantedAuthority> myAuthorities`依然进行了序列化，**但是当
List<GrantedAuthority> 变量名称为authorities时，注解@JSONField(serialize = false)正常忽略字段序列化**
### 期待的正确结果
我想知道导致这种情况发生的原因

### 相关日志输出
```
2023-08-09 22:41:18.590 ERROR 44220 --- [p-nio-80-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.data.redis.serializer.SerializationException: Could not deserialize: autoType is not support. org.springframework.security.core.authority.SimpleGrantedAuthority; nested exception is com.alibaba.fastjson2.JSONException: autoType is not support. org.springframework.security.core.authority.SimpleGrantedAuthority
	at com.alibaba.fastjson2.support.spring.data.redis.GenericFastJsonRedisSerializer.deserialize(GenericFastJsonRedisSerializer.java:71) ~[fastjson2-extension-spring5-2.0.38.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.deserializeValue(AbstractOperations.java:360) ~[spring-data-redis-2.7.14.jar:2.7.14]
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:62) ~[spring-data-redis-2.7.14.jar:2.7.14]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224) ~[spring-data-redis-2.7.14.jar:2.7.14]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191) ~[spring-data-redis-2.7.14.jar:2.7.14]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97) ~[spring-data-redis-2.7.14.jar:2.7.14]
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54) ~[spring-data-redis-2.7.14.jar:2.7.14]
	at indi.mrhe.utils.RedisUtils.getCacheObject(RedisUtils.java:72) ~[classes/:na]
	at indi.mrhe.filter.JwtAuthenticationTokenFilter.doFilterInternal(JwtAuthenticationTokenFilter.java:50) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter
```

**Comment by wenshao** [comment]
field myAuthorities和method getAuthorities无法识别到对应关系，将myAuthorities改名为authorities试试看？

**Comment by mrhegit** [comment]
> field myAuthorities和method getAuthorities无法识别到对应关系，将myAuthorities改名为authorities试试看？

是的，将变量名称改为authorities可以正常序列化，我在上面的issue也有提及到；fastjson会有一个检查get方法对应类型变量名称的机制吗？

**Comment by wenshao** [comment]
机制和 java.beans.Introspector#decapitalize 类似
