### ISSUE TITLE
[BUG] 可以序列化 java.nio.file.Path ，但不能反序列化

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/fastjson2#1732]
### 问题描述

```java
import java.nio.file.Path;
import java.nio.file.Paths;

import com.alibaba.fastjson2.JSON;

public class PathTest {

    private Path path;

    public Path getPath() {
        return path;
    }

    public void setPath(Path path) {
        this.path = path;
    }

    public static void main(String[] args) {
        PathTest test = new PathTest();
        test.setPath(Paths.get("/tmp"));

        String jsonString = JSON.toJSONString(test);

        System.out.println(jsonString);

        PathTest test2 = JSON.parseObject(jsonString, PathTest.class);

    }
}

```

出错信息：

```
{"path":"/tmp"}
Exception in thread "main" com.alibaba.fastjson2.JSONException: expect ':', but 125, offset 9, character ", line 1, column 10, fastjson-version 2.0.36 {"path":"/tmp"}
	at com.alibaba.fastjson2.JSONReaderASCII.readFieldNameHashCode(JSONReaderASCII.java:614)
	at com.alibaba.fastjson2.reader.ObjectReaderInterface.readObject(ObjectReaderInterface.java:140)
	at com.alibaba.fastjson2.reader.ORG_1_1_PathTest.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:726)
	at PathTest.main(PathTest.java:26)

```

### 环境信息

```xml
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.36</version>
        </dependency>
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by hengyunabc** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/ 问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

测试ok

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
