### ISSUE TITLE
[BUG]序列化具有泛化字段的对象失败

### ISSUE THREAD

**Issue by tiandankanfeng** [alibaba/fastjson2#1769]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [Macos]
 - JDK信息： [e.g.：Openjdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.39]
 

### 重现步骤
*如何操作可以重现该问题：*
将具有泛化属性的对象专为JSON，再转为Fastjson时有报异常
```java
//可在此输入示例代码
    @Test
    public void testOnInvokeJsonGenericParse() {
        AlimeFromConfig alimeFromConfig = new AlimeFromConfig();
        alimeFromConfig.setDefaultFromId("birtney");

        List<AbstractConfig> sourceConfigs = Lists.newArrayList();
        sourceConfigs.add(alimeFromConfig);
        Map<String, List<AbstractConfig>> configMap = new HashMap<>();
        configMap.put("FROM", sourceConfigs);

        BirtneyModel sourceModel = new BirtneyModel();
        sourceModel.setConfigs(configMap);

        BirtneyModel birtneyModel =
            JSONObject.parseObject(JSON.toJSONString(sourceModel, JSONWriter.Feature.WriteByteArrayAsBase64),
                BirtneyModel.class, Feature.Base64StringAsByteArray);

        System.out.println(birtneyModel);
    }

@Data
@EqualsAndHashCode(callSuper = true)
public class AlimeFromConfig extends AbstractConfig {

    private String defaultFromId;

    private Map<String, String> urlMap;

}

public abstract class AbstractConfig implements Serializable {

    private Long id;

    private String type;

    private String subType;

    private String sceneId;

    private Integer version;

}

@Data
public class BirtneyModel implements Serializable {

    private Map<String, List<AbstractConfig>> configs;

}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
正常能够序列化，并且不丢失泛化对象信息

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

com.alibaba.fastjson2.JSONException: create instance error, class com.birtney.jsontools.fastjson2.model.AbstractConfig

	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:400)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:332)
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.readObject(ObjectReaderImplList.java:609)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:373)
	at com.alibaba.fastjson2.reader.ORG_1_1_BirtneyModel.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1002)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1994)
	at com.birtney.jsontools.fastjson2.BirtneyJsontoolsFastjson2ApplicationTests.testOnInvokeJsonGenericParse(BirtneyJsontoolsFastjson2ApplicationTests.java:40)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.InstantiationException
	at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:394)
	... 75 more

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
<img width="1492" alt="image" src="https://github.com/alibaba/fastjson2/assets/58939282/c68f6f71-ffae-4e96-b0ef-2cfe76d4f644">

**Comment by tiandankanfeng** [comment]
> 把所有的` List<AbstractConfig>` 替换为 `List<? super AbstractConfig> `试试



> 把所有的` List<AbstractConfig>` 替换为 `List<? super AbstractConfig> `试试

切换后果然可以行得通了，这块是什么原理呢，必须得去设定其下界？设定下界是保证编译不报错且写入的数据不会丢失是么？

**Comment by wenshao** [comment]
使用? super之后List中的item类型是JSONObject。序列化的时候，没有保留类型信息，反序列化是无法成功的。

你可以做如下处理，在AbstractConfig上使用@JSONType指定使用AlimeFromConfig来反序列化：
```java
    @JSONType(builder = AlimeFromConfig.class)
    public abstract static class AbstractConfig
            implements Serializable {
        private Long id;
        private String type;
        private String subType;
        private String sceneId;
        private Integer version;
    }
```

**Comment by tiandankanfeng** [comment]
> 

AbstractConfig只是个抽象的基类，上述例子AlimeFromConfig只是其中一个子类

**Comment by tiandankanfeng** [comment]
> AbstractConfig只是个抽象的基类，上述例子AlimeFromConfig只是其中一个子类



> 使用? super之后List中的item类型是JSONObject。序列化的时候，没有保留类型信息，反序列化是无法成功的。
> 
> 你可以做如下处理，在AbstractConfig上使用@jsontype指定使用AlimeFromConfig来反序列化：
> 
> ```java
>     @JSONType(builder = AlimeFromConfig.class)
>     public abstract static class AbstractConfig
>             implements Serializable {
>         private Long id;
>         private String type;
>         private String subType;
>         private String sceneId;
>         private Integer version;
>     }
> ```

AbstractConfig只是个抽象的基类，上述例子AlimeFromConfig只是其中一个子类
