### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oneinhere** [alibaba/fastjson2#1772]
### 问题描述
![image](https://github.com/alibaba/fastjson2/assets/52879577/11964591-fd78-431a-a6f6-ebff25e7a929)
大小arrayList两千多就曝出 OutOfMemoryError
String json = JSON.toJSONString(jdyQuerryList);
![image](https://github.com/alibaba/fastjson2/assets/52879577/afdc6673-658c-42d9-aa31-f08813ffbe12)

目前使用
JSONArray eval = (JSONArray) jdyQuerryList.get("data"); 
这个是可行的

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：jdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.38]
 

### 期待的正确结果
希望能正确的判断大小

### 相关日志输出
```java
Caused by: java.lang.OutOfMemoryError: null
	at com.alibaba.fastjson2.JSONWriterUTF16.ensureCapacity(JSONWriterUTF16.java:1559)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeDecimal(JSONWriterUTF16.java:1284)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:497)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:371)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2756)
	at org.dromara.jdy.util.JdySetValue.jdyQueryAll(JdySetValue.java:230)
	at org.dromara.jdy.util.JdySetValue.getJdyQueryListAll(JdySetValue.java:188)
	at org.dromara.zenyi.activity.JdyActivityController.updateTimeToDb(JdyActivityController.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	... 61 common frames omitted
``

**Comment by CodePlayer** [comment]
和 Issue #1773 一样的问题。

Fastjson 2 默认只支持最多 **64M** 的数据，如果需要超过该限制，可以在写入时加上 `com.alibaba.fastjson2.JSONWriter.Feature.LargeObject` 这个支持大对象的 Feature，这样可以让支持的数据大小上限提高到 1G。

**Comment by oneinhere** [comment]
好的 谢谢
