### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sick-cat** [alibaba/fastjson2#1789]
### 问题描述
*简要描述您碰到的问题。*

ZoneOffset 序列化之后的内容，再反序列化回去报错。
报错信息：
```
com.alibaba.fastjson2.JSONException: expect ':', but }, offset 15, character ", line 1, column 16, fastjson-version 2.0.39 {"zoneOffset":"+08:00"}
	at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:1618)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:266)
	at com.alibaba.fastjson2.reader.ORG_1_9_Person.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:726)
	at org.example.JacksonTest.main(JacksonTest.java:52)
```

### 环境信息

 - JDK信息： 1.8
 - 版本信息：Fastjson2 2.0.39
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSON.toJSONString()` 方法
2. 拿toJSONString的结果放到 `JSON.parseObject(String text, Class<T> clazz)` 中解析

```java
@Data
class Person{
    private String name;
    private Integer age;
    private Object object;
    private Date date;
    private Duration duration;
    private LocalTime localTime;
    private LocalDate localDate;
    private LocalDateTime localDateTime;
    private ZoneOffset zoneOffset = ZoneOffset.ofHours(8);
}

public static void main(String[] args) throws IOException {
    Person person = new Person();
    person.setZoneOffset(ZoneOffset.ofHours(8));
    String str =  JSON.toJSONString(person); // {"zoneOffset":"+08:00"}
    JSON.parseObject(str, Person.class);
}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by sick-cat** [comment]
已验证，没问题。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
请用新版本
