### ISSUE TITLE
字段类型跟实体类定义的类型不一样时解析报错

### ISSUE THREAD

**Issue by DevinYDQ** [alibaba/fastjson2#1790]
```java
@Data
public class A {
        private String op;
	private JSONObject test;

	public static void main(String[] args) {
		String json = "{\"op\":\"yyy\",\"test\":\"{\\\"erw\\\":{\\\"qqq\\\":12313}}\"}";
		A a = JSON.parseObject(json, A.class);
		System.out.println(a);
	}
}
```

json里的test字段是带转义字符的字符串，解析时报错
Exception in thread "main" com.alibaba.fastjson2.JSONException: illegal input， offset 36, char }
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:2043)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:434)
	at com.alibaba.fastjson2.reader.ORG_1_1_A.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:726)
	at com.yumchina.uf.ms.store.service.impl.A.main(A.java:19)

问题1： 这种类型不匹配的情况该怎么解决？

问题2： 如果出现类型不匹配的字段，能否忽略该字段的解析，继续解析其他正常的字段？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本
