### ISSUE TITLE
[BUG]JSONReader.Feature.FieldBased不支持record类型的反序列化

### ISSUE THREAD

**Issue by iarrived** [alibaba/fastjson2#1798]
### 问题描述
*简要描述您碰到的问题。*

JSONReader.Feature.FieldBased不支持record类型的反序列化

### 环境信息
*请填写以下信息：*

 - OS信息：  centos 8
 - JDK信息：17
 - 版本信息：2.0.39
 

### 重现步骤
*如何操作可以重现该问题：*
```
record A(Sting id, Date data){}

A a = new A("a", new Date());
String s =JSON.toJSONString(a, JSONWriter.Feature.FieldBased, JSONWriter.Feature.WriteClassName);
a = JSON.parseObject(s, A.class,   JSONReader.Feature.FieldBased,   JSONReader.Feature.SupportAutoType);
```
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

正常反序列化

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
```
Caused by: java.lang.UnsupportedOperationException: can't get field offset on a record class: private final java.lang.String com.xxx$A.a
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:648) ~[na:na]
	at com.alibaba.fastjson2.reader.FieldReader.<init>(FieldReader.java:86) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObject.<init>(FieldReaderObject.java:40) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectField.<init>(FieldReaderObjectField.java:32) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderStringField.<init>(FieldReaderStringField.java:16) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReader(ObjectReaderCreator.java:2498) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createFieldReader(ObjectReaderCreatorASM.java:158) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReader(ObjectReaderCreator.java:1225) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.lambda$createFieldReaders$2(ObjectReaderCreator.java:1500) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.util.BeanUtils.declaredFields(BeanUtils.java:306) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaders(ObjectReaderCreator.java:1494) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:259) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReaderInternal(ObjectReaderProvider.java:843) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:738) ~[fastjson2-2.0.39.jar:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:999) ~[fastjson2-2.0.39.jar:na]
```
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本
