### ISSUE TITLE
[BUG]序列化JSON时报数组越界错误。

### ISSUE THREAD

**Issue by zhao-qiwei** [alibaba/fastjson2#1827]
### 问题描述
[BUG]序列化JSON是报数组越界错误。
序列号JSON是报数组越界错误。要序列化的数据结构是：
{
pages：Integer
total： Integer
current：Integer
size：Integer
data： ArrayList
}

### 环境信息
*请填写以下信息：*
 - 系统：centos7
 - Fastjson2版本： 2.0.34
 - JDK版本：1.8
 - Tomcat版本：9
 - SpringBoot版本：2.7.14

### 重现步骤
客户正式服务器总能再现，本地无法再现。
无法客户提供数据。

### 相关日志输出
org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: JSON#writeTo cannot serialize 'QmResultTable(pages=1, total=3686, current=1, size=10000)' to 'OutputStream'; nested exception is com.alibaba.fastjson2.JSONException: JSON#writeTo cannot serialize 'QmResultTable(pages=1, total=3686, current=1, size=10000)' to 'OutputStream'
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:150) ~[fastjson2-extension-spring5-2.0.34.jar:na]
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227) ~[spring-web-5.3.29.jar:5.3.29]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:86) ~[fastjson2-extension-spring5-2.0.34.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:183) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135) ~[spring-webmvc-5.3.29.jar:5.3.29]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Caused by: com.alibaba.fastjson2.JSONException: JSON#writeTo cannot serialize 'QmResultTable(pages=1, total=3686, current=1, size=10000)' to 'OutputStream'
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:3237) ~[fastjson2-2.0.34.jar:na]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:138) ~[fastjson2-extension-spring5-2.0.34.jar:na]
	... 95 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 314928
	at com.alibaba.fastjson2.util.IOUtils.writeInt64(IOUtils.java:901) ~[fastjson2-2.0.34.jar:na]
	at com.alibaba.fastjson2.util.IOUtils.writeDecimal(IOUtils.java:238) ~[fastjson2-2.0.34.jar:na]
	at com.alibaba.fastjson2.JSONWriterUTF8.writeDecimal(JSONWriterUTF8.java:2370) ~[fastjson2-2.0.34.jar:na]
	at com.alibaba.fastjson2.writer.FieldWriterBigDecimalField.write(FieldWriterBigDecimalField.java:32) ~[fastjson2-2.0.34.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:307) ~[fastjson2-2.0.34.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:371) ~[fastjson2-2.0.34.jar:na]
	at com.alibaba.fastjson2.writer.OWG_23_10_QmResultTable.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:3232) ~[fastjson2-2.0.34.jar:na]
	... 96 common frames omitted

#### 附加信息
看日志报错位置与JSONWriterUTF8.writeDecimal相关。我们的数据库定义的数值类型最大为decimal(20,8)，这个操作是从数据库中查出数据直接显示到画面，中间不涉及数值计算，所以数值类型的数据不会超过这个范围（12位整数8位小数）。我在我们测试数据环境中测试了981234567890.12345678大的数值，没有问题，不报错。但是同样的代码同样的系统，到了客户的环境，数据不一样，就会报错。

**Comment by wenshao** [comment]
问题修复过，请帮忙用2.0.40版本验证下是否问题还存在

**Comment by zhao-qiwei** [comment]
2.0.40数组越界的问题解决了，但是2.0.40又出了一个新的BUG（数组值不对），我再提一个issues。
