### ISSUE TITLE
[BUG] JSONB.parseObject error, `create instance error interface java.util.Set, offset 8`

### ISSUE THREAD

**Issue by liaozan** [alibaba/fastjson2#1857]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
 - JDK： openjdk 11
 - Fastjson2：2.0.40
 - Dubbo: 3.2.5
 

#### server
```java
java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: create instance error interface java.util.Set, offset 8
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.handleToIOException(DefaultSerializationExceptionWrapper.java:358)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.access$000(DefaultSerializationExceptionWrapper.java:28)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:168)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.drawArgs(DecodeableRpcInvocation.java:267)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:168)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:102)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:197)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:138)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:92)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:60)
	at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:103)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: create instance error interface java.util.Set, offset 8
	... 30 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: create instance error interface java.util.Set, offset 8
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.readJSONBObject(ObjectReaderImplList.java:468)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:540)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:125)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:166)
	... 27 common frames omitted
Caused by: java.lang.InstantiationException: java.util.Set
	at java.base/java.lang.Class.newInstance(Class.java:571)
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.readJSONBObject(ObjectReaderImplList.java:466)
	... 30 common frames omitted
Caused by: java.lang.NoSuchMethodException: java.util.Set.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	... 31 common frames omitted
```

#### client
```java
Caused by: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=xxxxxMethod, parameterTypes=null]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:249)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:200)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:188)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:65)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:206)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:152)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:205)
```

**Comment by liaozan** [comment]
使用同一份 bytes，在 dubbo 环境下会报错，非 dubbo 情况下不会报错

示例代码如下
```java
byte[] bytes = new byte[]{-110, 76, 83, 101, 116, 0, -92, 45, 2, 4, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 46, 47, 56, 48, 56, 49, 56, 50, 56, 51, 56, 52, 56, 53, 56, 54, 56, 55, 56, 56};

try {
    Collection<Integer> integers1 = readWithoutDubbo(bytes);
    log.info("integer1 info: {}", integers1);
} catch (Exception e) {
    log.error("integer1 error: {}", e.getMessage());
}

try {
    Collection<Integer> integers2 = readWithDubbo(bytes);
    log.info("integer2 info: {}", integers2);
} catch (Exception e) {
    log.error("integer2 error: {}", e.getMessage());
}

```
--- 
不使用 `Dubbo`的`ContextAutoTypeBeforeHandler`
```java
private Collection<Integer> readWithoutDubbo(byte[] bytes) {
    return JSONB.parseObject(bytes, Collection.class,
            JSONReader.Feature.UseDefaultConstructorAsPossible,
            JSONReader.Feature.ErrorOnNoneSerializable,
            JSONReader.Feature.IgnoreAutoTypeNotMatch,
            JSONReader.Feature.UseNativeObject,
            JSONReader.Feature.FieldBased);
}
```
不使用 `Dubbo`的`ContextAutoTypeBeforeHandler` 的输出
```
integer1 info: [2, 4, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]
```
--- 

使用 `Dubbo`的`ContextAutoTypeBeforeHandler`
```java
private Collection<Integer> readWithDubbo(byte[] bytes) {
  Fastjson2SecurityManager securityManager = FrameworkModel.defaultModel().getBeanFactory().getBean(Fastjson2SecurityManager.class);
  return JSONB.parseObject(bytes, Collection.class, securityManager.getSecurityFilter(),
          JSONReader.Feature.UseDefaultConstructorAsPossible,
          JSONReader.Feature.ErrorOnNoneSerializable,
          JSONReader.Feature.IgnoreAutoTypeNotMatch,
          JSONReader.Feature.UseNativeObject,
          JSONReader.Feature.FieldBased);
    }
```
使用 `Dubbo`的`ContextAutoTypeBeforeHandler`的输出
```
integer2 error: create instance error interface java.util.Set, offset 8
```

**Comment by liaozan** [comment]
由于 `bytes` 实际类型是 `Dubbo` 写入的`java.util.Set`的参数
简单跟了下代码，发现问题可能在
https://github.com/alibaba/fastjson2/blob/d9024ded721ec349ecbc35194246ff8f8725f143/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderBaseModule.java#L1831-L1833

走到这的时候，已经找到了对应的 Reader，往下走
https://github.com/alibaba/fastjson2/blob/d9024ded721ec349ecbc35194246ff8f8725f143/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderImplList.java#L94-L96

至此返回了一个新的`ObjectReaderImplList`
<img width="992" alt="image" src="https://github.com/alibaba/fastjson2/assets/26990889/6dae876c-a732-4bfd-8eec-6c7c166e461c">

回到
https://github.com/alibaba/fastjson2/blob/d9024ded721ec349ecbc35194246ff8f8725f143/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderImplList.java#L371-L378

<img width="1042" alt="image" src="https://github.com/alibaba/fastjson2/assets/26990889/555bd38b-a41b-4c74-8801-dec98099658e">

往下走到到报错位置

https://github.com/alibaba/fastjson2/blob/d9024ded721ec349ecbc35194246ff8f8725f143/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderImplList.java#L464-L469

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.41-SNAPSHOT/
问题没有重现，你能帮用这个版本验证下么？
