### ISSUE TITLE
[BUG] java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by catgptjourney** [alibaba/fastjson2#1860]
### 问题描述
*简要描述您碰到的问题。*
特殊字符转对象报下标越界 ArrayIndexOutOfBoundsException: 1

### 环境信息
 - OS信息：windows 11、centos7
 - JDK信息：Openjdk 1.8
 - 版本信息：Fastjson2 2.0.40
 
### 重现步骤
// 其他特殊字符也可以

```java
package com.test.soft.warn.service;

import com.alibaba.fastjson2.JSON;

public class JsonArrayIndexOutDemo {

    public static void main(String[] args) {
        String json = "+";
        Object object = JSON.parse(json);
        System.out.println(JSON.toJSONString(object));
    }

}
```

### 期待的正确结果
代码执行正常通过

### 相关日志输出
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.alibaba.fastjson2.JSONReaderUTF16.readNumber0(JSONReaderUTF16.java:4591)
	at com.alibaba.fastjson2.JSONReader.readNumber(JSONReader.java:1057)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:277)
	at com.alibaba.fastjson2.JSON.parse(JSON.java:79)
	at com.test.soft.warn.service.JsonArrayIndexOutDemo.main(JsonArrayIndexOutDemo.java:19)

**Comment by a1batr0ss** [comment]
期望是输出什么呢？

**Comment by catgptjourney** [comment]
> 期望是输出什么呢？

编译正常通过

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本
