### ISSUE TITLE
[BUG]反序列化500位小数时数字转换抛出异常

### ISSUE THREAD

**Issue by wulielbows** [alibaba/fastjson2#1919]
### 问题描述
调用http接口返回报文中存在500位小数字段，如截图
![返回报文](https://github.com/alibaba/fastjson2/assets/30711539/39eb23d1-a6aa-4d61-bb26-08843dba2e89)
反序列化时，抛出转换异常，具体如下堆栈：
java.lang.NumberFormatException: For input string: "1.00000"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.math.BigInteger.<init>(BigInteger.java:534)
	at java.base/java.math.BigInteger.<init>(BigInteger.java:672)
	at com.alibaba.fastjson2.JSONReader.getNumber(JSONReader.java:3011)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:2319)
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2584)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:280)
	at com.alibaba.fastjson2.reader.ORG_1_5_ResultData.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1486)
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.readType(FastJsonHttpMessageConverter.java:111)
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.read(FastJsonHttpMessageConverter.java:80)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:105)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:996)
过去fastjson 1.2.83是正常的

### 环境信息
*请填写以下信息：*

 - OS信息： windows 10
 - JDK信息： OpenJDK 11
 - 版本信息：FastJson2 2.0.41
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
    String a = "{\"precedeId\":1.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}";
        JSON.parseObject(a);
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
正常返回反序列化结果

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
为什么会有这种场景？被攻击了吧？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.42-SNAPSHOT/
问题已修复，请帮忙用2.0.42-SNAPSHOT版本验证，正式版本预计在下个周末（11月5日）发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.42
问题已修复，请用新版本
