### ISSUE TITLE
 JSON.parseObject() 无法处理不带引号的String字符串。

### ISSUE THREAD

**Issue by MoshiCoCo** [alibaba/fastjson2#1921]
### 问题描述

 JSON.parseObject() 无法处理不带引号的String字符串。

### 环境信息

 - OS信息：  [MacOS 14]
 - JDK信息： [corretto-11.0.20.1]
 - 版本信息：[Fastjson2 2.0.41]
 

### 重现步骤

```java
    @Test
    public void deserializeTest() {

        // 正常处理
        JSON.parseObject("\"SUCCESS\"", String.class, JSONReader.Feature.SupportAutoType, JSONReader.Feature.SupportSmartMatch);
        // 异常
        JSON.parseObject("SUCCESS", String.class, JSONReader.Feature.SupportAutoType, JSONReader.Feature.SupportSmartMatch);

        /**
         * com.alibaba.fastjson2.JSONException: illegal input : S, offset 1, character S, line 1, column 2, fastjson-version 2.0.41 SUCCESS
         *
         * 	at com.alibaba.fastjson2.JSONReaderASCII.readString(JSONReaderASCII.java:1727)
         * 	at com.alibaba.fastjson2.reader.ObjectReaderImplString.readObject(ObjectReaderImplString.java:25)
         * 	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1002)
         * 	at com.alen.clp.PaykuTest.movies2(PaykuTest.java:174)
         * 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
         * 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
         * 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
         */

    }
```

### 期待的正确结果

JSON.parseObject("SUCCESS", String.class, JSONReader.Feature.SupportAutoType, JSONReader.Feature.SupportSmartMatch); 

能够正常处理

此问题发生在我们操作redis缓存的时候，针对字符串 “ABC”，我们新建一个string 对象，是没问题的。但是如果在操作缓存的时候，直接使用常量字符串  “ABC”，则会在读取redis缓存的时候抛上述异常。

**Comment by MoshiCoCo** [comment]
FastJson2JsonRedisSerializer

```java
public class FastJson2JsonRedisSerializer<T> implements RedisSerializer<T>
{
    public static final Charset DEFAULT_CHARSET = Charset.forName("UTF-8");

    private Class<T> clazz;

    public FastJson2JsonRedisSerializer(Class<T> clazz)
    {
        super();
        this.clazz = clazz;
    }

    @Override
    public byte[] serialize(T t) throws SerializationException
    {
        if (t == null)
        {
            return new byte[0];
        }
        return JSON.toJSONString(t, JSONWriter.Feature.WriteClassName).getBytes(DEFAULT_CHARSET);
    }

    @Override
    public T deserialize(byte[] bytes) throws SerializationException
    {
        if (bytes == null || bytes.length <= 0)
        {
            return null;
        }
        String str = new String(bytes, DEFAULT_CHARSET);

        return JSON.parseObject(str, clazz, JSONReader.Feature.SupportAutoType, JSONReader.Feature.SupportSmartMatch);
    }
}
```
