### ISSUE TITLE
[BUG]2.0.41版本，使用的json字符串中的Integer parseObject为Long时报java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by benjava** [alibaba/fastjson2#1942]
### 问题描述
web前端修改实体时，id为long型，提交后报java.lang.Integer cannot be cast to java.lang.Long错误

### 环境信息
*请填写以下信息：*

 - OS信息：  Win10
 - JDK信息： jdk1.8.0_231
 - 版本信息：Fastjson2 2.0.41
 

### 重现步骤
示例代码段：
       String json = "{\"id\":1,\"name\":\"joe\"}";
        JSONObject obj = JSON.parseObject(json);
        SerializeConfig config = new SerializeConfig();
        config.put(Integer.class, DecimalSerializer.instance);

//        ParserConfig parserConfig = new ParserConfig();
//        parserConfig.putDeserializer(Integer.class, DecimalSerializer.instance);
        SysDic dic = JSON.parseObject(json, SysDic.class);
        dic = obj.toJavaObject(SysDic.class);
        System.out.println();

输出日志：

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

	at com.stec.masterdata.entity.common.MasterTreeEntity.setId(MasterTreeEntity.java:19)
	at com.alibaba.fastjson2.reader.ORG_1_11_SysDic.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:510)
	at com.stec.meta.web.test.JSONTest.idRevert(JSONTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

Disconnected from the target VM, address: '127.0.0.1:51458', transport: 'socket'

Process finished with exit code -1

**Comment by yanxutao89** [comment]
麻烦提供下完整的测试用例

**Comment by benjava** [comment]
SysDic.java
`import java.io.Serializable;

@Data
public class SysDic implements Serializable{

private Long id;

private String name;
}`

JSONTest.java
`public class JSONTest {

    @Test
    public void idRevert(){
        String json = "{\"id\":1,\"name\":\"joe\"}";
        JSONObject obj = JSON.parseObject(json);
        SerializeConfig config = new SerializeConfig();
        config.put(Integer.class, DecimalSerializer.instance);

//        ParserConfig parserConfig = new ParserConfig();
//        parserConfig.putDeserializer(Integer.class, DecimalSerializer.instance);
        SysDic dic = JSON.parseObject(json, SysDic.class);
        dic = obj.toJavaObject(SysDic.class);
        System.out.println();

    }
}`

异常结果如帖；
我使用的是fastjson2.0.41的fastjson1适配版！！

**Comment by benjava** [comment]
@yanxutao89   这个问题在我调整项目各依赖版本后，没有了！

**Comment by benjava** [comment]
叨扰了

**Comment by benjava** [comment]
再三测试，会随机（一半以上几率）出现，回退至2.0.40版本后问题消失；

**Comment by wenshao** [comment]
DecimalSerializer的代码提供下

**Comment by benjava** [comment]
public class DecimalSerializer implements ObjectSerializer {

    public final static SwaggerJsonSerializer instance = new SwaggerJsonSerializer();

    private static final DecimalFormat format = new DecimalFormat("#.################");

    public void write(JSONSerializer serializer,
                      Object object, Object fieldName, Type fieldType, int features) throws IOException {
        SerializeWriter out = serializer.getWriter();
        String value;
        if(object instanceof Long || object instanceof Float) {
            value = format.format(object);
        }
        else {
            value = object.toString();
        }
        out.write(value);
    }
}

**Comment by benjava** [comment]
我再多研究下

**Comment by benjava** [comment]
已经找到原因：系泛型问题，对应的id字段是作为泛型在基类（接口）中进行的定义（getter、setter）方法，实现类中使用了Long进行了继承，并创建了对应Long型id字段，但未显示的创建getter和setter方法，而是使用lombok注解@Data来生成的，这种情况下在fastjson的2.0.40之后的版本会出现，在实现层显示创建getter和setter方法即可。

**Comment by benjava** [comment]
@wenshao 建议针对上述描述，看是否解释下，如果确系lombok的问题，我就关闭问题。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.45
问题已修复，请用新版本
