### ISSUE TITLE
JSONPath 提取数据报错 [BUG]

### ISSUE THREAD

**Issue by lyn-my** [alibaba/fastjson2#1965]
### 问题描述
使用 fastjson2中jsonpath.eavl  提取数据时会报错

Exception in thread "main" com.alibaba.fastjson2.JSONException: error, offset 48, char :
	at com.alibaba.fastjson2.JSONReaderUTF16.skipValue(JSONReaderUTF16.java:4551)
	at com.alibaba.fastjson2.JSONPathSegmentIndex.accept(JSONPathSegmentIndex.java:486)
	at com.alibaba.fastjson2.JSONPathMulti.extract(JSONPathMulti.java:357)
	at com.alibaba.fastjson2.JSONPath.extract(JSONPath.java:56)
	at com.alibaba.fastjson2.JSONPath.eval(JSONPath.java:66)
	at Test.main(Test.java:24)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win11]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.41]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
String temp = "{\n" +
                "  \"code\": \"1003\", \n" +
                "  \"data\": [], \n" +
                "  \"message\": \"code: 1003 ,以【你好】开头的句子的长度不符合要求, 长度限制：3~500，实际长度：2\"\n" +
                "}\n";
 String b1 = (String) JSONPath.eval(temp, "$.data[0][0]");
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
jsonpath 提取不到，应该输出null  

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.42-SNAPSHOT/
问题已修复，请帮忙用2.0.42-SNAPSHOT版本验证，正式版本预计在下个周末（11月5日）发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.42
问题已修复，请用新版本
