### ISSUE TITLE
[BUG]字符串中有\n，解析对象报错

### ISSUE THREAD

**Issue by SouperGeng** [alibaba/fastjson2#1989]
### 问题描述
字符串中有\n，解析对象报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows11]
 - JDK信息： [e.g.：Openjdk 1.8.0_202]
 - 版本信息：[e.g.：Fastjson2 2.0.41]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
String paramStr = "{\n\"a\": \"\",\n\"b\": \"#b#\",\n\"d\": \"c\",\n\"d\": {\n\"f\": \"#f#\",\n\"g\": \"#g#\",\n\"h\": [\n    \"j\":[] \n]\n}\n}";
JSON.parse(paramStr);
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

执行以上代码时
报错 ：
Exception in thread "main" com.alibaba.fastjson2.JSONException: TODO : :
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2619)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:2322)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:208)
	at com.alibaba.fastjson2.JSON.parse(JSON.java:108)
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
```json
{
"a": "",
"b": "#b#",
"d": "c",
"d": {
"f": "#f#",
"g": "#g#",
"h": [
    "j":[] 
]
}
}
```

这个输入的格式是错的
