### ISSUE TITLE
[BUG]升级fastjson2后，使用JSON.parseObject(String,TypeReference)方法返回值错误

### ISSUE THREAD

**Issue by chen-jd** [alibaba/fastjson2#1995]
### 问题描述
升级fastjson2后，使用JSON.parseObject(String,TypeReference)方法返回值错误，会返回一个com.alibaba.fastjson.JSONObject，而不是我指定的类型。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：windows10]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.39]
 

### 重现步骤
```java
public class Main {
    public static void main(String[] args) {
        Map<Integer, Integer> map = new HashMap<>();
        map.put(1, 1);
        map.put(2, 2);
        map.put(3, 3);

        String json = JSON.toJSONString(map, SerializerFeature.WriteNonStringKeyAsString);
        System.out.println(json);
        Map<Integer, Integer> resMap = jsonToMap(json, Integer.class, Integer.class);
        System.out.println(resMap.getClass().getName());
        System.out.println(resMap);
        resMap.put(4, 4);
    }

    private static <K, V> Map<K, V> jsonToMap(String json, Class<K> keyType, Class<V> valueType) {
        return JSON.parseObject(json, new TypeReference<Map<K, V>>(keyType, valueType) { });
    }
}
```

### 期待的正确结果
跟使用老版本的fastjson 1.2.9一样，可以正常返回一个Map<Integer, Integer>
我参考的文档：https://github.com/alibaba/fastjson/wiki/TypeReference#22-%E5%8F%8C%E5%8F%82%E6%95%B0%E4%BE%8B%E5%AD%90

还是说我的使用方式不对？0.0

### 相关日志输出
升级后输出：
```
{"1":1,"2":2,"3":3}
com.alibaba.fastjson.JSONObject
{1:1,2:2,3:3}
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.alibaba.fastjson.JSONObject.put(JSONObject.java:48)
	at json.Main.main(Main.java:36)
```

**Comment by wenshao** [comment]
可以用com.alibaba.fastjson2这个package试下么？

**Comment by chen-jd** [comment]
使用com.alibaba.fastjson2这个package后没问题，也希望兼容包可以支持这种用法

**Comment by chen-jd** [comment]
使用2.0.43-SNAPSHOT没有问题，感谢

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43
请用新版本
