### ISSUE TITLE
[BUG] fastjson1 中保存的 float 类型 在fastjson2中解析报错

### ISSUE THREAD

**Issue by unknownzhouz** [alibaba/fastjson2#2004]
### 问题描述
*简要描述您碰到的问题。*
 
使用旧版 fastjson1 中保存的 float 类型值后面带了 'F'    如： "x":0.12962963F
换成新版 fastjson2  解析到该值报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.42.android4]
 

### 重现步骤
*如何操作可以重现该问题：*
1. 旧版 fastjson1  json对象转字符串后进行保存， 对象有浮点属性 "x":0.12962963F 
2. 使用新版 fastjson2 库解析当前json，出现该错误
3. 定位到是 JSONReaderUTF16 解析函数 skipValue 时 ，未解析数字后的 F字符 导致抛出错误
4. 源码位置 JSONReaderUTF16  4412行  throw new JSONException("error, offset " + offset + ", char " + ch);

### 期待的正确结果
 浮点型 0.12962963F  中带F后缀的也能正常解析

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
       W  com.alibaba.fastjson2.JSONException: error, offset 111, char F
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.JSONReaderUTF16.skipValue(JSONReaderUTF16.java:4412)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:126)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstructor.readObject(ObjectReaderNoneDefaultConstructor.java:281)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.reader.FieldReaderObject.readFieldValue(FieldReaderObject.java:268)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstructor.readObject(ObjectReaderNoneDefaultConstructor.java:285)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.reader.FieldReaderList.readFieldValue(FieldReaderList.java:167)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstructor.readObject(ObjectReaderNoneDefaultConstructor.java:285)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:731)
2023-11-08 14:23:36.417 29655-29655 System.err              com.jshd.auto                        W  	at com.jshd.auto.core.JobCache$Companion.restore(JobCache.kt:95)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43-SNAPSHOT/
问题已修复，请帮忙用2.0.43-SNAPSHOT版本验证，2.0.43正式版本预计在12月3日前发布

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43.android4-SNAPSHOT/
问题已修复，请帮忙用2.0.43.android4-SNAPSHOT版本验证，2.0.43.android4正式版本预计在12月3日前发布

**Comment by unknownzhouz** [comment]
好的，感谢



---原始邮件---
发件人: "Shaojin ***@***.***&gt;
发送时间: 2023年11月11日(周六) 晚上10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/fastjson2] [BUG] fastjson1 中保存的 float 类型 在fastjson2中解析报错 (Issue #2004)




 
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43.android4-SNAPSHOT/
 问题已修复，请帮忙用2.0.43.android4-SNAPSHOT版本验证，2.0.43.android4正式版本预计在12月3日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43
请用新版本
