### ISSUE TITLE
[BUG] actuator端点查看nacosdiscovery报错com.alibaba.fastjson2.JSONException: level too large : 2048

### ISSUE THREAD

**Issue by qingqingdaxia** [alibaba/fastjson2#2021]
### 问题描述
*简要描述您碰到的问题。*
在访问http://localhost:8080/actuator/nacosdiscovery 的时候报错 HttpMessageNotWritableException: Could not write JSON: JSON#writeTo cannot serialize.
报错信息定位到com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:150)

但是打断点查看cause显示com.alibaba.fastjson2.JSONException: level too large : 2048

### 环境信息
*请填写以下信息：*

 - OS信息：  Windows10
 - JDK信息： Openjdk 17.0.9
 - 版本信息：Fastjson2 2.0.42
 

### 重现步骤
*如何操作可以重现该问题：*
astjson2.version为2.0.42
fastjson2-extension-spring6-version为2.0.42
fastjson2.adapter.version为2.0.26
spring-cloud-alibaba-version为2022.0.0.0
spring-boot-starter-actuator自动引入版本为3.0.2

在访问http://localhost:8080/actuator/nacosdiscovery 的时候报错 HttpMessageNotWritableException: Could not write JSON: JSON#writeTo cannot serialize.
报错信息定位到com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:150)

但是打断点查看cause显示com.alibaba.fastjson2.JSONException: level too large : 2048

#1850 是否一样的问题.返回信息的时候,fastjson无法序列化

**Comment by qingqingdaxia** [comment]
@wenshao 
我在设置fastjsonconfig的时候注释掉所有的Features,然后就成功返回信息了.
晚点我测试一下看看是哪个Features加上去就会报错.

**Comment by qingqingdaxia** [comment]
@wenshao 
大神,测试了一下,JSONWriter.Feature.FieldBased这个序列化的时候报错.
没想通为什么.
原始数据如下:
{subscribe=[], NacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='192.168.7.166:8848', username='', password='', endpoint='', namespace='', watchDelay=30000, logName='', service='user-center', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={IPv6=null, preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.19.0.9', networkInterface='', port=8080, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}}

**Comment by wenshao** [comment]
能帮忙构建重现问题的testcase么？

**Comment by qingqingdaxia** [comment]
可以！
代码库可以剥离出来！
怎么给你呢？
你邮箱多少？


我邮箱 ***@***.***





---原始邮件---
发件人: "Shaojin ***@***.***&gt;
发送时间: 2023年11月19日(周日) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/fastjson2] [BUG] actuator端点查看nacosdiscovery报错com.alibaba.fastjson2.JSONException: level too large : 2048 (Issue #2021)




 
能帮忙构建重现问题的testcase么？

**Comment by wenshao** [comment]
可以脱敏后压缩上传到这里么？

**Comment by qingqingdaxia** [comment]
压缩包发送到你邮箱了.请查收!谢谢

**Comment by qingqingdaxia** [comment]
大神,压缩包收到了吗?
压缩包太大了,这里上传不了.

**Comment by wenshao** [comment]
压缩包没收到，加上这个JSONWriter.Feature.ReferenceDetection试试看

**Comment by qingqingdaxia** [comment]
![图片](https://github.com/alibaba/fastjson2/assets/21982180/8fe862ac-6be9-4488-b76b-7808466968c3)
发到这个邮箱了

**Comment by qingqingdaxia** [comment]
加上这个JSONWriter.Feature.ReferenceDetection没有问题
但是只要加上这个JSONWriter.Feature.FieldBased,就会报错

**Comment by qingqingdaxia** [comment]
FastJsonConfig config = new FastJsonConfig();
        config.setCharset(StandardCharsets.UTF_8);
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setReaderFeatures(
                JSONReader.Feature.FieldBased,
                JSONReader.Feature.SupportAutoType,
                JSONReader.Feature.SupportArrayToBean);
        config.setWriterFeatures(
                JSONWriter.Feature.FieldBased,
                JSONWriter.Feature.ReferenceDetection,
                JSONWriter.Feature.WriteMapNullValue,
                JSONWriter.Feature.WriteNullListAsEmpty,
                JSONWriter.Feature.WriteNullStringAsEmpty,
                JSONWriter.Feature.WriteNullNumberAsZero,
                JSONWriter.Feature.PrettyFormat);
上面是配置代码.
WriterFeatures这里只要加上JSONWriter.Feature.FieldBased就报错.去掉就没事.
actuator的一些端点报错一样

**Comment by qingqingdaxia** [comment]
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Dec 05 11:16:07 CST 2023
There was an unexpected error (type=Internal Server Error, status=500).
failed to access class java.lang.ref.ReferenceQueue$Lock from class com.alibaba.fastjson2.writer.OWG_94_3_Null (java.lang.ref.ReferenceQueue$Lock is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.writer.OWG_94_3_Null is in unnamed module of loader com.alibaba.fastjson2.util.DynamicClassLoader @560fbf0d)
java.lang.IllegalAccessError: failed to access class java.lang.ref.ReferenceQueue$Lock from class com.alibaba.fastjson2.writer.OWG_94_3_Null (java.lang.ref.ReferenceQueue$Lock is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.writer.OWG_94_3_Null is in unnamed module of loader com.alibaba.fastjson2.util.DynamicClassLoader @560fbf0d)
	at com.alibaba.fastjson2.writer.OWG_94_3_Null.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_93_4_SoftReference.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_92_4_SoftReferenceConfigurationPropertyCache.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_91_4_SpringIterableConfigurationPropertySource.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.writer.OWG_89_2_SpringConfigurationPropertySources.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_88_3_ConfigurationPropertySourcesPropertySource.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeListValue(FieldWriterList.java:228)
	at com.alibaba.fastjson2.writer.OWG_86_1_MutablePropertySources.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_85_10_DefaultResolver.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_4_11_ConfigurationPropertySourcesPropertyResolver.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_2_5_ApplicationServletEnvironment.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_1_32_NacosDiscoveryProperties.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:3250)
	at com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:138)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:226)
	at com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:86)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:297)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:194)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at com.alibaba.druid.support.jakarta.WebStatFilter.doFilter(WebStatFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by qingqingdaxia** [comment]
heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null
感觉是不是这种字段值的问题啊?
我在断点研究一下看看

**Comment by qingqingdaxia** [comment]
对象原始数据
{subscribe=[], NacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='192.168.7.166:8848', username='', password='', endpoint='', namespace='', watchDelay=30000, logName='', service='user-center', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={IPv6=null, preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.19.0.9', networkInterface='', port=8080, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}}

序列化输出的时候不加JSONWriter.Feature.FieldBased这个,输出的是
{"subscribe":[],"NacosDiscoveryProperties":{"accessKey":"","clusterName":"DEFAULT","endpoint":"","ephemeral":true,"failFast":true,"failureToleranceEnabled":false,"group":"UserGroup","heartBeatInterval":0,"heartBeatTimeout":0,"instanceEnabled":true,"ip":"192.168.2.61","ipDeleteTimeout":0,"ipType":"","logName":"","metadata":{"IPv6":null,"preserved.register.source":"SPRING_CLOUD"},"nacosProperties":{"password":"","endpoint":"","secretKey":"","serverAddr":"192.168.7.166:8848","accessKey":"","clusterName":"DEFAULT","namespace":"","com.alibaba.nacos.naming.log.filename":"","namingLoadCacheAtStart":"false","username":"","group":"UserGroup"},"namespace":"","namingLoadCacheAtStart":"false","networkInterface":"","password":"","port":8080,"registerEnabled":true,"secretKey":"","secure":false,"serverAddr":"192.168.7.166:8848","service":"user-center","username":"","watchDelay":30000,"weight":1}}

对比一下,发现输出的时候只有"IPv6":null这个字段输出了.
后面的heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null都没有输出,参照上面的错误信息,估计是这里null的序列化识别出了问题

请大神帮忙看看对不对?谢谢

**Comment by qingqingdaxia** [comment]
跟null相关的我都写上了,如下:
JSONWriter.Feature.ReferenceDetection,
                JSONWriter.Feature.WriteMapNullValue,
                JSONWriter.Feature.WriteNulls,
                JSONWriter.Feature.WriteNullListAsEmpty,
                JSONWriter.Feature.WriteNullStringAsEmpty,
                JSONWriter.Feature.WriteNullNumberAsZero,
                JSONWriter.Feature.WriteNullBooleanAsFalse,
                JSONWriter.Feature.NullAsDefaultValue,
                JSONWriter.Feature.PrettyFormat

目前看来,序列化之后,不分字段为null的参数会丢失掉.
而且JSONWriter.Feature.FieldBased这个不能加,加上就报错.

**Comment by qingqingdaxia** [comment]
![图片](https://github.com/alibaba/fastjson2/assets/21982180/22f5f7db-60f8-4572-9744-3fd8393791b2)

大神,追代码到这里报错,写入一个ConverterCacheKey的value报错.

**Comment by qingqingdaxia** [comment]
大神,再次测试了一下,好像是循环引用问题.
/actuator/nacosdiscovery端点返回了NacosDiscoveryProperties的数据,NacosDiscoveryProperties里面有个参数NacosServiceManager,然后NacosServiceManager里面又持有了NacosDiscoveryProperties.
配置JSONWriter.Feature.FieldBased的时候循环序列化了.
加上这个JSONWriter.Feature.ReferenceDetection还是会报错.
请大神在帮忙看看

**Comment by qingqingdaxia** [comment]
[usercenter_test.zip](https://github.com/alibaba/fastjson2/files/13556246/usercenter_test.zip)

大神,压缩包弄上来了.

**Comment by qingqingdaxia** [comment]
There was an unexpected error (type=Internal Server Error, status=500).
failed to access class java.lang.ref.ReferenceQueue$Lock from class com.alibaba.fastjson2.writer.OWG_95_3_Null (java.lang.ref.ReferenceQueue$Lock is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.writer.OWG_95_3_Null is in unnamed module of loader com.alibaba.fastjson2.util.DynamicClassLoader @502a8410)
java.lang.IllegalAccessError: failed to access class java.lang.ref.ReferenceQueue$Lock from class com.alibaba.fastjson2.writer.OWG_95_3_Null (java.lang.ref.ReferenceQueue$Lock is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.writer.OWG_95_3_Null is in unnamed module of loader com.alibaba.fastjson2.util.DynamicClassLoader @502a8410)
at com.alibaba.fastjson2.writer.OWG_95_3_Null.write(Unknown Source)


大神这个会是和jdk兼容的原因吗?
这个case用的jdk是17

**Comment by QYG2297248353** [comment]
+1 

![Image](https://github.com/user-attachments/assets/7b95a0c6-c1c1-4393-ace7-f03757485d3b)

 :: Environment ::                    Windows 11 10.0 amd64
 :: Java ::                           v17.0.9
 :: Spring Boot ::                    v3.4.1

**Comment by QYG2297248353** [comment]
解决方案：
``` java
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        // 默认消息转换器
        converters.add(new MappingJackson2HttpMessageConverter());

        // JSON 消息转换器
        FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
        FastJsonConfig config = new FastJsonConfig();
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
        config.setWriterFeatures(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat);
        converter.setFastJsonConfig(config);
        converter.setDefaultCharset(StandardCharsets.UTF_8);
        converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
        converters.add(0, converter);

        // 字节消息转换器
        converters.add(new ByteArrayHttpMessageConverter());
        // XML 消息转换器
        converters.add(new Jaxb2RootElementHttpMessageConverter());
    }
```
