### ISSUE TITLE
[BUG] dubbo 3.2.8 fastjson2 反序列化失败 ，hessian2正常

### ISSUE THREAD

**Issue by daliandazi** [alibaba/fastjson2#2044]
### 问题描述
Dubbo 3.2.8 中使用 fastjson2 序列化，遇到实体字段不一致，反序列化会失败，导致 dubbo 调用失败，如果切换回 hessian2 就一切正常。不确定是BUG还是我没用对。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：macOS 13.4  Apple M1 Pro 16 GB]
 - JDK信息： [e.g.：zulu jdk 11.0.14]
 - 版本信息：[e.g.：Fastjson2 2.0.41]
 

### 重现步骤

项目环境：spring boot 2.7.13 + dubbo  3.2.8 + fastjson2
有 2 个项目，A 是提供者，B 是消费者。
项目 A 提供了接口 com.xx.UserService的实现，下面有方法 getUser(Long userId)，返回实体 User。
项目 A 中 User 字段如下：
```java
public class User implements Serializable {
    private static final long serialVersionUID = 8295348195732708179L;
    private Long userId;  // 新增
    private String name;
    
}
```
项目 B 通过 dubbo 3 调用了 A 中方法 getUser，但是项目B中依赖的 jar 里面实体 User 是旧的，还没有 userId 字段，如下：
```java
public class User implements Serializable {
    private static final long serialVersionUID = 8295348195732708179L;
    private String name;
    
}
```
如果 A 给字段 userId 赋值，且长度大于5位，项目B中会在反序列化阶段报错。如果给 userId 的值小于等于5位，就不会出现异常。

<img width="1565" alt="image" src="https://github.com/alibaba/fastjson2/assets/14924479/a2f5c565-dd65-4f05-a7f4-ec7690ab6442">

### 临时解决办法

1. 如果B中把 User 所在jar更新到跟A一样，就一切正常。如果这个问题不能解决，那 Dubbo 中使用fastjson2的时候兼容性就不好搞了，实体加了字段，所以依赖的项目都需要加。
2. 切回 hessian2 序列化方式。

### 相关日志输出
```
2023-11-22 18:41:14.148  WARN 45548 --- [TID: N/A] [X-Request-ID:N/A] [           main] o.a.d.r.p.dubbo.DecodeableRpcResult      :  [DUBBO] Decode rpc result failed: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: skip not support type INT64 -59, dubbo version: 3.2.8, current host: 192.168.16.58, error code: 4-20. This may be caused by , go to https://dubbo.apache.org/faq/4/20 to find instructions. 

java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: skip not support type INT64 -59
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.handleToIOException(DefaultSerializationExceptionWrapper.java:358)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.access$000(DefaultSerializationExceptionWrapper.java:28)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:177)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.handleValue(DecodeableRpcResult.java:172)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:110)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:149)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:62)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:152)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:205)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71)
	at org.apache.dubbo.rpc.filter.RpcExceptionFilter.invoke(RpcExceptionFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.protocol.ReferenceCountInvokerWrapper.invoke(ReferenceCountInvokerWrapper.java:95)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:383)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:80)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:344)
	at org.apache.dubbo.rpc.cluster.router.RouterSnapshotFilter.invoke(RouterSnapshotFilter.java:46)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:108)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsClusterFilter.invoke(MetricsClusterFilter.java:59)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:52)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.ObservationSenderFilter.invoke(ObservationSenderFilter.java:61)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.spring.security.filter.ContextHolderParametersSelectedTransferFilter.invoke(ContextHolderParametersSelectedTransferFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.metrics.filter.MetricsFilter.invoke(MetricsFilter.java:76)
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsConsumerFilter.invoke(MetricsConsumerFilter.java:37)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerClassLoaderFilter.invoke(ConsumerClassLoaderFilter.java:40)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:116)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:91)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:103)
	at org.apache.dubbo.rpc.cluster.support.wrapper.ScopeClusterInvoker.invoke(ScopeClusterInvoker.java:156)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
	
```

**Comment by kaizen84** [comment]
确实 我们会把所有的依赖同步一次，可能这个是 JSONB 格式要求的？不知道

**Comment by wenshao** [comment]
升级2.0.42版本试试看，这个问题修复过

**Comment by daliandazi** [comment]
> 升级2.0.42版本试试看，这个问题修复过

测试完了，dubbo 3 消费者和提供者都升级到2.0.42，还是一样报错失。

**Comment by daliandazi** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43-SNAPSHOT/ 问题已重现并且修复，请帮忙用2.0.43-SNAPSHOT版本验证，2.0.43正式版本预计在12月3日前发布

测试完成，确实可以了，等待正式包。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43
请用新版本

**Comment by PupilCHen** [comment]
dubbo版本3.2.5，fastjson2:2.0.35，出现com.alibaba.fastjson2.JSONException: skip not support type DOUBLE -78类似的问题。
升级版本能解决吗？
