### ISSUE TITLE
[BUG] BigDecimal 0e-7序列化时候会有bug

### ISSUE THREAD

**Issue by liuze0118** [alibaba/fastjson2#2076]
### 问题描述
*简要描述您碰到的问题。*
调用 JSONObject.toJSONString(jsonObject); 当对象中有bigdecimal = 0e-7 字段时候，IOUtil 在 writeDecimal时候如果off = buffer.size 不会进行扩容，会报数组下标越界
java.lang.ArrayIndexOutOfBoundsException: Index 314928 out of bounds for length 8192
	at com.alibaba.fastjson2.util.IOUtils.writeInt64(IOUtils.java:1085)
	at com.alibaba.fastjson2.util.IOUtils.writeDecimal(IOUtils.java:381)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeDecimal(JSONWriterUTF16.java:1305)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:497)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2815)
	at com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1144)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.40]
 

### 重现步骤
*如何操作可以重现该问题：*
 public static void main(String[] args) throws IOException {
        String str = String.valueOf(FileUtil.readChars(new File("C:\\***\\SO1231205000018.txt")));
        JSONObject.toJSONString(str);
        JSONObject jsonObject = JSONObject.parseObject(str);
        JSONObject.toJSONString(jsonObject);
    }
![image](https://github.com/alibaba/fastjson2/assets/49011972/5a974db2-3ba3-4f87-84a5-dbf454200016)
等于的时候没有扩容 导致后续数组下标越界

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
java.lang.ArrayIndexOutOfBoundsException: Index 314928 out of bounds for length 8192
	at com.alibaba.fastjson2.util.IOUtils.writeInt64(IOUtils.java:1085)
	at com.alibaba.fastjson2.util.IOUtils.writeDecimal(IOUtils.java:381)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeDecimal(JSONWriterUTF16.java:1305)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:497)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2815)
	at com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1144)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
json文件在附件
[SO1231205000018.txt](https://github.com/alibaba/fastjson2/files/13556997/SO1231205000018.txt)
：

**Comment by liuze0118** [comment]
报错信息写错了，是这个：
java.lang.ArrayIndexOutOfBoundsException: Index 314928 out of bounds for length 314928
	at com.alibaba.fastjson2.util.IOUtils.writeInt64(IOUtils.java:1085)
	at com.alibaba.fastjson2.util.IOUtils.writeDecimal(IOUtils.java:381)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeDecimal(JSONWriterUTF16.java:1305)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:497)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:366)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:366)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:548)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2815)
	at com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1144)
	at com.sch.order.application.service.impl.SplitOrderServiceImpl.main(SplitOrderServiceImpl.java:412)
![image](https://github.com/alibaba/fastjson2/assets/49011972/aa0f6534-f332-46d2-a058-28a95991d154)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.44-SNAPSHOT/
问题重现并且修复，请帮忙用2.0.44-SNAPSHOT版本验证，2.0.44版本预计在2024年元旦发布

**Comment by liuze0118** [comment]
![image](https://github.com/alibaba/fastjson2/assets/49011972/e4e45222-9281-49c5-8cb2-fefd7ad06a03)
问题确实修改了，但是如图所示。 标记1. 当前bigdecimal是 0e-7 字符长度是9 位。   标记3 -标记 2 是偏移 长度 626-611 = 15 位 ，所以这种修改方式感觉不够精确
![image](https://github.com/alibaba/fastjson2/assets/49011972/a22c1264-88ef-4ba4-9952-7b640c3b3500)
上图是2.0.6版本的处理方式，直接使用了bigdecimal的字符串长度来做偏移，感觉这种处理方式更优雅

**Comment by wenshao** [comment]
2.0.6版本的实现性能较差，当前的实现不够精确，可以继续改进。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.44
请用新版本
