### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by youngledo** [alibaba/fastjson2#208]
### 问题描述
*简要描述您碰到的问题。*

当UUID碰上“id”时发生的的异常！

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.2]
 

### 重现步骤
*如何操作可以重现该问题：*

定义一个字段名叫“id”，并且其类型是UUID就会报错，如果把“id”改成别的名字（如ids）则正常。

单元测试，看示例代码。
```java
public class FastjsonTest {

    public class MemberMetadata {
        private String code;
        private byte formatType;
        //------这里是重点，不能使用id作为名称------
        private String id;
        private int level;

        public String getCode() {
            return code;
        }

        public void setCode(String code) {
            this.code = code;
        }

        public byte getFormatType() {
            return formatType;
        }

        public void setFormatType(byte formatType) {
            this.formatType = formatType;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public int getLevel() {
            return level;
        }

        public void setLevel(int level) {
            this.level = level;
        }
    }


    @Test
    public void testMemberMetadata() {
        String json = """
                {
                	"code": "项目成员1",
                	"formatType": 0,
                	"id": "a368f1ff-8702-4d80-9cdf-5260b5fe0fdd",
                	"level": 0,
                }""";
        MemberMetadata source = new MemberMetadata();
        source.setCode("项目成员1");
        source.setFormatType((byte) 0);
        source.setId("a368f1ff-8702-4d80-9cdf-5260b5fe0fdd");
        source.setLevel(0);
        String jsonString = JSON.toJSONString(source);
        System.out.println(jsonString);

        MemberMetadata memberMetadata = JSON.parseObject(json, MemberMetadata.class);
    }
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

解析正常，不报错

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

```
com.alibaba.fastjson2.JSONException: error, offset 84, char ,

	at com.alibaba.fastjson2.JSONReaderUTF16.skipValue(JSONReaderUTF16.java:1441)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstrutor.readObject(ObjectReaderNoneDefaultConstrutor.java:239)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:146)
	at com.mingyuanyun.tqncdwjspt.core.fastjson2.FastjsonTest.testMemberMetadata(FastjsonTest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by youngledo** [comment]
> 我刚验证是好的。。。

不好意思，示例代码中“id”的类型是UUID，已经调整了。Windows、MAC系统可复现。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.3-SNAPSHOT/

问题复现并修复，你可以用2.0.3-SNAPSHOT版本验证，预计这个周末发布2.0.3版本
