### ISSUE TITLE
[BUG]序列化包含BigDecimal的对象时，发生数组越界错误。JDK版本：1.8，Fastjson2版本：2.0.43

### ISSUE THREAD

**Issue by zhao-qiwei** [alibaba/fastjson2#2084]
### 问题描述
*简要描述您碰到的问题。*
序列化包含BigDecimal的对象时，发生数组越界错误。
JDK1.8与JDK17都可以再现这个异常。
同样的数据，不总是出错，有时会发生。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows11]
 - JDK信息： [e.g.：openjdk 1.8.0_362]
 - 版本信息：[e.g.：Fastjson2 2.0.43]
 

### 重现步骤
*如何操作可以重现该问题：*

1. fastJson的相关配置如下：
```java
    public static final JSONWriter.Feature[] JSON_WRITER_FEATURE = {
            JSONWriter.Feature.WriteEnumsUsingName,
            JSONWriter.Feature.FieldBased,
            // JSONWriter.Feature.WriteBigDecimalAsPlain,
            JSONWriter.Feature.LargeObject
            };

    public static final JSONReader.Feature[] JSON_READER_FEATURE = {
            JSONReader.Feature.AllowUnQuotedFieldNames,
            JSONReader.Feature.FieldBased};

    public static final String JSON_DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";

    static {
        JSON.config(JSON_WRITER_FEATURE);
        JSON.config(JSON_READER_FEATURE);
        JSON.configWriterDateFormat(JSON_DATE_FORMAT);
        JSON.configReaderDateFormat(JSON_DATE_FORMAT);
    }
```
同样的数据，不总是出错，有时会发生。
下面附件时不出错时，正常响应的数据。
[正常响应.txt](https://github.com/alibaba/fastjson2/files/13608085/default.txt)

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出

java.lang.ArrayIndexOutOfBoundsException: 18432
	at java.lang.String.getBytes(String.java:891)
	at com.alibaba.fastjson2.JSONWriterUTF8.writeDecimal(JSONWriterUTF8.java:2806)
	at com.alibaba.fastjson2.writer.FieldWriterBigDecimalField.write(FieldWriterBigDecimalField.java:32)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:308)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:358)
	at com.alibaba.fastjson2.writer.FieldWriterListField.write(FieldWriterListField.java:55)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:308)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:366)
	at com.alibaba.fastjson2.writer.OWG_2_10_QmResultTable.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:3250)
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:138)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:86)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:183)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by liuze0118** [comment]
https://github.com/alibaba/fastjson2/issues/2076   咱们遇到的是一样的问题，你可以看下这个Issue
