### ISSUE TITLE
SimpleGrantedAuthority 反序列化报错[BUG]

### ISSUE THREAD

**Issue by xiangyunup** [alibaba/fastjson2#2090]
### 问题描述
*简要描述您碰到的问题。*

登陆授权信息反序列化拿不到属性。1.2.83 正常。

### 环境信息
*请填写以下信息：*

 - OS信息： mac
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.42]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
static final Filter autoTypeFilter = JSONReader.autoTypeFilter(
            // 按需加上需要支持自动类型的类名前缀，范围越小越安全
            "org.springframework.security.core.authority.SimpleGrantedAuthority"
    );

public static void main(String[] args) {
        System.out.println(JSON.parseObject("\n" +
                "        {\"@type\": \"org.springframework.security.core.authority.SimpleGrantedAuthority\",\n" +
                "        \"authority\": \"dept:add\"\n" +
                "    }", SimpleGrantedAuthority.class, autoTypeFilter));
    }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

正确结果打印出：dept:add

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

Exception in thread "main" java.lang.IllegalArgumentException: A granted authority textual representation is required
	at org.springframework.util.Assert.hasText(Assert.java:289)
	at org.springframework.security.core.authority.SimpleGrantedAuthority.<init>(SimpleGrantedAuthority.java:39)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:148)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:15)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstructor.readObject(ObjectReaderNoneDefaultConstructor.java:327)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:768)

**Comment by kaizen84** [comment]
2.0.42没有复现
![image](https://github.com/alib.42aba/fastjson2/assets/49264728/88c12409-3fb0-4621-acff-8a5bd0173d19)

**Comment by kaizen84** [comment]
2.0.42没有复现
![image](https://github.com/alibaba/fastjson2/assets/49264728/ee505fce-6ded-4ab0-a119-3803fbea595c)

**Comment by xiangyunup** [comment]
> 2.0.42没有复现 ![image](https://private-user-images.githubusercontent.com/49264728/289726273-ee505fce-6ded-4ab0-a119-3803fbea595c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjI2MjQsIm5iZiI6MTcwMjM2MjMyNCwicGF0aCI6Ii80OTI2NDcyOC8yODk3MjYyNzMtZWU1MDVmY2UtNmRlZC00YWIwLWExMTktMzgwM2ZiZWE1OTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA2MjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZjJlOTg3NTJhNDU0NzM2MzgzYTFmZTg5NmQ3OTBlZmU4YzJkNTZiYzU3ZjhjYThlZDRjMDgzM2Y1NzBhYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFP0PbPlvO1NdFzBtUlTL0VcA731BaveBttcc__gQWQ)
<img width="1089" alt="image" src="https://github.com/alibaba/fastjson2/assets/33372099/10e7eb43-4b94-4e8e-bc84-a7c97b4178ce">
具体的原因我也不清楚，因为我已经发布到正式环境，使用缓存出现这个错误才发现的。但是我本地测试也确实是爆出了这个错误。

**Comment by xiangyunup** [comment]
<img width="1110" alt="image" src="https://github.com/alibaba/fastjson2/assets/33372099/e985df01-49d4-4c33-960f-83e9e083918e">
正式环境错误信息，spingboot版本 2.7.18

**Comment by xiangyunup** [comment]
我都已经忘记这个错误了。更新了2.0.51 突然修复了，结果导致我自己实现的兼容类又不能解析了，哎～又得重新删掉自定义实现类，删掉缓存～
