### ISSUE TITLE
升级到Springboot3.2.0 提示 java.lang.StackOverflowError: null   有没有兄弟遇到？

### ISSUE THREAD

**Issue by moto72** [alibaba/fastjson2#2103]
### 今天升级到spring boot 3.2.0 的时候，提示 java.lang.StackOverflowError: null
*java.lang.StackOverflowError: null
	at com.alibaba.fastjson2.JSONWriter.isWriteTypeInfo(JSONWriter.java:380)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:386)
	at com.alibaba.fastjson2.writer.OWG_14_8_ResolvableType.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:352)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:475)
	at com.alibaba.fastjson2.writer.OWG_14_8_ResolvableType.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:352)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:475)
	at com.alibaba.fastjson2.writer.OWG_14_8_ResolvableType.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:352)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:475)
	………………

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.44-SNAPSHOT/
问题重现并且修复，请帮忙用2.0.44-SNAPSHOT版本验证，2.0.44版本预计在12月24日（周末）发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.44
请用新版本

**Comment by OneFAnn** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.44 请用新版本


Caused by: java.lang.StackOverflowError: null
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:718)
	at java.base/java.time.LocalDate.ofEpochDay(LocalDate.java:345)
	at java.base/java.time.LocalDateTime.ofEpochSecond(LocalDateTime.java:424)
	at java.base/java.time.ZonedDateTime.create(ZonedDateTime.java:458)
	at java.base/java.time.ZonedDateTime.ofInstant(ZonedDateTime.java:411)
	at com.alibaba.fastjson2.writer.FieldWriterDate.writeDate(FieldWriterDate.java:265)
	at com.alibaba.fastjson2.writer.FieldWriterDateMethod.write(FieldWriterDateMethod.java:61)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:477)
	at com.alibaba.fastjson2.writer.OWG_3_9_Customer.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:381)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:477)
	at com.alibaba.fastjson2.writer.OWG_2_14_GoodsOrder.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:381)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:477)
	at com.alibaba.fastjson2.writer.OWG_4_13_GoodsOrderDetail.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:348)
	at com.alibaba.fastjson2.writer.FieldWriterListMethod.write(FieldWriterListMethod.java:78)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:477)
