### ISSUE TITLE
[QUESTION] with preset Content-Type 'null'

### ISSUE THREAD

**Issue by tcscat** [alibaba/fastjson2#2126]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
在使用FastJson覆盖springboot中关于json的转换器时出现
```java
org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class org.springframework.boot.actuate.endpoint.OperationResponseBodyMap] with preset Content-Type 'null'
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:319) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:194) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:136) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.14.jar:6.0.14]
```

配置如下：
```java
@Configuration
@Order(Ordered.HIGHEST_PRECEDENCE)
public class CustomWebMvcConfig implements WebMvcConfigurer {

    @Bean
    public HttpMessageConverter<String> responseBodyConverter() {
        return new StringHttpMessageConverter(StandardCharsets.UTF_8);
    }

    /**
     * 处理mvc json解析问题
     * @param converters
     */
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        // 1、需要先定义一个convert转换消息的对象；
        FastJsonHttpMessageConverter fastConverter = new FastJsonHttpMessageConverter();
        // 2、添加fastjson的配置信息，比如 是否要格式化返回json数据
        FastJsonConfig config = new FastJsonConfig();
        config.setCharset(StandardCharsets.UTF_8);
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setWriterFeatures(JSONWriter.Feature.WriteNulls, JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat); // 配置序列化的行为
        config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean); // 配置反序列化的行为
        fastConverter.setFastJsonConfig(config);

        fastConverter.setDefaultCharset(StandardCharsets.UTF_8);
        fastConverter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
        converters.add(0, fastConverter);
    }
}
```

**Comment by wenshao** [comment]
fastjson什么版本？

**Comment by QYG2297248353** [comment]
一样的报错
https://github.com/alibaba/fastjson2/issues/2021

**Comment by Muska-Ami** [comment]
同样的问题，在清除了 Jackson 的转换器以后，再访问 Actuator 端点即可直接触发，配置如下：

```kt
package cn.locyan.locyanfrp.shared.bean.config.fastjson2.webmvc

import com.alibaba.fastjson2.JSONReader
import com.alibaba.fastjson2.JSONWriter
import com.alibaba.fastjson2.support.config.FastJsonConfig
import com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.http.MediaType
import org.springframework.http.converter.HttpMessageConverter
import org.springframework.http.converter.HttpMessageConverters
import org.springframework.http.converter.json.JacksonJsonHttpMessageConverter
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer

@Configuration
class FastJson2WebMvcConfig : WebMvcConfigurer {

    @Bean
    fun fastJson2HttpMessageConverter(): HttpMessageConverter<*> {
        val converter = FastJsonHttpMessageConverter()

        val config = FastJsonConfig()
        config.setWriterFeatures(
            JSONWriter.Feature.WriteMapNullValue,
            JSONWriter.Feature.FieldBased,
        )
        config.setReaderFeatures(
            JSONReader.Feature.FieldBased,
        )

        converter.fastJsonConfig = config
        converter.supportedMediaTypes = listOf(
            MediaType.APPLICATION_JSON,
            MediaType.APPLICATION_FORM_URLENCODED,
            MediaType.TEXT_PLAIN,
            MediaType("application", "vnd.spring-boot.actuator.*+json"),
        )
        return converter
    }

    override fun configureMessageConverters(builder: HttpMessageConverters.ServerBuilder) {
            builder.withJsonConverter(fastJson2HttpMessageConverter())
    }
}
```

FastJSON 版本及引入的模块:

```toml
[versions]
fastjson = "2.0.59"
# ...

[libraries]
## Alibaba FastJSON2
alibaba-fastjson = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson" }
alibaba-fastjson-extension-spring = { module = "com.alibaba.fastjson2:fastjson2-extension-spring6", version.ref = "fastjson" }
# ...
```
