### ISSUE TITLE
[BUG]NullPointerException was found in 2.0.43,ObjectReaderBean.checkAutoType0(ObjectReaderBean.java:182)

### ISSUE THREAD

**Issue by imgoby** [alibaba/fastjson2#2127]
```
Caused by: java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.checkAutoType0(ObjectReaderBean.java:182)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.checkAutoType(ObjectReaderBean.java:165)
	at com.alibaba.fastjson2.reader.ORG_9_5_SubmitReportModel.readJSONBObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_8_18_SubmitMessageHighPropertiesModel.readJSONBObject(Unknown Source)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:540)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:149)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:175)
	... 118 more

```

![image](https://github.com/alibaba/fastjson2/assets/27885492/5847fed2-d614-408c-ada9-c55789263657)

**Comment by wenshao** [comment]
什么版本？

**Comment by imgoby** [comment]
2.0.43

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.45
问题已修复，请用新版本
