### ISSUE TITLE
[BUG] java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long

### ISSUE THREAD

**Issue by CodePlayer** [alibaba/fastjson2#2153]
### 问题描述
对下列 JSON 字符串反序列化为 Java 对象时，有一定概率会报错。
以下测试用例，目前在本机执行测试十几次左右，会出现一次报错。

在我们的项目代码中，由于方法的差异，出现的概率更高，基本上每两三次就会报错一次。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows 11 ]
 - JDK信息： [e.g.：OpenJDK 17]
 - 版本信息：[e.g.：Fastjson2 2.0.44]
 

### 重现步骤
```java
public interface ID extends Serializable {

	Serializable getId();

}

public interface Bean<K extends Serializable> extends ID {

	@Override
	K getId();

	void setId(K id);

	default boolean considerAsSameType(Bean<K> other) {
		return this == other || other != null && getClass() == other.getClass();
	}

	default boolean hasValidId() {
		return getId() != null;
	}

	default boolean eqId(@Nullable Bean<K> obj) {
		if (obj != null) {
			K id = getId();
			return id != null && (this == obj || id.equals(obj.getId()) && considerAsSameType(obj));
		}
		return false;
	}

	static <K extends Serializable, T extends Bean<K>> T of(Function<? super K, T> constructor, K id) {
		return id == null ? null : constructor.apply(id);
	}

	static boolean hasId(@Nullable Bean<? extends Serializable> obj) {
		return obj != null && obj.hasValidId();
	}

	static boolean isValidId(@Nullable Number id) {
		return id != null && id.longValue() > 0;
	}

	static boolean isValidId(Integer id) {
		return id != null && id > 0;
	}

	static boolean isValidId(@Nullable String id) {
		return id != null && !id.isEmpty();
	}

	static <K extends Serializable> K idOf(@Nullable Bean<K> obj) {
		return obj == null ? null : obj.getId();
	}

	@SuppressWarnings("unchecked")
	default <T extends Bean<K>> T withId(K id) {
		setId(id);
		return (T) this;
	}

	static <K extends Serializable, T extends Bean<K>> T of(Supplier<T> constructor, @Nullable K id) {
		if (id == null) {
			return null;
		}
		T t = constructor.get();
		t.setId(id);
		return t;
	}

	@Nullable
	static Long toLongId(@Nullable Bean<? extends Number> obj) {
		return obj == null ? null : toLong(obj.getId());
	}

	@Nullable
	static Long toLong(@Nullable Number id) {
		if (id == null) {
			return null;
		}
		return id instanceof Long ? (Long) id : id.longValue();
	}

	@Nullable
	static Integer toIntId(@Nullable Bean<? extends Number> obj) {
		return obj == null ? null : toInt(obj.getId());
	}

	@Nullable
	static Integer toInt(@Nullable Number id) {
		if (id == null) {
			return null;
		}
		return id instanceof Integer ? (Integer) id : Math.toIntExact(id.longValue());
	}

}

@Getter
@Setter
public static abstract class BaseEntity implements Bean<Long> {

	Long id;

}

@Getter
@Setter
public static abstract class TimeBaseEntity extends BaseEntity {

	Date addTime;
	Date updateTime;

}

@Getter
@Setter
public static class User extends BaseEntity {

	String addr;
	Long a, b, c, d, e, f, g;

}

@Test
public void jsonParseTest() {
	String str = """
			{"addTime":1703124696338,"updateTime":1703124696338,"id":7}
			""";
	User user = JSON.parseObject(str, User.class);
	System.out.println(user.toString());
}
```

### 期待的正确结果
正确完成反序列化。

### 相关日志输出
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')

	at com.demo.webapp.user.JavaTest$BaseEntity.setId(JavaTest.java:122)
	at com.alibaba.fastjson2.reader.ORG_1_9_User.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1068)
	at com.demo.context.web.Jsons.parseObject(Jsons.java:124)
	at com.demo.webapp.user.JavaTest.jsonParseTest(JavaTest.java:156)
```

#### 附加信息
我们通过实际的项目代码初步定位排查发现，原因如下：

1. 由于我们的 `BaseEntity` 实现了 Bean<Long> 的泛型接口。Java 的泛型是存在擦除的，所以 Java 会生成两个 setter方法：`BaseEntity.setId(java.lang.Long) ` 和 `BaseEntity.setId(java.io.Serializable)`。
2. FastJson2 在 创建 FieldReader 时会 通过 `BeanUtils.setters()` 遍历 所有的 Method。
   https://github.com/alibaba/fastjson2/blob/299168cfa95fc784bc6618fb9a7d004076db2f16/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderCreator.java#L1584
3. 遍历时，会调用 `putIfAbsent()` 方法进行去重。
https://github.com/alibaba/fastjson2/blob/299168cfa95fc784bc6618fb9a7d004076db2f16/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderCreator.java#L1498 
4. 由于 `BeanUtils.setters()`  执行时，`User.class.getMethods()` 返回的方法数组中 `BaseEntity.setId(Serializable)` 和 `BaseEntity.setId(Long)`的顺序是不定的。
如果遍历时， `BaseEntity.setId(Serializable)` 在前面，则后者会覆盖前者，Fastjson 就会调用 `setId( Long )` 进行设置，就一切正常。
如果 `BaseEntity.setId(Long)` 在前面，那么最终保留下来的就是 `BaseEntity.setId(Serializable)` ，此时调用就会报错。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/
问题已修复，请帮2.0.45-SNAPSHOT验证问题是否已经修复，将会在1月7日前发布新版本

**Comment by CodePlayer** [comment]
经过多次单元测试，目前暂未发现报错。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.45
问题已修复，请用新版本
