### ISSUE TITLE
[QUESTION]反序列化开启JSONReader.autoTypeFilter属性时过于依赖原串中@type属性的位置

### ISSUE THREAD

**Issue by mouaifulao** [alibaba/fastjson2#2158]
### 请描述您的问题
com.alibaba.fastjson2.JSON.parseObject()方法开启JSONReader.autoTypeFilter参数时，如果原json字符串中的@type属性**未在**其所在json节点的第一个位置，则其不会被识别。
我不清楚这是不是fastjson2的特有设计。请开源作者们抽空看下。谢谢。

### 环境信息

- OS信息：win10

- JDK信息： Java(TM) SE Runtime Environment (build 1.8.0_181-b13)；Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

- 版本信息：fastjson2-2.0.45

### 重现步骤

- PersonVO.java

```
package com.test.fastjson2;
public class PersonVO {

	public PersonVO() {	
	}
	
	private String name;
	
	private int age;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}
}

```

- AutoTypeTest.java

```
package com.test.fastjson2;
import org.junit.Test;
import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONReader;

public class AutoTypeTest {

	@Test
	public void test() {
               //如果把@type属性移至最前位置，不会报转换类型错
		String json = "{\"name\":\"李雷\",\"age\":30,\"@type\":\"com.test.fastjson2.PersonVO\"}";
		Object obj = JSON.parseObject(json, Object.class, JSONReader.autoTypeFilter("com.test.fastjson2.PersonVO"));
		PersonVO p = (PersonVO) obj;
		System.out.println("==========结果：" + p.getName());
	}
}
```
### 期望正确的结果
==========结果：李雷

### 相关日志输出
```
java.lang.ClassCastException: com.alibaba.fastjson2.JSONObject cannot be cast to com.test.fastjson2.PersonVO
	at com.test.fastjson2.AutoTypeTest.test(AutoTypeTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        ……
```

**Comment by wenshao** [comment]
只支持在第一个位置的@type
