### ISSUE TITLE
[BUG] fastjson1.x升级到2.x时，将java对象转换成JSONObject对象时，对于List集合对象字段，转换后的集合字段的集合元素类型没有变

### ISSUE THREAD

**Issue by litao11046** [alibaba/fastjson2#2187]
### 问题描述
*简要描述您碰到的问题。*
fastjson1.x升级到2.x时，将java对象转换成JSONObject对象时，对于List集合对象字段，转换后的集合字段的集合元素类型没有变。1.x版本会自动将集合元素的类型转换成JSONObject

```java
JSONObject dfDtoJson = (JSONObject) JSON.toJSON(obj, JSONWriter.Feature.FieldBased);
```

**Comment by wenshao** [comment]
能帮忙提供重现问题的testcase么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.46-SNAPSHOT/
问题已修复，请帮忙用2.0.46-SNAPSHOT版本验证，正式版本预计在3月初发布。

**Comment by litao11046** [comment]
2.0.46-SNAPSHOT版本出现了死循环异常：

	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.toJSONObject(ObjectWriterAdapter.java:652)
	at com.alibaba.fastjson2.JSON.toJSON(JSON.java:3495)
	at com.alibaba.fastjson2.JSON.toJSON(JSON.java:3469)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.toJSONObject(ObjectWriterAdapter.java:652)
	at com.alibaba.fastjson2.JSON.toJSON(JSON.java:3495)
	at com.alibaba.fastjson2.JSON.toJSON(JSON.java:3469)

**Comment by wenshao** [comment]
能帮构建重现死循环问题的testcase么？

**Comment by litao11046** [comment]
testcase如下：

定义如下两个类：
```
@Data
public class DynFormDto implements Serializable{
	private static final long serialVersionUID = 1L;
	
	private String sysName;
	private String name;
	private boolean enableTab;
	private int labelColSize;
	private String title; 
	private String hint;
	private List<DynFormComponentDto> componentList;
	private String notes;
}

@Data
public class DynFormComponentDto implements Serializable{
	private static final long serialVersionUID = 1L;
	private String name;
	private String nameText;
	private String functionName;
	private DynFormComponentStructType structType;
	private String compTypeName;
	private JSONObject props; // 组件完整配置
	private int widthColSize;
	protected int widthPercentage; //宽度百分比
	private String tabName;
	private boolean enabled;
	private long uid;
	private long parentFieldId;
	
    private List<DynFormComponentDto> subComponentList; //子组件集合
    
    // TODO 这个方法会引起异常
	public List<DynFormComponentDto> getFlatComponentDtos(){
		List<DynFormComponentDto> flatList = Lists.newArrayList();
		flatList.add(this);
		if(this.subComponentList!=null) {
			for(DynFormComponentDto tmpDto : this.subComponentList) {
				tmpDto.setParentFieldId(this.uid);
				flatList.addAll(tmpDto.getFlatComponentDtos());
			}
		}
		return flatList;
	}
}

```

上面的getFlatComponentDtos方法会引起死循环异常，测试方法如下：

```
	public static void main(String[] args) {
		String dfDtoJsonStr = "{\"componentList\":[{\"compTypeName\":\"Text\",\"enabled\":true,\"name\":\"notes\",\"nameText\":\"备注\",\"parentFieldId\":0,\"props\":{\"compTypeNameText\":\"文本框\",\"fieldName\":\"notes\",\"notes\":\"\",\"widthColSize\":2,\"widthPercentage\":\"80\",\"nameText\":\"备注\",\"type\":\"SingleField\",\"compTypeName\":\"Text\",\"parentFieldId\":0,\"enabled\":true,\"uid\":156592457733,\"structType\":\"Single\",\"valueType\":\"String\",\"name\":\"notes\",\"readonly\":false,\"required\":false},\"structType\":\"Single\",\"subComponentList\":[],\"uid\":156592457733,\"widthColSize\":2,\"widthPercentage\":0}],\"enableTab\":false,\"hint\":\"\",\"id\":0,\"labelColSize\":2,\"name\":\"test_test\",\"notes\":\"\",\"sysName\":\"StandingBook\",\"title\":\"\"}";
		DynFormDto dfDto = JSON.parseObject(dfDtoJsonStr, DynFormDto.class, JSONReader.Feature.FieldBased);
		JSONObject dfDtoJson = (JSONObject)JSON.toJSON(dfDto, JSONWriter.Feature.FieldBased); // 这一步出现死循环异常
	}
```

**Comment by litao11046** [comment]
没明白为何无法避免，这个代码在fastjson1.x是能正常运行的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
问题已修复，请用新版本

**Comment by litao11046** [comment]
不行，依旧死循环
