### ISSUE TITLE
[BUG] 序列化LocalDateTime字段时报错

### ISSUE THREAD

**Issue by yao147258** [alibaba/fastjson2#2206]
### 问题描述
*简要描述您碰到的问题。*
序列化
@JsonFormat(
                pattern = "yyyy-MM-dd'T'HH:mm:ssXXX",
                timezone = "GMT+8"
        )
private LocalDateTime birthday;
这样的字段时会出现以下错误

Exception in thread "main" com.alibaba.fastjson.JSONException: toJSONString error
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1498)
	at com.yzy.portal.YfqTest.main(YfqTest.java:28)
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds
	at java.time.LocalDate.get0(LocalDate.java:680)
	at java.time.LocalDate.getLong(LocalDate.java:659)
	at java.time.LocalDateTime.getLong(LocalDateTime.java:720)
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
	at java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3346)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2190)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at com.alibaba.fastjson2.writer.ObjectWriterImplLocalDateTime.write(ObjectWriterImplLocalDateTime.java:121)
	at com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:83)
	at com.alibaba.fastjson2.writer.ObjectWriter1.write(ObjectWriter1.java:68)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1490)
	... 1 more

Process finished with exit code 1

### 环境信息
*请填写以下信息：*

 - JDK信息：jdk1.8
 - 版本信息：Fastjson2  2.0.45
 

```java
public static void main(String[] args) {
        User user = new User();
        user.setBirthday(LocalDateTime.now());
        System.out.println(JSON.toJSONString(user));
   }

 @Data
    private static class User {
        @JsonFormat(
                pattern = "yyyy-MM-dd'T'HH:mm:ssXXX",
                timezone = "GMT+8"
        )
        private LocalDateTime birthday;
    }
```

**Comment by yao147258** [comment]
直接序列化
@jsonformat(
pattern = "yyyy-MM-dd'T'HH:mm:ssXXX",
timezone = "GMT+8"
)
private LocalDateTime birthday;

**Comment by rowstop** [comment]
LocalDateTime 不包含时区的数据
如果想用需要使用这种格式，可以使用OffsetDateTime或ZonedDateTime这种带有时区信息的类

**Comment by yao147258** [comment]
> LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")) 本身就不支持OffsetSeconds吧？

是新版本的不支持了吗，昨天从1点几版本升到2.0.45发现解析不了了

**Comment by yanxutao89** [comment]
> > LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")) 本身就不支持OffsetSeconds吧？
> 
> 是新版本的不支持了吗，昨天从1点几版本升到2.0.45发现解析不了了

麻烦发下可以支持的版本号

**Comment by yao147258** [comment]
> > > LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")) 本身就不支持OffsetSeconds吧？
> > 
> > 
> > 是新版本的不支持了吗，昨天从1点几版本升到2.0.45发现解析不了了
> 
> 麻烦发下可以支持的版本号

<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>1.2.79</version>
</dependency>
这个版本我试了是可以的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
问题已修复，请用新版本
