### ISSUE TITLE
[BUG] JSON 文件中注释 无法正确处理

### ISSUE THREAD

**Issue by mancong** [alibaba/fastjson2#229]
### 问题描述
*简要描述您碰到的问题。*
自定义 JSON 文件(字符) 中 注释 无法正确的识别处理。
 
### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Win10]
 - JDK信息： [e.g.：Openjdk 1.8.0_301]
 - 版本信息：[e.g.：Fastjson2 2.0.2]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
JSON.parse("{\"name\":{// 这是个注释 \"one\":2020,\"two\":\"red!\"}}");
```
```json
{
	\"name\": { //这是个注释
		\"one\": 2020,
		\"two\": \"red!\"
	}
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
正确解析 JSON 数据

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
```json
com.alibaba.fastjson2.JSONException: illegal input offset 6, char /

	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1092)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:421)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:74)
	at net.uncle.module.cache.DefaultCacheLoader.load(DefaultCacheLoader.java:35)
```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
请问此问题是否属于BUG 类别？

**Comment by wenshao** [comment]
目前是不只支持这个非标格式，但为了方便使用，这个会在后面的版本中支持的

**Comment by wenshao** [comment]
已经部分支持注释，并且能跑过你这个case，但支持注释还是实现不完整的，你可以2.0.3-SNAPSHOT版本验证
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.3-SNAPSHOT/

**Comment by mancong** [comment]
感谢回复。使用 2.0.3-SNAPSHOT 确实可以 通过。顺带问一下，有没有针对 JSON Schema 相关的 规划(例如：校验，生成，运算等操作)呢？

**Comment by wenshao** [comment]
你提个issue吧，但应该要晚一点，可能6~9月份这个阶段做

**Comment by mancong** [comment]
再次发现，在  value 值内 存在特殊字符时(例如: ' \' )，也会报该类错误。
JSON:
```json
{
            "enable": true,
            "regex": ".*\\.png",
            "msg": "文件类型错误！"
}
```
出现错误：
```json
com.alibaba.fastjson2.JSONException: illegal input offset 2938, char /

	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1092)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:1077)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:421)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:74)
```
使用 2.0.3-SNAPSHOT版本验证 依旧如此。请 确认一下

**Comment by mancong** [comment]
### 问题描述

2022-05-17 更新状况：

2.0.3 + 2.0.4-SNAPSHOT 版本 经过测试，在某些情况 依旧会在某些场景下存在问题。

### 重现步骤
方法如下：
```java
JSON.parse("//{"type_array_array":[["abcd","abcd"],[null,"abcd"]]}");
```
压缩格式：
```json
//{"type_array_array":[["abcd","abcd"],[null,"abcd"]]}
```
非压缩格式：
```json
//{
//  "type_array_array": [
//    ["abcd", "abcd"],
//    [null, "abcd"]
//  ]
//}
```

### 期待的正确结果

正确解析 JSON 数据

### 相关日志输出
```java
com.alibaba.fastjson2.JSONException: illegal input， offset 54, char 

	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:381)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:82)
	at net.uncle.module.ValidJsonQTest.testValid(ValidJsonQTest.java:36)
```

#### 附加信息
![1652774014(1)](https://user-images.githubusercontent.com/13076637/168759116-be758108-de4c-45f7-9aad-e13807a9c67b.png)
