### ISSUE TITLE
2.0.47版本反序列化问题[BUG]

### ISSUE THREAD

**Issue by tiger2015** [alibaba/fastjson2#2309]
### 问题描述
*简要描述您碰到的问题。*
json字符串中NaN反序列化问题

### 环境信息
*请填写以下信息：*

 - OS信息： win10 16 GB
 - JDK信息：jdk 1.8.0_381
 - 版本信息：Fastjson2 2.0.47
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 JSON.parseObject()` 方法
2. 输入 ` "{\"x\":NaN}"`  数据
3. 出现 `java.lang.NumberFormatException: empty String` 错误
```java
//可在此输入示例代码
 public static void main(String[] args) {
        String jsonStr = "{\"x\":NaN}";
        Data data = JSON.parseObject(jsonStr, Data.class);
        System.out.println(data);
    }
    
    @lombok.Data
    private static class Data {
        private Double x;

    }

```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
FastJson2Test.Data(x=NaN)

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
Exception in thread "main" java.lang.NumberFormatException: empty String
	at com.alibaba.fastjson2.util.TypeUtils.parseDouble(TypeUtils.java:390)
	at com.alibaba.fastjson2.JSONReaderUTF16.readDoubleValue(JSONReaderUTF16.java:2919)
	at com.alibaba.fastjson2.JSONReader.readDouble(JSONReader.java:974)
	at com.alibaba.fastjson2.reader.ORG_1_1_Data.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:786)
	at com.tiger.FastJson2Test.main(FastJson2Test.java:15)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
NaN不是标准的json格式

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/
Double和Float类型已经支持输入NaN，请帮忙用2.0.48-SNAPSHOT版本验证，正式版本预计月底前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
