### ISSUE TITLE
[BUG]LocalTime日期反序列化

### ISSUE THREAD

**Issue by zacat** [alibaba/fastjson2#2310]
fastjson 2.0.47

    @Data
    public static class TaskJobVO implements Serializable {
        LocalTime publishTime;
    }

    public static void main(String[] args) {
        String str = "{\"publishTime\": \"9:0:0\"}";
        TaskJobVO taskJobVO = JSONObject.parseObject(str,TaskJobVO.class);
        System.out.println(JSON.toJSONString(taskJobVO));
    }

Exception in thread "main" com.alibaba.fastjson2.JSONException: expect ':', but 125, offset 17, character ", line 1, column 17, fastjson-version 2.0.47 {"publishTime": "9:0:0"}
	at com.alibaba.fastjson2.JSONReaderASCII.readFieldNameHashCode(JSONReaderASCII.java:374)
	at com.alibaba.fastjson2.reader.ORG_1_1_TaskJobVO.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:786)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1984)

**Comment by yanxutao89** [comment]
9:0:0这个时间格式有误，换成09:00:00试试看

**Comment by wenshao** [comment]
@yanxutao89 fastjson2支持自动识别日期格式，这种格式也是要支持的

**Comment by yanxutao89** [comment]
> @yanxutao89 fastjson2支持自动识别日期格式，这种格式也是要支持的

那我看着改改

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/ 问题已修复，请帮忙用2.0.48-SNAPSHOT验证，2.0.48正式版本预计在月末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
