### ISSUE TITLE
[BUG]LocalDateTime 序列化失败 & locale 不生效

### ISSUE THREAD

**Issue by shentuzhigang** [alibaba/fastjson2#2328]
### 问题描述
*简要描述您碰到的问题。*
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds
	at java.base/java.time.LocalDate.get0(LocalDate.java:709)
	at java.base/java.time.LocalDate.getLong(LocalDate.java:688)
	at java.base/java.time.LocalDateTime.getLong(LocalDateTime.java:718)
	at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308)
	at java.base/java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3628)
	at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2402)
	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1849)
	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1823)
	at com.alibaba.fastjson2.writer.ObjectWriterImplLocalDateTime.write(ObjectWriterImplLocalDateTime.java:130)
	at com.alibaba.fastjson2.writer.OWG_1_11_Mblog.write(Unknown Source)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1518)
	... 74 common frames omitted

### 环境信息
*请填写以下信息：*

 - OS信息：  MAC
 - JDK信息： Openjdk 21
 - 版本信息：Fastjson2 2.0.47
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
"Wed Jan 10 17:58:02 +0800 2024"
3. 出现 `...` 错误
```java
    @JSONField(format = "E MMM dd HH:mm:ss Z yyyy", locale = "en_US")
    private LocalDateTime createdAt;
```

**Comment by shentuzhigang** [comment]
![image](https://github.com/alibaba/fastjson2/assets/46020123/b1d14293-7db8-4a64-aa7f-f025fb76df2a)
locale is null？

**Comment by shentuzhigang** [comment]
我尝试使用 ZonedDateTime 代替 LocalDateTime 但得到结果：周日 4月 09 10:34:40 +0800 2023 locale 不生效

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/
问题已修复，请帮忙用2.0.48-SNAPSHOT验证，2.0.48正式版本预计在月末发布

**Comment by shentuzhigang** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/ 问题已修复，请帮忙用2.0.48-SNAPSHOT验证，2.0.48正式版本预计在月末发布
```java
    @Test
    public void test1() throws Exception {
        Bean1 bean = JSON.to(Bean1.class,"{\"createdAt\":\"Tue Mar 12 21:18:36 +0800 2024\"}");
        String str = JSON.toJSONString(bean);
        assertEquals("{\"createdAt\":\"Tue Mar 12 21:18:36 +0800 2024\"}", str);

        Bean1 bean1 = JSON.parseObject(str, Bean1.class);
        assertEquals(bean.createdAt, bean1.createdAt);
    }

    @Data
    public static class Bean1 {
        @JSONField(format = "E MMM dd HH:mm:ss Z yyyy", locale = "en_US")
        private LocalDateTime createdAt;
    }

```

but 

```
java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds

	at java.base/java.time.LocalDate.get0(LocalDate.java:709)
	at java.base/java.time.LocalDate.getLong(LocalDate.java:688)
	at java.base/java.time.LocalDateTime.getLong(LocalDateTime.java:718)
	at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308)
	at java.base/java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3628)
	at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2402)
	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1849)
	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1823)
	at com.alibaba.fastjson2.writer.ObjectWriterImplLocalDateTime.write(ObjectWriterImplLocalDateTime.java:135)
	at com.alibaba.fastjson2.writer.OWG_1_1_Bean1.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2917)
```

**Comment by shentuzhigang** [comment]
> > https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/ 问题已修复，请帮忙用2.0.48-SNAPSHOT验证，2.0.48正式版本预计在月末发布
> 
> ```java
>     @Test
>     public void test1() throws Exception {
>         Bean1 bean = JSON.to(Bean1.class,"{\"createdAt\":\"Tue Mar 12 21:18:36 +0800 2024\"}");
>         String str = JSON.toJSONString(bean);
>         assertEquals("{\"createdAt\":\"Tue Mar 12 21:18:36 +0800 2024\"}", str);
> 
>         Bean1 bean1 = JSON.parseObject(str, Bean1.class);
>         assertEquals(bean.createdAt, bean1.createdAt);
>     }
> 
>     @Data
>     public static class Bean1 {
>         @JSONField(format = "E MMM dd HH:mm:ss Z yyyy", locale = "en_US")
>         private LocalDateTime createdAt;
>     }
> ```
> 
> but
> 
> ```
> java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds
> 
> 	at java.base/java.time.LocalDate.get0(LocalDate.java:709)
> 	at java.base/java.time.LocalDate.getLong(LocalDate.java:688)
> 	at java.base/java.time.LocalDateTime.getLong(LocalDateTime.java:718)
> 	at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308)
> 	at java.base/java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3628)
> 	at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2402)
> 	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1849)
> 	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1823)
> 	at com.alibaba.fastjson2.writer.ObjectWriterImplLocalDateTime.write(ObjectWriterImplLocalDateTime.java:135)
> 	at com.alibaba.fastjson2.writer.OWG_1_1_Bean1.write(Unknown Source)
> 	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2917)
> ```
当createdAt是public时，满足预期，当createdAt是private时，通过get方法获取值时依然存在问题

**Comment by wenshao** [comment]
需要更新快照版本，最新的快照版本在createdAt是private时也支持的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
