### ISSUE TITLE
[BUG] 序列化巨大对象时OOM

### ISSUE THREAD

**Issue by Deliay** [alibaba/fastjson2#2351]
### 问题描述
序列化巨大对象时OOM

### 环境信息
 - JDK信息： openjdk version "11.0.22" 2024-01-16 LTS
 - 版本信息：fastjson2 2.0.47
 

### 重现步骤
```java
@Data
public class HugeDataClass {
  private List<Double> data;

  public void fillData() {
     for (int i = 0; i < 21600000; i++) {
         data.add((double) i);
     }
  }
}

HugeDataClass dataClass = new HugeDataClass();
dataClass.setData(new ArrayList<>(21600000));
dataClass.fillData();

// OOM
String result = JSON.toJSONString(dataClass);
```

### 期待的正确结果
输出一个长度为 21 600 000 个元素的JSON字符串数组字符串。

### 相关日志输出
```
Exception in thread "main" java.lang.OutOfMemoryError
	at com.alibaba.fastjson2.JSONWriterUTF16.ensureCapacity(JSONWriterUTF16.java:1564)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeDouble(JSONWriterUTF16.java:1915)
	at com.alibaba.fastjson2.writer.ObjectWriterImplDouble.write(ObjectWriterImplDouble.java:48)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeListValue(FieldWriterList.java:218)
	at com.alibaba.fastjson2.writer.OWG_1_1_HugeDataClass.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2917)
	at demo.DatFileResolver.main(DatFileResolver.java:41)
```

**Comment by Deliay** [comment]
搜了下issues，可以通过第二个参数支持，但throw的异常希望能够指明我这里应该启用LargeObject这个Feature参数
