### ISSUE TITLE
[BUG] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by chenxushaoxia** [alibaba/fastjson2#2373]
问题描述
原来帮忙更改过这个问题，这次是另一个重载的方法报错了。
分析是List modules更改了。
只有多处地方调用了 JSON.parseObject同一个类，怀疑跟类加载器不一致相关，这两个类加载器有做切换。
代码片段，在多线程的环境下执行偶现ConcurrentModificationException。
Utils.useFunctionClassLoader();
T val = (T) JSON.parseObject(new String(bytes, StandardCharsets.UTF_8), this.type,
JSONReader.Feature.SupportAutoType, JSONReader.Feature.SupportClassForName);
Utils.useInstanceClassLoader();
return val;

报错堆栈信息。
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getFieldInfo(ObjectReaderProvider.java:901)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReader(ObjectReaderCreator.java:1411)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.lambda$createFieldReaders$4(ObjectReaderCreator.java:1660)
	at com.alibaba.fastjson2.util.BeanUtils.setters(BeanUtils.java:575)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaders(ObjectReaderCreator.java:1656)
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:260)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReaderInternal(ObjectReaderProvider.java:856)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:748)
	at com.alibaba.fastjson2.JSONReader.getObjectReader(JSONReader.java:401)
	at com.alibaba.fastjson2.reader.FieldReaderObject.getObjectReader(FieldReaderObject.java:70)
	at com.alibaba.fastjson2.reader.ORG_16_3_JeDraftTransferVO.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_10_9_JeDraftMsgVO.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1062)
	at com.huawei.dff.functions.runtime.serde.MsgpackSerDe.deserialize(MsgpackSerDe.java:33)
	at com.huawei.dff.functions.runtime.serde.SerDeUtils.deserializeMessage(SerDeUtils.java:37)
	at com.huawei.dff.functions.runtime.io.yuanrong.YuanRongSource.run(YuanRongSource.java:177)
	at com.huawei.dff.functions.runtime.JavaInstanceRunnable.lambda$startSource$0(JavaInstanceRunnable.java:321)
	at java.base/java.lang.Thread.run(Unknown Source)

环境信息
请填写以下信息：

OS信息： [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
JDK信息： [e.g.：Openjdk 1.8.0_312]
版本信息：[e.g.：Fastjson2 2.x.x]
重现步骤
如何操作可以重现该问题：

使用 xxx.xxx 方法
输入 ... 数据
出现 ... 错误
//可在此输入示例代码
期待的正确结果
对您期望发生的结果进行清晰简洁的描述。

相关日志输出
请复制并粘贴任何相关的日志输出。

附加信息
如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。

**Comment by mek1986** [comment]
能不能提供完整的出错代码

**Comment by chenxushaoxia** [comment]
已使用手动设置每个线程ObjectReaderProvider的方式规避了这个问题。
