### ISSUE TITLE
[BUG] JSONWriterUTF16.writeName8Raw(long name)方法抛出java.lang.ArrayIndexOutOfBoundsException异常

### ISSUE THREAD

**Issue by plliang** [alibaba/fastjson2#2419]
### 问题描述
想要将一个大对象转换为JSON字符串，转换过程中抛出ArrayIndexOutOfBoundsException数组越界异常，debug截图如下：

![FastJSON-Debug](https://github.com/alibaba/fastjson2/assets/23230617/c81fa824-3d73-476f-bbfd-fa24ee7ec720)

进入该方法时，`this.off == 27637`，计算`minCapacity`判断是否扩容时，只增加了10个容量，此时`27637 + 10 = 27647`小于`chars.length = 27648`，判断为不需要扩容。在执行后续步骤时，实际上会取到11个偏移量，由于`chars`数组的最大下标为`27647`，因此造成数组越界。

### 环境信息
*请填写以下信息：*

 - OS信息：  [Deepin 社区版（20.9） 8Core 3.00GHz 32 GB]
 - JDK信息： [openjdk version "11.0.9.1" 2020-11-04]
 - 版本信息：[Fastjson2 2.0.48]
 

### 重现步骤

示例代码如下（内部数据，无法提供）：
```java
JSON.config(JSONWriter.Feature.LargeObject, true);  
String jsonString = JSONObject.toJSONString(dataBasePO, SerializerFeature.DisableCircularReferenceDetect);
```

### 期待的正确结果
期望能够正确将对象转换为JSON字符串，不要抛出异常。或者通过某些配置能够实现正确转换

### 相关日志输出
```java
com.alibaba.fastjson.JSONException: toJSONString error
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1578)
	at com.uxsino.uxsync.core.infrastructure.repository.impl.MetaDataInFileRepositoryImpl.save(MetaDataInFileRepositoryImpl.java:62)
	at com.uxsino.uxsync.core.domain.service.MetaDataDomainService.save(MetaDataDomainService.java:48)
	at com.uxsino.uxsync.core.app.service.MetaDataAppService.refreshAll(MetaDataAppService.java:51)
	at com.uxsino.db.uxsync.metadata.domain.service.MetaDataDomainService.lambda$submitTask$0(MetaDataDomainService.java:151)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 27648 out of bounds for length 27648
	at com.alibaba.fastjson2.JSONWriterUTF16.writeName8Raw(JSONWriterUTF16.java:1719)
	at com.alibaba.fastjson2.writer.OWG_7_18_ColumnPO.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeListValue(FieldWriterList.java:218)
	at com.alibaba.fastjson2.writer.OWG_6_15_DataBasePO.write(Unknown Source)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1570)
	... 10 common frames omitted
```

#### 附加信息
暂无其它信息提供

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.49-SNAPSHOT/
问题已经修复，请帮忙用2.0.49-SNAPSHOT版本验证，2.0.49版本预计在本周末（4月14日）前发布

**Comment by plliang** [comment]
使用 [fastjson2-2.0.49-20240412.055049-9.jar](https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.49-SNAPSHOT/fastjson2-2.0.49-20240412.055049-9.jar) 包替换验证，能够成功转换JSON字符串。谢谢 @wenshao

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.49
请用新版本

**Comment by xuanwangjue** [comment]
java.lang.ArrayIndexOutOfBoundsException: 62945
	at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:1300)
	at com.alibaba.fastjson2.reader.ORG_13_6_PriceItem.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_12_14_PriceDetail.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_8_60_ChargingStation.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:515)
	at com.newlink.crawler.kd.controller.DispatchController.lambda$importKingXdt$6(DispatchController.java:131)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	
	@wenshao 反序列化也有这个问题
