### ISSUE TITLE
[BUG]JDK17 序列化异常

### ISSUE THREAD

**Issue by changeAtLater** [alibaba/fastjson2#2437]
### 问题描述
java.lang.IllegalAccessError: failed to access class java.util.concurrent.locks.ReentrantLock$Sync from class com.alibaba.fastjson2.writer.OWG_23_1_ReentrantLock (java.util.concurrent.locks.ReentrantLock$Sync is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.writer.OWG_23_1_ReentrantLock is in unnamed module of loader com.alibaba.fastjson2.util.DynamicClassLoader @38a01810)
	at com.alibaba.fastjson2.writer.OWG_23_1_ReentrantLock.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:379)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeJSONB(ObjectWriterAdapter.java:205)
	at com.alibaba.fastjson2.writer.OWG_22_6_ItemDataSource.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.writeJSONB(ObjectWriterImplMap.java:362)
	at com.alibaba.fastjson2.writer.OWG_21_9_DynamicRoutingDataSource.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_20_3_Environment.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_19_53_Configuration.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_18_1_DefaultSqlSessionFactory.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_17_3_SqlSessionTemplate.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_16_3_MapperProxy.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_15_1_$Proxy211.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_14_2_SysDeptServiceImpl.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_13_1_OrganizationDataAscriptionCustomDataScope.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:1225)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectOutput.writeObject(FastJson2ObjectOutput.java:115)

### 环境信息
*请填写以下信息：*

 - OS信息：  window10
 - JDK信息： jdk-17.0.8
 - 版本信息：Fastjson2 2.0.43
 

### 重现步骤
*如何操作可以重现该问题：使用dubbo 3.2.7版本出现的*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.49
问题已修复，请帮忙用新版本验证

**Comment by changeAtLater** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.49 问题已修复，请帮忙用新版本验证

有个问题,后来我发现,rebuild一下项目就好了,我没法复现...

**Comment by changeAtLater** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.49 问题已修复，请帮忙用新版本验证

我从dubbo中简单复制了一下代码尝试复现该问题:
```java
public static void main(String[] args) throws IOException {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            Bean bean = new Bean();
            byte[] bytes = JSONB.toBytes(bean, JSONWriter.Feature.WriteClassName,
                    JSONWriter.Feature.FieldBased,
                    JSONWriter.Feature.ReferenceDetection,
                    JSONWriter.Feature.WriteNulls,
                    JSONWriter.Feature.NotWriteDefaultValue,
                    JSONWriter.Feature.NotWriteHashMapArrayListClassName,
                    JSONWriter.Feature.WriteNameAsSymbol);
            writeLength(outputStream, bytes.length);
            outputStream.write(bytes);
            outputStream.flush();
        }
    }

    private static void writeLength(ByteArrayOutputStream outputStream, int value) throws IOException {
        byte[] bytes = new byte[Integer.BYTES];
        int length = bytes.length;
        for (int i = 0; i < length; i++) {
            bytes[length - i - 1] = (byte) (value & 0xFF);
            value >>= 8;
        }
        outputStream.write(bytes);
    }

    public static class Bean {
        public Lock lock = new ReentrantLock();
    }
```
但报的错是:
```
Exception in thread "main" java.lang.IllegalAccessError: failed to access class java.util.concurrent.locks.ReentrantLock$Sync from class com.alibaba.fastjson2.writer.OWG_2_1_ReentrantLock (java.util.concurrent.locks.ReentrantLock$Sync is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.writer.OWG_2_1_ReentrantLock is in unnamed module of loader com.alibaba.fastjson2.util.DynamicClassLoader @271053e1)
	at com.alibaba.fastjson2.writer.OWG_2_1_ReentrantLock.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_1_1_Bean.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:1225)
```
不知道是否有价值(看不懂OWG_2_1_ReentrantLock 是什么和OWG_23_1_ReentrantLock有什么区别,非常抱歉)

**Comment by changeAtLater** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.49 问题已修复，请帮忙用新版本验证

如果`lock`是外部传入的话,序列化再反序列化,`lock`就没了,算不算问题?
```java
public static void main(String[] args) throws IOException {
    Bean bean = new Bean();
    bean.lock = new ReentrantLock();
    bean.lock.lock();
    byte[] bytes = JSONB.toBytes(bean, JSONWriter.Feature.WriteClassName,
            JSONWriter.Feature.FieldBased,
            JSONWriter.Feature.ReferenceDetection,
            JSONWriter.Feature.WriteNulls,
            JSONWriter.Feature.NotWriteDefaultValue,
            JSONWriter.Feature.NotWriteHashMapArrayListClassName,
            JSONWriter.Feature.WriteNameAsSymbol);
    System.out.println(Objects.nonNull(bytes));
    Bean bean1 = JSONB.parseObject(bytes, Bean.class,
            JSONReader.Feature.UseDefaultConstructorAsPossible,
            JSONReader.Feature.UseNativeObject,
            JSONReader.Feature.IgnoreAutoTypeNotMatch,
            JSONReader.Feature.FieldBased);
    System.out.println(bean1.lock);
}

public static class Bean {
    public Lock lock;
}
```
测试结果:
```
true
null
```
