### ISSUE TITLE
[BUG] 字符串与List类型不匹配时转换异常

### ISSUE THREAD

**Issue by DamonBao** [alibaba/fastjson2#2440]
### 问题描述
类型不匹配时转换异常

    @Test
    public void testJson() {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("lines", "1,2");
        Sample sample = jsonObject.toJavaObject(Sample.class);
        System.out.println(sample);
    }

    static class Sample {

        private List<String> lines;

        public List<String> getLines() {
            return lines;
        }

        public void setLines(List<String> lines) {
            this.lines = lines;
        }
    }

### 环境信息
*请填写以下信息：*

 - OS信息：  macos / windows11
 - JDK信息： jdk8 jdk17
 - 版本信息：Fastjson2 2.0.48 1.x兼容包 2.0.48
 

### 重现步骤
*如何操作可以重现该问题：*

以上代码报错

### 期待的正确结果

如果类型不匹配，还是能够转换成功，值可以为null，避免报错。
fastjson 1.2.83目前是可以转换成功，lines[0]值为"1,2"

### 相关日志输出
com.alibaba.fastjson2.JSONException: offset 1, character 1, line 1, column 1, fastjson-version 2.0.48 1,2

	at com.alibaba.fastjson2.reader.ObjectReaderImplList.readObject(ObjectReaderImplList.java:589)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:786)
	at com.alibaba.fastjson2.function.impl.StringToAny.apply(StringToAny.java:81)
	at com.alibaba.fastjson2.reader.FieldReader.acceptAny(FieldReader.java:425)
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:659)
	at com.alibaba.fastjson.JSONObject.toJavaObject(JSONObject.java:1011)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
问题已修复，请帮忙用2.0.50-SNAPSHOT版本验证，2.0.50版本预计在5月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本
