### ISSUE TITLE
[BUG] LocalDateTime类型字段如果是空字符串，反序列化成Object时报错

### ISSUE THREAD

**Issue by HsinDumas** [alibaba/fastjson2#261]
### 问题描述
LocalDateTime类型字段如果是空字符串，反序列化成Object时报错

Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_265]
	at java.lang.Long.parseLong(Long.java:601) ~[?:1.8.0_265]
	at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_265]
	at com.alibaba.fastjson2.JSONReader.readLocalDateTime(JSONReader.java:736) ~[fastjson2-2.0.3.jar!/:?]
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule$LocalDateTimeImpl.readObject(ObjectReaderBaseModule.java:1916) ~[fastjson2-2.0.3.jar!/:?]

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.4
问题已经在2.0.4版本中修复，请用新版本
