### ISSUE TITLE
[BUG] JSON.parseObject("8924992445", AtomicLong.class) 报错

### ISSUE THREAD

**Issue by 156370005** [alibaba/fastjson2#2615]
报警信息：
Exception in thread "main" com.alibaba.fastjson2.JSONException: integer overflow 8924992445, offset 11, character , line 1, column 10, fastjson-version 2.0.50 8924992445
	at com.alibaba.fastjson2.JSONReader.getInt32Value(JSONReader.java:807)
	at com.alibaba.fastjson2.JSONReaderUTF8.readInt32Value(JSONReaderUTF8.java:3531)
	at com.alibaba.fastjson2.reader.ObjectReaderImplFromLong.readObject(ObjectReaderImplFromLong.java:35)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:786)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.51-SNAPSHOT/
问题已修复，请帮忙用2.0.51-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.51
问题已修复，请用新版本
