### ISSUE TITLE
[BUG] 使用JSON.toJSONString()，输出org.springframework.cloud.client.ServiceInstance的JSON 报错

### ISSUE THREAD

**Issue by Jay2293** [alibaba/fastjson2#2621]
### 问题描述

*使用JSON.toJSONString()，输出org.springframework.cloud.client.ServiceInstance的JSON 报错*

### 环境信息

 - OS信息：  k8s1.28.9-aliyun.1
 - JDK信息： Openjdk 21]
 - 版本信息：Fastjson2 2.0.49

### 重现步骤

*使用以下代码可以实现：*

1. 使用 JSON.toJSONString()，输出org.springframework.cloud.client.ServiceInstance的JSON` 方法
2. 输入 `报错`  数据
3. 出现 `can't get field offset on a record class: private final boolean org.springframework.cloud.kubernetes.commons.discovery.DefaultKubernetesServiceInstance.secure
   at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
    at com.alibaba.fastjson2.writer.FieldWriter.<init>(FieldWriter.java:116)` 

```java
import com.alibaba.fastjson2.JSON;
import com.nitxe.western.common.type.Result;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.client.ServiceInstance;
import org.springframework.cloud.client.discovery.DiscoveryClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@Slf4j
@RestController
@RequiredArgsConstructor
public class HelloWorldController {

    @GetMapping("/hello-world")
    public Result<List<ServiceInstance>> helloWorld() {

        List<ServiceInstance> instances = discoveryClient.getInstances(serviceName);

        if (instances.isEmpty()) {
            return Result.fail("No online services available.");
        }

        log.info("Calling Hello World Interface Success Result Is {}", JSON.toJSONString(instances));

        return Result.ok(instances);
    }

    @Value("${spring.application.name}")
    private String serviceName;

    private final DiscoveryClient discoveryClient;
}

```

### 期待的正确结果

*正常输出json*

### 相关日志输出

* UnsupportedOperationException was catch : java.lang.UnsupportedOperationException: can't get field offset on a record class: private final boolean org.springframework.cloud.kubernetes.commons.discovery.DefaultKubernetesServiceInstance.secure
  at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
   at com.alibaba.fastjson2.writer.FieldWriter.<init>(FieldWriter.java:116)
   at com.alibaba.fastjson2.writer.FieldWriterBoolean.<init>(FieldWriterBoolean.java:32)
   at com.alibaba.fastjson2.writer.FieldWriterBoolMethod.<init>(FieldWriterBoolMethod.java:21)
   at com.alibaba.fastjson2.writer.ObjectWriterCreator.createFieldWriter(ObjectWriterCreator.java:929)
   at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.lambda$createObjectWriter$1(ObjectWriterCreatorASM.java:327)
   at com.alibaba.fastjson2.util.BeanUtils.getters(BeanUtils.java:1048)
   at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.createObjectWriter(ObjectWriterCreatorASM.java:234)
   at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriterInternal(ObjectWriterProvider.java:455)
   at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:337)
   at com.alibaba.fastjson2.JSONWriter$Context.getObjectWriter(JSONWriter.java:1782)
   at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:343)
   at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2917)
   at com.nitxe.virgo.platform.base.controller.HelloWorldController.helloWorld(HelloWorldController.java:30)
   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
   at java.base/java.lang.reflect.Method.invoke(Method.java:580)
   at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
   at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
   at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
   at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
   at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:206)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150)
   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150)
   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150)
   at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150)
   at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150)
   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150)
   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
   at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:731)
   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
   at java.base/java.lang.Thread.run(Thread.java:1583)*

**Comment by wenshao** [comment]
org.springframework.cloud.client.ServiceInstance 这类在哪个Maven坐标下，找不到无法重现

**Comment by Jay2293** [comment]
> org.springframework.cloud.client.ServiceInstance 蚂蚁在哪个Maven坐标下，找不到无法重现

我使用的是 spring boot 3.2.5
maven坐标是  有这个依赖引入的
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-fabric8-all</artifactId>
        </dependency>
他自动引入的 具体版本是 3.1.0

**Comment by hnyyghk** [comment]
this is a simple unit test, will cause UnsupportedOperationException("can't get field offset on a record class: " + f)

```
TestRecord testRecord = new TestRecord("123");
log.info(com.alibaba.fastjson2.JSON.toJSONString(testRecord));

public record TestRecord(String instanceId) {
    public String getInstanceId() {
        return instanceId;
    }
}
```

![image](https://github.com/alibaba/fastjson2/assets/17867953/d46f8a38-b4de-4c61-a726-03602c2aa962)

**Comment by ityangkai-coder** [comment]
> org.springframework.cloud.client.ServiceInstance 这类在哪个Maven坐标下，找不到无法重现

我认为和Spring无关，针对record class的boolean属性都会出现这个问题，可以参考一下我提出的问题：https://github.com/alibaba/fastjson2/issues/3090

使用最基础的boolean就会出问题，fastjson2针对boolean有特殊的处理，导致问题出现，同样使用Boolean就不会，麻烦尽快修复一下
