### ISSUE TITLE
[QUESTION] java.lang.OutOfMemoryError: try enabling LargeObject feature instead

### ISSUE THREAD

**Issue by 156370005** [alibaba/fastjson2#2628]
请问下，什么情况下会报这个错误：
Caused by: java.lang.OutOfMemoryError: try enabling LargeObject feature instead
	at com.alibaba.fastjson2.JSONWriterUTF8.ensureCapacity(JSONWriterUTF8.java:2122) ~[fastjson2-2.0.50.jar:?]
	at com.alibaba.fastjson2.JSONWriterUTF8.writeStringUTF16(JSONWriterUTF8.java:570) ~[fastjson2-2.0.50.jar:?]
	at com.alibaba.fastjson2.writer.OWG_14_27_BaseCar.write(Unknown Source) ~[?:?]
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:364) ~[fastjson2-2.0.50.jar:?]
	at com.alibaba.fastjson2.writer.ObjectWriterArray.write(ObjectWriterArray.java:103) ~[fastjson2-2.0.50.jar:?]
	at com.alibaba.fastjson2.writer.OWG_3_3_Result.write(Unknown Source) ~[?:?]
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:3481) ~[fastjson2-2.0.50.jar:?]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:138) ~[fastjson2-extension-spring5-2.0.50.jar:?]
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227) ~[spring-web-5.3.19.jar:5.3.19]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:86) ~[fastjson2-extension-spring5-2.0.50.jar:?]

在fastjson1时，不报错的，谢谢！

**Comment by chensanjiu** [comment]
> 按照提示开启LargeObject

大佬，springBoot使用FastJsonHttpMessageConverter处理响应，FastJsonHttpMessageConverter没有地方设置LargeObject，导致接口返回数据时超过64M就报错了

**Comment by sai129198** [comment]
设置了LargeObject也没用，遇到超过1G的对象还是会报错。。。版本2.0.53

<img width="822" alt="Image" src="https://github.com/user-attachments/assets/f89336d1-748f-43a9-9048-c0d6972c1c76" />

**Comment by wodejiong** [comment]
<img width="952" height="244" alt="Image" src="https://github.com/user-attachments/assets/2f8da185-58e2-478b-b9aa-713ac4707c94" />
开启了也会报.内容大概26M

**Comment by wenshao** [comment]
是不是有循环引用了？

**Comment by wodejiong** [comment]
> 是不是有循环引用了？

<img width="1237" height="215" alt="Image" src="https://github.com/user-attachments/assets/f890c045-18ba-4e0e-9f07-abca1251fc18" />
代码比较简单.但是result是json字符串.

**Comment by wodejiong** [comment]
2.0.21版本以及之前的版本可以正常使用.
