### ISSUE TITLE
[BUG] 当对象出使用Character 出现java.lang.OutOfMemoryError异常。

### ISSUE THREAD

**Issue by lichuang-dp** [alibaba/fastjson2#2638]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*
public class FastjsonTest {

    @Test
    public void test() {
        String str = "[{\"createBy\":1,\"createDate\":1449141681209,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"545eb6295aac432597ea0f94669f279b\",\"label\":\"xe6xb5x8bxe8xafx95xe6x94xafxe4xbbx98\",\"sort\":0,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271730117,\"value\":\"00\"},{\"createBy\":1,\"createDate\":1432273316602,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"fa9bfed3ca8743f4bd8011460e114275\",\"label\":\"xe6x94xafxe4xbbx98xe5xaex9d\",\"remarks\":\"xe8xaexa2xe5x8dx95xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"sort\":1,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271746158,\"value\":\"01\"},{\"createBy\":1,\"createDate\":1432273336118,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"a1a2867324a34d599bca20824f088435\",\"label\":\"xe9x93xb6xe8x81x94xe7xbdx91xe5x85xb3xe6x94xafxe4xbbx98\",\"sort\":2,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1536720660875,\"value\":\"02\"},{\"createBy\":1,\"createDate\":1432273357852,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"07ccd874a73f4c5fbd4c71ab4aeb0ac3\",\"label\":\"payDollar\",\"sort\":3,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1463363099188,\"value\":\"03\"},{\"createBy\":1,\"createDate\":1432273371935,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"c475019c9de840d59f0e4f181969e667\",\"label\":\"xe9x93xb6xe8x81x94xe6x94xafxe4xbbx98\",\"sort\":4,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271762168,\"value\":\"04\"},{\"createBy\":1,\"createDate\":1432273381505,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"385567ded5d54a6b83f4e9684c126136\",\"label\":\"xe6x89x8bxe6x9cxbaxe6x94xafxe4xbbx98xe5xaex9d\",\"sort\":5,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271770794,\"value\":\"05\"},{\"createBy\":1,\"createDate\":1432273395377,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"0520cdc031444dbdbd3ebe79df6093ac\",\"label\":\"xe5xbexaexe4xbfxa1xe6x94xafxe4xbbx98\",\"sort\":6,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271790186,\"value\":\"06\"},{\"createBy\":1,\"createDate\":1444269856407,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"2aaba92e6d2d4666ab4a9c1e29f56077\",\"label\":\"xe5xbexaexe4xbfxa1xe6x94xafxe4xbbx98xefxbcx88xe5xaexa2xe6x88xb7xe7xabxafxefxbcx89\",\"sort\":7,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271819194,\"value\":\"07\"},{\"createBy\":1,\"createDate\":1444269869583,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"57639f0c251f4a189d3379b051121b72\",\"label\":\"xe6x94xafxe4xbbx98xe5xaex9dxefxbcx88xe5xaexa2xe6x88xb7xe7xabxafxefxbcx89\",\"sort\":8,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271783917,\"value\":\"08\"},{\"createBy\":1,\"createDate\":1449042107563,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"5319662caad54b7da9416d6486582906\",\"label\":\"xe9x93xb6xe8x81x94xe5x9cxa8xe7xbaxbfxe6x94xafxe4xbbx98\",\"sort\":9,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271737881,\"value\":\"09\"},{\"createBy\":1,\"createDate\":1432273406709,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"3a2f17fd993e4f0e9825ffb775f468c2\",\"label\":\"xe7x8exb0xe9x87x91xe5xb8x90xe6x88xb7\",\"sort\":10,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271809509,\"value\":\"10\"},{\"createBy\":1,\"createDate\":1432273425687,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"1e02b3edb16c468f96c9713b3324796c\",\"label\":\"xe9xbex99xe8x85xbexe5x8dxa1xe6x9dx83xe7x9bx8a\",\"sort\":11,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1521082613230,\"value\":\"11\"},{\"createBy\":1,\"createDate\":1432273437577,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"265a60f3468f4dd0aae255e6009ab706\",\"label\":\"xe9xbex99xe8x85xbexe5x8dxa1xe7x82xb9xe6x95xb0\",\"sort\":12,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1504662661132,\"value\":\"12\"},{\"createBy\":1,\"createDate\":1447896221152,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"a50f7d8b9a324b1f83339f9875527270\",\"label\":\"xe7x8exb0xe9x87x91xe5x88xb8xe5x85xa8xe9xa2x9d\",\"sort\":13,\"type\":\"order_pay_type\",\"updateBy\":1468736,\"updateDate\":1466649765054,\"value\":\"13\"},{\"createBy\":1167218,\"createDate\":1515047473683,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"7b156e708ac8418e8d2032daff6c7472\",\"label\":\"xe6xb4xbbxe5x8axa8xe7xabx8bxe5x87x8f\",\"sort\":15,\"type\":\"order_pay_type\",\"updateBy\":1167218,\"updateDate\":1515047473683,\"value\":\"15\"},{\"createBy\":1468736,\"createDate\":1466649740942,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"3020223a2c4142b3befd0ac8670be7f1\",\"label\":\"xe9x93xb6xe8x81x94xe5xbfxabxe6x8dxb7xe6x94xafxe4xbbx98\",\"sort\":20,\"type\":\"order_pay_type\",\"updateBy\":1468736,\"updateDate\":1466649740942,\"value\":\"20\"},{\"createBy\":1,\"createDate\":1432273447853,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"c223efd1b4fc4ca18c910b67f3fba418\",\"label\":\"xe6xb5xa6xe5x8fx91xe6x94xafxe4xbbx98\",\"sort\":21,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1451271713325,\"value\":\"21\"},{\"createBy\":1,\"createDate\":1466402779621,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"a27edd3adb3740a9ac4978371987cbfa\",\"label\":\"xe4xb8xadxe8xa1x8cxe7xbdx91xe9x93xb6xe6x94xafxe4xbbx98\",\"sort\":22,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1466402779621,\"value\":\"22\"},{\"createBy\":1468736,\"createDate\":1466649699634,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"5c91a74bc4904fcaa200c76008c6391c\",\"label\":\"xe5xb7xa5xe8xa1x8cxe7xbdx91xe9x93xb6xe6x94xafxe4xbbx98\",\"sort\":23,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1473302180586,\"value\":\"23\"},{\"createBy\":1,\"createDate\":1473302141155,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"f5d1da381ea84f529df4a40b4018ac7f\",\"label\":\"xe8xa5xbfxe5xaex89xe9x93xb6xe8xa1x8cxe6x94xafxe4xbbx98\",\"sort\":24,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1473302150175,\"value\":\"24\"},{\"createBy\":1,\"createDate\":1478757301859,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"fd14762712b74a3fbaf23cd1625aabf3\",\"label\":\"Apple Pay\",\"sort\":25,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1478757308764,\"value\":\"25\"},{\"createBy\":1,\"createDate\":1478765806342,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"8977a744e66e43f5893ed0e9d2bd06a9\",\"label\":\"xe5xbexaexe4xbfxa1xe6x89xabxe7xa0x81xe6x94xafxe4xbbx98\",\"sort\":26,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1478765806342,\"value\":\"26\"},{\"createBy\":1,\"createDate\":1480915375386,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"a4e898ee9abe4db6884e560da5f3b22c\",\"label\":\"Stripe Pay\",\"sort\":27,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1480915375386,\"value\":\"27\"},{\"createBy\":4463176,\"createDate\":1481524298161,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"a9b54cd6d76e433cac5af61f5ef2c58a\",\"label\":\"xe7xbfxbcxe6x94xafxe4xbbx98\",\"sort\":28,\"type\":\"order_pay_type\",\"updateBy\":4463176,\"updateDate\":1481524308697,\"value\":\"28\"},{\"createBy\":4463176,\"createDate\":1490169666068,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"a006caacd1c142b49f294a2f0ff25ee2\",\"label\":\"xe5xb7xa5xe8xa1x8cxe6x89xabxe7xa0x81xe6x94xafxe4xbbx98\",\"remarks\":\"xe5xb7xa5xe8xa1x8cexe8x81x94xe6x89xabxe7xa0x81xe6x94xafxe4xbbx98\",\"sort\":29,\"type\":\"order_pay_type\",\"updateBy\":4463176,\"updateDate\":1490169707216,\"value\":\"29\"},{\"createBy\":1,\"createDate\":1494485179806,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"45e4a0ee716d4ae6be748b1e13614053\",\"label\":\"payDollar(xe6x96xb0)\",\"sort\":30,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1494485179806,\"value\":\"30\"},{\"createBy\":1468736,\"createDate\":1445411439148,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"2d26a33f421c4ce3813d8b4a250e7625\",\"label\":\"xe5xa4xa7xe5xaexa2xe6x88xb7xe6x9dx83xe7x9bx8a\",\"sort\":31,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1521082623493,\"value\":\"31\"},{\"createBy\":4463176,\"createDate\":1497235678238,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"eb884883401c412a83d926e57cea1178\",\"label\":\"xe6xb8xa4xe6xb5xb7xe9x93xb6xe8xa1x8c\",\"sort\":32,\"type\":\"order_pay_type\",\"updateBy\":4463176,\"updateDate\":1497235678238,\"value\":\"32\"},{\"createBy\":4463176,\"createDate\":1501664078295,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"d7da73c7932342cbab0b0d646b390c26\",\"label\":\"xe5xb7xa5xe8xa1x8cexe6x94xafxe4xbbx98\",\"sort\":33,\"type\":\"order_pay_type\",\"updateBy\":4463176,\"updateDate\":1501664088498,\"value\":\"33\"},{\"createBy\":1,\"createDate\":1532593679017,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"1ef7d115f3bc4a03afc62d7b17431d1f\",\"label\":\"xe8x9cx80xe4xbfxa1Exe6x94xafxe4xbbx98\",\"sort\":34,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1532593683125,\"value\":\"34\"},{\"createBy\":1,\"createDate\":1532921659503,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"8f261ad7cc7c4fdf89a0eb74e7587425\",\"label\":\"xe5x85x89xe5xa4xa7APPxe6x94xafxe4xbbx98\",\"sort\":35,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1533173306302,\"value\":\"35\"},{\"createBy\":1,\"createDate\":1542873313890,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"c4768ca12b0443fc8e603aa3e504d444\",\"label\":\"xe5xa2x83xe5xa4x96xe9x93xb6xe8x81x94xe5xbfxabxe6x8dxb7xe6x94xafxe4xbbx98\",\"sort\":36,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1542873322738,\"value\":\"36\"},{\"createBy\":1,\"createDate\":1547544947727,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"7c468d51f0714565a2cffe58cc742ab3\",\"label\":\"xe4xb8xadxe8xa1x8cxe7xbcxa4xe7xbaxb7xe6x94xafxe4xbbx98\",\"sort\":37,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1547544947727,\"value\":\"37\"},{\"createBy\":1,\"createDate\":1555312337886,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"ad76237b9a634a3e9329d996d7652f38\",\"label\":\"xe4xbaxacxe4xb8x9cxe6x94xafxe4xbbx98\",\"sort\":38,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1555312337886,\"value\":\"38\"},{\"createBy\":19040421,\"createDate\":1581317943249,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"9E0EF8ED0F3E3C18E0530164A8C077E8\",\"label\":\"xe4xbax91xe9x97xaaxe4xbbx98(SDK)\",\"sort\":39,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1600919508259,\"value\":\"39\"},{\"createBy\":1,\"createDate\":1591001542314,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"A6E202BAE4005F07E0530164A8C01FE6\",\"label\":\"xe6x8bx9bxe8xa1x8cH5xe6x94xafxe4xbbx98\",\"sort\":40,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1591001551465,\"value\":\"40\"},{\"createBy\":1,\"createDate\":1591001575360,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"A6E202BAE4015F07E0530164A8C01FE6\",\"label\":\"xe6x8bx9bxe8xa1x8cxe5xb0x8fxe7xa8x8bxe5xbax8fxe6x94xafxe4xbbx98\",\"sort\":41,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1591001585166,\"value\":\"41\"},{\"createBy\":1,\"createDate\":1591152988061,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"A6FC527D8A313AEEE0530164A8C04426\",\"label\":\"xe6x8bx9bxe8xa1x8cxe4xbax8cxe7xbbxb4xe7xa0x81xe6x94xafxe4xbbx98\",\"sort\":42,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1591152988061,\"value\":\"42\"},{\"createBy\":1,\"createDate\":1592376727267,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"A8408B283BBA0B2FE0530264A8C0F746\",\"label\":\"xe5xb9xbfxe5x8fx91xe6x94xafxe4xbbx98\",\"sort\":43,\"type\":\"order_pay_type\",\"updateBy\":19040421,\"updateDate\":1596680559478,\"value\":\"43\"},{\"createBy\":19040421,\"createDate\":1597829357155,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"AD2EFA99CAA10390E0530164A8C0AA9B\",\"label\":\"xe4xbaxacxe4xb8x9cxe5x85x88xe4xbaxabxe5x90x8exe4xbbx98\",\"sort\":44,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1598586503239,\"value\":\"44\"},{\"createBy\":1,\"createDate\":1598404621508,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"ADA2358682F82F9FE0530264A8C0C6F3\",\"label\":\"xe4xb8xadxe4xbfxa1xe9x93xb6xe8xa1x8cxe6x94xafxe4xbbx98\",\"sort\":45,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1598404621508,\"value\":\"45\"},{\"createBy\":1,\"createDate\":1598586518923,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"ADD5136CD8CE5352E0530264A8C07B47\",\"label\":\"xe5x85xb4xe4xb8x9axe9x93xb6xe8xa1x8cxe6x94xafxe4xbbx98\",\"sort\":46,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1598586518923,\"value\":\"46\"},{\"createBy\":1,\"createDate\":1641259587955,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"D447839F6FE041C9E0530164A8C0DA0C\",\"label\":\"xe4xbaxa4xe9x80x9axe9x93xb6xe8xa1x8cxe6x94xafxe4xbbx98\",\"sort\":47,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1641259587955,\"value\":\"47\"},{\"createBy\":1,\"createDate\":1600919538897,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"AFCED63E1D9706F8E0530164A8C03CE2\",\"label\":\"xe4xbax91xe9x97xaaxe4xbbx98(APP)\",\"sort\":49,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1600919556886,\"value\":\"49\"},{\"createBy\":1,\"createDate\":1621255093000,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"AFCED63E1D9706F8E0530164A8C03s32\",\"label\":\"xe9xa1xb9xe7x9bxaexe6x94xafxe4xbbx98\",\"sort\":50,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1621255093000,\"value\":\"50\"},{\"createBy\":1,\"createDate\":1621255093000,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"AFCED63E1D9706F8E0530164A8C03es2\",\"label\":\"xe6x9dx83xe7x9bx8axe6x94xafxe4xbbx98\",\"sort\":51,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1621255093000,\"value\":\"51\"},{\"createBy\":1,\"createDate\":1621255093000,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"AFCED63E1D9706F8E0530164A8C03es3\",\"label\":\"xe7xacxacxe4xb8x89xe6x96xb9xe6x9dx83xe7x9bx8axe6x94xafxe4xbbx98\",\"sort\":52,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1621255093000,\"value\":\"52\"},{\"createBy\":1,\"createDate\":1634536800000,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"AFCED63E1D9706F8E0530164A8C13es3\",\"label\":\"xe5x85xb6xe4xbbx96\",\"sort\":53,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1634536800000,\"value\":\"53\"},{\"createBy\":1468736,\"createDate\":1681712960838,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"F97E867D0F96CA6EE053CA64A8C0BDB0\",\"label\":\"xe6xb0x91xe7x94x9fxe9x93xb6xe8xa1x8cxe6x94xafxe4xbbx98\",\"sort\":54,\"type\":\"order_pay_type\",\"updateBy\":1468736,\"updateDate\":1681712960838,\"value\":\"54\"},{\"createBy\":1468736,\"createDate\":1690160915049,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"0131B3607B45126AE063CA64A8C065E0\",\"label\":\"xe6x94xafxe4xbbx98xe5xaex9dxe5x8dx8fxe8xaexaexe6x89xa3xe6xacxbe\",\"sort\":55,\"type\":\"order_pay_type\",\"updateBy\":1468736,\"updateDate\":1690160915049,\"value\":\"55\"},{\"createBy\":1468736,\"createDate\":1690160934894,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"0131B3607B46126AE063CA64A8C065E0\",\"label\":\"xe5xbexaexe4xbfxa1xe5x8dx8fxe8xaexaexe6x89xa3xe6xacxbe\",\"sort\":56,\"type\":\"order_pay_type\",\"updateBy\":1468736,\"updateDate\":1690160934894,\"value\":\"56\"},{\"createBy\":1,\"createDate\":1528855261716,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"d546eba2be4642e086853932bd824b4c\",\"label\":\"xe7xacxacxe4xb8x89xe6x96xb9xe6x9dx83xe7x9bx8a\",\"sort\":98,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1528855269348,\"value\":\"98\"},{\"createBy\":1,\"createDate\":1464746962443,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"2f0b8accab934602a6387aaa72deab6c\",\"label\":\"xe8xb5xa0xe9x80x81xe8xaexa2xe5x8dx95\",\"sort\":99,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1464746962443,\"value\":\"99\"},{\"createBy\":14461759,\"createDate\":1555569630197,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe6x96xb9xe5xbcx8f\",\"id\":\"146cd2085af1485a9b445a33d55df540\",\"label\":\"xe5xb9xbfxe5x86x9cxe5x95x86xe7xa7xafxe5x88x86xe6x94xafxe4xbbx98\",\"sort\":100,\"type\":\"order_pay_type\",\"updateBy\":14461759,\"updateDate\":1555569630197,\"value\":\"100\"},{\"createBy\":1,\"createDate\":1464746962443,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"2f0b8accab934602a6387dsa72deab6c\",\"label\":\"xe7xa7xafxe5x88x86xe6x94xafxe4xbbx98\",\"sort\":101,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1464746962443,\"value\":\"101\"},{\"createBy\":1,\"createDate\":1630289362443,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"2f0b8accab938952a6387dsa72deab6c\",\"label\":\"xe7xa7xafxe5x88x86+xe7x8exb0xe9x87x91\",\"sort\":102,\"type\":\"order_pay_type\",\"updateBy\":1,\"updateDate\":1630289362443,\"value\":\"102\"},{\"createBy\":13823763,\"createDate\":1603338793723,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"B2241688A8B1415DE0530164A8C0E1AF\",\"label\":\"Yandex Pay\",\"remarks\":\"xe8x8bxb1xe6x96x87appxe6x94xafxe4xbbx98\",\"sort\":105,\"type\":\"order_pay_type\",\"updateBy\":13823763,\"updateDate\":1603338793723,\"value\":\"105\"},{\"createBy\":13823763,\"createDate\":1633942201252,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"CDA416F468E5160DE0530164A8C08549\",\"label\":\"Ingenico Pay\",\"sort\":106,\"type\":\"order_pay_type\",\"updateBy\":13823763,\"updateDate\":1633942201252,\"value\":\"106\"},{\"createBy\":13823763,\"createDate\":1668751200000,\"delFlag\":\"0\",\"description\":\"xe6x94xafxe4xbbx98xe7xb1xbbxe5x9ex8b\",\"id\":\"CDA416F468E5160DE0530114A8C08107\",\"label\":\"xe4xbcx81xe4xb8x9axe8xb4xa6xe6x88xb7\",\"sort\":107,\"type\":\"order_pay_type\",\"updateBy\":13823763,\"updateDate\":1668751200000,\"value\":\"107\"}]";

        List<Dict> list = JSONArray.parseArray(str).toJavaList(Dict.class);

        String value = JSON.toJSONString(list);

        System.out.println(value);
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public class Dict extends BaseModel {
        private static final long serialVersionUID = 1L;
        private String id;
        private String label;
        private String value;
        private String type;
        private String description;
        private Integer sort;
        private Long createBy;
        private Date createDate;
        private Long updateBy;
        private Date updateDate;
        private String remarks;
        private Character delFlag;
    }
}

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

java.lang.OutOfMemoryError
	at com.alibaba.fastjson2.JSONWriterUTF16.writeChar(JSONWriterUTF16.java:852)
	at com.alibaba.fastjson2.writer.ObjectWriterImplCharacter.write(ObjectWriterImplCharacter.java:32)
	at com.alibaba.fastjson2.writer.OWG_1_19_Dict.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:373)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1473)
	at FastjsonTest.test(FastjsonTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://github.com/alibaba/fastjson2/assets/171111773/7cab9e2a-0a93-46ba-85f0-dbb11221b5af)

**Comment by lzz513** [comment]
<img width="510" alt="1716974500710" src="https://github.com/alibaba/fastjson2/assets/45329907/cd2ca0f3-f7c0-4444-afb4-116e65617751">
这个地方应该要用off，我看新版本已经修复了可以切50试下

**Comment by wenshao** [comment]
这个问题修复过，请跟新到2.0.51版本
