### ISSUE TITLE
[BUG]JSON文件 第一行为 注释时，提示非法字符 

### ISSUE THREAD

**Issue by mancong** [alibaba/fastjson2#264]
### 问题描述

当JSON文件第一行(或开始的 两个字符)为 注释时( '//' )，则会出现 非法字符 问题

### 环境信息

 - JDK信息： [e.g.：Openjdk 1.8.0_201]
 - 版本信息：[e.g.：Fastjson2 2.0.3]
 

### 重现步骤
RT 操作。

原始JSON文件
```json
// 首行的注释
{
  // 此处的注释没有问题
  "type_number": 1,
  "type_boolean": true,
  "type_string": "abcd",
  "type_object": {
    "o1_1": "555",
    "o1_2": "abcd"
  }
}
```

```java
JSON.parseObject("//首行的注释有{//此处的注释没有问题\"type_number\":1,\"type_boolean\":true,\"type_string\":\"abcd\",\"type_object\":{\"o1_1\":\"555\",\"o1_2\":\"abcd\"}}")
```

### 期待的正确结果
正确解析

### 相关日志输出
```java
com.alibaba.fastjson2.JSONException: illegal input， offset 1, char /

	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:376)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:79)
	at net.uncle.module.ValidJsonQTest.testValid(Test.java:36)
```

**Comment by presenth7s** [comment]
如果说注释引起的，不属于bug吧，根据JSON文件规范（http://www.json.org, RFC 4627, RFC 7159）提示JSON文件本身就是不支持注释的

**Comment by mancong** [comment]
> 支持了，但还是不完善的，你还可以用2.0.4-SNAPSHOT版本验证

感谢回复，我测试一下。

**Comment by mancong** [comment]
> 已经支持了，但仍然是不完善的，你可以用2.0.4-SNAPSHOT版本验证

经过测试，当前case 已经可以 解析
