### ISSUE TITLE
[BUG] Support `@JsonBackReference` and `JsonManagedReference` annotations

### ISSUE THREAD

**Issue by jorgerod** [alibaba/fastjson2#2644]
Hi

We are testing `FastJson2` in a spring-boot based application and we have a DTO with the `@JsonManagedReference` and `@JsonBackReference` annotation and it is being supported and throws the following exception:

```java
com.alibaba.fastjson2.JSONException: level too large : 2048

	at com.alibaba.fastjson2.JSONWriterUTF16.startObject(JSONWriterUTF16.java:122)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
	at com.alibaba.fastjson2.writer.ObjectWriter2.write(ObjectWriter2.java:71)
	at com.alibaba.fastjson2.writer.OWG_1_2_Item.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:353)
	at com.alibaba.fastjson2.writer.FieldWriterListFunc.write(FieldWriterListFunc.java:76)
```

Test to reproduce:

```java
public class JsonManagedReferenceTest {

  @Test
  public void testJsonBackReference() throws Exception {
    // given
    final JsonManagedReferenceDTO dto = new JsonManagedReferenceDTO();

    final Item item = new Item();
    item.setItemName("Item1");
    item.setUser(dto);

    dto.getItems().add(item);

    // when
    final ObjectMapper mapper = new ObjectMapper();
    final String jsonJackson = mapper.writeValueAsString(dto);

    final String jsonFastjson2 = JSON.toJSONString(dto);

    // then
    assertThat(jsonJackson).isEqualTo(jsonFastjson2);
  }

  static class JsonManagedReferenceDTO {
    String id;

    @JsonManagedReference
    private List<Item> items = new ArrayList<>();

    public String getId() {
      return this.id;
    }

    public void setId(final String id) {
      this.id = id;
    }

    public List<Item> getItems() {
      return this.items;
    }

    public void setItems(final List<Item> items) {
      this.items = items;
    }

    static class Item {

      private String itemName;

      @JsonBackReference
      private JsonManagedReferenceDTO user;

      public String getItemName() {
        return this.itemName;
      }

      public void setItemName(final String itemName) {
        this.itemName = itemName;
      }

      public JsonManagedReferenceDTO getUser() {
        return this.user;
      }

      public void setUser(final JsonManagedReferenceDTO user) {
        this.user = user;
      }
    }
  }
}

```
I have tried adding 
```java
 String jsonFastjson2 = JSON.toJSONString(dto, Feature.ReferenceDetection); and the result is not correct either:
```
Result FastJson2
```json
{"items":[{"itemName":"Item1","user":{"$ref":"$"}}]}
````
Result Jackson
```
{"id":null,"items":[{"itemName":"Item1"}]}
```

Thank you very much

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.51-SNAPSHOT/

The BUG has been fixed. Please help verify it with version 2.0.51-SNAPSHOT

**Comment by jorgerod** [comment]
Fixed! Thank you very much

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.51
Please use the new version 2.0.51
