### ISSUE TITLE
[BUG]无法解析 $ref: @

### ISSUE THREAD

**Issue by raychow** [alibaba/fastjson2#2671]
### 问题描述

fastjson2 2.0.51

```java
final var str = "{\"context\":{\"$ref\":\"@\"}}";
JSON.parseObject(str, Map.class);
```

报错:

Exception in thread "main" com.alibaba.fastjson2.JSONException: reference path invalid : @
	at com.alibaba.fastjson2.JSONReader.handleResolveTasks(JSONReader.java:311)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:866)

在 fastjson1 中, 可以被解析为 `{"context":{"context":...}}`

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.52-SNAPSHOT/
问题已修复，请用2.0.52-SNAPSHOT版本帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.52
问题已修复，请用新版本
