### ISSUE TITLE
[BUG]大数解析报错

### ISSUE THREAD

**Issue by raychow** [alibaba/fastjson2#2672]
### 问题描述

fastjson2 2.0.51

```java
JSON.parseObject("{\"token\": 2.105465717176397390012604E+1294}");
```

报错:
Exception in thread "main" com.alibaba.fastjson2.JSONException: too large exp value : 1294
	at com.alibaba.fastjson2.JSONReaderUTF8.readNumber0(JSONReaderUTF8.java:5458)
	at com.alibaba.fastjson2.JSONReader.readNumber(JSONReader.java:1004)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:2087)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:348)

在 fastjson1 中 token 可被解析为 BigDecimal

**Comment by wenshao** [comment]
为什么有这么大的exp数值，你这个是测试数据还是业务数据？

目前做了限制最大1023。做这个限制是防止恶意输入做DOS攻击。

**Comment by raychow** [comment]
> 为什么有这么大的exp数值，你这个是测试数据还是业务数据？
> 
> 目前做了限制最大1023。做这个限制是防止恶意输入做DOS攻击。

我们上游系统的数据, 这个值是脏数据, 可以忽略, 但现在解析的时候没有时机处理.

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.52-SNAPSHOT/
问题已修复，最大exp调整为2048了，请用2.0.52-SNAPSHOT版本帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.52
问题已修复，请用新版本
