### ISSUE TITLE
[BUG] 数组含有注释，解析异常

### ISSUE THREAD

**Issue by houseBetter** [alibaba/fastjson2#2686]
### 问题描述
*简要描述您碰到的问题。*
JSON.parse() 解析数组，数组元素有注释，解析异常

### 环境信息
*请填写以下信息：*

 - JDK信息： 11.0.17
 - 版本信息：Fastjson 2.0.31
 

### 重现步骤
*如何操作可以重现该问题：*

```java
public static void main(String[] args) {
        String str = "{\n" +
                "    \n" +
                "    array: [\n" +
                "        // {\n" +
                "        //     name: 'hello',\n" +
                "        // },\n" +
                "        {\n" +
                "            name: \"world\",\n" +
                "        },\n" +
                "      ],\n" +
                "}";
        JSONObject o =  (JSONObject)JSON.parse(str);
        System.out.println(o);
    }
```
```java
Exception in thread "main" com.alibaba.fastjson.JSONException
	at com.alibaba.fastjson.JSON.parse(JSON.java:828)
	at cc.fi.gis.FastjsonTest.main(FastjsonTest.java:19)
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2283)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1713)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:396)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1834)
	at com.alibaba.fastjson.JSON.parse(JSON.java:824)
	... 1 more
```

### 期待的正确结果
不报错

**Comment by yanxutao89** [comment]
属性名未带双引号请显式启用AllowUnQuotedFieldNames

**Comment by houseBetter** [comment]
> 属性名未带双引号请显式启用AllowUnQuotedFieldNames

跟这个没关系，加了，还是报错

**Comment by yanxutao89** [comment]
> > 属性名未带双引号请显式启用AllowUnQuotedFieldNames
> 
> 跟这个没关系，加了，还是报错

升级最新版本试试

**Comment by houseBetter** [comment]
> > > 属性名未带双引号请显式启用AllowUnQuotedFieldNames
> > 
> > 
> > 跟这个没关系，加了，还是报错
> 
> 升级最新版本试试

有效，谢谢啊
