### ISSUE TITLE
[BUG]解析为对象时，json中不存在的字段会报错，AllowUnQuotedFieldNames 或 NullOnError 也没用

### ISSUE THREAD

**Issue by Forest-Fairy** [alibaba/fastjson2#2702]
![image](https://github.com/alibaba/fastjson2/assets/58804359/237887aa-de68-4ce7-92e1-df57bc96f200)
![image](https://github.com/alibaba/fastjson2/assets/58804359/529cf19f-9bf0-4aed-bdab-316b6bf7b718)
** 报错信息
Exception in thread "main" com.alibaba.fastjson2.JSONException: TODO : '
	at com.alibaba.fastjson2.JSONReaderUTF8.skipValue(JSONReaderUTF8.java:3489)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:117)
	at com.alibaba.fastjson2.reader.ORG_1_2_Test.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:857)
	at top.ff.JsonUtil.parseJson(JsonUtil.java:26)
	at top.ff.Main.main(Main.java:27)

**Comment by Forest-Fairy** [comment]
我自己简单搞了下 ok了  单引号就会 双引号不会。

**Comment by Forest-Fairy** [comment]
![image](https://github.com/alibaba/fastjson2/assets/58804359/73d7d912-7c7c-4f71-b25e-8c52a05e460d)
等官方修复咯

**Comment by yanxutao89** [comment]
麻烦提供下可复现的示例代码

**Comment by yanxutao89** [comment]
麻烦提供下可复现的示例代码

**Comment by Forest-Fairy** [comment]
> 麻烦提供下可复现的示例代码

代码不在我现在的电脑里，复现很简单，用单引号的json串 {'name': 'a', 'age1': 4} 转化成带有name和age的对象，age会匹配不上然后报错。用双引号就没问题。最后发现在JSONReader的那个跳过判断，加上单引号就好

**Comment by Forest-Fairy** [comment]
是我的问题 编译器提示我最高版本是2.0.29 今天发现最新的是51 切换到51 没有这个问题
