### ISSUE TITLE
[BUG] Dubbo反序列化出现UnsupportedOperationException

### ISSUE THREAD

**Issue by nieqiurong** [alibaba/fastjson2#2734]
### 问题描述
Dubbo反序列化时使用了JSONReader.Feature.FieldBased导致UnsupportedOperationException

### 环境信息

 - OS信息：  win11
 - JDK信息： 21
 - 版本信息：2.0.51
 

### 重现步骤
*如何操作可以重现该问题：*
模型属性定义默认Collections.emptyList()值;

```java
    public static void main(String[] args) {
        Page<String> page = new Page<>();
        List<String> data = new ArrayList<>();
        data.add("1234");
        page.setData(data);
        byte[] bytes = JSONB.toBytes(page);
        Page page1 = JSONB.parseObject(bytes, Page.class, JSONReader.Feature.FieldBased);
        System.out.println(page1);
    }

    public static class Page<T> {

        private List<T> data = Collections.emptyList();

        public void setData(List<T> items) {
            this.data = items;
        }

        public List<T> getData() {
            return data;
        }
    }

```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:155)
	at java.base/java.util.AbstractList.add(AbstractList.java:113)
	at com.alibaba.fastjson2.reader.ORG_1_1_Page.readJSONBObject(Unknown Source)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:799)
	at com.baomidou.mybatisplus.test.App.main(App.java:18)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by rowstop** [comment]
#2691
