### ISSUE TITLE
[BUG] 在尝试解析字符串到Long类型时，报错信息不明确

### ISSUE THREAD

**Issue by bruce-wqz** [alibaba/fastjson2#2749]
### 问题描述
*在尝试解析字符串到Long类型时，报错信息不明确*

### 环境信息
*请填写以下信息：*

 - OS信息：  Macos
 - JDK信息： Openjdk 17
 - 版本信息：Fastjson2 2.0.51
 

### 重现步骤
*如何操作可以重现该问题：*

1. Bean
```java
public class User{
    private Long userId;
...
}
```

2. json
```
{"userId":"Alexander77"}
```

3、报错信息

java.lang.NullPointerException: date
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.time.LocalDateTime.of(LocalDateTime.java:376)
	at com.alibaba.fastjson2.util.DateUtils.parseLocalDateTime(DateUtils.java:1409)
	at com.alibaba.fastjson2.util.DateUtils.parseMillis(DateUtils.java:1601)
	at com.alibaba.fastjson2.util.DateUtils.parseMillis(DateUtils.java:182)
	at com.alibaba.fastjson2.JSONReader.toInt64(JSONReader.java:3095)
	at com.alibaba.fastjson2.JSONReader.getInt64Value(JSONReader.java:902)
	at com.alibaba.fastjson2.JSONReaderUTF8.readInt64(JSONReaderUTF8.java:3774)

### 期待的正确结果

希望能明确报出是哪个字段，及错误原因，这样的提示有点摸不着头脑。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.56
问题已修复，请用新版本
