### ISSUE TITLE
[BUG]JSONB在注册了自定义的Writer、Reader方法后错误

### ISSUE THREAD

**Issue by ywzou** [alibaba/fastjson2#2752]
JSONB自定义了ObjectWriter、ObjectReader，或使用@JSONField(format = "yyyy-MM-dd")定义时间格式后，反序列化异常

### 环境信息
*请填写以下信息：*

 - OS信息：  window
 - JDK信息： 21
 - 版本信息：Fastjson2 2.0.51
 

### 重现步骤
1、自定义了一个BigDecimalWriter实现BigDecimal序列化的时候转换为格式化千分位转换为String类型
`public class BigDecimalWriter implements ObjectWriter<BigDecimal> {
	public final static BigDecimalWriter INSTANCE = new BigDecimalWriter();

	@Override
	public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
		if (object == null) {
			jsonWriter.writeNull();
			return;
		}

		if (object instanceof BigDecimal value) { 
                        DecimalFormat fmt = new DecimalFormat("###,##0.00")
			String str =fmt.format(value);
			jsonWriter.writeString(str);
		}
	}
}`

2、定义了一个BigDecimalReader在反序列化的时候去除字符中的千分位逗号转为BigDecimal
`public class BigDecimalReader implements ObjectReader<BigDecimal> {

	private static final Logger log = LoggerFactory.getLogger(BigDecimalReader.class);

	public final static BigDecimalReader INSTANCE = new BigDecimalReader();

	@Override
	public BigDecimal readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
		if (jsonReader.nextIfNull()) {
			return null;
		}

		String typeName = fieldType.getTypeName();
		log.info(typeName);

		String value = jsonReader.readString();
		if (null == value || value.length() < 1) {
			return null;
		}
		return new BigDecimal(value.replaceAll(",", ""));
	}

}
`

3、使用@JSONField定义LocalDateTime序列化格式
`
public class DemoBean {
        private BigDecimal amount;

        @JSONField(format = "yyyy-MM-dd")
	private LocalDateTime createDate;

       ...get/set
       ...toString
}
`

4、反序列化异常
`
	public static void main(String[] args) {

		JSON.register(BigDecimal.class, BigDecimalWriter.INSTANCE); 
		JSON.register(BigDecimal.class, BigDecimalReader.INSTANCE); 

		DemoBean bean = new DemoBean(); 
		bean.setCreateDate(LocalDateTime.now());
		bean.setAmount(new BigDecimal("136996364556545465.36"));
		byte[] bytes = JSONB.toBytes(bean);

		DemoBean user = JSONB.parseObject(bytes, DemoBean.class);

		System.out.println(user);
	}

`

异常A-时间反序列化异常
`Caused by: com.alibaba.fastjson2.JSONException: fieldName not support input type LOCAL_DATE -87, offset 47`

异常B-BigDecimal反序列化异常

**Comment by ywzou** [comment]
异常B-BigDecimal反序列化异常
`Exception in thread "main" com.alibaba.fastjson2.JSONException: read field 'com.bijiangzb.loan.starter.adapter.model.DemoBean.setAmount, offset 36
	at com.alibaba.fastjson2.reader.FieldReaderObject.readFieldValue(FieldReaderObject.java:167)
	at com.alibaba.fastjson2.reader.ObjectReader3.readJSONBObject(ObjectReader3.java:196)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:491)
	at com.bijiangzb.loan.starter.adapter.JsonTest.main(JsonTest.java:30)
Caused by: com.alibaba.fastjson2.JSONException: name not support input : OBJECT_END -91
	at com.alibaba.fastjson2.JSONReaderJSONB.notSupportType(JSONReaderJSONB.java:2633)
	at com.alibaba.fastjson2.JSONReaderJSONB.skipValue(JSONReaderJSONB.java:2594)
	at com.alibaba.fastjson2.reader.ObjectReader.readJSONBObject(ObjectReader.java:250)
	at com.alibaba.fastjson2.reader.FieldReaderObject.readFieldValue(FieldReaderObject.java:151)
	... 3 more
`

**Comment by ywzou** [comment]
BigDecimal反序列化异常丁武问题  `com.alibaba.fastjson2.JSONReaderJSONB.readFieldNameHashCode()` 方法的
`   
        final int strlen;
        if (strtype >= BC_STR_ASCII_FIX_MIN && strtype <= BC_STR_ASCII_FIX_MAX) {
            strlen = strtype - BC_STR_ASCII_FIX_MIN;
        } else if (strtype == BC_STR_ASCII || strtype == BC_STR_UTF8) {
            strlen = readLength();
        } else {
           // 异常
            throw readFieldNameHashCodeError();
        }
`
