### ISSUE TITLE
[BUG]JSONB.parseObject deserialization parsing can appear "java.lang.UnsupportedOperationException"

### ISSUE THREAD

**Issue by tanglinyan** [alibaba/fastjson2#2753]
### 问题描述
*简要描述您碰到的问题。*
JSONB.parseObject deserialization parsing can appear "java.lang.UnsupportedOperationException"

### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：Openjdk jdk-21.0.2.jdk]
 - 版本信息：[e.g.：Fastjson2 2.0.51]
 

### 重现步骤
*如何操作可以重现该问题：*

JSONB.parseObject Deserialization https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/pagination/Page.java. 
Java will appear "java.lang. UnsupportedOperationException" error

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
The new version can be solved

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:155)
	at java.base/java.util.AbstractList.add(AbstractList.java:113)
	at com.alibaba.fastjson2.reader.ORG_3_10_Page.readJSONBObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReaderInterface.readJSONBObject(ObjectReaderInterface.java:36)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:591)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:161)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:170)
	... 104 more

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by yanxutao89** [comment]
麻烦更新到2.0.52版本进行验证

**Comment by tanglinyan** [comment]
Have been settled
How big of you
