### ISSUE TITLE
[BUG] JSON.parseObject ConcurrentModificationException

### ISSUE THREAD

**Issue by shaolinwu** [alibaba/fastjson2#2783]
### 问题描述
*简要描述您碰到的问题。*

Hello, 

系统在执行了一周后，突然出现一个JSON.parseObject时遇到多线程问题。请问是什么原因？

java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.getFieldInfo(ObjectReaderProvider.java:675)
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReader(ObjectReaderCreator.java:1235)
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.lambda$createFieldReaders$3(ObjectReaderCreator.java:1572)
        at com.alibaba.fastjson2.util.BeanUtils.declaredFields(BeanUtils.java:309)
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaders(ObjectReaderCreator.java:1566)
        at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:259)
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReaderInternal(ObjectReaderProvider.java:854)
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:746)
        at com.alibaba.fastjson2.JSONReader$Context.getObjectReader(JSONReader.java:4228)
        at com.alibaba.fastjson2.reader.FieldReader.getItemObjectReader(FieldReader.java:494)
        at com.alibaba.fastjson2.reader.FieldReader.getItemObjectReader(FieldReader.java:498)
        at com.alibaba.fastjson2.reader.ORG_3_2_BatchTransfers.readObject(Unknown Source)
        at com.alibaba.fastjson2.JSON.parseObject(JSON.java:726)
        xxx$SingleTransfer.consume(RocketMQListener.java:375)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.46]
 

### 重现步骤
*如何操作可以重现该问题：*
偶然现像，无法重现。

```java

@Data
@ToString
public class BatchTransfers {

    private List<ExTrade> tradedListForTx;
    private ExOrder takerExOrder;

}

#RocketMQ MessageView
public ConsumeResult consume(MessageView mview) {

    byte[] bodyBytes = new byte[mview.getBody().limit() - mview.getBody().position()]; 
    mview.getBody().get(bodyBytes, 0, mview.getBody().limit());
    String rawString = new String(bodyBytes, "UTF-8");
    BatchTransfers trade = JSON.parseObject(rawString, BatchTransfers.class);
   
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
JSON.parseObject需要严格保证线程安全。

**Comment by wenshao** [comment]
这个问题修复过，更新到2.0.51试下问题是否还存在

**Comment by shaolinwu** [comment]
super! thank you so much!

**Comment by shaolinwu** [comment]
the issue is still occurred after running 2 weeks as I reported this issue. upgraded to fastjson2-2.0.51 version without luck.
