### ISSUE TITLE
解析本地文件时抛出异常：offset 1, character /, line 1, column 1

### ISSUE THREAD

**Issue by pengweizhong** [alibaba/fastjson2#2898]
### 问题描述
**解析json文件时抛出异常：**  
```log
Exception in thread "main" com.alibaba.fastjson2.JSONException: offset 1, character /, line 1, column 1, fastjson-version 2.0.52 /Users/pengwz/Desktop/config-bug.json
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1995)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:348)
	at org.example.Main.main(Main.java:102)  
```

### 环境信息

 - OS信息：    
```bash
pengwz@bogon ~ % sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
```
 - JDK信息：  
```bash
pengwz@bogon ~ % java -version
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)
```
 - 版本信息：
 ```xml
<dependency>
     <groupId>com.alibaba.fastjson2</groupId>
     <artifactId>fastjson2</artifactId>
     <version>2.0.52</version>
</dependency>
```
 

### 重现步骤
**直接解析会导致异常**
**代码如下：**
```java
    public static void main(String[] args) {
         //这里就报错了
        JSONObject config = JSON.parseObject(getConfigPath());
        // ... ....
        System.out.println(config.toJSONString());
    }
    //文件在附件中
    public static String getConfigPath() {
        return "/Users/pengwz/Desktop/config-bug.json";
    }
```
**这种方式可以让JSON解析正常工作，需要先把文件加载到内存中。  就像这样：：**  
```java
        try {
            String content = new String(Files.readAllBytes(Paths.get(getConfigPath())), "UTF-8");
            System.out.println(content);  // 输出文件内容，检查是否正确读取
            JSON.parseObject(content);  // 解析 JSON 内容
        } catch (Exception e) {
            e.printStackTrace();
        }
```
**在这里下载测试json文件：**  
[config-bug.json](https://github.com/user-attachments/files/16791308/config-bug.json)

**Comment by mek1986** [comment]
这个不算没事bug吧，JSON.parseObject就是解析字符串，不是解析文件路径哈

**Comment by pengweizhong** [comment]
好的
