### ISSUE TITLE
[BUG] json字符串内容过长时引发 illegal fieldName input 122, offset 4773, character z, line 9, column 8, fastjson-version 2.0.52。

### ISSUE THREAD

**Issue by Xiao-A-Zhai** [alibaba/fastjson2#2904]
### 问题描述
*JSON反序列化时，当json字符串内容过长时，出现 illegal fieldName input 122, offset 4773, character z, line 9, column 8, fastjson-version 2.0.52。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Microsoft Windows [版本 10.0.19045.4780]]
 - JDK信息： [e.g.：Openjdk 22.0.1]
 - 版本信息：[e.g.：Fastjson2 2.0.52]
 

### 重现步骤
*如何操作可以重现该问题：*
可以复制以下代码测试。我将数据放在多个json在线解析网站测试，结果都是无误的，不存在格式之类的问题

public class Test {
    public static void main(String[] args) {
        String a = "[{\"location\":{\"x\": \"-0.768332\",\"y\": \"0.05704\",\"z\": \"0.0\"},\"index\": 2},{\"location\":{\"x\": \"-0.811024\",\"y\": \"0.008477\",\"z\": \"0.0\"},\"index\": 4},{\"location\":{\"x\": \"-0.830571\",\"y\": \"-0.013758\",\"z\": \"0.0\"},\"index\": 6},{\"location\":{\"x\": \"-0.824935\",\"y\": \"-0.007346\",\"z\": \"0.0\"},\"index\": 8},{\"location\":{\"x\": \"-0.795674\",\"y\": \"0.025938\",\"z\": \"0.0\"},\"index\": 10},{\"location\":{\"x\": \"-0.738112\",\"y\": \"0.091415\",\"z\": \"0.0\"},\"index\": 12},{\"location\":{\"x\": \"-0.659925\",\"y\": \"0.180356\",\"z\": \"0.0\"},\"index\": 14},{\"location\":{\"x\": \"-0.554274\",\"y\": \"0.300534\",\"z\": \"0.0\"},\"inde\n" +
                "x\": 16},{\"location\":{\"x\": \"-0.369033\",\"y\": \"0.780241\",\"z\": \"0.0\"},\"index\": 19},{\"location\":{\"x\": \"0.144912\",\"y\": \"0.797848\",\"z\": \"0.0\"},\"index\": 21},{\"location\":{\"x\": \"0.233746\",\"y\": \"1.012275\",\"z\": \"0.0\"},\"index\": 23},{\"location\":{\"x\": \"0.086928\",\"y\": \"0.580593\",\"z\": \"0.0\"},\"index\": 24},{\"location\":{\"x\": \"0.035156\",\"y\": \"0.6286\",\"z\": \"0.0\"},\"index\": 25},{\"location\":{\"x\": \"-0.054684\",\"y\": \"0.681895\",\"z\": \"0.0\"},\"index\": 26},{\"location\":{\"x\": \"-0.160876\",\"y\": \"0.742971\",\"z\": \"0.0\"},\"index\": 27},{\"location\":{\"x\": \"-0.281857\",\"y\": \"0.860878\",\"z\": \"0.0\"},\"index\": 28},{\"location\":{\"x\": \"-0.388065\",\n" +
                "\"y\": \"0.991797\",\"z\": \"0.0\"},\"index\": 29},{\"location\":{\"x\": \"-0.469992\",\"y\": \"1.100613\",\"z\": \"0.0\"},\"index\": 30},{\"location\":{\"x\": \"-0.532405\",\"y\": \"1.19655\",\"z\": \"0.0\"},\"index\": 31},{\"location\":{\"x\": \"-0.5597\",\"y\": \"1.255629\",\"z\": \"0.0\"},\"index\": 32},{\"location\":{\"x\": \"-0.562715\",\"y\": \"1.292603\",\"z\": \"0.0\"},\"index\": 33},{\"location\":{\"x\": \"-0.576496\",\"y\": \"1.297537\",\"z\": \"0.0\"},\"index\": 34},{\"location\":{\"x\": \"-0.634179\",\"y\": \"1.288641\",\"z\": \"0.0\"},\"index\": 35},{\"location\":{\"x\": \"-0.683457\",\"y\": \"1.324805\",\"z\": \"0.0\"},\"index\": 36},{\"location\":{\"x\": \"-0.694109\",\"y\": \"1.407581\",\"z\": \"0.0\"},\"index\"\n" +
                ": 37},{\"location\":{\"x\": \"-0.675899\",\"y\": \"1.535812\",\"z\": \"0.0\"},\"index\": 38},{\"location\":{\"x\": \"-0.628826\",\"y\": \"1.709494\",\"z\": \"0.0\"},\"index\": 39},{\"location\":{\"x\": \"-0.552893\",\"y\": \"1.928629\",\"z\": \"0.0\"},\"index\": 40},{\"location\":{\"x\": \"-0.52288\",\"y\": \"2.274498\",\"z\": \"0.0\"},\"index\": 41},{\"location\":{\"x\": \"-0.53556\",\"y\": \"2.56024\",\"z\": \"0.0\"},\"index\": 42},{\"location\":{\"x\": \"-0.503766\",\"y\": \"2.745405\",\"z\": \"0.0\"},\"index\": 43},{\"location\":{\"x\": \"-0.427497\",\"y\": \"2.829996\",\"z\": \"0.0\"},\"index\": 44},{\"location\":{\"x\": \"-0.306759\",\"y\": \"2.814007\",\"z\": \"0.0\"},\"index\": 45},{\"location\":{\"x\": \"-0.111591\"\n" +
                ",\"y\": \"2.66642\",\"z\": \"0.0\"},\"index\": 46},{\"location\":{\"x\": \"0.142525\",\"y\": \"2.450066\",\"z\": \"0.0\"},\"index\": 47},{\"location\":{\"x\": \"0.5204\",\"y\": \"2.272087\",\"z\": \"0.0\"},\"index\": 48},{\"location\":{\"x\": \"0.829484\",\"y\": \"2.162884\",\"z\": \"0.0\"},\"index\": 49},{\"location\":{\"x\": \"0.967172\",\"y\": \"2.094109\",\"z\": \"0.0\"},\"index\": 50},{\"location\":{\"x\": \"0.904161\",\"y\": \"2.067463\",\"z\": \"0.0\"},\"index\": 51},{\"location\":{\"x\": \"0.656207\",\"y\": \"2.089619\",\"z\": \"0.0\"},\"index\": 52},{\"location\":{\"x\": \"0.236857\",\"y\": \"2.152184\",\"z\": \"0.0\"},\"index\": 53},{\"location\":{\"x\": \"-0.297248\",\"y\": \"2.217514\",\"z\": \"0.0\"},\"index\": 54},\n" +
                "{\"location\":{\"x\": \"-0.766695\",\"y\": \"2.236366\",\"z\": \"0.0\"},\"index\": 55},{\"location\":{\"x\": \"-1.140412\",\"y\": \"2.255207\",\"z\": \"0.0\"},\"index\": 56},{\"location\":{\"x\": \"-1.328735\",\"y\": \"2.28587\",\"z\": \"0.0\"},\"index\": 57},{\"location\":{\"x\": \"-1.393793\",\"y\": \"2.329117\",\"z\": \"0.0\"},\"index\": 58},{\"location\":{\"x\": \"-1.335579\",\"y\": \"2.384964\",\"z\": \"0.0\"},\"index\": 59},{\"location\":{\"x\": \"-1.154099\",\"y\": \"2.453384\",\"z\": \"0.0\"},\"index\": 60},{\"location\":{\"x\": \"-1.071793\",\"y\": \"2.522034\",\"z\": \"0.0\"},\"index\": 61},{\"location\":{\"x\": \"-0.956085\",\"y\": \"2.725189\",\"z\": \"0.0\"},\"index\": 62},{\"location\":{\"x\": \"-0.494337\",\"y\"\n" +
                ": \"3.161255\",\"z\": \"0.0\"},\"index\": 63},{\"location\":{\"x\": \"0.281134\",\"y\": \"3.855354\",\"z\": \"0.0\"},\"index\": 64},{\"location\":{\"x\": \"1.00738\",\"y\": \"4.531952\",\"z\": \"0.0\"},\"index\": 65},{\"location\":{\"x\": \"1.319183\",\"y\": \"4.759972\",\"z\": \"0.0\"},\"index\": 66},{\"location\":{\"x\": \"1.214396\",\"y\": \"4.55452\",\"z\": \"0.0\"},\"index\": 67},{\"location\":{\"x\": \"1.211981\",\"y\": \"4.475883\",\"z\": \"0.0\"},\"index\": 68},{\"location\":{\"x\": \"1.169556\",\"y\": \"4.318573\",\"z\": \"0.0\"},\"index\": 69},{\"location\":{\"x\": \"0.866768\",\"y\": \"3.817009\",\"z\": \"0.0\"},\"index\": 70},{\"location\":{\"x\": \"0.339333\",\"y\": \"3.01899\",\"z\": \"0.0\"},\"index\": 71},{\"loc\n" +
                "ation\":{\"x\": \"0.038861\",\"y\": \"2.521973\",\"z\": \"0.0\"},\"index\": 72},{\"location\":{\"x\": \"-0.056871\",\"y\": \"2.259514\",\"z\": \"0.0\"},\"index\": 73},{\"location\":{\"x\": \"-0.050248\",\"y\": \"2.134033\",\"z\": \"0.0\"},\"index\": 74},{\"location\":{\"x\": \"-0.100498\",\"y\": \"1.950005\",\"z\": \"0.0\"},\"index\": 75},{\"location\":{\"x\": \"-0.115635\",\"y\": \"1.70536\",\"z\": \"0.0\"},\"index\": 76},{\"location\":{\"x\": \"-0.063417\",\"y\": \"1.480621\",\"z\": \"0.0\"},\"index\": 77},{\"location\":{\"x\": \"-0.011171\",\"y\": \"1.235985\",\"z\": \"0.0\"},\"index\": 78},{\"location\":{\"x\": \"0.010653\",\"y\": \"1.038094\",\"z\": \"0.0\"},\"index\": 79},{\"location\":{\"x\": \"0.009596\",\"y\": \"0.920\n" +
                "036\",\"z\": \"0.0\"},\"index\": 80},{\"location\":{\"x\": \"0.005243\",\"y\": \"0.922554\",\"z\": \"0.0\"},\"index\": 81},{\"location\":{\"x\": \"0.01108\",\"y\": \"0.954651\",\"z\": \"0.0\"},\"index\": 82},{\"location\":{\"x\": \"0.012066\",\"y\": \"0.935028\",\"z\": \"0.0\"},\"index\": 83},{\"location\":{\"x\": \"0.008198\",\"y\": \"0.863815\",\"z\": \"0.0\"},\"index\": 84},{\"location\":{\"x\": \"-0.000525\",\"y\": \"0.740875\",\"z\": \"0.0\"},\"index\": 85},{\"location\":{\"x\": \"-0.016732\",\"y\": \"0.533966\",\"z\": \"0.0\"},\"index\": 86},{\"location\":{\"x\": \"-0.078013\",\"y\": \"0.528214\",\"z\": \"0.0\"},\"index\": 88},{\"location\":{\"x\": \"-0.545872\",\"y\": \"-0.089172\",\"z\": \"0.0\"},\"index\": 97},{\"loca\n" +
                "tion\":{\"x\": \"-0.251307\",\"y\": \"-0.541229\",\"z\": \"0.0\"},\"index\": 106},{\"location\":{\"x\": \"0.090087\",\"y\": \"-0.563965\",\"z\": \"0.0\"},\"index\": 111},{\"location\":{\"x\": \"0.07787\",\"y\": \"-0.523376\",\"z\": \"0.0\"},\"index\": 115},{\"location\":{\"x\": \"0.060936\",\"y\": \"-0.640396\",\"z\": \"0.0\"},\"index\": 118},{\"location\":{\"x\": \"0.219096\",\"y\": \"0.560257\",\"z\": \"0.0\"},\"index\": 127},{\"location\":{\"x\": \"0.091289\",\"y\": \"0.619583\",\"z\": \"0.0\"},\"index\": 130},{\"location\":{\"x\": \"0.092523\",\"y\": \"0.774017\",\"z\": \"0.0\"},\"index\": 133},{\"location\":{\"x\": \"0.058727\",\"y\": \"0.665146\",\"z\": \"0.0\"},\"index\": 135},{\"location\":{\"x\": \"0.053468\",\"y\": \n" +
                "\"0.843719\",\"z\": \"0.0\"},\"index\": 137},{\"location\":{\"x\": \"0.046363\",\"y\": \"1.051315\",\"z\": \"0.0\"},\"index\": 139},{\"location\":{\"x\": \"0.019871\",\"y\": \"0.615494\",\"z\": \"0.0\"},\"index\": 140},{\"location\":{\"x\": \"0.016915\",\"y\": \"0.692123\",\"z\": \"0.0\"},\"index\": 141},{\"location\":{\"x\": \"0.014041\",\"y\": \"0.764374\",\"z\": \"0.0\"},\"index\": 142},{\"location\":{\"x\": \"0.010906\",\"y\": \"0.841629\",\"z\": \"0.0\"},\"index\": 143},{\"location\":{\"x\": \"0.001625\",\"y\": \"0.940063\",\"z\": \"0.0\"},\"index\": 144},{\"location\":{\"x\": \"-0.017946\",\"y\": \"1.069077\",\"z\": \"0.0\"},\"index\": 145},{\"location\":{\"x\": \"-0.039027\",\"y\": \"1.210983\",\"z\": \"0.0\"},\"index\"\n" +
                ": 146},{\"location\":{\"x\": \"-0.053061\",\"y\": \"1.320877\",\"z\": \"0.0\"},\"index\": 147},{\"location\":{\"x\": \"-0.063165\",\"y\": \"1.417953\",\"z\": \"0.0\"},\"index\": 148},{\"location\":{\"x\": \"-0.069345\",\"y\": \"1.50235\",\"z\": \"0.0\"},\"index\": 149},{\"location\":{\"x\": \"-0.071602\",\"y\": \"1.573959\",\"z\": \"0.0\"},\"index\": 150},{\"location\":{\"x\": \"-0.069133\",\"y\": \"1.639404\",\"z\": \"0.0\"},\"index\": 151},{\"location\":{\"x\": \"-0.062554\",\"y\": \"1.682266\",\"z\": \"0.0\"},\"index\": 152},{\"location\":{\"x\": \"-0.052053\",\"y\": \"1.712463\",\"z\": \"0.0\"},\"index\": 153},{\"location\":{\"x\": \"-0.037623\",\"y\": \"1.729767\",\"z\": \"0.0\"},\"index\": 154},{\"location\":{\"x\": \n" +
                "\"-0.019269\",\"y\": \"1.734421\",\"z\": \"0.0\"},\"index\": 155},{\"location\":{\"x\": \"0.006757\",\"y\": \"1.723206\",\"z\": \"0.0\"},\"index\": 156},{\"location\":{\"x\": \"0.033942\",\"y\": \"1.699142\",\"z\": \"0.0\"},\"index\": 157},{\"location\":{\"x\": \"0.065054\",\"y\": \"1.662323\",\"z\": \"0.0\"},\"index\": 158},{\"location\":{\"x\": \"0.100094\",\"y\": \"1.612671\",\"z\": \"0.0\"},\"index\": 159},{\"location\":{\"x\": \"0.139055\",\"y\": \"1.550232\",\"z\": \"0.0\"},\"index\": 160},{\"location\":{\"x\": \"0.194776\",\"y\": \"1.520416\",\"z\": \"0.0\"},\"index\": 161},{\"location\":{\"x\": \"0.246774\",\"y\": \"1.535873\",\"z\": \"0.0\"},\"index\": 162},{\"location\":{\"x\": \"0.293115\",\"y\": \"1.545883\",\"z\":\n" +
                " \"0.0\"},\"index\": 163},{\"location\":{\"x\": \"0.333815\",\"y\": \"1.550537\",\"z\": \"0.0\"},\"index\": 164},{\"location\":{\"x\": \"0.368876\",\"y\": \"1.54985\",\"z\": \"0.0\"},\"index\": 165},{\"location\":{\"x\": \"0.401687\",\"y\": \"1.542145\",\"z\": \"0.0\"},\"index\": 166},{\"location\":{\"x\": \"0.424045\",\"y\": \"1.529404\",\"z\": \"0.0\"},\"index\": 167}]";
        System.out.println(JSON.parseArray(a, ActorSkillMontageRootMotionBo.class));
    }
}
@Data
public class ActorSkillMontageRootMotionBo {

    private int index;

    private Location location;
}

/**
 * 坐标
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Location implements Location3D {

    private double x;

    private double y;

    private double z;

}

### 期待的正确结果
*反序列化应该是正常的，当只有10多个元素时，序列化正常，我尝试只序列化报错内容指定的那一段数据是正常的，删除报错得那段数据测试后依旧报错，目前得出得结果发现只要数据过多时必报错。如日志所示*

### 相关日志输出
*Exception in thread "main" com.alibaba.fastjson2.JSONException: illegal fieldName input 122, offset 4773, character z, line 9, column 8, fastjson-version 2.0.52
[{"location":{"x": "-0.768332","y": "0.05704","z": "0.0"},"index": 2},{"location":{"x": "-0.811024","y": "0.008477","z": "0.0"},"index": 4},{"location":{"x": "-0.830571","y": "-0.013758","z": "0.0"},"index": 6},{"location":{"x": "-0.824935","y": "-0.007346","z": "0.0"},"index": 8},{"location":{"x": "-0.795674","y": "0.025938","z": "0.0"},"index": 10},{"location":{"x": "-0.738112","y": "0.091415","z": "0.0"},"index": 12},{"location":{"x": "-0.659925","y": "0.180356","z": "0.0"},"index": 14},{"location":{"x": "-0.554274","y": "0.300534","z": "0.0"},"inde
x": 16},{"location":{"x": "-0.369033","y": "0.780241","z": "0.0"},"index": 19},{"location":{"x": "0.144912","y": "0.797848","z": "0.0"},"index": 21},{"location":{"x": "0.233746","y": "1.012275","z": "0.0"},"index": 23},{"location":{"x": "0.086928","y": "0.580593","z": "0.0"},"index": 24},{"location":{"x": "0.035156","y": "0.6286","z": "0.0"},"index": 25},{"location":{"x": "-0.054684","y": "0.681895","z": "0.0"},"index": 26},{"location":{"x": "-0.160876","y": "0.742971","z": "0.0"},"index": 27},{"location":{"x": "-0.281857","y": "0.860878","z": "0.0"},"index": 28},{"location":{"x": "-0.388065",
"y": "0.991797","z": "0.0"},"index": 29},{"location":{"x": "-0.469992","y": "1.100613","z": "0.0"},"index": 30},{"location":{"x": "-0.532405","y": "1.19655","z": "0.0"},"index": 31},{"location":{"x": "-0.5597","y": "1.255629","z": "0.0"},"index": 32},{"location":{"x": "-0.562715","y": "1.292603","z": "0.0"},"index": 33},{"location":{"x": "-0.576496","y": "1.297537","z": "0.0"},"index": 34},{"location":{"x": "-0.634179","y": "1.288641","z": "0.0"},"index": 35},{"location":{"x": "-0.683457","y": "1.324805","z": "0.0"},"index": 36},{"location":{"x": "-0.694109","y": "1.407581","z": "0.0"},"index"
: 37},{"location":{"x": "-0.675899","y": "1.535812","z": "0.0"},"index": 38},{"location":{"x": "-0.628826","y": "1.709494","z": "0.0"},"index": 39},{"location":{"x": "-0.552893","y": "1.928629","z": "0.0"},"index": 40},{"location":{"x": "-0.52288","y": "2.274498","z": "0.0"},"index": 41},{"location":{"x": "-0.53556","y": "2.56024","z": "0.0"},"index": 42},{"location":{"x": "-0.503766","y": "2.745405","z": "0.0"},"index": 43},{"location":{"x": "-0.427497","y": "2.829996","z": "0.0"},"index": 44},{"location":{"x": "-0.306759","y": "2.814007","z": "0.0"},"index": 45},{"location":{"x": "-0.111591"
,"y": "2.66642","z": "0.0"},"index": 46},{"location":{"x": "0.142525","y": "2.450066","z": "0.0"},"index": 47},{"location":{"x": "0.5204","y": "2.272087","z": "0.0"},"index": 48},{"location":{"x": "0.829484","y": "2.162884","z": "0.0"},"index": 49},{"location":{"x": "0.967172","y": "2.094109","z": "0.0"},"index": 50},{"location":{"x": "0.904161","y": "2.067463","z": "0.0"},"index": 51},{"location":{"x": "0.656207","y": "2.089619","z": "0.0"},"index": 52},{"location":{"x": "0.236857","y": "2.152184","z": "0.0"},"index": 53},{"location":{"x": "-0.297248","y": "2.217514","z": "0.0"},"index": 54},
{"location":{"x": "-0.766695","y": "2.236366","z": "0.0"},"index": 55},{"location":{"x": "-1.140412","y": "2.255207","z": "0.0"},"index": 56},{"location":{"x": "-1.328735","y": "2.28587","z": "0.0"},"index": 57},{"location":{"x": "-1.393793","y": "2.329117","z": "0.0"},"index": 58},{"location":{"x": "-1.335579","y": "2.384964","z": "0.0"},"index": 59},{"location":{"x": "-1.154099","y": "2.453384","z": "0.0"},"index": 60},{"location":{"x": "-1.071793","y": "2.522034","z": "0.0"},"index": 61},{"location":{"x": "-0.956085","y": "2.725189","z": "0.0"},"index": 62},{"location":{"x": "-0.494337","y"
: "3.161255","z": "0.0"},"index": 63},{"location":{"x": "0.281134","y": "3.855354","z": "0.0"},"index": 64},{"location":{"x": "1.00738","y": "4.531952","z": "0.0"},"index": 65},{"location":{"x": "1.319183","y": "4.759972","z": "0.0"},"index": 66},{"location":{"x": "1.214396","y": "4.55452","z": "0.0"},"index": 67},{"location":{"x": "1.211981","y": "4.475883","z": "0.0"},"index": 68},{"location":{"x": "1.169556","y": "4.318573","z": "0.0"},"index": 69},{"location":{"x": "0.866768","y": "3.817009","z": "0.0"},"index": 70},{"location":{"x": "0.339333","y": "3.01899","z": "0.0"},"index": 71},{"loc
ation":{"x": "0.038861","y": "2.521973","z": "0.0"},"index": 72},{"location":{"x": "-0.056871","y": "2.259514","z": "0.0"},"index": 73},{"location":{"x": "-0.050248","y": "2.134033","z": "0.0"},"index": 74},{"location":{"x": "-0.100498","y": "1.950005","z": "0.0"},"index": 75},{"location":{"x": "-0.115635","y": "1.70536","z": "0.0"},"index": 76},{"location":{"x": "-0.063417","y": "1.480621","z": "0.0"},"index": 77},{"location":{"x": "-0.011171","y": "1.235985","z": "0.0"},"index": 78},{"location":{"x": "0.010653","y": "1.038094","z": "0.0"},"index": 79},{"location":{"x": "0.009596","y": "0.920
036","z": "0.0"},"index": 80},{"location":{"x": "0.005243","y": "0.922554","z": "0.0"},"index": 81},{"location":{"x": "0.01108","y": "0.954651","z": "0.0"},"index": 82},{"location":{"x": "0.012066","y": "0.935028","z": "0.0"},"index": 83},{"location":{"x": "0.008198","y": "0.863815","z": "0.0"},"index": 84},{"location":{"x": "-0.000525","y": "0.740875","z": "0.0"},"index": 85},{"location":{"x": "-0.016732","y": "0.533966","z": "0.0"},"index": 86},{"location":{"x": "-0.078013","y": "0.528214","z": "0.0"},"index": 88},{"location":{"x": "-0.545872","y": "-0.089172","z": "0.0"},"index": 97},{"loca
tion":{"x": "-0.251307","y": "-0.541229","z": "0.0"},"index": 106},{"location":{"x": "0.090087","y": "-0.563965","z": "0.0"},"index": 111},{"location":{"x": "0.07787","y": "-0.523376","z": "0.0"},"index": 115},{"location":{"x": "0.060936","y": "-0.640396","z": "0.0"},"index": 118},{"location":{"x": "0.219096","y": "0.560257","z": "0.0"},"index": 127},{"location":{"x": "0.091289","y": "0.619583","z": "0.0"},"index": 130},{"location":{"x": "0.092523","y": "0.774017","z": "0.0"},"index": 133},{"location":{"x": "0.058727","y": "0.665146","z": "0.0"},"index": 135},{"location":{"x": "0.053468","y": 
"0.843719","z": "0.0"},"index": 137},{"location":{"x": "0.046363","y": "1.051315","z": "0.0"},"index": 139},{"location":{"x": "0.019871","y": "0.615494","z": "0.0"},"index": 140},{"location":{"x": "0.016915","y": "0.692123","z": "0.0"},"index": 141},{"location":{"x": "0.014041","y": "0.764374","z": "0.0"},"index": 142},{"location":{"x": "0.010906","y": "0.841629","z": "0.0"},"index": 143},{"location":{"x": "0.001625","y": "0.940063","z": "0.0"},"index": 144},{"location":{"x": "-0.017946","y": "1.069077","z": "0.0"},"index": 145},{"location":{"x": "-0.039027","y": "1.210983","z": "0.0"},"index"
: 146},{"location":{"x": "-0.053061","y": "1.320877","z": "0.0"},"index": 147},{"location":{"x": "-0.063165","y": "1.417953","z": "0.0"},"index": 148},{"location":{"x": "-0.069345","y": "1.50235","z": "0.0"},"index": 149},{"location":{"x": "-0.071602","y": "1.573959","z": "0.0"},"index": 150},{"location":{"x": "-0.069133","y": "1.639404","z": "0.0"},"index": 151},{"location":{"x": "-0.062554","y": "1.682266","z": "0.0"},"index": 152},{"location":{"x": "-0.052053","y": "1.712463","z": "0.0"},"index": 153},{"location":{"x": "-0.037623","y": "1.729767","z": "0.0"},"index": 154},{"location":{"x": 
"-0.019269","y": "1.734421","z": "0.0"},"index": 155},{"location":{"x": "0.006757","y": "1.723206","z": "0.0"},"index": 156},{"location":{"x": "0.033942","y": "1.699142","z": "0.0"},"index": 157},{"location":{"x": "0.065054","y": "1.662323","z": "0.0"},"index": 158},{"location":{"x": "0.100094","y": "1.612671","z": "0.0"},"index": 159},{"location":{"x": "0.139055","y": "1.550232","z": "0.0"},"index": 160},{"location":{"x": "0.194776","y": "1.520416","z": "0.0"},"index": 161},{"location":{"x": "0.246774","y": "1.535873","z": "0.0"},"index": 162},{"location":{"x": "0.293115","y": "1.545883","z":
 "0.0"},"index": 163},{"location":{"x": "0.333815","y": "1.550537","z": "0.0"},"index": 164},{"location":{"x": "0.368876","y": "1.54985","z": "0.0"},"index": 165},{"location":{"x": "0.401687","y": "1.542145","z": "0.0"},"index": 166},{"location":{"x": "0.424045","y": "1.529404","z": "0.0"},"index": 167}]
	at com.alibaba.fastjson2.JSONReaderASCII.readFieldNameHashCode(JSONReaderASCII.java:125)
	at com.alibaba.fastjson2.reader.ORG_2_3_Location.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_1_2_ActorSkillMontageRootMotionBo.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2396)
	at com.alibaba.fastjson2.JSON.parseArray(JSON.java:2767)
	at Test.main(Test.java:38)*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by Xiao-A-Zhai** [comment]
补充一下，接口Locaion3D的代码片段
public interface Location3D {


    double getX();

    double getY();

    double getZ();
}

**Comment by Xiao-A-Zhai** [comment]
我发现是数据内容里面有换行符\r\n导致了这个问题，去掉后没有了
