### ISSUE TITLE
[BUG]  fieldName not support input type STR_UTF16 123, offset 1

### ISSUE THREAD

**Issue by cutv** [alibaba/fastjson2#2993]
### 问题描述
*简要描述您碰到的问题。*

JSONString: {"terminal_version":"MT5","server":"Exness-MT5Trial14","login":189193036,"client_id":"$1$E6e.eu23$ZKPS96lkiCcfSo5iILvgl.","type":"initialize","data":"{\"server\":\"Exness-MT5Trial14\",\"login\":189193036}"}

CODE: JSON.parseObject(raw, DtbMessage.class);
EXCEPTION:
com.alibaba.fastjson2.JSONException: not support input {"server":"Exness-MT5Trial14","login":189193036}, offset 206, character }, line 1, column 206, fastjson-version 2.0.53 {"terminal_version":"MT5","server":"Exness-MT5Trial14","login":189193036,"client_id":"$1$E6e.eu23$ZKPS96lkiCcfSo5iILvgl.","type":"initialize","data":"{\"server\":\"Exness-MT5Trial14\",\"login\":189193036}"}
	at com.alibaba.fastjson2.JSONReader.readBinary(JSONReader.java:690)
	at com.alibaba.fastjson2.reader.ObjectReaderImplInt8ValueArray.readObject(ObjectReaderImplInt8ValueArray.java:82)
	at com.alibaba.fastjson2.reader.ORG_2_6_DtbMessage.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1534)

JSONString: {"terminal_version":"MT5","server":"Exness-MT5Trial14","login":189193036,"client_id":"$1$E6e.eu23$ZKPS96lkiCcfSo5iILvgl.","type":"initialize","data":"{\"server\":\"Exness-MT5Trial14\",\"login\":189193036}"}
CODE: JSONB.parseObject(raw, DtbMessage.class);  raw is byte[]
EXCEPTION:
com.alibaba.fastjson2.JSONException: fieldName not support input type STR_UTF16 123, offset 1
	at com.alibaba.fastjson2.JSONReaderJSONB.readFieldNameHashCodeError(JSONReaderJSONB.java:1635)
	at com.alibaba.fastjson2.JSONReaderJSONB.readFieldNameHashCode(JSONReaderJSONB.java:1537)
	at com.alibaba.fastjson2.reader.ORG_1_6_DtbMessage.readJSONBObject(Unknown Source)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:491)

![image](https://github.com/user-attachments/assets/d70bfca9-8179-491b-86c4-61e0ea4a34a4)

 Fastjson2 2.0.53

**Comment by wenshao** [comment]
能帮忙构造重现问题的testcase么？
