### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by scf18857887860** [alibaba/fastjson2#2995]
### 问题描述
*简要描述您碰到的问题。*

<img width="931" alt="image" src="https://github.com/user-attachments/assets/c8015165-6b9e-495b-994a-747aa9aa4a83">

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：windos7 or windo10]
 - JDK信息： [e.g.：jdk 1.8 32位]
 - 版本信息：[e.g.：Fastjson2 2.0.51]
 

### 重现步骤
*如何操作可以重现该问题：*
暂时我也不清楚，客户侧偶发产生的问题，没有相关日志收集到

```java
      Map<String, Object> map = new HashMap<>();
 String jsonString = JSON.toJSONString(map);
        return JSON.parseObject(jsonString, tClass);
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
JSON.parseObject(jsonString, tClass); 执行正常

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
com.alibaba.fastjson2.JSONException: create objectReader error, objectType com.mes.employee.bean.req.login.LogoutRequest
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.jitObjectReader(ObjectReaderCreatorASM.java:619)
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:347)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReaderInternal(ObjectReaderProvider.java:831)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:753)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:858)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
由此问题是否会导致metaspace的溢出，因为我的程序后续就出现了java.lang.OutOfMemoryError: Metaspace

**Comment by scf18857887860** [comment]
查看源码发现，每次有新的类从jsonstring转换为指定object时，都会通过asm加载出一个新的类，然后这个类会缓存起来，也就是引用一直存在，gc也无法回收，当这样的类足够多，而metaspace大小有限时，最后就会导致oom，而1.2.x版本的fastjson里面转换对象时用的并不是asm这种方式，所以不存在这个问题
