### ISSUE TITLE
[BUG] 针对Record类，boolean类型，JSON.toJSONString()报错

### ISSUE THREAD

**Issue by ityangkai-coder** [alibaba/fastjson2#3090]
### 问题描述
针对Record类，boolean类型，JSON.toJSONString()报错

### 环境信息
*请填写以下信息：*

 - OS信息： Macos
 - JDK信息： java21
 - 版本信息：2.0.53
 

### 重现步骤
```java
 public record GoodUpdatedCheck(boolean isUpgrade, boolean isDowngrade, boolean isChangeSubscriptionGood) {
      // boolean会报错
        public static void main(String[] args) {
            GoodUpdatedCheck goodUpdatedCheck = new GoodUpdatedCheck(true, true, true);
            System.out.println(JSON.toJSONString(goodUpdatedCheck));
        }
    }
   
 public record GoodUpdatedCheck2(Boolean isUpgrade, Boolean isDowngrade, Boolean isChangeSubscriptionGood) {
    // Boolean不会报错
        public static void main(String[] args) {
            GoodUpdatedCheck2 goodUpdatedCheck = new GoodUpdatedCheck2(true, true, true);
            System.out.println(JSON.toJSONString(goodUpdatedCheck));
        }
    }
    
```

### 期待的正确结果
*正确JSON格式化*

### 相关日志输出
*com.truckerpath.vip.utils.SubscriptionGoodsUtil$GoodUpdatedCheck
Exception in thread "main" java.lang.UnsupportedOperationException: can't get field offset on a record class: private final boolean *.SubscriptionGoodsUtil$GoodUpdatedCheck.isChangeSubscriptionGood
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
	at com.alibaba.fastjson2.writer.FieldWriter.<init>(FieldWriter.java:118)
	at com.alibaba.fastjson2.writer.FieldWriterBoolean.<init>(FieldWriterBoolean.java:32)
	at com.alibaba.fastjson2.writer.FieldWriterBoolMethod.<init>(FieldWriterBoolMethod.java:21)
	at com.alibaba.fastjson2.writer.ObjectWriterCreator.createFieldWriter(ObjectWriterCreator.java:933)
	at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.lambda$createObjectWriter$1(ObjectWriterCreatorASM.java:330)
	at com.alibaba.fastjson2.util.BeanUtils.getters(BeanUtils.java:1040)
	at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.createObjectWriter(ObjectWriterCreatorASM.java:237)
	at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriterInternal(ObjectWriterProvider.java:462)
	at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:340)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:3021)
	at com.truckerpath.vip.utils.SubscriptionGoodsUtil$GoodUpdatedCheck.main(SubscriptionGoodsUtil.java:101)
*

#### 附加信息
报错位置：当boolean类型时，field != null, 所以会进行UNSAFE.objectFieldOffset(field); 由于class为record类，所以导致报错
![QQ_1728531130761](https://github.com/user-attachments/assets/a2957d45-cc5f-4a26-9dd7-2c72659840a8)
![QQ_1728531298202](https://github.com/user-attachments/assets/68d73292-c074-4ebc-8a4b-6033eecaded8)

而Boolean类型，field == null，不会使用UNSAFE.objectFieldOffset(field);所以可以正常进行格式化，具体feild入值，针对boolean类型有特殊的判断，不知道为了解决什么问题
![QQ_1728531438143](https://github.com/user-attachments/assets/8426ae80-4e4c-41e2-8aae-925482b96184)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.54-SNAPSHOT/
问题已修复，请帮忙用2.0.54-SNAPSHOT快照版本验证，2.0.54正式版本预计在月底发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.54
问题已修复，请用新版本
