### ISSUE TITLE
[BUG]java.lang.IllegalStateException: Dont call getValueBoolean() on a non BOOLEAN ElementValue 	at org.apache.bcel.classfile.SimpleElementValue.getValueBoolean(SimpleElementValue.java:65) ~[bcel-6.7.0.jar:6.7.0] 	at com.alibaba.fastjson2.writer.OWG_11_11_SimpleElementValue.write(Unknown Source) ~[?:?] 	at com.alibaba.fastjson2.writer.ObjectWriterArray.write(ObjectWriterArray.java:103) ~[fastjson2-2.0.53.jar:?] 	at com.alibaba.fastjson2.writer.OWG_10_3_ArrayElementValue.write(Unknown Source) ~[?:?] 	at com.alibaba.fastjson2.writer.OWG_9_3_ElementValuePair.write(Unknown Source) ~[?:?] 	at com.alibaba.fastjson2.writer.ObjectWriterArray.write(ObjectWriterArray.java:103) ~[fastjson2-2.0.53.jar:?] 	at com.alibaba.fastjson2.writer.OWG_1_7_AnnotationEntry.write(Unknown Source) ~[?:?] 	at com.alibaba.fastjson2.writer.ObjectWriterArray.write(ObjectWriterArray.java:103) ~[fastjson2-2.0.53.jar:?] 	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:3026) ~[fastjson2-2.0.53.jar:?]

### ISSUE THREAD

**Issue by meishuangjie** [alibaba/fastjson2#3138]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by meishuangjie** [comment]
<dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.53</version>
        </dependency>

**Comment by CodePlayer** [comment]
你复现问题的代码都不提供，也没有提供任何有效的任何描述，你让大家怎么排查问题 ？
BTW：错误堆栈信息不应该作为反馈的标题。

**Comment by rowstop** [comment]
尝试开启`JSONWriter.Feature.FieldBased`
