### ISSUE TITLE
[QUESTION] fastjson2和fastjson抽象类反序列化默认行为不一致

### ISSUE THREAD

**Issue by rock-byte** [alibaba/fastjson2#3143]
### 问题描述

fastjson2和fastjson抽象类反序列化默认行为不一致，fastjson2在反序列化抽象类时会抛出异常，fastjson会跳过该类。并没有找到配置项控制该行为。

### 重现步骤

```java
public static abstract class Foo {

        private String value;
    }

    public static void main(String[] args) {
        String jsonString = "{\"value\":\"bar\"}";
        com.alibaba.fastjson2.JSON.config(JSONReader.Feature.FieldBased);
        Foo fooBefore = com.alibaba.fastjson.JSON.parseObject(jsonString, Foo.class);
        System.out.println(fooBefore);
        Foo foo = com.alibaba.fastjson2.JSON.parseObject(jsonString, Foo.class);
        System.out.println(foo);
    }
```

### 结果

```
null
Exception in thread "main" com.alibaba.fastjson2.JSONException: create instance error, class Test$Foo
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:411)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:386)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:864)
	at Test.main(Test.java:19)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:405)
	... 3 more
```

### 期待结果

fastjson2和fastjson对于抽象类反序列化默认行为一致，或至少提供配置项控制。

**Comment by amabilee** [comment]
Have you tried instead of directly deserializing the abstract class, deserialize a concrete subclass that extends the abstract class?
This way, you can avoid the exception thrown by `fastjson2`.

**Comment by rock-byte** [comment]
This is for illustration. Actually I try to deserialize class A, which contains a abstarct class B as field. In fastjson, I only need to set the field manually. But in fastjson2, it throws exception, thus stops the whole deserialization, that is inconvenient.

**Comment by amabilee** [comment]
One approach is to use a custom deserializer, this can help manage how the abstract class is instantiated.
```
    public static void main(String[] args) {
        String jsonString = "{\"foo\":{\"value\":\"bar\"}}";

        ObjectReaderProvider provider = new ObjectReaderProvider();
        provider.register(Foo.class, new ObjectReader<Foo>() {

            public Foo createInstance(JSONReader jsonReader) {
                return new ConcreteFoo(); 
            }

            public Foo readObject(JSONReader jsonReader, long features) {
                return createInstance(jsonReader); 
            }
        });

        JSON.config(provider); 

        A a = JSON.parseObject(jsonString, A.class, JSONReader.Feature.FieldBased);
        System.out.println(a.getFoo().getValue()); 
    }
```
