### ISSUE TITLE
android9下运行  JSONObject info =new JSONObject(); 出错：No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView

### ISSUE THREAD

**Issue by sgnah** [alibaba/fastjson2#315]
Process: com.jbzh.jbzhpadcore, PID: 4348
    java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-oj.jar)
        at com.alibaba.fastjson2.util.TypeUtils.<clinit>(TypeUtils.java:396)
        at com.alibaba.fastjson2.util.TypeUtils.getTypeName(TypeUtils.java:413)
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.<init>(ObjectReaderProvider.java:320)
        at com.alibaba.fastjson2.JSONFactory.<clinit>(JSONFactory.java:228)
        at com.alibaba.fastjson2.JSONFactory.getDefaultObjectReaderProvider(JSONFactory.java:251)
        at com.alibaba.fastjson2.JSONObject.<clinit>(JSONObject.java:31)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
