### ISSUE TITLE
[BUG]在使用 JSONObject.toJavaObject 反序列化 JSONObject 到带默认值的 Kotlin 类时遇到问题。

### ISSUE THREAD

**Issue by IceCream-QAQ** [alibaba/fastjson2#3152]
### 问题描述
在使用 JSONObject.toJavaObject 反序列化 JSONObject 到带默认值的 Kotlin 类时遇到问题。
但直接使用 JSON.parseObject 没有问题。

### 环境信息

 - OS信息：  [e.g.：macOS 15.1]
 - JDK信息： [e.g.：Openjdk 21]
 - 版本信息：[e.g.：Fastjson2 2.0.53]
 

### 重现步骤
要求构造函数至少有两个参数。
构造函数中，至少含有一个带有默认值的参数。
另一个参数应该是反序列化到另一个类。

```Kotlin
data class Foo(val int: Int = 0, val bar: Bar )
data class Bar(val text: String = "")

fun main() {
    val json = """
        {
            "int": 0,
            "bar": {
                "text" : "hello"
            }
        }
    """.trimIndent()


    val jo = JSON.parseObject(json)
    val foo = jo.toJavaObject(Foo::class.java)
    println(foo)
}
```

### 期待的正确结果
可以正确反序列化到目标对象。

### 相关日志输出
```
Exception in thread "main" com.alibaba.fastjson2.JSONException: invoke constructor error, public Foo(int,Bar,int,kotlin.jvm.internal.DefaultConstructorMarker)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:222)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:15)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstructor.createInstanceNoneDefaultConstructor(ObjectReaderNoneDefaultConstructor.java:73)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstructor.createInstance(ObjectReaderNoneDefaultConstructor.java:495)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1278)
	at com.alibaba.fastjson2.JSONObject.toJavaObject(JSONObject.java:1297)
	at MainKt.main(main.kt:19)
	at MainKt.main(main.kt)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:65)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:219)
	... 7 more
Caused by: java.lang.ClassCastException: Cannot cast com.alibaba.fastjson2.JSONObject to Bar
	at java.base/java.lang.Class.cast(Class.java:4067)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 10 more
```

**Comment by IceCream-QAQ** [comment]
报错与是否是 data class 无关。

**Comment by EmptyDreams** [comment]
我也遇到了类似的问题，但是我认为这不仅存在默认值的问题，我查看了 fastjson2 的代码，注意到这个位置：

`com/alibaba/fastjson2/reader/ObjectReaderNoneDefaultConstructor.java`:

```java
for (Map.Entry entry : (Iterable<Map.Entry>) map.entrySet()) {
    String fieldName = entry.getKey().toString();
    Object fieldValue = entry.getValue();
    FieldReader fieldReader = getFieldReader(fieldName);
    if (fieldReader != null) {
        if (fieldValue != null) {
            Class<?> valueClass = fieldValue.getClass();
            Class fieldClass = fieldReader.fieldClass;
            if (valueClass != fieldClass) {
                Function typeConvert = provider.getTypeConvert(valueClass, fieldClass);
                if (typeConvert != null) {
                    fieldValue = typeConvert.apply(fieldValue);
                }
            }
        }
        if (valueMap == null) {
            valueMap = new LinkedHashMap<>();
        }
        long hash;
        if (fieldReader instanceof FieldReaderObjectParam) {
            hash = ((FieldReaderObjectParam<?>) fieldReader).paramNameHash;
        } else {
            hash = fieldReader.fieldNameHash;
        }
        valueMap.put(hash, fieldValue);
    }
}
```

这段代码在尝试将 `map` 转换为指定的对象，对于 `map` 中的每一个 `value`，都会使用 `getTypeConvert` 匹配转换器。

这看起来没什么问题，但是当 `map` 的 `value` 是 `JSONObject` 时，代码将无法匹配到对应的转换器，所以这个 `value` 会保留原始的值。按理说这个地方应该检查一下 `value` 是否为类似于 `JSONObject` 的 `map`，如果是的话应该按照 `toJavaObject` 的逻辑处理，而不是简单的进行类型匹配。

随后这段代码将会跳转到 `com/alibaba/fastjson2/reader/ConstructorFunction.java` 的 `apply` 函数当中：

```java
Object[] args = new Object[constructor.getParameterCount()];
...
try {
    return (T) constructor.newInstance(args);
} catch (InstantiationException | IllegalAccessException | IllegalArgumentException |
         InvocationTargetException e) {
    throw new JSONException("invoke constructor error, " + constructor, e);
}
```

由于在 `ObjectReaderNoneDefaultConstructor` 中是将 `JSONObject` 保留了原始的值，所以构造函数的默认值不会生效，会被直接尝试转换为对应的类型，这导致在 `JSONObject` 中嵌套的有 `JSONObject` 时调用 `toJavaObject` 百分之百会报错，无一例外。

**Comment by EmptyDreams** [comment]
我刚刚没有看到上面的 fix，看了一下已经是修复了

**Comment by IceCream-QAQ** [comment]
> 我也遇到了类似的问题，但是我认为这不仅存在默认值的问题，我查看了 fastjson2 的代码，注意到这个位置：
> 
> `com/alibaba/fastjson2/reader/ObjectReaderNoneDefaultConstructor.java`:
> 
> ```java
> for (Map.Entry entry : (Iterable<Map.Entry>) map.entrySet()) {
>     String fieldName = entry.getKey().toString();
>     Object fieldValue = entry.getValue();
>     FieldReader fieldReader = getFieldReader(fieldName);
>     if (fieldReader != null) {
>         if (fieldValue != null) {
>             Class<?> valueClass = fieldValue.getClass();
>             Class fieldClass = fieldReader.fieldClass;
>             if (valueClass != fieldClass) {
>                 Function typeConvert = provider.getTypeConvert(valueClass, fieldClass);
>                 if (typeConvert != null) {
>                     fieldValue = typeConvert.apply(fieldValue);
>                 }
>             }
>         }
>         if (valueMap == null) {
>             valueMap = new LinkedHashMap<>();
>         }
>         long hash;
>         if (fieldReader instanceof FieldReaderObjectParam) {
>             hash = ((FieldReaderObjectParam<?>) fieldReader).paramNameHash;
>         } else {
>             hash = fieldReader.fieldNameHash;
>         }
>         valueMap.put(hash, fieldValue);
>     }
> }
> ```
> 
> 这段代码在尝试将 `map` 转换为指定的对象，对于 `map` 中的每一个 `value`，都会使用 `getTypeConvert` 匹配转换器。
> 
> 这看起来没什么问题，但是当 `map` 的 `value` 是 `JSONObject` 时，代码将无法匹配到对应的转换器，所以这个 `value` 会保留原始的值。按理说这个地方应该检查一下 `value` 是否为类似于 `JSONObject` 的 `map`，如果是的话应该按照 `toJavaObject` 的逻辑处理，而不是简单的进行类型匹配。
> 
> 随后这段代码将会跳转到 `com/alibaba/fastjson2/reader/ConstructorFunction.java` 的 `apply` 函数当中：
> 
> ```java
> Object[] args = new Object[constructor.getParameterCount()];
> ...
> try {
>     return (T) constructor.newInstance(args);
> } catch (InstantiationException | IllegalAccessException | IllegalArgumentException |
>          InvocationTargetException e) {
>     throw new JSONException("invoke constructor error, " + constructor, e);
> }
> ```
> 
> 由于在 `ObjectReaderNoneDefaultConstructor` 中是将 `JSONObject` 保留了原始的值，所以构造函数的默认值不会生效，会被直接尝试转换为对应的类型，这导致在 `JSONObject` 中嵌套的有 `JSONObject` 时调用 `toJavaObject` 百分之百会报错，无一例外。

经过我的测试场景，在嵌套 JSONObject 时，如果 Kotlin 构造函数没有默认值，FastJSON 2 能正确构造对象。但具体原因我没有准确定位，我只简单处理了问题。

**Comment by EmptyDreams** [comment]
> 经过我的测试场景，在嵌套 JSONObject 时，如果 Kotlin 构造函数没有默认值，FastJSON 2 能正确构造对象。但具体原因我没有准确定位，我只简单处理了问题。

我知道了，`ConstructorFunction.java` 的构造函数中通过 `mark` 字段标记了是否是带默认值的构造函数，在 `mark` 为 false 时检测了类型是否匹配并进行了转换：

```java
if (!paramClass.isInstance(arg)) {
    arg = TypeUtils.cast(arg, paramClass);
} else if (paramType instanceof ParameterizedType) {
    arg = TypeUtils.cast(arg, paramType);
}
```

但是 `mark` 为 true 的分支没有类似的逻辑。
