### ISSUE TITLE
[BUG] 在使用了JSONWriter.Feature.WriteClassName后，FastJson2无法正确处理Map<String, Integer>

### ISSUE THREAD

**Issue by fwhdzh** [alibaba/fastjson2#3153]
### 问题描述

我有一个类
```
    public static class TestState {

        Map<String, Integer> currentTerm;

        public TestState(Map<String, Integer> currentTerm) {
            this.currentTerm = currentTerm;
        }
    }
```
如果我在序列化时使用了`JSONWriter.Feature.WriteClassName`，那么在反序列化处理时，FastJson2在处理`currentTerm`时会报错`com.alibaba.fastjson2.JSONException: parseInt error, value : java.util.HashMap`

### 环境信息

 - OS信息： Ubuntu 22.04.3 LTS
 - JDK信息： Oracle JDK 1.8.0_421
 - 版本信息：Fastjson2 2.0.53
 

### 重现步骤

可使用下列完整单元测试代码来复现该缺陷

```
import java.util.Map;

import org.junit.jupiter.api.Test;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.filter.Filter;


public class TestFastJSON {

    public static class TestState {

        Map<String, Integer> currentTerm;

        public TestState(Map<String, Integer> currentTerm) {
            this.currentTerm = currentTerm;
        }
    }

    private static final Filter autoTypeFilter = JSONReader.autoTypeFilter(
            "com.",
            "org.",
            "java.",
            "edu.");

    public JSONWriter.Feature[] features = new JSONWriter.Feature[] {
            JSONWriter.Feature.WriteClassName,
            JSONWriter.Feature.FieldBased,
    };

    public JSONReader.Feature[] readerFeatures = new JSONReader.Feature[] {
            JSONReader.Feature.FieldBased,
    };

    @Test
    void testFastJSON() {
        Map<String, Integer> currentTerm = new java.util.HashMap<>();
        currentTerm.put("N1", 2);
        currentTerm.put("N2", 2);
        currentTerm.put("N3", 1);
        TestState ts = new TestState(currentTerm);
        String stateJSONStr = JSONObject.toJSONString(ts, features);
        TestState deseriObj = JSON.parseObject(stateJSONStr, TestState.class,
                autoTypeFilter,
                readerFeatures);
    }
}
```

将上述代码复制到任意支持Junit 5的测试框架中，运行`testFastJSON`单元测试，可观察到完整报错信息如下：

```
com.alibaba.fastjson2.JSONException: parseInt error, value : java.util.HashMap
 at com.alibaba.fastjson2.JSONReader.toInt32(JSONReader.java:3050)
 at com.alibaba.fastjson2.JSONReader.getInt32Value(JSONReader.java:843)
 at com.alibaba.fastjson2.JSONReaderUTF16.readInt32(JSONReaderUTF16.java:2506)
 at com.alibaba.fastjson2.reader.ObjectReaderImplInteger.readObject(ObjectReaderImplInteger.java:22)
 at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:408)
 at com.alibaba.fastjson2.reader.ORG_1_1_TestState.readObject(Unknown Source)
 at com.alibaba.fastjson2.reader.ObjectReaderAdapter.autoType(ObjectReaderAdapter.java:247)
 at com.alibaba.fastjson2.reader.ORG_1_1_TestState.readObject(Unknown Source)
 at com.alibaba.fastjson2.JSON.parseObject(JSON.java:906)
 at ...TestFastJSON.testFastJSON(TestFastJSON.java:48)
 at java.util.ArrayList.forEach(ArrayList.java:1259)
 at java.util.ArrayList.forEach(ArrayList.java:1259)
```

### 期待的正确结果

可以正确的将TestState反序列化

### 相关日志输出

如上

#### 附加信息

无

**Comment by fwhdzh** [comment]
目前最新版本的FaustJson2中，显示`JSONReader.Feature.SupportAutoType`已被弃用，具体信息为“It is not safe to explicitly turn on autoType, it is recommended to use AutoTypeBeforeHandler”。

我基于 #2178 编写了上面的测试用例，然而看起来并不能正常工作。

请问上面的测试用例中的`JSONReader.autoTypeFilter`使用是否有问题？如果确实存在问题，应该如何正确使用`JSONReader.autoTypeFilter`?

**Comment by CodePlayer** [comment]
你这个例子，我在本地测试过，是OK的，你所谓的不能正常工作的例子，有完整版的可以发出来吗？

另外，`JSONReader.Feature.SupportAutoType` 这个枚举之所以被标记为已弃用，是因为它存在安全隐患。
你可以想一想，如果外部随便传入一个 JSON字符串，里面也有 `@type`，而且它的值可能是一些导致安全隐患的类型名称，比如 `java.lang.System` 或 `java.lang.Runtime` 之类的，那么是不是可能因为设置了某些属性或方法，而产生安全隐患 ？

所以：
1. 要么，只有自己可信可控的 JSON 字符串来源，才能使用这个枚举。比如  是你自己将可信的类型对象序列化后存入 Redis ，又是你自己从 Redis 中反序列化回来。
2. 要么，就不要使用 `WriteClassName` 和 `SupportAutoType` 这一对组合枚举，自己每次在反序列化时手动指定类型，就像你写的 `JSON.parseObject(stateJSONStr, TestState.class)` 一样，这种情况是不需要设置 `WriteClassName` 来序列化的。

**Comment by fwhdzh** [comment]
完整的例子已经放到了https://github.com/fwhdzh/fastjsontest

所使用的环境为
OS信息： Ubuntu 22.04.3 LTS
JDK信息： Oracle JDK 1.8.0_421
Maven信息：Apache Maven 3.9.9

运行方式和报错信息可见于该项目的README文档。

**Comment by fwhdzh** [comment]
感谢您的回复！我在加上了`JSONReader.Feature.SupportAutoType`后，该测试用例可以正常通过。

不过当前的FastJson2版本中，直接将`SupportAutoType`标记为弃用感觉很容易让人产生误解。基于当前的该枚举注释所提供的信息以及其他issue(#217 )中的讨论，我将其误解为了目前"*在任何情况下都应该尽量避免使用该枚举，同时仅使用`AutoTypeBeforeHandler`即可以在不使用该枚举的情况下完成预期的功能*"。

是否可以考虑重构下这部分代码，比如在使用`AutoTypeBeforeHandler`时，自动在对应的局部反序列化过程中调用该枚举。或者将当前的该注解的`@Deprecated`注解去除并仅通过注释来进行警告？
