### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by donglianghan** [alibaba/fastjson2#3197]
### 问题描述
*简要描述您碰到的问题。*
用 scala 环境下，fastjson2 反序列编译异常

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]

scala : 2.12.15
sbt: 1.6.2
"com.alibaba" % "fastjson" % "2.0.53",

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
1.
case class EventDto（@BeanProperty var eventCode: String）

val eventDto: EventDto = JSON.parseObject(item, classOf[EventDto])

sbt assembly  或者 sbt clean compile

3.
[error] (Compile / compileIncremental) scala.reflect.internal.FatalError: 

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
[error]     last tree to typer: Ident(JSON)
[error]        tree position: line 68 of 
[error]               symbol: <none>
[error]    symbol definition: <none> (a NoSymbol)
[error]       symbol package: <none>
[error]        symbol owners: 
[error]            call site: method main in object in package bigdata

[error]    at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
[error]         at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
[error]         at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.errorBadIndex(ClassfileParser.scala:386)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getExternalName(ClassfileParser.scala:250)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.readParamNames$1(ClassfileParser.scala:841)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:847)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$7(ClassfileParser.scala:921)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:921)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:623)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseClass$4(ClassfileParser.scala:536)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:536)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$2(ClassfileParser.scala:161)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:147)
[error]         at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:130)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:343)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:250)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.load(SymbolLoaders.scala:269)
[error]         at scala.reflect.internal.Symbols$Symbol.$anonfun$typeParams$1(Symbols.scala:1772)
[error]         at scala.reflect.internal.Symbols$Symbol.completeTypeParams$1(Symbols.scala:1772)
[error]         at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1779)
[error]         at scala.reflect.internal.Types.isRawIfWithoutArgs(Types.scala:3930)
[error]         at scala.reflect.internal.Types.isRawIfWithoutArgs$(Types.scala:3930)
[error]         at scala.reflect.internal.SymbolTable.isRawIfWithoutArgs(SymbolTable.scala:28)
[error]         at scala.reflect.internal.tpe.TypeMaps$$anon$1.apply(TypeMaps.scala:356)
[error]         at scala.reflect.internal.tpe.TypeMaps$$anon$1.apply(TypeMaps.scala:353)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
[error]         at scala.reflect.internal.tpe.TypeMaps$$anon$1.apply(TypeMaps.scala:366)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:232)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:242)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:246)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:259)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$1(TypeMaps.scala:137)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
[error]         at scala.reflect.internal.tpe.TypeMaps$$anon$1.apply(TypeMaps.scala:366)
[error]         at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:143)
[error]         at scala.reflect.internal.tpe.TypeMaps$$anon$1.apply(TypeMaps.scala:366)
[error]         at scala.reflect.internal.tpe.TypeMaps$$anon$1.apply(TypeMaps.scala:353)
[error]         at scala.reflect.internal.Symbols$Symbol.modifyInfo(Symbols.scala:1572)
[error]         at scala.reflect.internal.Symbols$Symbol.$anonfun$cookJavaRawInfo$2(Symbols.scala:1729)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error]         at scala.collection.immutable.List.foreach(List.scala:431)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error]         at scala.reflect.internal.Symbols$Symbol.cookJavaRawInfo(Symbols.scala:1729)
[error]         at scala.tools.nsc.typechecker.Infer$Inferencer.checkAccessible(Infer.scala:280)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.makeAccessible(Typers.scala:593)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$59(Typers.scala:5137)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$silent$2(Typers.scala:726)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:726)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:5137)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5197)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5737)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$39(Typers.scala:4891)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:713)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4893)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4921)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5736)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:5997)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedValDef(Typers.scala:2058)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5700)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5845)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2497)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$103(Typers.scala:5711)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:500)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5746)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedFunction(Typers.scala:5856)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedFunction(Typers.scala:3043)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$102(Typers.scala:5677)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedFunction$1(Typers.scala:500)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5714)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5746)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3355)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:491)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3748)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$32(Typers.scala:3756)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3756)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3767)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4912)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4921)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5736)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:5997)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedValDef(Typers.scala:2058)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5700)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5845)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2497)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$103(Typers.scala:5711)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:500)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5746)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedFunction(Typers.scala:5856)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedFunction(Typers.scala:3043)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$102(Typers.scala:5677)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedFunction$1(Typers.scala:500)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5714)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5746)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3355)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:491)
[error]         at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgWithFormal$1(PatternTypers.scala:113)
[error]         at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.$anonfun$typedArgsForFormals$4(PatternTypers.scala:127)
[error]         at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals(PatternTypers.scala:127)
[error]         at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals$(PatternTypers.scala:108)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:202)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3697)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3730)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.tryNamesDefaults$1(Typers.scala:3666)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3680)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$26(Typers.scala:4826)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:713)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4826)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4910)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4921)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5736)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5856)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1114)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1733)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1919)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1870)
[error]         at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:877)
[error]         at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2082)
[error]         at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2080)
[error]         at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2075)
[error]         at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1542)
[error]         at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
[error]         at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1698)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5406)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5845)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2497)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$103(Typers.scala:5711)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:500)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5746)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5997)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5701)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5845)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2019)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1885)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5703)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5845)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3337)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5413)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5705)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5781)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:114)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:102)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1514)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1498)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
[error]         at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1602)
[error]         at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
[error]         at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error]         at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error]         at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error]         at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error]         at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error]         at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error]         at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error]         at sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error]         at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]         at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[error] (Compile / compileIncremental) scala.reflect.internal.FatalError: 

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by donglianghan** [comment]
"com.alibaba.fastjson2" % "fastjson2" % "2.0.53" 和 "com.alibaba" % "fastjson" % "2.0.53" 均有此问题
但是低版本编码未报错
"com.alibaba" % "fastjson" % "1.2.58",

**Comment by YangSiyong** [comment]
我这边碰到了同样的问题，有两个办法解决的：1.通过升级fastjson2到2.0.54修复该问题。2.提供一个java的util函数封装fastjson2的反序列化函数，再让scala代码调用java工具函数规避该问题

**Comment by YangSiyong** [comment]
> 我这边碰到了同样的问题，有两个办法解决的：1.通过升级fastjson2到2.0.54修复该问题。2.提供一个java的util函数封装fastjson2的反序列化函数，再让scala代码调用java工具函数规避该问题

并且我发现个奇怪的事情，我将2.0.53的源码下载下来之后，本地编译生成jar包，scala依赖这个jar包，编译问题就不存在了

**Comment by donglianghan** [comment]
> 我这边碰到了同样的问题，有两个办法解决的：1.通过升级fastjson2到2.0.54修复该问题。2.提供一个java的util函数封装fastjson2的反序列化函数，再让scala代码调用java工具函数规避该问题

嗯嗯，第二种方法我也试过，还是报同样的错误。高版本可能会解决问题，我使用 fastjson 的低版本，来规避这个任务。

**Comment by donglianghan** [comment]
> > 我这边碰到了同样的问题，有两个办法解决的：1.通过升级fastjson2到2.0.54修复该问题。2.提供一个java的util函数封装fastjson2的反序列化函数，再让scala代码调用java工具函数规避该问题
> 
> 并且我发现个奇怪的事情，我将2.0.53的源码下载下来之后，本地编译生成jar包，scala依赖这个jar包，编译问题就不存在了

可能和打包方式有关系？
