### ISSUE TITLE
[BUG]byte[]转成jsonString后，fastjson可以解析出来，fastjson2解析则报错。

### ISSUE THREAD

**Issue by dyhhh** [alibaba/fastjson2#3208]
### 问题描述
byte[]转成jsonString后，fastjson可以解析出来，fastjson2解析则报错。
请见下面的截图。

### 环境信息
 - 版本信息：[fastjson2是2.0.52，fastjson是1.2.79]

**Comment by dyhhh** [comment]
### 问题描述
byte[]转成jsonString后，fastjson可以解析出来，fastjson2解析则报错。
请见下面的截图。

### 环境信息
 - 版本信息：[fastjson2是2.0.52，fastjson是1.2.79]

**Comment by dyhhh** [comment]
![代码](https://github.com/user-attachments/assets/fd94c8ea-2a81-47e3-91d0-4b7118cf9b6a)
![报错](https://github.com/user-attachments/assets/b311e6f3-b13b-49a1-9cf2-52609fb22ef3)

**Comment by wenshao** [comment]
可以文本的方式提供testcase么？

**Comment by dyhhh** [comment]
import com.alibaba.fastjson.serializer.SerializerFeature;

import java.util.Arrays;

public class Main {
    public static void main(String[] args) {
        // 构造数据
        byte[] data = new byte[3];
        data[0] = 1;
        data[1] = 2;
        data[2] = 3;
        // 老版本会将数据转成jsonString并放到redis里面
        String jsonString = com.alibaba.fastjson.JSONObject.toJSONString(data, SerializerFeature.WriteClassName, SerializerFeature.NotWriteDefaultValue);

        // 老版本使用fastjson解析数据，可以拿到数据
        System.out.println("fastjson解析获得数据：" + Arrays.toString((byte[]) com.alibaba.fastjson.JSON.parse(jsonString)));

        // 新版本使用fastjson2解析数据，会报错
        System.out.println("fastjson2解析获得数据：" + Arrays.toString((byte[]) com.alibaba.fastjson2.JSON.parse(jsonString)));
    }
}

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.54
问题已修复，请用新版本

**Comment by citytianya** [comment]
作为对象的成员还是解析不出来。
```
        Data data = new Data();
        byte[] bytes = new byte[3];
        bytes[0] = 1;
        bytes[1] = 2;
        bytes[2] = 3;
        data.setByteArray(bytes);
        String jsonString = com.alibaba.fastjson.JSONObject.toJSONString(data);
        Logger.info("origin: {}", jsonString);
        Logger.info("fastjson1: {}", Arrays.toString(com.alibaba.fastjson.JSON.parseObject(jsonString, Data.class).getByteArray()));
        Logger.info("fastjson2: {}", Arrays.toString(JSON.parseObject(jsonString, Data.class).getByteArray()));
```
报错如下
```
Caused by: com.alibaba.fastjson2.JSONException: not support input AQID, offset 32, character }, line 1, column 32, fastjson-version 2.0.54 {"a":1,"b":2,"byteArray":"AQID"}
	at com.alibaba.fastjson2.JSONReader.readBinary(JSONReader.java:695) ~[fastjson2-2.0.54.jar:?]
	at com.alibaba.fastjson2.reader.ObjectReaderImplInt8ValueArray.readObject(ObjectReaderImplInt8ValueArray.java:82) ~[fastjson2-2.0.54.jar:?]
	at com.alibaba.fastjson2.reader.ORG_1_4_Data.readObject(Unknown Source) ~[?:?]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:864) ~[fastjson2-2.0.54.jar:?]
	at com.huawei.childcloudserver.tests.framework.cases.FastJson2Test.testObjectBytes(FastJson2Test.java:102) ~[classes/:?]
```
@wenshao
