### ISSUE TITLE
[BUG] 纳秒精度的时间字符串，反序列化成Date类型不兼容

### ISSUE THREAD

**Issue by zyhui98** [alibaba/fastjson2#3210]
### 问题描述

原因是升级JDK21之后，LocalDateTime默认精度从毫秒升级到纳秒了。

重现代码如下：
```java
@Data
public class TestBean {
    private Date time;
}

public static void main(String[] args) throws Exception {
        String s = "{\"time\":\"2024-12-04T20:43:15.000000999\"}";
        System.out.println(JSONObject.parseObject(s, TestBean.class));
}


```

异常堆栈：
Exception in thread "main" java.time.format.DateTimeParseException: Text '2024-12-04T20:43:15.000000999' could not be parsed, unparsed text found at index 19
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2111)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2010)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readDate(ObjectReaderImplDate.java:148)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readObject(ObjectReaderImplDate.java:48)
	at com.alibaba.fastjson2.reader.ORG_1_1_TestBean.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:542)

**Comment by wenshao** [comment]
你用的是什么版本，我测试下来是支持的

**Comment by zyhui98** [comment]
> 你用的是什么版本，我测试下来是支持的
2.0.53

**Comment by zyhui98** [comment]
1.2.70也不行的。

**Comment by zyhui98** [comment]
> 你用的是什么版本，我测试下来是支持的

请问，你是什么版本，我试试

**Comment by wenshao** [comment]
```java
import com.alibaba.fastjson2.JSONObject;
import lombok.Data;
import org.junit.jupiter.api.Test;
import java.util.Date;
import static org.junit.jupiter.api.Assertions.assertNotNull;
public class Issue3210 {
    @Data
    public static class Bean {
        private Date time;
    }
    @Test
    public void test() {
        String s = "{\"time\":\"2024-12-04T20:43:15.000000999\"}";
        Bean bean = JSONObject.parseObject(s, Bean.class);
        assertNotNull(bean.time);
    }
}
```
当前的main分支的代码，我测试是好的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.54
问题已修复，请用新版本

**Comment by zyhui98** [comment]
我试过了从2.0.0就可以了，可能是之前time上面加了注解导致    
@JSONField(format = "yyyy-MM-ddTHH:mm:ss")
@wenshao thank you
