### ISSUE TITLE
RocketMq无法启动[BUG]

### ISSUE THREAD

**Issue by JayFeiFei** [alibaba/fastjson2#344]
java.lang.NoSuchMethodError: com.alibaba.fastjson.JSON.toJSONString(Ljava/lang/Object;Z)Ljava/lang/String;
	at org.apache.rocketmq.remoting.protocol.RemotingSerializable.toJson(RemotingSerializable.java:34) ~[rocketmq-remoting-4.9.3.jar:4.9.3]
	at org.apache.rocketmq.remoting.protocol.RemotingSerializable.encode(RemotingSerializable.java:26) ~[rocketmq-remoting-4.9.3.jar:4.9.3]
	at org.apache.rocketmq.remoting.protocol.RemotingCommand.headerEncode(RemotingCommand.java:367) ~[rocketmq-remoting-4.9.3.jar:4.9.3]
	at org.apache.rocketmq.remoting.protocol.RemotingCommand.encodeHeader(RemotingCommand.java:409) ~[rocketmq-remoting-4.9.3.jar:4.9.3]
	at org.apache.rocketmq.remoting.protocol.RemotingCommand.encodeHeader(RemotingCommand.java:400) ~[rocketmq-remoting-4.9.3.jar:4.9.3]
	at org.apache.rocketmq.remoting.netty.NettyEncoder.encode(NettyEncoder.java:38) ~[rocketmq-remoting-4.9.3.jar:4.9.3]
	at org.apache.rocketmq.remoting.netty.NettyEncoder.encode(NettyEncoder.java:30) ~[rocketmq-remoting-4.9.3.jar:4.9.3]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.75.Final.jar:4.1.75.Final]
	... 17 common frames omitted

The following method did not exist:

    com.alibaba.fastjson.JSON.toJSONString(Ljava/lang/Object;Z)Ljava/lang/String;

The calling method's class, org.apache.rocketmq.remoting.protocol.RemotingSerializable, was loaded from the following location:

    jar:file:/D:/MavenRepository/org/apache/rocketmq/rocketmq-remoting/4.9.3/rocketmq-remoting-4.9.3.jar!/org/apache/rocketmq/remoting/protocol/RemotingSerializable.class

The called method's class, com.alibaba.fastjson.JSON, is available from the following locations:

    jar:file:/D:/MavenRepository/com/alibaba/fastjson/2.0.4/fastjson-2.0.4.jar!/com/alibaba/fastjson/JSON.class

The called method's class hierarchy was loaded from the following locations:

    com.alibaba.fastjson.JSON: file:/D:/MavenRepository/com/alibaba/fastjson/2.0.4/fastjson-2.0.4.jar

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.5-SNAPSHOT/
这个兼容问题已经修复，你可以用2.0.5-SNAPSHOT验证，预计本周内会发布2.0.5版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本

**Comment by xiangyunup** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.5 问题已修复，请使用新版本

如果使用 RocketMq 的话，是不是就得同时依赖了 fastjson  和 fastjson2

**Comment by wenshao** [comment]
@xiangyunup 可以用fastjson 2.0.8的兼容包，平滑升级
