### ISSUE TITLE
[BUG] No virtual method keySet() (Android)

### ISSUE THREAD

**Issue by xDragonZ** [alibaba/fastjson2#350]
### 问题描述
`NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView`

### 环境信息

 - OS信息： Android 9
 - JDK信息： JavaVersion.VERSION_1_8
 - 版本信息：2.0.4.android (Samsung S9+)
 

### 重现步骤
*如何操作可以重现该问题：*

```
Map<String, String> test = new HashMap<>()
test.put("ABC", "XYZ");
JSON.toJSONString(test); // <- Crash
```

### 相关日志输出
```
   java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-oj.jar)
        at com.alibaba.fastjson2.util.TypeUtils.<clinit>(TypeUtils.java:396)
        at com.alibaba.fastjson2.util.TypeUtils.getTypeName(TypeUtils.java:413)
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.<init>(ObjectReaderProvider.java:320)
        at com.alibaba.fastjson2.JSONFactory.<clinit>(JSONFactory.java:228)
        at com.alibaba.fastjson2.JSONFactory.createWriteContext(JSONFactory.java:235)
        at com.alibaba.fastjson2.JSONWriter.of(JSONWriter.java:392)
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:919)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本

**Comment by xDragonZ** [comment]
New issue found #375
