### ISSUE TITLE
fastjson2怎么让null属性序列化成空字符串[QUESTION]

### ISSUE THREAD

**Issue by JackJieZhang** [alibaba/fastjson2#351]
### fastjson2怎么让null属性序列化成空字符串
* fastjson1直接使用
```
ValueFilter valueFilter = (o, s, o1) -> {
            if (Objects.isNull(o1)) {
                return "";
            } else {
                return o1;
            }
        };
```
* fastjson2使用这个方法会导致异常
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:207)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:383)
	at com.alibaba.fastjson2.writer.ObjectWriter_2.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:254)
	at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:196)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:387)
	at com.alibaba.fastjson2.writer.ObjectWriter_1.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1005)
	at com.jtech.srm.sys.Test1.test1(Test1.java:121)
```

**Comment by wsxe9988** [comment]
Bean bean = ...;
JSON.toJSONString(bean, JSONWriter.Feature.NullAsDefaultValue); // 将空置输出为缺省值，Number类型的null都输出为0，String类型的null输出为""，数组和Collection类型的输出为[]

**Comment by JackJieZhang** [comment]
@wsxe9988 恩，这个我看了，有这样的情况,
```
class A{
String a;
}
class B{
String c;
 A a;
}

B b = new B();
b.setC("1");
b.setA(null);
JSON.toJSONString(b);
```
我想要序列化b的时候，如果属性A是null，就转成空字符串，这个A是自己定义的类。
这样的情况在fastjson1的时候用`ValueFilter`可以处理，但是fastjson2会抛异常。

**Comment by wenshao** [comment]
问题没重现，能否能够提供重现问题的testcase？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
