### ISSUE TITLE
[BUG] No field coder in class Ljava/lang/String; (Android) 

### ISSUE THREAD

**Issue by xDragonZ** [alibaba/fastjson2#375]
### 问题描述
`NoSuchFieldException: No field coder in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)`

### 环境信息

 - OS信息： Android 9
 - JDK信息： JavaVersion.VERSION_1_8
 - 版本信息：2.0.5.android (Samsung S9+)
 

### 重现步骤
*如何操作可以重现该问题：*

```
Map<String, String> test = new HashMap<>()
test.put("ABC", "XYZ");
JSON.toJSONString(test); // <- Crash
```

### 相关日志输出
```
java.lang.ExceptionInInitializerError
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.of(ObjectWriterImplMap.java:69)
        at com.alibaba.fastjson2.writer.ObjectWriterBaseModule.getObjectWriter(ObjectWriterBaseModule.java:778)
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:107)
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:397)
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1312)
        [removed]
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: com.alibaba.fastjson2.JSONException: unsafe get String.coder error
        at com.alibaba.fastjson2.util.UnsafeUtils.getStringCoder(UnsafeUtils.java:77)
        at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:698)
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.<clinit>(ObjectWriterImplMap.java:15)
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.of(ObjectWriterImplMap.java:69) 
        at com.alibaba.fastjson2.writer.ObjectWriterBaseModule.getObjectWriter(ObjectWriterBaseModule.java:778) 
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:107) 
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:397) 
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1312) 
        [removed]
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.NoSuchFieldException: No field coder in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.alibaba.fastjson2.util.UnsafeUtils.getStringCoder(UnsafeUtils.java:74)
        at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:698) 
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.<clinit>(ObjectWriterImplMap.java:15) 
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.of(ObjectWriterImplMap.java:69) 
        at com.alibaba.fastjson2.writer.ObjectWriterBaseModule.getObjectWriter(ObjectWriterBaseModule.java:778) 
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:107) 
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:397) 
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1312) 
```

**Comment by wenshao** [comment]
问题已修复，请帮忙用2.0.6-SNAPSHOT验证
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6.android-SNAPSHOT/

很抱歉，android版本一直没弄好，需要帮助

**Comment by xDragonZ** [comment]
辛苦了，我测试了 问题已解决 :smile:

**Comment by wenshao** [comment]
能提供重现问题的case么？

**Comment by xDragonZ** [comment]
好的 这个issue可以关了 因为新的问题和这个没关系

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本

**Comment by yqsmile** [comment]
'com.alibaba.fastjson2:fastjson2:2.0.8' 这个版本，在AndroidS上仍旧报这个错误。

**Comment by wenshao** [comment]
用com.alibaba.fastjson2:fastjson2:2.0.8.android

**Comment by misland** [comment]
```
compileSdkVersion 29
    buildToolsVersion "29.0.3"
    defaultConfig {
        applicationId "com.heping.helloworld"
        minSdkVersion 29
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```
2.0.9报同样的错误，然后切换到了2.0.6，报`Didn't find class "java.lang.management.ManagementFactory"`，果断放弃了，用原生的得了

**Comment by foxitdog** [comment]
2.0.20 android 也在报这个错误

java.lang.ExceptionInInitializerError
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.of(ObjectWriterImplMap.java:69)
        at com.alibaba.fastjson2.writer.ObjectWriterBaseModule.getObjectWriter(ObjectWriterBaseModule.java:778)
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:107)
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:397)
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1312)
        [removed]
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: com.alibaba.fastjson2.JSONException: unsafe get String.coder error
        at com.alibaba.fastjson2.util.UnsafeUtils.getStringCoder(UnsafeUtils.java:77)
        at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:698)
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.<clinit>(ObjectWriterImplMap.java:15)
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.of(ObjectWriterImplMap.java:69) 
        at com.alibaba.fastjson2.writer.ObjectWriterBaseModule.getObjectWriter(ObjectWriterBaseModule.java:778) 
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:107) 
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:397) 
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1312) 
        [removed]
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.NoSuchFieldException: No field coder in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.alibaba.fastjson2.util.UnsafeUtils.getStringCoder(UnsafeUtils.java:74)
        at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:698) 
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.<clinit>(ObjectWriterImplMap.java:15) 
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.of(ObjectWriterImplMap.java:69) 
        at com.alibaba.fastjson2.writer.ObjectWriterBaseModule.getObjectWriter(ObjectWriterBaseModule.java:778) 
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:107) 
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:397) 
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1312)
