### ISSUE TITLE
[BUG]Android 6报错NoClassDefFoundError Ljava/time/ZoneId

### ISSUE THREAD

**Issue by sharfy** [alibaba/fastjson2#401]
### 问题描述
*简要描述您碰到的问题。*
调用 JSON.toJSONString(object, JSONWriter.Feature.WriteMapNullValue);报错

 Process: com.example.facesdk, PID: 2498
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
        at com.alibaba.fastjson2.JSONWriter$Context.<clinit>(:1264)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: java.time.ZoneId

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：android 6]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.4]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSON.toJSONString(object, JSONWriter.Feature.WriteMapNullValue);` 方法
2. 出现 `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId` 错误
```java
ZoneId 不存在

![image](https://user-images.githubusercontent.com/11766936/171805379-e92376a5-1446-41a6-8d2a-1cc6e683183f.png)

**Comment by wenshao** [comment]
fastjson2最近支持android 8，不支持android 6

**Comment by famik** [comment]
> fastjson2最近支持android 8，不支持android 6

以后会考虑支持android 7以下吗？

**Comment by wenshao** [comment]
@famik 不考虑了，如果要支持android 7，工作量比较大，维护不过来的
