### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dance3366** [alibaba/fastjson2#413]
### 问题描述
反序列unixtime时间字符串到java.util.Date报错

### 环境信息
 - JDK信息： Openjdk 1.8.0_312
 - 版本信息：Fastjson2 0.6
 
### 重现步骤
1. 使用 `JSON.parseObject` 方法
2. 出现 `Exception in thread "main" java.lang.IllegalArgumentException: Unknown pattern letter: i` 错误
```java
String date1 = JSONObject.of("date1", "1654134285").toString();
Date date = JSON.parseObject(date1, Test.class).getDate1();

@Data
class Test{
    @JSONField(format = "unixtime")
    private Date date1;
}
```

### 期待的正确结果
反序列化成功

### 相关日志输出
Exception in thread "main" java.lang.IllegalArgumentException: Unknown pattern letter: i
	at java.time.format.DateTimeFormatterBuilder.parsePattern(DateTimeFormatterBuilder.java:1672)
	at java.time.format.DateTimeFormatterBuilder.appendPattern(DateTimeFormatterBuilder.java:1581)
	at java.time.format.DateTimeFormatter.ofPattern(DateTimeFormatter.java:536)
	at com.alibaba.fastjson2.reader.FieldReaderDateMethod.getFormatter(FieldReaderDateMethod.java:117)
	at com.alibaba.fastjson2.reader.FieldReaderDateMethod.readFieldValue(FieldReaderDateMethod.java:76)
	at com.alibaba.fastjson2.reader.ObjectReader1.readObject(ObjectReader1.java:242)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:421)
	at com.example.jdbc.UnixTimeTest.main(UnixTimeTest.java:22)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/

问题已经修复，你用2.0.7-SNAPSHOT先验证一下

**Comment by dance3366** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/
> 
> 问题已经修复，你用2.0.7-SNAPSHOT先验证一下

maven的settings文件配置可以发一下，我配置如下，依赖一直下载不成功
``` xml
	 <mirror>
		<!--指定镜像ID（可自己改名）-->
		<id>nexus-snapshots</id>
		<!--匹配中央仓库（阿里云的仓库名称，不可修改）-->
		<mirrorOf>Snapshots</mirrorOf>
		<!--指定镜像名称（可自己改名）-->
		<name>Nexus snapshots</name>
		<!--指定镜像路径（镜像地址）-->
		<url> https://oss.sonatype.org/content/repositories/snapshots/</url>
	 </mirror>
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
