### ISSUE TITLE
[BUG] parseObject异常抛出文案不友好

### ISSUE THREAD

**Issue by oday-xiexin** [alibaba/fastjson2#414]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：windows10]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.6]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
![企业微信截图_16544785141224](https://user-images.githubusercontent.com/40761282/172083034-0d88f3f5-f12a-488a-9490-ced7ab501989.png)

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
相比1.2.84 转换异常抛出的文案比较友好，如java.lang.Integer cannot be cast to com.alibaba.fastjson.JSONObject，但fastjson2 只会抛出com.alibaba.fastjson.JSONException: illegal input， offset 1, char 2

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
com.alibaba.fastjson.JSONException: illegal input， offset 1, char 2
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:109)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:66)
	at com.platform.dict.aspect.DictAspect.parseDictText(DictAspect.java:90)
	at com.platform.dict.aspect.DictAspect.doAround(DictAspect.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.platform.modules.match.MatchApiController$$EnhancerBySpringCGLIB$$4e338cb9.policyYear(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.alibaba.fastjson2.JSONException: illegal input， offset 1, char 2
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readObject(ObjectReaderImplMap.java:366)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1164)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:99)
	... 68 common frames omitted

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本

**Comment by dzzxjl** [comment]
2.0.22 版本依然遇到此问题

**Comment by wenshao** [comment]
能提供输入json字符串和新的报错堆栈信息么？

**Comment by dzzxjl** [comment]
> 能提供输入json字符串和新的报错堆栈信息么？

`Caused by: com.alibaba.fastjson2.JSONException: illegal input， offset 1, char n
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1444)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:183)
	... 11 more`

**Comment by kuailehaibin** [comment]
2.0.26 版本也遇到了这个问题
com.alibaba.fastjson.JSONException: illegal input， offset 1, char F
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:192)
	at com.alipay.dataphin.utils.OdpsUtils.queryMapReduceInfo(OdpsUtils.java:276)
	at com.alipay.dataphin.model.instance.OdpsEngineInstance.queryMapReduceInfo(OdpsEngineInstance.java:105)
	at com.alipay.dataphin.service.sql.performance.diagnosis.BaseDiagnosis.queryMapReduceInfo(BaseDiagnosis.java:98)
	at com.alipay.dataphin.service.sql.performance.diagnosis.SkewJoinDiagnosis.evaluate(SkewJoinDiagnosis.java:127)
	at com.aliyun.odps.udf.impl.batch.UdfEval8ba7e81ba90f48278113ee0ccec532b0.evaluate(Unknown Source)
	at com.aliyun.odps.udf.impl.batch.UDFZeroCopyEvaluatorForEE.batchProcess(UDFZeroCopyEvaluatorForEE.java:177)
Caused by: com.alibaba.fastjson2.JSONException: illegal input， offset 1, char F
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1459)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:183)
	... 6 more

**Comment by Harbor404** [comment]
2.0.56也遇到了

com.alibaba.fastjson.JSONException: invalid escape character EOI, offset 581, character ", line 20, column 19, fastjson-version 2.0.56
{
  "busInfo": {
    "item": [
      {
        "dbuscard": "苏E-06971D",
        "lguid": "0000000000LINELINEINFO12111220461674",
        "sguid": "000000000LINESTANDINFO20062947271526",
        "lastslon": 1,
        "lastlongitude": "121.14617",
        "lastlatitude": "31.40971",
        "lastspeed": 23,
        "lastdirection": 202,
        "oilvalue": "0",
        "passengeramount": 0,
        "modifydate": "2025-08-12 06:10:29"
      },
      {
        "dbuscard": "苏E-38766D",
        "lguid": "0000000000LINELINEINFO12111220461674",
        "sguid": "000000000LINESTANDINFO16111121726477",
        "lastslon": 7,
        "lastlongitude": "121.12266",
        "lastlatitude": "31.41918",
        "lastspeed": 0,
        "lastdirection": 0,
        "oilvalue": "0",
        "passengeramount": 0,
        "modifydate": "2025-08-12 06:10:27"
      }
    ]
  }
}
	at com.yg84.chelaile.octobus.datasource.t.taicangsuzhou.TaicangSuzhouSessionHandler.handleGpsDataMessages(TaicangSuzhouSessionHandler.java:132) ~[classes/:?]
	at com.yg84.chelaile.octobus.datasource.t.taicangsuzhou.TaicangSuzhouSessionHandler.processMessageByType(TaicangSuzhouSessionHandler.java:87) ~[classes/:?]
	at com.yg84.chelaile.octobus.datasource.t.taicangsuzhou.TaicangSuzhouSessionHandler.onMessagesPackageReceived(TaicangSuzhouSessionHandler.java:66) ~[classes/:?]
	at com.yg84.chelaile.octobus.engine.datafetcher.impl.socket.mina.DataFetcherIoHandler.messageReceived(DataFetcherIoHandler.java:113) ~[classes/:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:1015) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:418) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:257) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:122) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:643) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:539) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$1200(AbstractPollingIoProcessor.java:68) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1224) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1213) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:683) ~[mina-core-2.1.7.jar:?]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) ~[mina-core-2.1.7.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_451]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_451]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_451]
