### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 2594726366** [alibaba/fastjson2#425]
### 问题描述
设备采集过来的数据 会有正负号，负号没问题 就是数据有+号时转换成数字报错

### 重现步骤
*如何操作可以重现该问题：
1. JSONObject.parseObject(bb,xxx.class);
4. xxx包含Float型等
5. com.alibaba.fastjson2.JSONException: parseLong error, value : +000.00

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
加上＋可以解析正数

### 相关日志输出
com.alibaba.fastjson2.JSONException: parseLong error, value : +000.00
	at com.alibaba.fastjson2.JSONReader.toInt64(JSONReader.java:1658)
	at com.alibaba.fastjson2.JSONReader.getNumber(JSONReader.java:1565)
	at com.alibaba.fastjson2.JSONReader.readNumber(JSONReader.java:642)
	at com.alibaba.fastjson2.JSONReader.readFloat(JSONReader.java:617)
	at com.alibaba.fastjson2.reader.FieldReaderFloatMethod.readFieldValue(FieldReaderFloatMethod.java:19)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:174)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/
bug已修复，请帮用2.0.7-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
