### ISSUE TITLE
[FEATURE]fastjson2.0.6反序列化Boolean时的兼容问题

### ISSUE THREAD

**Issue by HuShao96** [alibaba/fastjson2#429]
### 请描述您的需求或者改进建议
代码如下：属性d为Boolean类型；当我转成对象的时候：由于d为空字符串，所以报错
        String ss ="{\"a\":null,\"b\":\"\",\"c\":[],\"d\":\"\",\"date\":\"2022-06-07\"}";
        System.out.println(JSON.parseObject(ss,Entity.class));

### 描述您考虑过的替代方案
1.x版本是可以把这个进行过滤掉的；；2.x是否考虑也是如此？

#### 附加信息
![image](https://user-images.githubusercontent.com/26806329/172305505-42deba04-a897-4391-87ff-528584a3e3f5.png)

Exception in thread "main" com.alibaba.fastjson2.JSONException: can not convert to boolean : 
	at com.alibaba.fastjson2.JSONReader.readBoolValue(JSONReader.java:1333)
	at com.alibaba.fastjson2.JSONReader.readBool(JSONReader.java:1266)
	at com.alibaba.fastjson2.reader.FieldReaderBoolMethod.readFieldValue(FieldReaderBoolMethod.java:19)
	at com.alibaba.fastjson2.reader.ObjectReader5.readObject(ObjectReader5.java:300)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:421)
	at FastJsonTest.main(FastJsonTest.java:30)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/
已经支持，请用2.0.7-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
