### ISSUE TITLE
[BUG] Kotlin序列化报错

### ISSUE THREAD

**Issue by xiaolei123** [alibaba/fastjson2#440]
### 问题描述
我的kotlin类：
`
class User {
    val map = mapOf(1 to 2, "a" to "a", 3f to 3f)
}
`

### 环境信息
AndroidStudio

### 重现步骤
val user = User()
val bytes = JSONB.toBytes(user)

### 相关日志输出
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.writeJSONB(ObjectWriterImplMap.java:214)
        at com.alibaba.fastjson2.writer.FieldWriterObject.write(FieldWriterObject.java:196)

#### 附加信息
我看了一下源码，发现我的key是int，但是在 ObjectWriterImplMap 第124行，发现是这样子实现的：

if (entryKey instanceof String || (contextFeatures & JSONWriter.Feature.WriteClassName.mask) == 0) {
  String key = (String) entryKey;
  xxxx
 }

这里爆出的类型转换失败

**Comment by wenshao** [comment]
fastjson什么版本？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/
问题已经重现并修复，请用2.0.7-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
