### ISSUE TITLE
[BUG] "seat" 是FastJson 关键字?

### ISSUE THREAD

**Issue by stephenlam520** [alibaba/fastjson2#441]
### 问题描述
"seat" 是FastJson 关键字?为什么javaBean 用seat 这个成员变量序列化成json 就会报错?

### 环境信息
*请填写以下信息：*

 - OS信息：  [win10 21H2 ]
 - JDK信息： [1.8.0_312]
 - 版本信息：[Fastjson2 2.0.6]
 

### 重现步骤
测试方法:
public class Test {
	public static void main(String[] args) {
		User user = new User();
		user.setSeat(1);
		
		UserVo userVo = new UserVo(user);
				
		String roomInfo = JSONObject.toJSONString(userVo);
		System.out.println(roomInfo);
	}
}

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper=false)
public class UserVo extends BaseResponseVo {
	
   private static final long serialVersionUID = 5757659865865333180L;
    private Integer seat;
    
    public UserVo (User user){
    	this.seat = user.getSeat();
    }
}

### 相关日志输出
Exception in thread "main" java.lang.IllegalAccessError: tried to access field com.xy.lq.mj.model.vo.UserVo.seat from class com.alibaba.fastjson2.writer.ObjectWriter_1
	at com.alibaba.fastjson2.writer.ObjectWriter_1.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1658)
	at com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1080)
	at com.xy.lq.mj.Test.main(Test.java:14)

#### 附加信息
经过测试只要把"seat" 换成其他的就好了,比如"seat1","seat2".....

**Comment by stephenlam520** [comment]
找到问题了
