### ISSUE TITLE
[BUG]LocalDate字段用@JSONField注解，反序列化导致内存溢出

### ISSUE THREAD

**Issue by 893230716** [alibaba/fastjson2#448]
### 问题描述
bean中用了JDK8的时间日期类，在类上的jdk8的日期字段加@JSONField(format = "yyyyMMdd")注解，测试bean里面嵌套同类的bean，反序列化时导致OOM

### 环境信息
*请填写以下信息：*

 - OS信息：  Windows 10 专业版 21H2 内部版本19044.1706 4核 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz   3.41 GHz 16.0 GB
 - JDK信息： Oracle jdk1.8.0_271
 - 版本信息：Fastjson2 2.0.6
 

### 重现步骤

运行FastjsonTest测试用例里面的test()方法，反序列化一直卡住，一段时间后，就会导致OOM异常

```java

import com.alibaba.fastjson2.annotation.JSONField;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 *  测试bean
 */
@Data
public class BasicStaff implements Serializable {

    // 小弟列表 
    private List<BasicStaff> boyList;

    @JSONField(format = "yyyyMMdd")
    private LocalDate localDate;

    @JSONField(format = "yyyyMMdd HH:mm:ss")
    private LocalDateTime localDateTime;
}


/**
 * 测试用例
 */
public class FastjsonTest {

    // 测试数据
    private BasicStaff prepare() {
        BasicStaff staff = new BasicStaff();
        staff.setLocalDate(LocalDate.now());
        staff.setLocalDateTime(LocalDateTime.now());

        List<BasicStaff> list = new ArrayList<>();
       
        for (int i = 0; i < 1; i++) {
            BasicStaff staffI = new BasicStaff();

            staffI.setLocalDate(LocalDate.now());
            staffI.setLocalDateTime(LocalDateTime.now());

            list.add(staffI);
        }
        //  嵌套同样类型的bean，就会导致OOM
        staff.setBoyList(list);

        return staff;
    }

    @Test
    public void test() {
        BasicStaff staff = prepare();

        // 序列化
        String jsonString = JSON.toJSONString(staff, JSONWriter.Feature.WriteClassName);
        System.out.println(jsonString);
       
        System.out.println(">>> 准备反序列化");

        // 反序列化（就在这出的问题）
        BasicStaff staffD = (BasicStaff) JSON.parseObject(jsonString, Object.class, JSONReader.Feature.SupportAutoType);
        System.out.println(staffD);
    }
}

```

### 期待的正确结果
可以正常反序列化出BasicStaff实体类

### 相关日志输出
{"@type":"cn.ygs.api.basic.entity.BasicStaff","boyList":[{"localDate":"20220609","localDateTime":"20220609 17:45:01"}],"localDate":"20220609","localDateTime":"20220609 17:45:01"}

>>> 准备反序列化

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:267)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
	at java.util.ArrayList.add(ArrayList.java:464)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:80)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:597)
	at cn.ygs.cache.FastjsonTest.test(FastjsonTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$119/1234776885.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall$$Lambda$120/1440047379.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$$Lambda$280/1586845078.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$291/660879561.execute(Unknown Source)

#### 附加信息
pom文件大致如下
使用了springboot2.6.7版本
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
        <relativePath/>
    </parent>

引入了springboot的test依赖
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
</dependency>

使用了lombok 
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.24</version>
</dependency>

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
