### ISSUE TITLE
[BUG] 解析JSON失败，对应的类属性是 List ，List里面的元素有 Integer[] 等数组类型的字段时，如果对应的值是空字符串无法解析 

### ISSUE THREAD

**Issue by ly-az** [alibaba/fastjson2#464]
### 问题描述
*解析JSON，对应的类的字段属性是 List，List里面的元素又有 Integer[] 等数组类型的字段时，如果对应的值是空字符串无法解析*

### 环境信息
*请填写以下信息：*

 - OS信息：  [Windows 10 专业版 4Core 3.60GHz 16 GB]
 - JDK信息： [Openjdk 1.8.0_312]
 - 版本信息：[Fastjson2 2.0.7]
 

### 重现步骤
```java

public class JSONTest {

    public static void main(String[] args) {
        String str = "{\"test\":[{\"demo\":\"\"}]}";
        System.out.println("str = " + str);
        TestParam param = JSON.parseObject(str, TestParam.class);
        System.out.println("list = " + param);

    }

    @Data
    static class TestParam {
        List<Demo> test;
    }

    @Data
    static class Demo{
        private Integer[] demo;
    }


}
```

### 期待的正确结果
JSONTest.TestParam(test=[JSONTest.Demo(demo=null)])

### 相关日志输出
Exception in thread "main" com.alibaba.fastjson2.JSONException: read field error : test, offset 18, character ", line 1, column 19, fastjson-version 2.0.7 {"test":[{"demo":""}]}
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:112)
	at com.alibaba.fastjson2.reader.ObjectReader1.readObject(ObjectReader1.java:241)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:453)
	at JSONTest.main(JSONTest.java:13)
Caused by: com.alibaba.fastjson2.JSONException: read field error : demo, offset 18, character ", line 1, column 19, fastjson-version 2.0.7 {"test":[{"demo":""}]}
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:112)
	at com.alibaba.fastjson2.reader.ObjectReader1.readObject(ObjectReader1.java:241)
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1409)
	at com.alibaba.fastjson2.reader.ObjectArrayTypedReader.readObject(ObjectArrayTypedReader.java:62)
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:109)
	... 3 more
Caused by: com.alibaba.fastjson2.JSONException: TODO, offset 18, character ", line 1, column 19, fastjson-version 2.0.7 {"test":[{"demo":""}]}
	at com.alibaba.fastjson2.reader.ObjectReaderImplInt32Array.readObject(ObjectReaderImplInt32Array.java:74)
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:109)
	... 7 more

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by ly-az** [comment]
将 Demo 类中的 demo 字段有 `Integer[]` 修改为 `List<Integer>`后，传入空字符串也是可以解析的，

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/
问题已经修复，请帮忙用2.0.8-SNAPSHOT验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
