### ISSUE TITLE
[BUG]多层嵌套json，包含多个arr时，使用JSONPath无法获取到期望值

### ISSUE THREAD

**Issue by qsj** [alibaba/fastjson2#487]
### 问题描述
目标JSON是一个多层嵌套的json，如：{"v1":[{"v2":[{"v3":{"v4":1}}]}]} 使用jsonpath：$.v1[*].v2[*].v3.v4 期望得到[1]，但是得到了null

### 环境信息
*请填写以下信息：*

 - OS信息：  windows 10 
 - JDK信息： jdk 1.8.0_281
 - 版本信息：Fastjson2 2.0.7

### 重现步骤
*如何操作可以重现该问题：*

```java
@Test
public void testNestedJson(){
    Assert.assertEquals("[1]",
                        JSON.toJSONString(
                            JSONPath.of("$.v1[*].v2[*].v3.v4")
                            .extract(
                                JSONReader.of("{\"v1\":[{\"v2\":[{\"v3\":{\"v4\":1}}]}]}")
                            )
                        )
                       );
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

执行通过

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

```
org.junit.ComparisonFailure: 
Expected :[1]
Actual   :null
<Click to see difference>


	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.secsmart.JsonParseTest.testNestedJson(JsonParseTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/

问题已经修复，请用2.0.8-SNAPSHOT验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
