### ISSUE TITLE
[BUG] JSON.toJSONString无法解析

### ISSUE THREAD

**Issue by solochen** [alibaba/fastjson2#500]
### 问题描述
按文档Gradle导入FastJson2:
implementation 'com.alibaba.fastjson2:fastjson2:2.0.7'

简单测试 JSON.toJSONString、JSON.parseObject("", UserInfo.class) 失败，报异常： java.lang.UnsupportedOperationException: can't load this type of class file

### 环境信息
 - OS信息： OnePlus IN2020 Snapdragon 865 8GB RAM + 128GB ROM
 - JDK信息：Openjdk 1.8.0_144
 - 版本信息：Fastjson2 2.0.7
 

### 重现步骤
1. 创建简单实体类，implements Serializable
2. 调用toJSONString转json
3. 运行报错

```
UserInfo userInfo = new UserInfo();
userInfo.setName("test");
String userInfoString = JSON.toJSONString(userInfo);

```
### 相关日志输出
```
 java.lang.UnsupportedOperationException: can't load this type of class file
        at java.lang.ClassLoader.defineClass(ClassLoader.java:591)
        at com.alibaba.fastjson2.util.DynamicClassLoader.defineClassPublic(DynamicClassLoader.java:120)
        at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.createObjectWriter(ObjectWriterCreatorASM.java:381)
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:176)
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:409)
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1692)
        at com.solo.test.utils.MDJSON.parse(MDJSON.java:14)
        at com.solo.test.fragment.TestAFragment.onViewCreated(TestAFragment.kt:27)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1525)
        at android.app.Activity.performStart(Activity.java:8030)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3648)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by wenshao** [comment]
UserInfo这个类的代码提供下

**Comment by solochen** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/12407279/174948964-b3ef2e6c-a801-41f5-b60c-04699487f87f.png">
```
public class UserInfo implements Serializable {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}

```

**Comment by solochen** [comment]
```
import java.io.Serializable;

public class UserInfo implements Serializable {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

**Comment by solochen** [comment]
使用JSON.parseObject也是报同样异常：

```
 public static void parse(){
        UserInfo userInfo = JSON.parseObject("{\"name\":\"test\"}", UserInfo.class);
    }
```

**Comment by wenshao** [comment]
https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2/2.0.7.android/

Android环境用Android版本

**Comment by solochen** [comment]
> https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2/2.0.7.android/
> 
> Android环境用Android版本

可以了，真棒👍🏻
