### ISSUE TITLE
[BUG]JSONObject.parseObject(string, clazz)无法转换问题

### ISSUE THREAD

**Issue by zhangptang** [alibaba/fastjson2#502]
### 问题描述
出现使用 `JSONObject.parseObject(String.clazz)`时出现报错`Exception in thread "main" java.lang.UnsupportedOperationException`

### 环境信息

 - OS信息：  [e.g.：win11]
 - JDK信息： [e.g.：jdk 1.8.0_111]
 - 版本信息：[e.g.：Fastjson2 2.0.7]
 
### 重现步骤

1. 使用 `JSONObject.parseObject(result, ThirdCommonResult.class);` 方法
2. 输入json类型的字符串 数据
3. 出现 `Exception in thread "main" java.lang.UnsupportedOperationException` 错误
```java
ThirdCommonResult thirdCommonResult = JSONObject.parseObject(result, ThirdCommonResult.class);
        System.out.println(thirdCommonResult.getTaskId());
```

### 期待的正确结果
期待能正常解析数据

### 相关日志输出
出现错误日志

#### 附加信息

附加返回的数据结构

```java
@Data
public class ThirdCommonResult {

    private String msg;

    private String flag;

    private String taskId;

    private JSONArray data;
}
```

**Comment by kailanyue** [comment]
遇到了同样的问题，

### 环境信息
#### JDK
java version "11.0.15.1" 2022-04-22 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15.1+2-LTS-10)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15.1+2-LTS-10, mixed mode)

#### OS
版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.105

#### Fastjson2 版本
Fastjson2 2.0.7

**Comment by wenshao** [comment]
请提供ThirdCommonResult类的代码，最好能提供错误的堆栈信息

**Comment by zhangptang** [comment]
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.alibaba.fastjson2.reader.FieldReader.getItemObjectReader(FieldReader.java:200)
	at com.alibaba.fastjson2.reader.FieldReader.getItemObjectReader(FieldReader.java:204)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:453)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1812)
	at com.iflytek.pl.undertow.jsontest.ResultTransforTest.test1(ResultTransforTest.java:46)
	at com.iflytek.pl.undertow.jsontest.ResultTransforTest.main(ResultTransforTest.java:14)

**Comment by wenshao** [comment]
能帮用2.0.8验证下问题是否已经解决么？

**Comment by zhangptang** [comment]
这是我的测试代码：
```java
public static void main(String[] args) {
        String s = "{  \"msg\":\"success\",\"flag\":\"ok\",\"taskId\":\"13fee3000dddc\"," +
                "\"data\":[{\"rq\":\"2022-06-28 12:03:52\",\"lng\":\"172.342\"," +
                "\"lat\":\"31.4532\",\"name\":\"ceshi\"}]}";
        //实体数据上面已给出
        ThirdCommonResult result = JSONObject.parseObject(s, ThirdCommonResult.class);
        System.out.println(result.getTaskId());
    }
```
错误显示
```java
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.alibaba.fastjson2.reader.FieldReader.getItemObjectReader(FieldReader.java:200)
	at com.alibaba.fastjson2.reader.FieldReader.getItemObjectReader(FieldReader.java:204)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:453)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1812)
	at com.zptang.json.test.JsonTest.main(JsonTest.java:11)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/

感谢反馈，原因是JSONArray data这个字段，问题已经修复，请用2.0.9-SNAPSHOT版本验证。2.0.9版本预计在7月10日发布。

**Comment by zhangptang** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
> 
> 感谢反馈，原因是JSONArray data这个字段，问题已经修复，请用2.0.9-SNAPSHOT版本验证。2.0.9版本预计在7月10日发布。

nice

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
