### ISSUE TITLE
[BUG] Graalvm版本 构建native image后出现 Defining hidden classes at runtime is not supported

### ISSUE THREAD

**Issue by huyu-tom** [alibaba/fastjson2#509]
2.0.8.graal 版本
以下代码出错
List<Person> ls = JSON.parseArray(strJson, Person.class);

环境信息
OS信息：window11
JDK信息：GraalVM EE 22.1.0 (build 17.0.3+8-LTS-jvmci-22.1-b05)
版本信息：2.0.8.graal
重现步骤
List<Person> ls = JSON.parseArray(strJson, Person.class);

期待的正确结果
能正确转成List

相关日志输出
com.oracle.svm.core.jdk.UnsupportedFeatureError: Defining hidden classes at runtime is not supported.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
        at java.lang.ClassLoader.defineClass0(ClassLoader.java:336) ~[graalvm.exe:na]
        at java.lang.System$2.defineClass(System.java:2307) ~[na:na]
        at java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2439) ~[na:na]
        at java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClassAsLookup(MethodHandles.java:2420) ~[na:na]
        at java.lang.invoke.MethodHandles$Lookup.defineHiddenClass(MethodHandles.java:2127) ~[na:na]
        at java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:407) ~[na:na]
        at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:315) ~[na:na]
        at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:228) ~[na:na]
        at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:341) ~[na:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreatorLambda.lambdaFunction(ObjectReaderCreatorLambda.java:322) ~[na:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreatorLambda.createFieldReaderLambda(ObjectReaderCreatorLambda.java:307) ~[na:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreatorLambda.createFieldReaderMethod(ObjectReaderCreatorLambda.java:225) ~[na:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReader(ObjectReaderCreator.java:996) ~[graalvm.exe:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.lambda$createFieldReaders$4(ObjectReaderCreator.java:1075) ~[graalvm.exe:na]
        at com.alibaba.fastjson2.util.BeanUtils.setters(BeanUtils.java:406) ~[na:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaders(ObjectReaderCreator.java:1073) ~[graalvm.exe:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreator.createObjectReader(ObjectReaderCreator.java:611) ~[graalvm.exe:na]
        at com.alibaba.fastjson2.reader.ObjectReaderCreatorLambda.createObjectReader(ObjectReaderCreatorLambda.java:84) ~[na:na]
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:739) ~[na:na]
        at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1259) ~[graalvm.exe:na]
        at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:1630) ~[graalvm.exe:na]
        at com.alibaba.fastjson2.JSON.parseArray(JSON.java:1579) ~[na:na]
        at com.huyu.controller.TestController.parsePerson(TestController.java:30) ~[graalvm.exe:1.0.0]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[graalvm.exe:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[graalvm.exe:5.3.20]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[graalvm.exe:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[graalvm.exe:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[graalvm.exe:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[graalvm.exe:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[graalvm.exe:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[graalvm.exe:9.0.63]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[graalvm.exe:5.3.20]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[graalvm.exe:5.3.20]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[graalvm.exe:5.3.20]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[graalvm.exe:5.3.20]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[graalvm.exe:5.3.20]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[graalvm.exe:5.3.20]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[na:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[na:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[graalvm.exe:9.0.63]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[na:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[graalvm.exe:9.0.63]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[na:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[na:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[na:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[graalvm.exe:9.0.63]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[na:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[graalvm.exe:9.0.63]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
        at java.lang.Thread.run(Thread.java:833) ~[graalvm.exe:na]
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704) ~[graalvm.exe:na]
        at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143) ~[na:na]

**Comment by wenshao** [comment]
Person这个类的代码可以提供下么？

**Comment by huyu-tom** [comment]
> Person这个类的代码可以提供下么？
好的,
[person.zip](https://github.com/alibaba/fastjson2/files/8985758/person.zip)
采用了SpringBoot:2.7.0,spring-native:0.12.0,jdk:GraalVM EE 22.1.0

**Comment by wenshao** [comment]
需要使用 @ReflectionHint，比如：
```java

@ReflectionHint
class User {
    private Integer id;
    private String nick;

    public User() {
    }

    public User(Integer id, String nick) {
        this.id = id;
        this.nick = nick;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }
}
```

**Comment by huyu-tom** [comment]
> ```java
> ReflectionHint
> ```
这个目的就是让其可以反射，加入到native-images的反射配置当中去,可是我使用 Spring-natvie的类似作用的注解
package com.huyu.config;

import com.huyu.controller.Person;
import org.springframework.nativex.hint.*;
import org.springframework.nativex.type.NativeConfiguration;
import org.springframework.stereotype.Component;


@NativeHint(
        types = {
                @TypeHint(types = {Person.class}, access = {
                        TypeAccess.QUERY_DECLARED_CONSTRUCTORS,
                        TypeAccess.QUERY_DECLARED_METHODS,
                        TypeAccess.QUERY_PUBLIC_CONSTRUCTORS,
                        TypeAccess.QUERY_PUBLIC_METHODS,
                        TypeAccess.DECLARED_FIELDS,
                        TypeAccess.PUBLIC_FIELDS,
                })
        },
        serializables = {
                @SerializationHint(
                        types = {Person.class}
                )
        },
        resources = {
                @ResourceHint(
                        patterns = {"com/huyu/controller/Person.class"},
                        isBundle = false
                )
        }
)
@Component
public class Config implements NativeConfiguration {

}
，并且也是有用的，在编译器，可以看到反射的配置文件，我配置的也在里面，就比如 Person
并且自己测试调用反射，那个配置也是生效的
@GetMapping("/inv2")
    public Object invork2(@RequestParam(value = "methodName", name = "methodName") String methodName,
                          @RequestParam(value = "paramType") String paramType,
                          @RequestParam(value = "className") String className,
                          @RequestParam(value = "value") String value) throws Exception {
        Class<?> aClass = MethodHandles.lookup().findClass(className);
        Class<?> paramTypeClass = Class.forName(paramType);
        Method method = aClass.getDeclaredMethod(methodName, paramTypeClass);
        method.setAccessible(true);
        return method.invoke(aClass.newInstance(), value);
    }

**Comment by huyu-tom** [comment]
> 需要使用 @ReflectionHint，比如：
> 
> ```java
> @ReflectionHint
> class User {
>     private Integer id;
>     private String nick;
> 
>     public User() {
>     }
> 
>     public User(Integer id, String nick) {
>         this.id = id;
>         this.nick = nick;
>     }
> 
>     public Integer getId() {
>         return id;
>     }
> 
>     public void setId(Integer id) {
>         this.id = id;
>     }
> 
>     public String getNick() {
>         return nick;
>     }
> 
>     public void setNick(String nick) {
>         this.nick = nick;
>     }
> }
> ```
加上这个还是不行！！！
![image](https://user-images.githubusercontent.com/54206202/175808008-a6df5e53-4864-43d5-8ecc-5935013006cc.png)
![image](https://user-images.githubusercontent.com/54206202/175808025-9de5ceca-befb-47bd-b327-173c355ad614.png)

![image](https://user-images.githubusercontent.com/54206202/175808035-3696aefd-ed4a-48bc-9e9c-235fa3dfe2af.png)
![image](https://user-images.githubusercontent.com/54206202/175808051-63c37041-3dfa-4bfb-9f74-fa7ff78a5826.png)
![image](https://user-images.githubusercontent.com/54206202/175808056-897520b9-5685-44b2-9d47-46435137225d.png)
而且资源文件在native-image的参数里面已经加载上去了

**Comment by huyu-tom** [comment]
> 需要使用 @ReflectionHint，比如：
> 
> ```java
> @ReflectionHint
> class User {
>     private Integer id;
>     private String nick;
> 
>     public User() {
>     }
> 
>     public User(Integer id, String nick) {
>         this.id = id;
>         this.nick = nick;
>     }
> 
>     public Integer getId() {
>         return id;
>     }
> 
>     public void setId(Integer id) {
>         this.id = id;
>     }
> 
>     public String getNick() {
>         return nick;
>     }
> 
>     public void setNick(String nick) {
>         this.nick = nick;
>     }
> }
> ```
结论: 需要转换json的类和Main方法同属在同一个java文件里面就可以，TestFastJson2ParseInner 类是可以的
package com.huyu;

import com.alibaba.fastjson2.JSON;
import io.goodforgod.graalvm.hint.annotation.ReflectionHint;

public class TestFastJson2ParseInner {

    public static void main(String[] args) throws Exception {
        User user = new User();
        user.setAge(100);
        user.setName("fastjson2--yyds");
        String userJson = JSON.toJSONString(user);
        User userObj = JSON.parseObject(userJson, User.class);
        System.out.println(userObj);

//        Class<?> aClass = Class.forName("com.apl.po.User");
//        Object o = aClass.newInstance();
//        Method setAge = aClass.getDeclaredMethod("setAge", Integer.class);
//        setAge.setAccessible(true);
//        setAge.invoke(o, 10);
//        Method toString = aClass.getDeclaredMethod("toString");
//        Object invoke1 = toString.invoke(o);
//        System.out.println(invoke1);
    }
}

@ReflectionHint
class User {
    private String name;
    private Integer age;


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}

需要json转换的类不是在同一个类里面就不行
package com.huyu;

import com.alibaba.fastjson2.JSON;

public class TestFastJson2Parse {
    public static void main(String[] args) throws Exception {
        Person user = new Person();
        user.setAge(100);
        user.setName("fastjson2--yyds");
        String userJson = JSON.toJSONString(user);
        User userObj = JSON.parseObject(userJson, User.class);
        System.out.println(userObj);

//        Class<?> aClass = Class.forName("com.apl.po.User");
//        Object o = aClass.newInstance();
//        Method setAge = aClass.getDeclaredMethod("setAge", Integer.class);
//        setAge.setAccessible(true);
//        setAge.invoke(o, 10);
//        Method toString = aClass.getDeclaredMethod("toString");
//        Object invoke1 = toString.invoke(o);
//        System.out.println(invoke1);
    }
}
package com.huyu;

import io.goodforgod.graalvm.hint.annotation.ReflectionHint;

@ReflectionHint
public class Person {
    private String name;
    private Integer age;


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}

**Comment by wenshao** [comment]
我目前也不知道解法，你有什么建议么？

**Comment by huyu-tom** [comment]
> getObjectWriter

我也没有什么解决方案，最原始的反射倒是可以

**Comment by huyu-tom** [comment]
> 我目前也不知道解法，你有什么建议么？
暂时也没有解决方案，原始的反射倒还可以

**Comment by wenshao** [comment]
启动参数加上-Dfastjson2.creator=reflect试下是否可以

**Comment by huyu-tom** [comment]
> 启动参数加上-Dfastjson2.creator=reflect试下是否可以
不行
![image](https://user-images.githubusercontent.com/54206202/175813507-14917c79-87bb-4ea1-b278-7e1ce3d5eedd.png)
堆栈信息:
Exception in thread "main" com.alibaba.fastjson2.JSONException: create fieldLambdaGetter error, method : public java.lang.String com.huyu.Person.getName()
        at com.alibaba.fastjson2.writer.ObjectWriterCreatorLambda.lambdaSetter(ObjectWriterCreatorLambda.java:171)
        at com.alibaba.fastjson2.writer.ObjectWriterCreatorLambda.createFieldWriter(ObjectWriterCreatorLambda.java:68)
        at com.alibaba.fastjson2.writer.ObjectWriterCreator.lambda$createObjectWriter$2(ObjectWriterCreator.java:285)
        at com.alibaba.fastjson2.util.BeanUtils.getters(BeanUtils.java:668)
        at com.alibaba.fastjson2.writer.ObjectWriterCreator.createObjectWriter(ObjectWriterCreator.java:222)
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:154)
        at com.alibaba.fastjson2.JSONWriter.getObjectWriter(JSONWriter.java:388)
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:924)
        at com.huyu.TestFastJson2Parse.main(TestFastJson2Parse.java:12)
Caused by: java.lang.InternalError: com.oracle.svm.core.jdk.UnsupportedFeatureError: Defining hidden classes at runtime is not supported.
        at java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:413)
        at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:315)
        at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:228)
        at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:341)
        at com.alibaba.fastjson2.writer.ObjectWriterCreatorLambda.lambdaSetter(ObjectWriterCreatorLambda.java:158)
        ... 8 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Defining hidden classes at runtime is not supported.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.lang.ClassLoader.defineClass0(ClassLoader.java:336)
        at java.lang.System$2.defineClass(System.java:2307)
        at java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2439)
        at java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClassAsLookup(MethodHandles.java:2420)
        at java.lang.invoke.MethodHandles$Lookup.defineHiddenClass(MethodHandles.java:2127)
        at java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:407)
        ... 12 more

**Comment by WillsonYip** [comment]
我遇到了类似的问题， 问题所在还是ObjectWriterCreatorLambda.lambdaSetter()方法

问题代码如下：

`CallSite callSite = LambdaMetafactory.metafactory(
                    lookup,
                    buildInfo.methodName,
                    invokedType,
                    func.erase(),
                    target,
                    func
            );`

这个方法会等价于定义了新的函数对象的类，这明显是native image无法支持的。

**Comment by wenshao** [comment]
@WillsonYip @huyu-tom 
我改成通过反射了，帮用2.0.9.graal-SNAPSHOT版本验证下是否
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9.graal-SNAPSHOT/

**Comment by wenshao** [comment]
> 我遇到了类似的问题， 问题所在还是ObjectWriterCreatorLambda.lambdaSetter()方法
> 
> 问题代码如下：
> 
> `CallSite callSite = LambdaMetafactory.metafactory( lookup, buildInfo.methodName, invokedType, func.erase(), target, func );`
> 
> 这个方法会等价于定义了新的函数对象的类，这明显是native image无法支持的。

native image也支持的，我验证过，但我不清楚为什么在你的场景不行

**Comment by WillsonYip** [comment]
> > 我遇到了类似的问题， 问题所在还是ObjectWriterCreatorLambda.lambdaSetter()方法
> > 问题代码如下：
> > `CallSite callSite = LambdaMetafactory.metafactory( lookup, buildInfo.methodName, invokedType, func.erase(), target, func );`
> > 这个方法会等价于定义了新的函数对象的类，这明显是native image无法支持的。
> 
> native image也支持的，我验证过，但我不清楚为什么在你的场景不行

我的场景是把JAVA库导成.so文件 ，给c++调用。后面发现系统变量只有编译的时候有效，给C++调用的时候无效。 
现在的方法是直接在JAVA代码上设置系统变量就可以了
`static {
        System.setProperty("fastjson2.creator", "reflect");
    }`

**Comment by huyu-tom** [comment]
> @WillsonYip @huyu-tom 我改成通过反射了，帮用2.0.9.graal-SNAPSHOT版本验证下是否 https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9.graal-SNAPSHOT/

现在可以了

**Comment by wenshao** [comment]
如果不能用LambdaMetafactory只能用反射，反射在GraalVM中的性能是怎样的？哪里有数据啊

**Comment by huyu-tom** [comment]
> 如果不能用LambdaMetafactory只能用反射，反射在GraalVM中的性能是怎样的？哪里有数据啊

经过一些测试，发现 LambdaMetafactory 调用有问题,但是我不知道我的这个写法是否是正确的调用!!!
![9457336c8a8d2d2798a5f6a129881fa](https://user-images.githubusercontent.com/54206202/176168160-2158a0e2-e17d-4045-bbe9-37ca3d51c7a4.png)
![9b97a77cc0d103f2b3697f44dd86953](https://user-images.githubusercontent.com/54206202/176168194-3d5b435b-ae2e-41d0-8940-3c2e24167fa9.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
