### ISSUE TITLE
[QUESTION] NoClassDefFoundError: Failed resolution of: Ljava/awt/Color

### ISSUE THREAD

**Issue by t894924815** [alibaba/fastjson2#511]
版本: com.alibaba:fastjson:2.0.8.android
在 android 上集成以上版本，使用 `JSON.parse` 相关方法后会直接崩溃，报错信息:

`
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;
        at com.alibaba.fastjson2.support.AwtRederModule.getObjectReader(AwtRederModule.java:27)
        at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:658)
        at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1426)
        at com.alibaba.fastjson2.JSONReader.readAny(JSONReader.java:1613)
        at com.alibaba.fastjson.JSON.parse(JSON.java:408)
`

**Comment by wenshao** [comment]
2.0.8.android的兼容包确实有这个问题，你可以先用2.0.9.android-SNAPSHOT先验证下么？
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.9.android-SNAPSHOT/

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本

**Comment by kevin-leak** [comment]
![image](https://user-images.githubusercontent.com/30002212/207555947-83499fb6-8549-4c1d-9cf3-0c32eddc2f77.png)

alosalso  find in 'com.alibaba:fastjson:2.0.19'

**Comment by wenshao** [comment]
@kevin-leak 试下2.0.21.android版本
