### ISSUE TITLE
[BUG]2.0.9-SNAPSHOT序列化异常

### ISSUE THREAD

**Issue by prog-ape** [alibaba/fastjson2#529]
版本：2.0.9-SNAPSHOT
序列化报错：
org.springframework.data.redis.serializer.SerializationException: Could not deserialize: illegal character ; nested exception is com.alibaba.fastjson2.JSONException: illegal character
        at com.alibaba.fastjson2.support.spring.data.redis.GenericFastJsonRedisSerializer.deserialize(GenericFastJsonRedisSerializer.java:71)
        at org.springframework.data.redis.core.AbstractOperations.deserializeValue(AbstractOperations.java:360)
        at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:62)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
        at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54)

2.0.8-SNAPSHOT版本正常
[json.txt](https://github.com/alibaba/fastjson2/files/9045204/json.txt)

**Comment by wenshao** [comment]
没有重现问题，需要你补充相关DTO的类信息

**Comment by alon-sys** [comment]
> 没有重现问题，需要你补充相关DTO的类信息

温少，这个json文件报的是这个问题：Could not deserialize: illegal character , offset 9102, character , line 1, column 9103

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.24
@alon-sys 可以帮忙验证下2.0.24是否还存在问题么？
