### ISSUE TITLE
[BUG]JSONObject.getObject获取List时出现java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by LoftyKumo** [alibaba/fastjson2#536]
### 问题描述
由fastjson1升级至fastjson2的过程中
fastjson2版本2.0.7
使用JSONObject.getObject(key, List.class)时, 会抛出java.lang.UnsupportedOperationException

fastjson2版本2.0.8   2.0.9-SNAPSHOT
使用JSONObject.getObject(key, List.class)时,会抛出com.alibaba.fastjson2.JSONException: UnsupportedOperation

### 环境信息

 - OS信息：  macOS 10.13.6
 - JDK信息： JDK 11.0.2
 - 版本信息：2.0.7   2.0.8   2.0.9-SNAPSHOT
 

### 重现步骤
使用测试代码如下
        Map<String, Object> map = null;
        List<Object> objects = Lists.newArrayList();
        for (int i = 0; i < 1; i++) {
            map = Maps.newHashMap();
            map.put("cursor", i);
            objects.add(map);
        }
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("data", objects);
        jsonObject.getObject("data", List.class);

### 期待的正确结果
运行通过, 可正常获取data字段数据

### 相关日志输出
fastjson版本2.0.7
java.lang.UnsupportedOperationException
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule$PrimitiveImpl.createInstance(ObjectReaderBaseModule.java:1809)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.createInstance(ObjectReaderImplObject.java:15)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:78)
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.createInstance(ObjectReaderImplList.java:186)
	at com.alibaba.fastjson2.JSONObject.getObject(JSONObject.java:1273)

fastjson2.0.8   fastjson2.0.9-SNAPSHOT
com.alibaba.fastjson2.JSONException: UnsupportedOperation
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule$PrimitiveImpl.createInstance(ObjectReaderBaseModule.java:1810)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.createInstance(ObjectReaderImplObject.java:15)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:78)
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.createInstance(ObjectReaderImplList.java:186)
	at com.alibaba.fastjson2.JSONObject.getObject(JSONObject.java:1273)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
问题已经修复，请用2.0.9-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本

**Comment by howiekang** [comment]
@LoftyKumo 使用2.0.9之后 这个bug问题还存在吗？

**Comment by LoftyKumo** [comment]
> @LoftyKumo 使用2.0.9之后 这个bug问题还存在吗？

2.0.9修复了这个问题, 出现了https://github.com/alibaba/fastjson2/issues/541  目前改为了使用JSONArray

**Comment by 532780857** [comment]
![image](https://user-images.githubusercontent.com/39074601/188772220-df3934b3-8517-41ec-8425-823d3763924f.png)
```xml        <groupId>com.alibaba.fastjson2</groupId>
        <artifactId>fastjson2-parent</artifactId>
        <version>2.0.12</version>
`

```log
java.lang.UnsupportedOperationException: com.alibaba.fastjson2.reader.ObjectReaderImplObject
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:37)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.createInstance(ObjectReaderImplMapTyped.java:91)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1141)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:107)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1189)
	at com.solvay.bzj.entity.codeFlow.importFlow.entity.IntelligentMasterSlaveEntity.getEntity(IntelligentMasterSlaveEntity.java:38)
`

我这个也是同样的问题吗？
