### ISSUE TITLE
[BUG] 对象中的List<Long> 字段，反序列化报错

### ISSUE THREAD

**Issue by HsinDumas** [alibaba/fastjson2#539]
2.0.8版本

```java
     public static void main(String[] args) {
        TestParam param = new TestParam();
        List<Long> list = new ArrayList<>();
        list.add(1L);
        param.setIds(list);
        System.out.println(JSON.parseObject("{\"ids\":[1]}").to(TestParam.class));
    }
```

Exception in thread "main" java.lang.UnsupportedOperationException: com.alibaba.fastjson2.reader.FieldReaderListInt64
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:37)
	at com.alibaba.fastjson2.JSONArray.to(JSONArray.java:938)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:109)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1190)
	at com.mcd.cn.rms.order.core.controller.ComplainController.main(ComplainController.java:36)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
问题已经修复，请帮忙用2.0.9-SNAPSHOT验证，2.0.9版本预计明天发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
