### ISSUE TITLE
[BUG] 内部类反序列化报错

### ISSUE THREAD

**Issue by stephenlam520** [alibaba/fastjson2#565]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win10 3.8GHz 32 GB]
 - JDK信息： [e.g.：Oracle JDK1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.9]
 

### 重现步骤
1. 使用 JSON.parseObject(responseData, Response.class) 方法
2. 输入数据: {"roomType":"GRASS_SQUARE_FLOWER","users":[{"name":"STTEST02","userId":"101177"},{"name":"STTEST01","userId":"101176"}]}  

3. 出现 `om.alibaba.fastjson2.JSONException: invoke constructor error` 错误
Exception in thread "AWT-EventQueue-0" com.alibaba.fastjson2.JSONException: invoke constructor error, public org.xx.entity.Response$AccountInfo(org.xx.entity.Response,java.lang.String,java.lang.String)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:144)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:15)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstrutor.createInstanceNoneDefaultConstructor(ObjectReaderNoneDefaultConstrutor.java:53)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstrutor.readObject(ObjectReaderNoneDefaultConstrutor.java:276)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:453)

//可在此输入示例代码
pojo:
public class Response implements Serializable {
	private static final long serialVersionUID = 7868798773717812999L;
	private String roomType;
	private List<AccountInfo> users;

	public class AccountInfo {
		private String userId;
		private String name;
		public AccountInfo() {
		}
		public AccountInfo(String userId, String name) {
			this.userId = userId;
			this.name = name;
		}
		public String getUserId() {
			return userId;
		}
		public void setUserId(String userId) {
			this.userId = userId;
		}
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
		@Override
		public String toString() {
			// TODO Auto-generated method stub
			return this.name;
		}
	}

	public String getRoomType() {
		return roomType;
	}
	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}
	public List<AccountInfo> getUsers() {
		return users;
	}
	public void setUsers(List<AccountInfo> users) {
		this.users = users;
	}
}

### 期待的正确结果
fastjson 1.2.80 是没问题的,换成fastjson2 2.0.9 报错.

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
为什么关闭了？

**Comment by stephenlam520** [comment]
改用静态内部类就没问题了

发自我的iPhone
