### ISSUE TITLE
[BUG]在大对象序列化时报错：java.lang.OutOfMemoryError: null

### ISSUE THREAD

**Issue by CoderLiuyang** [alibaba/fastjson2#568]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息： windows/centos都报错
 - JDK信息：1.8_221
 - 版本信息：Fastjson2 2.0.9
 

### 重现步骤
*如何操作可以重现该问题：*
使用方法JSON.toJSONString
大对象大小为90m
序列化后报java.lang.OutOfMemoryError: null
### 相关日志输出
java.lang.OutOfMemoryError: null
	at com.alibaba.fastjson2.JSONWriterUTF16.writeNameRaw(JSONWriterUTF16.java:561)
	at com.alibaba.fastjson2.writer.FieldWriterImpl.writeFieldName(FieldWriterImpl.java:143)
	at com.alibaba.fastjson2.writer.ObjectWriter_3.write(Unknown Source)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:770)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wsxe9988** [comment]
麻烦能否提供下相关case以及测试数据

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/blob/main/docs/features_cn.md
参考这个，JSON.toJSONString的时候，加上JSONWriter.Feature. ReferenceDetection
