### ISSUE TITLE
> 复测过，升级到fastjson 2.0.10兼容版本和fastjson2 2.0.10 不会抛出异常。 json字符串里面params属性的值是null 转换后的bo的params还是null，没有赋值

### ISSUE THREAD

**Issue by leblancvn** [alibaba/fastjson2#605]
> 复测过，升级到fastjson 2.0.10兼容版本和fastjson2 2.0.10 不会抛出异常。 json字符串里面params属性的值是null 转换后的bo的params还是null，没有赋值

使用了2.0.10版本是当使用了lombok的@Accessors(chain = true)注解的时候依然会报错.
```java
@Setter
@Getter
@Accessors(chain = true)
public class WinningInformationBo{
    private boolean isSuccess;
    private String wxId;
    private Map<String, String> parems;
}
```
编译后的类为:
```java
public class WinningInformationBo{
    private boolean isSuccess;
    private String wxId;
    private Map<String, String> parems;

    public TestVO() {
    }

    public TestVO setSuccess(final boolean isSuccess) {
        this.isSuccess = isSuccess;
        return this;
    }

    public TestVO setWxId(final String wxId) {
        this.wxId = wxId;
        return this;
    }

    public TestVO setParems(final Map<String, String> parems) {
        this.parems = parems;
        return this;
    }

    public boolean isSuccess() {
        return this.isSuccess;
    }

    public String getWxId() {
        return this.wxId;
    }

    public Map<String, String> getParems() {
        return this.parems;
    }
}
```

_Originally posted by @leblancvn in https://github.com/alibaba/fastjson2/issues/596#issuecomment-1199280295_

**Comment by leblancvn** [comment]
@Setter
@Getter
@Accessors(chain = true)
public class WinningInformationBo {
    private boolean isSuccess;
    private String wxId;
    private Map<String, String> parems;
}

String str3 = "{\"wx_id\":\"xxx\",\"success\":true,\"parems\":null}";
WinningInformationBo bo = JSON.parseObject(str3, WinningInformationBo.class);
此时会报错抛出异常。
使用fastjson 2.0.10兼容版本和fastjson2 2.0.10都会报错。
期望值是null时不用赋值

**Comment by wsxe9988** [comment]
parems 为{}是不会抛异常，但params=null的时候确实会抛异常
```
Exception in thread "main" com.alibaba.fastjson.JSONException: error, offset 44, char 
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:197)
	at com.zhuoyun.test3.TestMain.main(TestMain.java:13)
Caused by: com.alibaba.fastjson2.JSONException: error, offset 44, char 
	at com.alibaba.fastjson2.JSONReaderUTF16.skipValue(JSONReaderUTF16.java:2264)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:47)
	at com.alibaba.fastjson2.reader.ObjectReader3.readObject(ObjectReader3.java:311)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:187)
	... 1 more
```
@wenshao

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.11-SNAPSHOT/
问题已修复，请用2.0.11-SNAPSHOT版本帮忙验证，2.0.11版本预计在8月7日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.11
问题已修复，请用新版本
