### ISSUE TITLE
json.parse解析报错Java heap space[BUG]

### ISSUE THREAD

**Issue by xqlsq** [alibaba/fastjson2#610]
### 问题描述
2.0.3版本出现乱码字符和异常的时候，报错java.lang.OutOfMemoryError: Java heap space

### 重现步骤

1. 使用 `JSON.parse` 方法
2. 输入 `{"bbbb":"cccc"[+D�HPndroid 10"}`  数据
3. 出现 `java.lang.OutOfMemoryError: Java heap space` 错误
```java
JSON.parse({"bbbb":"cccc"[+D�HPndroid 10"})
```

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3210)
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:267)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
        at java.util.ArrayList.add(ArrayList.java:464)
        at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:1279)
        at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:110)
        at com.alibaba.fastjson2.JSON.parse(JSON.java:42)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
问题已经修复过，请请用2.0.10验证

**Comment by xqlsq** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.10 问题已经修复过，请用2.0.10验证

请问有类似的issue吗？原因是啥

**Comment by wenshao** [comment]
是因为处理非法格式没有中断退出导致
