### ISSUE TITLE
[BUG] 无法序列化java.util.ImmutableCollections$Map1

### ISSUE THREAD

**Issue by itlihuaxin** [alibaba/fastjson2#640]
版本信息：[2.0.10]

在使用GenericFastJsonRedisSerializer时异常

输入：java.utilMap.of("abc", 1);

异常：
Caused by: org.springframework.data.redis.serializer.SerializationException: Could not deserialize: create map error : class java.util.ImmutableCollections$Map1; nested exception is com.alibaba.fastjson2.JSONException: create map error : class java.util.ImmutableCollections$Map1
	at com.alibaba.fastjson2.support.spring.data.redis.GenericFastJsonRedisSerializer.deserialize(GenericFastJsonRedisSerializer.java:71)
	at org.springframework.data.redis.core.AbstractOperations.deserializeValue(AbstractOperations.java:335)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:61)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:222)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultListOperations.rightPop(DefaultListOperations.java:239)

之前的2.0.5是没问题的

**Comment by itlihuaxin** [comment]
看了redis 2.0.10版本后台信息带有{"@type":"java.util.ImmutableCollections$Map1"}

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.11
问题已修复，请用新版本
