### ISSUE TITLE
[BUG] JsonPath not support -

### ISSUE THREAD

**Issue by Nailcui** [alibaba/fastjson2#642]
### 问题描述
*简要描述您碰到的问题。*

我有个json数据，计划用JsonPath获取其中 `x-limit` 字段的数据，`JSONPath.of("$.x-limit")` 时候抛出异常提示: `com.alibaba.fastjson2.JSONException: not support -`

```json
{
    "x-limit":10
}
```

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Mac ]
 - JDK信息： [e.g.：Openjdk 1.8.0_231]
 - 版本信息：[e.g.：Fastjson2 2.0.11]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
public class Main {
  public static void main(String[] args) {
    JSONPath path = JSONPath.of("$.x-limit");
  }
}

```

### 期待的正确结果

期望正常运行，无异常抛出

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

实际执行结果：
```
Exception in thread "main" com.alibaba.fastjson2.JSONException: not support -
	at com.alibaba.fastjson2.JSONPath$JSONPathParser.parse(JSONPath.java:5997)
	at com.alibaba.fastjson2.JSONPath.of(JSONPath.java:392)
	at com.caocao.eventbus.pattern.Main.main(Main.java:12)

```

**Comment by wenshao** [comment]
其中-需要做转义，可以两种办法解决你的问题，比如：

```java
String str = "{\n" +
        "    \"x-limit\":10\n" +
        "}";
JSONObject object = JSON.parseObject(str);
assertEquals(
        10,
        JSONPath
                .of("$.x\\-limit")
                .eval(object)
);
assertEquals(
        10,
        JSONPath
                .of("$['x-limit']")
                .eval(object)
);
```
