### ISSUE TITLE
[BUG]Failed resolution of: Ljava/time/LocalTime;

### ISSUE THREAD

**Issue by ncnnnnn** [alibaba/fastjson2#645]
implementation 'com.alibaba:fastjson:2.0.11.android'

android 7.1  不支持 ObjectWriterProvider的  java.time.LocalTime.class,

 JSON.toJSONString(hashMapOf<String, String>(Pair("1", "a")))

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalTime;
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.<clinit>(ObjectWriterProvider.java:185)
        at com.alibaba.fastjson2.JSONFactory.<clinit>(JSONFactory.java:242)
        at com.alibaba.fastjson2.JSONFactory.getDefaultObjectReaderProvider(JSONFactory.java:303)
        at com.alibaba.fastjson.JSON.<clinit>(JSON.java:50)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:756)

**Comment by wenshao** [comment]
需要Android 8+，不支持Android 7.1
