### ISSUE TITLE
[V2.0.11，执行 JSON.toJSONString() 报错，JSONFactory无法初始化]

### ISSUE THREAD

**Issue by conquener** [alibaba/fastjson2#649]
### 问题描述
程序启动时,JSONObject class 对象尚未加载。

此时JSONFactory无法初始化，检查发现2.0.11版本，JSONFactory 的静态成员defaultObjectReaderProvider 的类上有块静态代码块，执行了以下代码：
 `hashCache.put(Fnv.hashCode64(TypeUtils.getTypeName(HashMap.class)), ObjectReaderImplMap.INSTANCE);`

类ObjectReaderImplMap 初始化时调用
`Class.forName("com.alibaba.fastjson.JSONObject");` ， 该处抛出了ClassNotFound的异常。

### 环境信息
*请填写以下信息：*
 - OS信息：  [e.g.：Windows]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.11]
 

### 重现步骤
测试代码如下：
`HashSet<String> hashSet = new HashSet<>();
hashSet.add("1");
JSONObject jsonObject = new JSONObject();
System.out.println(JSON.toJSONString(hashSet));`
注释 第三行代码，就会报错。

### 相关日志输出
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.<clinit>(ObjectReaderImplMap.java:27)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.<init>(ObjectReaderProvider.java:331)
	at com.alibaba.fastjson2.JSONFactory.<clinit>(JSONFactory.java:254)
	at com.alibaba.fastjson2.JSONWriter.of(JSONWriter.java:397)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1721)
	at com.hyjsxy.qb.api.TestA.main(TestA.java:24)
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.JSONFactory.getDefaultObjectReaderProvider(JSONFactory.java:330)
	at com.alibaba.fastjson.JSON.<clinit>(JSON.java:52)
	... 8 more

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
已修复，请帮忙验证下2.0.12-SNAPSHOT版本

**Comment by conquener** [comment]
我已收到邮件,工作事宜将于工作日处理.Best regards，peng.H

**Comment by conquener** [comment]
已验证，2.0.12-SNAPSHOT版本 已修复 iusse #649。

**Comment by conquener** [comment]
我已收到邮件!Best regards，peng.H

**Comment by DoneSpeak** [comment]
那这个版本还能用吗？看到2.0.12的milestone进度，感觉还要等很久很久才能用上

**Comment by conquener** [comment]
用应该可以用，项目启动前初始化一下JSONObject，引发问题的代码是遗留的没有用的一块代码，新版本是直接注释了。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本
