### ISSUE TITLE
[BUG]解析错误的数据结构时，死循环最终内存溢出

### ISSUE THREAD

**Issue by HsinDumas** [alibaba/fastjson2#669]
### 问题描述
*解析错误的数据结构时，死循环最终内存溢出*

### 环境信息
*请填写以下信息：*

 - JDK信息： 1.8
 - 版本信息：Fastjson2 2.0.11
 

### 重现步骤
*如何操作可以重现该问题：*

```java

   public static void main(String[] args) {
        System.out.println(com.alibaba.fastjson2.JSON.parseArray("[\"3330354\"]", Test.class));
    }

    @Data
    public static class Test {
        private String a;
    }

```

### 期待的正确结果
*正常报错，而不是一直死循环，最后OOM*

### 相关日志输出
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:1671)
	at com.alibaba.fastjson2.JSON.parseArray(JSON.java:1600)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
问题已修复，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本
