### ISSUE TITLE
hashMap key为null时序列化失败,报空指针[BUG]

### ISSUE THREAD

**Issue by dyj2012** [alibaba/fastjson2#697]
### 问题描述
*简要描述您碰到的问题。*
hashMap key为null时序列化失败,报空指针

```
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.writeJSONB(ObjectWriterImplMap.java:230) ~[fastjson2-2.0.6.jar!/:?]
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.writeJSONB(ObjectWriterImplMap.java:298) ~[fastjson2-2.0.6.jar!/:?]
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.writeJSONB(ObjectWriterImplMap.java:298) ~[fastjson2-2.0.6.jar!/:?]
	at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:873) ~[fastjson2-2.0.6.jar!/:?]
```

**Comment by wenshao** [comment]
升级到2.0.11试下看问题是否还存在

**Comment by dyj2012** [comment]
> 升级到2.0.11试下看问题是否还存在
存在
java.lang.NullPointerException
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.writeJSONB(ObjectWriterImplMap.java:245)
	at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:894)


```
    @Test
    public void toJSON() {
		HashMap<String, Object> map = new HashMap<>();
		map.put("1","1");
		map.put("2","2");
		map.put(null,"3");
		JSONB.toBytes(map, JSONWriter.Feature.WriteClassName);
    }
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
问题已修复，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

**Comment by dyj2012** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/ 问题已修复，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

验证通过

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本
