### ISSUE TITLE
[QUESTION] 是否考虑支持接口的反序列化

### ISSUE THREAD

**Issue by DoneSpeak** [alibaba/fastjson2#698]
### 请描述您的问题

希望可以支持接口的反序列化。

Fastjson1 实现
```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.alibaba.fastjson.JSON;
import com.fasterxml.jackson.core.JsonProcessingException;
import org.junit.Test;

public class TestFastjsonDeserializeInterface {

    static interface Entity {
        String getName();
    }

    // 不支持动态代理
    @Test
    public void testInterfaceProxy() throws JsonProcessingException {
        final var EXPECTED_NAME = "jhahah";
        String jsonString = JSON.toJSONString(new Entity() {
            @Override
            public String getName() {
                return EXPECTED_NAME;
            }
        });
        Entity result = JSON.parseObject(jsonString, Entity.class);
        // actual: null
        assertEquals(EXPECTED_NAME, result.getName());
    }
}
```

Fastjson2 实现
```xml
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.10</version>
        </dependency>
```

```java

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.alibaba.fastjson2.JSON;
import org.junit.Test;

public class TestFastjsonDeserializeInterface {

    static interface Entity {
        String getName();
    }

    // 不支持动态代理
    @Test
    public void testInterfaceProxy() {
        final var EXPECTED_NAME = "jhahah";
        String jsonString = JSON.toJSONString(new Entity() {
            @Override
            public String getName() {
                return EXPECTED_NAME;
            }
        });
        Entity result = JSON.parseObject(jsonString, Entity.class);
        // actual: null
        assertEquals(EXPECTED_NAME, result.getName());
    }

    // 不支持动态代理
    @Test
    public void testDeserialize() {
        final var EXPECTED_NAME = "jhahah";
        var jsonString = String.format("{\"name\":\"%s\"}", EXPECTED_NAME);
        Entity result = JSON.parseObject(jsonString, Entity.class);
        // actual: null
        assertEquals(EXPECTED_NAME, result.getName());
    }
}
```

测试结果：
```java
org.opentest4j.AssertionFailedError: expected: <jhahah> but was: <null>
Expected :jhahah
Actual   :null
```

**Comment by DoneSpeak** [comment]
有fastjson2的钉钉群吗？想加入讨论群

**Comment by DoneSpeak** [comment]
找到序列化失败的原因了，是2.0.11的bug，回退到2.0.10就没有问题了。

相关issue：https://github.com/alibaba/fastjson2/issues/649

使用2.0.10的测试结果如下：
```
org.opentest4j.AssertionFailedError: expected: <jhahah> but was: <null>
Expected :jhahah
Actual   :null
<Click to see difference>


	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at io.gitlab.donespeak.tutorial.TestFastjsonDeserializeInterface.testDeserialize(TestFastjsonDeserializeInterface.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code 255
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
请帮忙验证下2.0.12-SNAPSHOT版本是否已经修复

**Comment by DoneSpeak** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/ 请帮忙验证下2.0.12-SNAPSHOT版本是否已经修复

#### 测试结果：
序列化功能正常

#### 测试过程
```java
    @Test
    public void testSerialize() {
        final var EXPECTED_NAME = "jhahah";
        String jsonString = JSON.toJSONString(new Entity() {
            @Override
            public String getName() {
                return EXPECTED_NAME;
            }
        });
        assertEquals("{\"name\":\"jhahah\"}", jsonString);
    }
```

修改`~/.m2/settings.xml`，增加如下profile
```xml
    <profile>
        <id>allow-snapshots</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
        <repositories>
            <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
            </repository>
        </repositories>
        </profile>
    </profiles>
```

使用2.0.12-SNAPSHOT
```xml
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.12-SNAPSHOT</version>
        </dependency>
```

@wenshao

**Comment by DoneSpeak** [comment]
可以考虑使用动态代理实现接口的反序列化：

```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.reader.ObjectReader;
import com.alibaba.fastjson2.writer.ObjectWriter;
import java.lang.reflect.Proxy;
import java.lang.reflect.Type;
import org.junit.Test;

public class InterfaceProxyTest {

    static interface Entity {
        String getName();
    }

    static class BigEntity {
        @JSONField(serializeUsing = ProxyReader.class, deserializeUsing = ProxyReader.class)
        private Entity entity;

        public BigEntity() {}

        public void setEntity(Entity entity) {
            this.entity = entity;
        }

        public Entity getEntity() {
            return entity;
        }
    }

    @Test
    public void testDeserialize() {
        final var EXPECTED_NAME = "jhahah";
        var jsonString = String.format("{\"entity\":{\"name\":\"%s\"}}", EXPECTED_NAME);
        BigEntity result = JSON.parseObject(jsonString, BigEntity.class);
        assertEquals(EXPECTED_NAME, result.getEntity().getName());
    }

    public static class ProxyReader implements ObjectReader {

        @Override
        public Object readObject(JSONReader jsonReader, Type type,
            Object o, long l) {
            var jsonObject = jsonReader.read(JSONObject.class);
            Class<?> clazz = (Class<?>) type;
            if (!clazz.isInterface()) {
                return jsonReader.read(type);
            }
            ClassLoader loader = Thread.currentThread().getContextClassLoader();
            return Proxy.newProxyInstance(loader, new Class<?>[] { clazz }, jsonObject);
        }
    }
}
```

**Comment by DoneSpeak** [comment]
如果使用嵌套的接口结构就会失败：
```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.reader.ObjectReader;
import java.lang.reflect.Proxy;
import java.lang.reflect.Type;
import org.junit.Test;

public class InterfaceProxyTest {

    static interface Entity {
        String getName();
    }

    static interface MiddleEntity {
        @JSONField(deserializeUsing = ProxyReader.class)
        Entity getEntity();
    }

    static class BigEntity {
        @JSONField(deserializeUsing = ProxyReader.class)
        private MiddleEntity middleEntity;

        public BigEntity() {}

        public void setMiddleEntity(MiddleEntity middleEntity) {
            this.middleEntity = middleEntity;
        }

        public MiddleEntity getMiddleEntity() {
            return middleEntity;
        }
    }

    @Test
    public void testDeserialize() {
        final var EXPECTED_NAME = "jhahah";
        var jsonString = String.format("{\"middleEntity\":{\"entity\":{\"name\":\"%s\"}}}", EXPECTED_NAME);
        BigEntity result = JSON.parseObject(jsonString, BigEntity.class);
        assertEquals(EXPECTED_NAME, result.getMiddleEntity().getEntity().getName());
    }

    public static class ProxyReader implements ObjectReader {

        @Override
        public Object readObject(JSONReader jsonReader, Type type,
            Object o, long l) {
            var jsonObject = jsonReader.read(JSONObject.class);
            Class<?> clazz = (Class<?>) type;
            if (!clazz.isInterface()) {
                return jsonReader.read(type);
            }
            ClassLoader loader = Thread.currentThread().getContextClassLoader();
            return Proxy.newProxyInstance(loader, new Class<?>[] { clazz }, jsonObject);
        }
    }
}
```

```

java.lang.ClassCastException: class com.alibaba.fastjson2.JSONObject cannot be cast to class io.gitlab.donespeak.tutorial.InterfaceProxyTest$Entity (com.alibaba.fastjson2.JSONObject and io.gitlab.donespeak.tutorial.InterfaceProxyTest$Entity are in unnamed module of loader 'app')

	at io.gitlab.donespeak.tutorial.$Proxy8.getEntity(Unknown Source)
	at io.gitlab.donespeak.tutorial.InterfaceProxyTest.testDeserialize(InterfaceProxyTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

Disconnected from the target VM, address: '127.0.0.1:61035', transport: 'socket'

Process finished with exit code 255
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
