### ISSUE TITLE
[BUG]fastjson-version 2.0.12 异常，而 Fastjson2 2.0.11 版本是正常的。

### ISSUE THREAD

**Issue by lyhu** [alibaba/fastjson2#704]
### 问题描述
*fastjson-version 2.0.12 异常，而 Fastjson2 2.0.11 版本是正常的。业务代码没有修改，只做了fastjson2升级*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_251]
 - 版本信息：[e.g.：Fastjson2 2.0.12]
 

### 日志如下：

```text
08-22 20:58:04.717 -ERROR 20317[http-nio-2230-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet] [175]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.fastjson2.JSONException: expect ':', but ,, offset 18, character ", line 1, column 19, fastjson-version 2.0.12 {"code":0,"data":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY2MTE3MzY4NCwiY3JlYXRlZCI6MTY2MTE3MzA4NDcxNSwiYXV0aG9yaXRpZXMiOltdfQ.7u9FrI7lkKWTMz_u8llQrDNr_wRER9OP3KsiCG3DvmiE9OeGmK_IUREGNTswTFRQajYB3L5DUWyDq0oWRzcbfw","message":"成功"}] with root cause
10.
com.alibaba.fastjson2.JSONException: expect ':', but ,, offset 18, character ", line 1, column 19, fastjson-version 2.0.12 {"code":0,"data":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY2MTE3MzY4NCwiY3JlYXRlZCI6MTY2MTE3MzA4NDcxNSwiYXV0aG9yaXRpZXMiOltdfQ.7u9FrI7lkKWTMz_u8llQrDNr_wRER9OP3KsiCG3DvmiE9OeGmK_IUREGNTswTFRQajYB3L5DUWyDq0oWRzcbfw","message":"成功"}
11.
at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:842)
12.
at com.alibaba.fastjson2.reader.ObjectReader_5.readObject(Unknown Source)
13.
at com.alibaba.fastjson2.reader.ObjectReader_4.readObject(Unknown Source)
14.
at com.alibaba.fastjson2.JSON.parseObject(JSON.java:587)

```

### 期待的正确结果
*在v2.0.11 没有出现过这样的问题*

**Comment by wenshao** [comment]
类型信息能提供下么？
