### ISSUE TITLE
[BUG]时间格式错误，反序列化成LocalDateTime时空指针

### ISSUE THREAD

**Issue by HsinDumas** [alibaba/fastjson2#727]
### 问题描述
*时间格式错误，反序列化成LocalDateTime时空指针*

### 环境信息
*请填写以下信息：*

 - 版本信息：[e.g.：Fastjson2 2.0.12]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
         public static void main(String[] args) {
        System.out.println(JSON.parseObject("{\"dateTime\":\"20220-09-01 10:41:00\"}", Test.class));
    }
    @Data
    public static class Test{
        private LocalDateTime dateTime;
    }

```

### 期待的正确结果
*提示格式错误*

### 相关日志输出
*Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.fastjson2.JSONReader.readLocalDateTime(JSONReader.java:838)
	at com.alibaba.fastjson2.reader.ObjectReaderImplLocalDateTime.readObject(ObjectReaderImplLocalDateTime.java:57)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:459)*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，能够争取报错了，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
