### ISSUE TITLE
[BUG]toJavaObject在嵌套JsonObject时无法序列化

### ISSUE THREAD

**Issue by luomo1301532** [alibaba/fastjson2#728]
### 问题描述
*简要描述您碰到的问题。*
toJavaObject在嵌套JsonObject时无法序列化
在很多情况下，嵌套json里层会被转化成linkedHashMap，但是linkedHashMap转成jsonobject会遇到问题

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 Fastjson2 2.0.12

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
class TestClass
   private JSONObject data;

String a="{\"test\":\"123465\"}";

LinkedHashMap linkedHashMap = JSON.toJavaObject(a, LinkedHashMap.class);
JSONObject jsonObject =new JSONObject();
jsonObject.put("data",linkedHashMap);
System.out.println("a = " + linkedHashMap);

System.out.println("a = " + jsonObject.toJavaObject(TestClass.class));//报错

to

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
a = {test=123465}
Exception in thread "main" com.alibaba.fastjson2.JSONException: invoke constructor error, public com.iflytek.skylab.service.proxy.controller.TestClass2(com.alibaba.fastjson2.JSONObject)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:148)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:15)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstrutor.createInstanceNoneDefaultConstructor(ObjectReaderNoneDefaultConstrutor.java:53)
	at com.alibaba.fastjson2.reader.ObjectReaderNoneDefaultConstrutor.createInstance(ObjectReaderNoneDefaultConstrutor.java:327)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1189)
	at com.alibaba.fastjson2.JSONObject.toJavaObject(JSONObject.java:1201)
	at com.iflytek.skylab.service.proxy.controller.TestClass.main(TestClass.java:30)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.fastjson2.reader.ConstructorFunction.apply(ConstructorFunction.java:146)
	... 6 more

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
