### ISSUE TITLE
[BUG]StringSchema正则校验format字符串pattern not match, expect %, but %s错误

### ISSUE THREAD

**Issue by ai3forever** [alibaba/fastjson2#770]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：任何版本]
 - JDK信息： [e.g.：任何版本]
 - 版本信息：[e.g.：任何版本]
 

### 重现步骤
String类型校验正则失败时异常
查看StringSchema.java源码，发现format字符串错误%应该为%s，后面有附加截图

//可在此输入示例代码
```
public class MyTest {

    public static void main(String[] args) throws JsonProcessingException {
        String schemaStr = "{\n" +
                "  \"required\":[\"memory\"],\n" +
                "  \"properties\": {\n" +
                "    \"memory\": {\n" +
                "      \"type\":\"string\",\n" +
                "      \"pattern\": \"^([1-9][0-9]{0,1}|100)$\"\n" +
                "    }\n" +
                "  }\n" +
                "}";
        JSONObject js = JSONObject.of("memory", "101");
        JSONSchema jsonSchema = JSONSchema.parseSchema(schemaStr);
        ValidateResult vr = jsonSchema.validate(js);
        System.out.println(vr.isSuccess() + "====" + vr.getMessage());
    }
}
```

### 期待的正确结果
*正常获取到message信息*

### 相关日志输出

Exception in thread "main" java.util.FormatFlagsConversionMismatchException: Conversion = b, Flags =  
	at java.base/java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4422)
	at java.base/java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3151)
	at java.base/java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3109)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2870)
	at java.base/java.util.Formatter.parse(Formatter.java:2713)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.alibaba.fastjson2.schema.ValidateResult.getMessage(ValidateResult.java:42)
	at com.alibaba.fastjson2.schema.ValidateResult.getMessage(ValidateResult.java:44)
	at com.lixiang.licloud.oam.MyTest.main(MyTest.java:31)

#### 附加信息
![image](https://user-images.githubusercontent.com/15645774/190353683-624da27a-1a60-4d2b-928a-3df919f006d5.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.14-SNAPSHOT/
问题已修复，请用2.0.14-SNAPSHOT版本帮忙验证，2.0.14版本预计在9月17日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.14
问题已修复，请用新版本
