### ISSUE TITLE
[BUG] 对象包含Map添加WriteClassName 反序列化失败

### ISSUE THREAD

**Issue by aimilin6688** [alibaba/fastjson2#771]
### 问题描述
*简要描述您碰到的问题。*
对象中包含Map类型字段，设置写入类型，反序列化失败！

### 环境信息
*请填写以下信息：*

 - OS信息：  Max OS
 - JDK信息： 17.0.2,  1.8.0_311
 - 版本信息：2.0.13
 

### 重现步骤
*如何操作可以重现该问题：*

```java
@Data
public class User {

    // 开始时间
    private Date startTime;
    // 当前页
    private Integer pageNo;
    // 每页大小
    private Integer pageSize;
    // 已完成结果
    private Map<String, Integer> finishMap;

    public static void main(String[] args) {
        User startInfo = new User();
        startInfo.setStartTime(new Date());
        startInfo.setPageNo(1);
        startInfo.setPageSize(20);
        HashMap<String, Integer> map = new HashMap<>();
        map.put("111", 1);
        startInfo.setFinishMap(map);
        String s = JSON.toJSONString(startInfo, JSONWriter.Feature.WriteClassName);
        System.out.println(s);
        Object parse = JSON.parseObject(s, User.class, JSONReader.Feature.SupportAutoType);
        System.out.println(parse);
    }
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
输出结果：
```txt
{"@type":"com.entity.User","finishMap":{"@type":"java.util.HashMap","111":1},"pageNo":1,"pageSize":20,"startTime":"2022-09-15T18:41:06.083+08:00"}
Exception in thread "main" com.alibaba.fastjson2.JSONException: parseInt error, value : java.util.HashMap
	at com.alibaba.fastjson2.JSONReader.toInt32(JSONReader.java:2411)
	at com.alibaba.fastjson2.JSONReader.getInt32Value(JSONReader.java:528)
	at com.alibaba.fastjson2.JSONReaderUTF8.readInt32(JSONReaderUTF8.java:1976)
	at com.alibaba.fastjson2.reader.ObjectReaderImplInteger.readObject(ObjectReaderImplInteger.java:23)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:285)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.auoType(ObjectReaderAdapter.java:133)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:749)
	at com.jd.gxf.component.spare.dao.entity.User.main(User.java:41)
```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.14-SNAPSHOT/
问题已修复，请用2.0.14-SNAPSHOT版本帮忙验证，2.0.14版本预计在9月17日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.14
问题已修复，请用新版本
