### ISSUE TITLE
[BUG]使用JSONWriter.Feature.FieldBased配置后，如果有循环引用，会导致栈溢出

### ISSUE THREAD

**Issue by lirui-andy** [alibaba/fastjson2#772]
### 问题描述
使用JSONWriter.Feature.FieldBased配置后，如果有循环引用，会导致栈溢出

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：any]
 - JDK信息： [e.g.：any]
 - 版本信息：[e.g.：2.0.6]
 

### 重现步骤
见以下代码
```java
import org.junit.Test;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.filter.Filter;
import com.alibaba.fastjson2.filter.NameFilter;
import com.alibaba.fastjson2.filter.ValueFilter;
public class MyTest {
	@Test
	public void testCase(){
		NameFilter nameFilter = (o, s, o1) -> s;
		ValueFilter localDateFormatter1 = (o, s, source) -> {
			return source;
		};
		Filter[] defaultSerializeFilters = {nameFilter, localDateFormatter1};

		JSONWriter.Feature[] serializeFeatures = {
				/* 
				 * 基于字段序列化，如果不配置，会默认基于public的field和getter方法序列化。配置后，会基于非static的field（包括private）做反序列化。
				 * 注意:如果指定了filter，不配置此参数，IgnoreErrorGetter 会失效。
				 * */
				JSONWriter.Feature.FieldBased,
		};

		DataVO4 d = new DataVO4("0");
		DataVO4 d1 = new DataVO4("1");
		DataVO4 d2 = new DataVO4("2");
		d2.dv = d1;
		d1.dv = d;
		d.dv = d2;
		String json1 = JSON.toJSONString(d, "yyyy-MM-dd HH:mm:ss", defaultSerializeFilters, serializeFeatures);
		System.out.println(json1);
		String json2 = JSON.toJSONString(d);
		System.out.println(json2);
	}

	static class DataVO4 {
		DataVO4(String name){this.name = name;}
		String name;
		DataVO4 dv;
		
	}
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
java.lang.StackOverflowError
	at com.alibaba.fastjson2.JSONWriterUTF16.startObject(JSONWriterUTF16.java:67)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:323)
	at com.alibaba.fastjson2.writer.ObjectWriter_1.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.writeWithFilter(ObjectWriterAdapter.java:415)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本
