### ISSUE TITLE
[BUG] 时间戳为整形是反序列化为Date报错

### ISSUE THREAD

**Issue by logan2013** [alibaba/fastjson2#861]
### 问题描述
*简要描述您碰到的问题。*

Caused by: com.alibaba.fastjson2.JSONException: can not cast to Date from class java.lang.Integer
        at com.alibaba.fastjson2.util.TypeUtils.toDate(TypeUtils.java:116) ~[fastjson2-2.0.15.jar!/:na]
        at com.alibaba.fastjson2.util.TypeUtils.cast(TypeUtils.java:169) ~[fastjson2-2.0.15.jar!/:na]
        at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:111) ~[fastjson2-2.0.15.jar!/:na]
        at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1152) ~[fastjson2-2.0.15.jar!/:na]
        at com.tlsj.framwork.common.util.json.JsonUtils.parseObject(JsonUtils.java:73) ~[tlsj-common-1.2.1-SNAPSHOT.jar!/:na]
        at com.tlsj.framework.feign.core.consumer.UnwrapDecoder.decode(UnwrapDecoder.java:29) ~[tlsj-starter-feign-1.2.1-SNAPSHOT.jar!/:na]
        at feign.AsyncResponseHandler.decode(AsyncResponseHandler.java:115) ~[feign-core-10.12.jar!/:na]

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 
fastjson2-2.0.15

### 重现步骤
*如何操作可以重现该问题：*

A服务：从数据库查出来的json中包含字段"unbindOpenalipayTime":0（数据库的值为1970-01-01 08:00:00）
B服务调用A服务：将unbindOpenalipayTime反序列化，报错

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
问题已经修复，请用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月23日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本
