### ISSUE TITLE
[BUG]NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId

### ISSUE THREAD

**Issue by dlluotian** [alibaba/fastjson2#864]
### 问题描述
将Java对象序列化为JSON时，出现以下错误
 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
                                                                                                    	at com.alibaba.fastjson2.JSONWriter$Context.<clinit>(JSONWriter.java:1142)
                                                                                                    	at com.alibaba.fastjson2.JSON$-CC.toJSONString(JSON.java:2004)

但是使用1.1.72.android就不会出现任何错误

### 环境信息
 - OS信息：  [android 5.1.1]
 - JDK信息： [e.g.：Openjdk 11.0.13]
 - 版本信息：[e.g.：Fastjson2 2.0.16.android]

**Comment by dlluotian** [comment]
不好意思，没注意到fastjson2不支持api26以下的系统

**Comment by dlluotian** [comment]
不好意思，没注意到fastjson2不支持api26以下的系统

**Comment by wenshao** [comment]
要做支持的有成本，目前忙不过来
