### ISSUE TITLE
[BUG] Could not initialize class com.alibaba.fastjson.util.TypeUtils

### ISSUE THREAD

**Issue by tangzhichao** [alibaba/fastjson2#880]
### 问题描述
使用com.alibaba.fastjson.JSONObject.getLong报错java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.fastjson.util.TypeUtils

### 环境信息
 - OS信息：  win10
 - JDK信息： java8
 - 版本信息：fastjson 2.0.0
 

### 重现步骤
在@ServerEndpoint注解的websocket类中，使用com.alibaba.fastjson.JSONObject.getLong报错java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.fastjson.util.TypeUtils。

### 期待的正确结果
不报错正确返回。

### 相关日志输出
`java.lang.RuntimeException: Could not initialize class com.alibaba.fastjson.util.TypeUtils
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerBase.handlePojoMethodException(PojoMessageHandlerBase.java:119)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:82)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:395)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.fastjson.util.TypeUtils
	at com.alibaba.fastjson.JSONObject.getLong(JSONObject.java:260)
	at com.xxxx.open.front.websocket.WebSocketServer.onMessage(WebSocketServer.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80)
	... 18 common frames omitted
`

**Comment by wenshao** [comment]
升级到2.0.17版本试试看

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本
