### ISSUE TITLE
[QUESTION] 该如何解决 LocalDateTime 序列化后可变长度毫秒的问题？

### ISSUE THREAD

**Issue by huangluyu** [alibaba/fastjson2#890]
我在使用 LocalDateTime 作为全局日期格式时遇到了问题，序列化与反序列化的表现不统一。
因为我需求中需要毫秒，JSON.toJSONString 会保留毫秒，但是配置 FastJsonHttpMessageConverter 我不知道该如何配置毫秒。

#### 具体问题如下：
我把例子中的配置原封不动复制到我的项目中。
https://github.com/alibaba/fastjson2/blob/main/spring-test/src/main/java/com/alibaba/fastjson2/example/springtest/config/WebMvcConfigurer.java

例子中的格式化（包括 FastJsonConfig 的默认 dateTimeFomatter）是 yyyy-MM-dd HH:mm:ss，而我需要的是 yyyy-MM-dd HH:mm:ss.SSS。
 
当我使用 JSON.toJSONString 时，会获得 0 到 3 位长度的毫秒。如果我的毫秒是 0，例如日期数据 2022-11-02 09:46:16，这时 FastJsonHttpMessageConverter 就会报错。
```
java.time.format.DateTimeParseException: Text '2022-11-02 09:46:16' could not be parsed at index 19
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[na:1.8.0_321]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_321]
	at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[na:1.8.0_321]
	at com.alibaba.fastjson2.JSONReader.readLocalDateTime(JSONReader.java:897) ~[fastjson2-2.0.16.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderImplLocalDateTime.readObject(ObjectReaderImplLocalDateTime.java:57) ~[fastjson2-2.0.16.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1234) ~[fastjson2-2.0.16.jar:na]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.readType(FastJsonHttpMessageConverter.java:108) ~[fastjson2-extension-2.0.16.jar:na]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.read(FastJsonHttpMessageConverter.java:77) ~[fastjson2-extension-2.0.16.jar:na]
省略。。。
```

如果是用 Jackson，它的格式化应该是 yyyy-MM-dd HH:mm:ss[.SSS][.SS][.S]，我该如何在 FastJson2 中实现？

**Comment by huangluyu** [comment]
该问题即将关闭，我可能找到了最后的原因。

经过我的排查，我发现我的问题是  **Spring Web 的 `Controller` 返回数据时对 `LocalDateTime` 的序列化默认策略会丢失纳秒**，而接收时没有问题。

我发现 `FastJsonHttpMessageConverter` 中 `FastJsonConfig` 的默认 `dataFormatter` 是 `yyyy-MM-dd HH:mm:ss`，如果我把 `dataFormatter` 手动设置为 `null`，将完全符合我的预期。

这一点我是在浏览 `com.alibaba.fastjson2.JSON` 中 `static int writeTo(OutputStream out,
                       Object object,
                       String format,
                       Filter[] filters,
                       JSONWriter.Feature... features)` 方法时发现的。

我觉得这个默认的 `dataFormatter` 是导致了 `JSON.toJSONString` 与 `FastJsonHttpMessageConverter.write` 行为不一致的原因。

下面是一个测试用例。
**JDK8: 1.8.0_321
FastJson2: 2.0.16**

```
import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.support.config.FastJsonConfig;
import com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpInputMessage;
import org.springframework.http.HttpOutputMessage;
import org.springframework.http.MediaType;

import java.io.*;
import java.time.LocalDateTime;

public class LocalDateTimeFastJsonConvertTest {

    @Test
    void test_local_date_time() {
        LocalDateTime time1 = LocalDateTime.of(2022, 11, 3, 9, 54, 0,
                987654321);
        LocalDateTime time2 = LocalDateTime.of(2022, 11, 3, 9, 54, 0,
                654321);
        LocalDateTime time3 = LocalDateTime.of(2022, 11, 3, 9, 54, 0,
                1);
        LocalDateTime time4 = LocalDateTime.of(2022, 11, 3, 9, 54, 0,
                0);

        String timeStr1 = "\"2022-11-03 09:54:00.987654321\"";
        String timeStr2 = "\"2022-11-03 09:54:00.000654321\"";
        String timeStr3 = "\"2022-11-03 09:54:00.000000001\"";
        String timeStr4 = "\"2022-11-03 09:54:00\"";

        Assertions.assertEquals(timeStr1, JSON.toJSONString(time1));
        Assertions.assertEquals(timeStr2, JSON.toJSONString(time2));
        Assertions.assertEquals(timeStr3, JSON.toJSONString(time3));
        Assertions.assertEquals(timeStr4, JSON.toJSONString(time4));

        Assertions.assertEquals(time1, JSON.parseObject(timeStr1, LocalDateTime.class));
        Assertions.assertEquals(time2, JSON.parseObject(timeStr2, LocalDateTime.class));
        Assertions.assertEquals(time3, JSON.parseObject(timeStr3, LocalDateTime.class));
        Assertions.assertEquals(time4, JSON.parseObject(timeStr4, LocalDateTime.class));

        Assertions.assertEquals(time1, convertStrToTime(timeStr1));
        Assertions.assertEquals(time2, convertStrToTime(timeStr2));
        Assertions.assertEquals(time3, convertStrToTime(timeStr3));
        Assertions.assertEquals(time4, convertStrToTime(timeStr4));

        Assertions.assertEquals(timeStr1, convertTimeToString(time1));
        Assertions.assertEquals(timeStr2, convertTimeToString(time2));
        Assertions.assertEquals(timeStr3, convertTimeToString(time3));
        Assertions.assertEquals(timeStr4, convertTimeToString(time4));

    }

    public LocalDateTime convertStrToTime(String dateTimeStr) {
        FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
        // 无需指定 dateformatter 也没有问题

        try {
            return (LocalDateTime) converter.read(LocalDateTime.class, String.class, new HttpInputMessage() {
                @Override
                public InputStream getBody() {
                    return new ByteArrayInputStream(dateTimeStr.getBytes());
                }

                @Override
                public HttpHeaders getHeaders() {
                    return null;
                }
            });
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public String convertTimeToString(LocalDateTime dateTimeStr) {
        FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
        FastJsonConfig fastJsonConfig = new FastJsonConfig();
        // 去除下面这行，调用该方法的测试将不会通过
        fastJsonConfig.setDateFormat(null);
        converter.setFastJsonConfig(fastJsonConfig);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream(1000);
        try {
            converter.write(dateTimeStr, MediaType.APPLICATION_JSON, new HttpOutputMessage() {
                @Override
                public OutputStream getBody() {
                    return outputStream;
                }

                @Override
                public HttpHeaders getHeaders() {
                    HttpHeaders httpHeaders = new HttpHeaders();
                    httpHeaders.set(HttpHeaders.CONTENT_TYPE, String.valueOf(MediaType.APPLICATION_JSON));
                    return httpHeaders;
                }
            });
            return outputStream.toString();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
```
