### ISSUE TITLE
[BUG]小long类型自定义序列化失效

### ISSUE THREAD

**Issue by leonchen83** [alibaba/fastjson2#891]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息： windows10
 - JDK信息： jdk11
 - 版本信息：2.0.17
 
```java
package cn.nextop.gadget.json;

import java.lang.reflect.Type;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.reader.ObjectReader;
import com.alibaba.fastjson2.writer.ObjectWriter;

import cn.nextop.gadget.core.util.Objects;

/**
 * @author Baoyi Chen
 */
public class Main {
	public static void main(String[] args) {
		JSON.register(long.class, new ObjectWriter<Long>() {
			@Override
			public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
				Long value = (Long) object;
				if (value == null) jsonWriter.writeNull(); else jsonWriter.writeString(Long.toString(value));
			}
		});
		
		JSON.register(long.class, new ObjectReader<Long>() {

			@Override
			public Long readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
				final Object o = jsonReader.readAny();
				if (o instanceof String) return Objects.cast(Long.valueOf((String)o));
				throw new UnsupportedOperationException();
			}
		});

		Test t = new Test();
		t.setStatus(12345678L);
		System.out.println(JSON.toJSONString(t));
		
		String str = "{\"status\":\"12345678\"}";
		Test v = JSON.parseObject(str, Test.class);
		System.out.println(v.getStatus());
	}

	public static class Test {
		long status;

		public long getStatus() {
			return status;
		}

		public void setStatus(long status) {
			this.status = status;
		}
	}

}

```

实际输出
```
{"status":12345678}
12345678
```

期待输出
```
{"status":"12345678"}
12345678
```

debug发现没有进到自定义的serializer和deserializer

**Comment by leonchen83** [comment]
@wenshao 并且使用`System.out.println(JSON.toJSONString(t, JSONWriter.Feature.WriteLongAsString));`直接抛异常了
```java
Exception in thread "main" com.alibaba.fastjson2.JSONException: not support none serializable class cn.nextop.gadget.json.Main$Test
	at com.alibaba.fastjson2.writer.ObjectWriterAdapter.errorOnNoneSerializable(ObjectWriterAdapter.java:596)
	at com.alibaba.fastjson2.writer.ObjectWriter_1.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2245)
	at cn.nextop.gadget.json.Main.main(Main.java:54)

```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.18-SNAPSHOT/
WriteLongAsString的问题已修复，请帮忙用2.0.18-SNAPSHOT版本验证，2.0.18版本预计在11月底发布

**Comment by leonchen83** [comment]
@wenshao 不用`JSONWriter.Feature.WriteLongAsString`, 自定义的小long序列化器反序列化器仍然不好用

**Comment by wenshao** [comment]
这些内置类型要支持有额外开销的，你的需求如果能通过内置功能实现最好，WriteLongAsString不能满足要求么？

**Comment by leonchen83** [comment]
让用户自定义序列化反序列化覆盖默认行为是很正常的思路，也许把long 序列化为base64之类的，我不提这个issue也可能有其他人提出这个issue。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.18-SNAPSHOT/
问题已修复，请帮忙用2.0.18-SNAPSHOT版本验证，2.0.18版本预计在周末发布

**Comment by leonchen83** [comment]
@wenshao 
```java
package cn.nextop.gadget.json;

import java.lang.reflect.Type;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.reader.ObjectReader;
import com.alibaba.fastjson2.writer.ObjectWriter;

import cn.nextop.gadget.core.util.Objects;

/**
 * @author Baoyi Chen
 */
public class Main {
	public static void main(String[] args) {
		JSON.register(long.class, new ObjectWriter<Long>() {
			@Override
			public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
				Long value = (Long) object;
				if (value == null) jsonWriter.writeNull(); else jsonWriter.writeString(Long.toString(value));
			}
		});
		
		JSON.register(long.class, new ObjectReader<Long>() {

			@Override
			public Long readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
				final Object o = jsonReader.readAny();
				if (o instanceof String) return Objects.cast(Long.valueOf((String)o));
				throw new UnsupportedOperationException();
			}
		});

		Test t = new Test();
		t.setStatus(12345678L);
		t.setV2(new long[]{1234L, 4567L});
		System.out.println(JSON.toJSONString(t));
		
		String str = "{\"status\":\"12345678\"}";
		Test v = JSON.parseObject(str, Test.class);
		System.out.println(v.getStatus());
	}

	public static class Test {
		long status;
		long[] v2;

		public long getStatus() {
			return status;
		}

		public void setStatus(long status) {
			this.status = status;
		}

		public long[] getV2() {
			return v2;
		}

		public void setV2(long[] v2) {
			this.v2 = v2;
		}
	}

}
```
小long的序列化器和反序列化器是不是应该对long[]也生效呢。还是要写一个long[]的序列化器。目前看是不生效的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.18
问题已修复，请用新版本
