### ISSUE TITLE
[BUG] Mybatis-plus注解@TableField报错

### ISSUE THREAD

**Issue by atmJava** [alibaba/fastjson2#892]
### 问题描述
*简要描述您碰到的问题。*
实体类字段加上Mybatis-plus注解@TableField，反序列化时会报错

### 环境信息
*请填写以下信息：*

 - OS信息：windows10
 - JDK信息： 1.8
 - spring-boot版本信息：2.7.5
 -mybatis-plus版本：3.5.2

### 重现步骤
*如何操作可以重现该问题：

@Data
class SysUser
{
    private static final long serialVersionUID = 1L;

    /** 用户ID */
   @TableField(fill = FieldFill.INSERT)
    private String userName;
}

    public static void main(String[] args) {
        String json = "{\"userName\":\"hhhh\"}";

        SysUser sysUser = JSON.parseObject(json, SysUser.class);
        System.out.println(sysUser);
    }

报错信息：
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/ibatis/type/JdbcType
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:112)
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:109)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:109)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1153)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1151)
	at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:1139)
	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:207)
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule$ReaderAnnotationProcessor.getFieldInfo(ObjectReaderBaseModule.java:615)
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule$ReaderAnnotationProcessor.lambda$getFieldInfo$9(ObjectReaderBaseModule.java:710)
	at com.alibaba.fastjson2.util.BeanUtils.declaredFields(BeanUtils.java:280)
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule$ReaderAnnotationProcessor.getFieldInfo(ObjectReaderBaseModule.java:706)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReader(ObjectReaderCreator.java:960)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.lambda$createFieldReaders$4(ObjectReaderCreator.java:1129)
	at com.alibaba.fastjson2.util.BeanUtils.setters(BeanUtils.java:466)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createFieldReaders(ObjectReaderCreator.java:1126)
	at com.alibaba.fastjson2.reader.ObjectReaderCreator.createObjectReader(ObjectReaderCreator.java:663)
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:275)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:808)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:598)
	at com.phj.json.FastJsonTest.main(FastJsonTest.java:19)
Caused by: java.lang.ClassNotFoundException: org.apache.ibatis.type.JdbcType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 28 more

**Comment by atmJava** [comment]
fastjson为2.0.17，2.0.14

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.18-SNAPSHOT/
已经支持，请帮忙用2.0.18-SNAPSHOT版本验证，2.0.18版本预计在周末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.18
问题已修复，请用新版本
