### ISSUE TITLE
[BUG] 反序列化时报错，百分百复现。

### ISSUE THREAD

**Issue by jiangqiang1996** [alibaba/fastjson2#913]
### 问题描述
*简要描述您碰到的问题。*
序列化没问题，反序列化报错

### 环境信息
*请填写以下信息：*

 - JDK信息：jdk17
 

### 重现步骤
*如何操作可以重现该问题：*

直接运行下方代码
```java
package top.jiangqiang.module.cms.controller;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * @author Jiangqiang
 * @version 1.0
 * @description
 * @date 2022/11/9 10:54
 */
@Data
public class Test implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    private PathObj pathObj = new PathObj();

    @Data
    public static class PathObj implements Serializable {
        @Serial
        private static final long serialVersionUID = 1L;

        private final List<String> homePathList = CmsConstants.homePathList;

    }

    public static void main(String[] args) {
        System.out.println(toJsonStrWithClass(new Test()));
        System.out.println(parse(toJsonStrWithClass(new Test())));

    }

    public static final class CmsConstants {
        public final static List<String> homePathList = List.of("/index");
    }

    public static Object parse(String jsonStr, JSONReader.Feature... features) {
        ArrayList<JSONReader.Feature> tmpFeatures = new ArrayList<>(Arrays.stream(features).toList());
        tmpFeatures.add(JSONReader.Feature.SupportAutoType);
        return JSON.parseObject(jsonStr, Object.class, tmpFeatures.toArray(JSONReader.Feature[]::new));
    }
    public static String toJsonStrWithClass(Object object, JSONWriter.Feature... features) {
        ArrayList<JSONWriter.Feature> tmpFeatures = new ArrayList<>(Arrays.stream(features).toList());
        tmpFeatures.add(JSONWriter.Feature.WriteClassName);
        return JSON.toJSONString(object, tmpFeatures.toArray(new JSONWriter.Feature[0]));
    }
}

```

### 相关日志输出
```
D:\develop\Java\jdk-17.0.3.1\bin\java.exe --enable-preview -javaagent:C:\Users\Administrator\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29\lib\idea_rt.jar=59508:C:\Users\Administrator\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29\bin -Dfile.encoding=UTF-8 -classpath D:\Documents\IdeaProjects\QianYiCloud\qy-module-cms\target\classes;D:\Documents\IdeaProjects\QianYiCloud\qy-framework\qy-spring-boot-starter-system\target\classes;D:\Documents\IdeaProjects\QianYiCloud\qy-framework\qy-common\target\classes;D:\develop\repository\org\springframework\boot\spring-boot-starter-data-redis\3.0.0-M4\spring-boot-starter-data-redis-3.0.0-M4.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter\3.0.0-M4\spring-boot-starter-3.0.0-M4.jar;D:\develop\repository\org\springframework\boot\spring-boot\3.0.0-M4\spring-boot-3.0.0-M4.jar;D:\develop\repository\org\springframework\boot\spring-boot-autoconfigure\3.0.0-M4\spring-boot-autoconfigure-3.0.0-M4.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-logging\3.0.0-M4\spring-boot-starter-logging-3.0.0-M4.jar;D:\develop\repository\ch\qos\logback\logback-classic\1.2.11\logback-classic-1.2.11.jar;D:\develop\repository\ch\qos\logback\logback-core\1.2.11\logback-core-1.2.11.jar;D:\develop\repository\org\apache\logging\log4j\log4j-to-slf4j\2.18.0\log4j-to-slf4j-2.18.0.jar;D:\develop\repository\org\apache\logging\log4j\log4j-api\2.18.0\log4j-api-2.18.0.jar;D:\develop\repository\org\slf4j\jul-to-slf4j\1.7.36\jul-to-slf4j-1.7.36.jar;D:\develop\repository\jakarta\annotation\jakarta.annotation-api\2.0.0\jakarta.annotation-api-2.0.0.jar;D:\develop\repository\org\springframework\spring-core\6.0.0-M5\spring-core-6.0.0-M5.jar;D:\develop\repository\org\springframework\spring-jcl\6.0.0-M5\spring-jcl-6.0.0-M5.jar;D:\develop\repository\org\yaml\snakeyaml\1.30\snakeyaml-1.30.jar;D:\develop\repository\org\springframework\data\spring-data-redis\3.0.0-M5\spring-data-redis-3.0.0-M5.jar;D:\develop\repository\org\springframework\data\spring-data-keyvalue\3.0.0-M5\spring-data-keyvalue-3.0.0-M5.jar;D:\develop\repository\org\springframework\data\spring-data-commons\3.0.0-M5\spring-data-commons-3.0.0-M5.jar;D:\develop\repository\org\springframework\spring-oxm\6.0.0-M5\spring-oxm-6.0.0-M5.jar;D:\develop\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\develop\repository\io\lettuce\lettuce-core\6.2.0.RELEASE\lettuce-core-6.2.0.RELEASE.jar;D:\develop\repository\io\netty\netty-common\4.1.79.Final\netty-common-4.1.79.Final.jar;D:\develop\repository\io\netty\netty-handler\4.1.79.Final\netty-handler-4.1.79.Final.jar;D:\develop\repository\io\netty\netty-resolver\4.1.79.Final\netty-resolver-4.1.79.Final.jar;D:\develop\repository\io\netty\netty-buffer\4.1.79.Final\netty-buffer-4.1.79.Final.jar;D:\develop\repository\io\netty\netty-transport-native-unix-common\4.1.79.Final\netty-transport-native-unix-common-4.1.79.Final.jar;D:\develop\repository\io\netty\netty-codec\4.1.79.Final\netty-codec-4.1.79.Final.jar;D:\develop\repository\io\netty\netty-transport\4.1.79.Final\netty-transport-4.1.79.Final.jar;D:\develop\repository\io\projectreactor\reactor-core\3.5.0-M4\reactor-core-3.5.0-M4.jar;D:\develop\repository\org\reactivestreams\reactive-streams\1.0.4\reactive-streams-1.0.4.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-freemarker\3.0.0-M4\spring-boot-starter-freemarker-3.0.0-M4.jar;D:\develop\repository\org\freemarker\freemarker\2.3.31\freemarker-2.3.31.jar;D:\develop\repository\org\springframework\spring-context-support\6.0.0-M5\spring-context-support-6.0.0-M5.jar;D:\develop\repository\org\springframework\spring-beans\6.0.0-M5\spring-beans-6.0.0-M5.jar;D:\develop\repository\org\springframework\spring-context\6.0.0-M5\spring-context-6.0.0-M5.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-jdbc\3.0.0-M4\spring-boot-starter-jdbc-3.0.0-M4.jar;D:\develop\repository\com\zaxxer\HikariCP\5.0.1\HikariCP-5.0.1.jar;D:\develop\repository\org\springframework\spring-jdbc\6.0.0-M5\spring-jdbc-6.0.0-M5.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-quartz\3.0.0-M4\spring-boot-starter-quartz-3.0.0-M4.jar;D:\develop\repository\org\springframework\spring-tx\6.0.0-M5\spring-tx-6.0.0-M5.jar;D:\develop\repository\org\quartz-scheduler\quartz\2.3.2\quartz-2.3.2.jar;D:\develop\repository\com\mchange\mchange-commons-java\0.2.15\mchange-commons-java-0.2.15.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-security\3.0.0-M4\spring-boot-starter-security-3.0.0-M4.jar;D:\develop\repository\org\springframework\spring-aop\6.0.0-M5\spring-aop-6.0.0-M5.jar;D:\develop\repository\org\springframework\security\spring-security-config\6.0.0-M6\spring-security-config-6.0.0-M6.jar;D:\develop\repository\org\springframework\security\spring-security-core\6.0.0-M6\spring-security-core-6.0.0-M6.jar;D:\develop\repository\org\springframework\security\spring-security-crypto\6.0.0-M6\spring-security-crypto-6.0.0-M6.jar;D:\develop\repository\org\springframework\security\spring-security-web\6.0.0-M6\spring-security-web-6.0.0-M6.jar;D:\develop\repository\org\springframework\spring-expression\6.0.0-M5\spring-expression-6.0.0-M5.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-validation\3.0.0-M4\spring-boot-starter-validation-3.0.0-M4.jar;D:\develop\repository\org\apache\tomcat\embed\tomcat-embed-el\10.0.22\tomcat-embed-el-10.0.22.jar;D:\develop\repository\org\hibernate\validator\hibernate-validator\7.0.4.Final\hibernate-validator-7.0.4.Final.jar;D:\develop\repository\jakarta\validation\jakarta.validation-api\3.0.2\jakarta.validation-api-3.0.2.jar;D:\develop\repository\org\jboss\logging\jboss-logging\3.5.0.Final\jboss-logging-3.5.0.Final.jar;D:\develop\repository\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-web\3.0.0-M4\spring-boot-starter-web-3.0.0-M4.jar;D:\develop\repository\org\springframework\boot\spring-boot-starter-tomcat\3.0.0-M4\spring-boot-starter-tomcat-3.0.0-M4.jar;D:\develop\repository\org\apache\tomcat\embed\tomcat-embed-core\10.0.22\tomcat-embed-core-10.0.22.jar;D:\develop\repository\org\apache\tomcat\embed\tomcat-embed-websocket\10.0.22\tomcat-embed-websocket-10.0.22.jar;D:\develop\repository\org\springframework\spring-web\6.0.0-M5\spring-web-6.0.0-M5.jar;D:\develop\repository\org\springframework\spring-webmvc\6.0.0-M5\spring-webmvc-6.0.0-M5.jar;D:\develop\repository\org\projectlombok\lombok\1.18.24\lombok-1.18.24.jar;D:\develop\repository\cn\hutool\hutool-core\5.8.8\hutool-core-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-cron\5.8.8\hutool-cron-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-setting\5.8.8\hutool-setting-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-log\5.8.8\hutool-log-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-extra\5.8.8\hutool-extra-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-system\5.8.8\hutool-system-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-cache\5.8.8\hutool-cache-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-jwt\5.8.8\hutool-jwt-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-json\5.8.8\hutool-json-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-crypto\5.8.8\hutool-crypto-5.8.8.jar;D:\develop\repository\cn\hutool\hutool-http\5.8.8\hutool-http-5.8.8.jar;D:\develop\repository\com\github\whvcse\easy-captcha\1.6.2\easy-captcha-1.6.2.jar;D:\develop\repository\org\mapstruct\mapstruct\1.5.2.Final\mapstruct-1.5.2.Final.jar;D:\develop\repository\org\mapstruct\mapstruct-jdk8\1.5.2.Final\mapstruct-jdk8-1.5.2.Final.jar;D:\develop\repository\org\mapstruct\mapstruct-processor\1.5.2.Final\mapstruct-processor-1.5.2.Final.jar;D:\develop\repository\com\alibaba\fastjson2\fastjson2\2.0.14\fastjson2-2.0.14.jar;D:\develop\repository\com\alibaba\fastjson2\fastjson2-extension\2.0.14\fastjson2-extension-2.0.14.jar;D:\develop\repository\com\github\promeg\tinypinyin\2.0.3\tinypinyin-2.0.3.jar;D:\develop\repository\org\ahocorasick\ahocorasick\0.3.0\ahocorasick-0.3.0.jar;D:\develop\repository\org\jsoup\jsoup\1.15.3\jsoup-1.15.3.jar;D:\develop\repository\com\vdurmont\emoji-java\5.1.1\emoji-java-5.1.1.jar;D:\develop\repository\org\json\json\20170516\json-20170516.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-all\0.64.0\flexmark-all-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark\0.64.0\flexmark-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-abbreviation\0.64.0\flexmark-ext-abbreviation-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util\0.64.0\flexmark-util-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-admonition\0.64.0\flexmark-ext-admonition-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-anchorlink\0.64.0\flexmark-ext-anchorlink-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-aside\0.64.0\flexmark-ext-aside-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-attributes\0.64.0\flexmark-ext-attributes-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-autolink\0.64.0\flexmark-ext-autolink-0.64.0.jar;D:\develop\repository\org\nibor\autolink\autolink\0.6.0\autolink-0.6.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-definition\0.64.0\flexmark-ext-definition-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-emoji\0.64.0\flexmark-ext-emoji-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-enumerated-reference\0.64.0\flexmark-ext-enumerated-reference-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-escaped-character\0.64.0\flexmark-ext-escaped-character-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-footnotes\0.64.0\flexmark-ext-footnotes-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-gfm-issues\0.64.0\flexmark-ext-gfm-issues-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-gfm-strikethrough\0.64.0\flexmark-ext-gfm-strikethrough-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-gfm-tasklist\0.64.0\flexmark-ext-gfm-tasklist-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-gfm-users\0.64.0\flexmark-ext-gfm-users-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-gitlab\0.64.0\flexmark-ext-gitlab-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-jekyll-front-matter\0.64.0\flexmark-ext-jekyll-front-matter-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-jekyll-tag\0.64.0\flexmark-ext-jekyll-tag-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-media-tags\0.64.0\flexmark-ext-media-tags-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-resizable-image\0.64.0\flexmark-ext-resizable-image-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-macros\0.64.0\flexmark-ext-macros-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-ins\0.64.0\flexmark-ext-ins-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-xwiki-macros\0.64.0\flexmark-ext-xwiki-macros-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-superscript\0.64.0\flexmark-ext-superscript-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-tables\0.64.0\flexmark-ext-tables-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-toc\0.64.0\flexmark-ext-toc-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-typographic\0.64.0\flexmark-ext-typographic-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-wikilink\0.64.0\flexmark-ext-wikilink-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-yaml-front-matter\0.64.0\flexmark-ext-yaml-front-matter-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-ext-youtube-embedded\0.64.0\flexmark-ext-youtube-embedded-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-html2md-converter\0.64.0\flexmark-html2md-converter-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-jira-converter\0.64.0\flexmark-jira-converter-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-pdf-converter\0.64.0\flexmark-pdf-converter-0.64.0.jar;D:\develop\repository\com\openhtmltopdf\openhtmltopdf-core\1.0.10\openhtmltopdf-core-1.0.10.jar;D:\develop\repository\com\openhtmltopdf\openhtmltopdf-pdfbox\1.0.10\openhtmltopdf-pdfbox-1.0.10.jar;D:\develop\repository\org\apache\pdfbox\pdfbox\2.0.24\pdfbox-2.0.24.jar;D:\develop\repository\org\apache\pdfbox\fontbox\2.0.24\fontbox-2.0.24.jar;D:\develop\repository\org\apache\pdfbox\xmpbox\2.0.24\xmpbox-2.0.24.jar;D:\develop\repository\de\rototor\pdfbox\graphics2d\0.32\graphics2d-0.32.jar;D:\develop\repository\com\openhtmltopdf\openhtmltopdf-rtl-support\1.0.10\openhtmltopdf-rtl-support-1.0.10.jar;D:\develop\repository\com\ibm\icu\icu4j\59.1\icu4j-59.1.jar;D:\develop\repository\com\openhtmltopdf\openhtmltopdf-jsoup-dom-converter\1.0.0\openhtmltopdf-jsoup-dom-converter-1.0.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-profile-pegdown\0.64.0\flexmark-profile-pegdown-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-ast\0.64.0\flexmark-util-ast-0.64.0.jar;D:\develop\repository\org\jetbrains\annotations\15.0\annotations-15.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-builder\0.64.0\flexmark-util-builder-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-collection\0.64.0\flexmark-util-collection-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-data\0.64.0\flexmark-util-data-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-dependency\0.64.0\flexmark-util-dependency-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-format\0.64.0\flexmark-util-format-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-html\0.64.0\flexmark-util-html-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-misc\0.64.0\flexmark-util-misc-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-options\0.64.0\flexmark-util-options-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-sequence\0.64.0\flexmark-util-sequence-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-util-visitor\0.64.0\flexmark-util-visitor-0.64.0.jar;D:\develop\repository\com\vladsch\flexmark\flexmark-youtrack-converter\0.64.0\flexmark-youtrack-converter-0.64.0.jar;D:\Documents\IdeaProjects\QianYiCloud\qy-framework\qy-spring-boot-starter-storage\target\classes;D:\Documents\IdeaProjects\QianYiCloud\qy-framework\qy-spring-boot-starter-core\target\classes;D:\Documents\IdeaProjects\QianYiCloud\qy-framework\qy-spring-boot-starter-database\target\classes;D:\develop\repository\mysql\mysql-connector-java\8.0.29\mysql-connector-java-8.0.29.jar;D:\develop\repository\com\alibaba\druid-spring-boot-starter\1.2.13\druid-spring-boot-starter-1.2.13.jar;D:\develop\repository\com\alibaba\druid\1.2.13\druid-1.2.13.jar;D:\develop\repository\com\baomidou\mybatis-plus-boot-starter\3.5.2.4-SNAPSHOT\mybatis-plus-boot-starter-3.5.2.4-SNAPSHOT.jar;D:\develop\repository\com\baomidou\mybatis-plus\3.5.2.4-SNAPSHOT\mybatis-plus-3.5.2.4-SNAPSHOT.jar;D:\develop\repository\com\baomidou\mybatis-plus-extension\3.5.2.4-SNAPSHOT\mybatis-plus-extension-3.5.2.4-SNAPSHOT.jar;D:\develop\repository\com\baomidou\mybatis-plus-core\3.5.2.4-SNAPSHOT\mybatis-plus-core-3.5.2.4-SNAPSHOT.jar;D:\develop\repository\com\baomidou\mybatis-plus-annotation\3.5.2.4-SNAPSHOT\mybatis-plus-annotation-3.5.2.4-SNAPSHOT.jar;D:\develop\repository\com\github\jsqlparser\jsqlparser\4.4\jsqlparser-4.4.jar;D:\develop\repository\org\mybatis\mybatis\3.5.10\mybatis-3.5.10.jar;D:\develop\repository\org\mybatis\mybatis-spring\2.0.7\mybatis-spring-2.0.7.jar;D:\develop\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.7.10\kotlin-stdlib-jdk8-1.7.10.jar;D:\develop\repository\org\jetbrains\kotlin\kotlin-stdlib\1.7.10\kotlin-stdlib-1.7.10.jar;D:\develop\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.7.10\kotlin-stdlib-common-1.7.10.jar;D:\develop\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.7.10\kotlin-stdlib-jdk7-1.7.10.jar;D:\develop\repository\com\aliyun\oss\aliyun-sdk-oss\3.15.2\aliyun-sdk-oss-3.15.2.jar;D:\develop\repository\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;D:\develop\repository\org\apache\httpcomponents\httpcore\4.4.15\httpcore-4.4.15.jar;D:\develop\repository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;D:\develop\repository\org\jdom\jdom2\2.0.6.1\jdom2-2.0.6.1.jar;D:\develop\repository\org\codehaus\jettison\jettison\1.1\jettison-1.1.jar;D:\develop\repository\stax\stax-api\1.0.1\stax-api-1.0.1.jar;D:\develop\repository\com\aliyun\aliyun-java-sdk-core\4.5.10\aliyun-java-sdk-core-4.5.10.jar;D:\develop\repository\com\google\code\gson\gson\2.9.0\gson-2.9.0.jar;D:\develop\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\develop\repository\javax\xml\bind\jaxb-api\2.3.1\jaxb-api-2.3.1.jar;D:\develop\repository\javax\activation\javax.activation-api\1.2.0\javax.activation-api-1.2.0.jar;D:\develop\repository\org\jacoco\org.jacoco.agent\0.8.5\org.jacoco.agent-0.8.5-runtime.jar;D:\develop\repository\org\ini4j\ini4j\0.5.4\ini4j-0.5.4.jar;D:\develop\repository\io\opentracing\opentracing-api\0.33.0\opentracing-api-0.33.0.jar;D:\develop\repository\io\opentracing\opentracing-util\0.33.0\opentracing-util-0.33.0.jar;D:\develop\repository\io\opentracing\opentracing-noop\0.33.0\opentracing-noop-0.33.0.jar;D:\develop\repository\com\aliyun\aliyun-java-sdk-ram\3.1.0\aliyun-java-sdk-ram-3.1.0.jar;D:\develop\repository\com\aliyun\aliyun-java-sdk-kms\2.11.0\aliyun-java-sdk-kms-2.11.0.jar top.jiangqiang.module.cms.controller.Test
{"@type":"top.jiangqiang.module.cms.controller.Test","pathObj":{"homePathList":["/index"]}}
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147)
	at com.alibaba.fastjson2.reader.FieldReaderCollectionMethodReadOnly.accept(FieldReaderCollectionMethodReadOnly.java:87)
	at com.alibaba.fastjson2.reader.FieldReaderCollectionMethodReadOnly.readFieldValue(FieldReaderCollectionMethodReadOnly.java:110)
	at com.alibaba.fastjson2.reader.ObjectReader1.readObject(ObjectReader1.java:277)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:117)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:749)
	at top.jiangqiang.module.cms.controller.Test.parse(Test.java:49)
	at top.jiangqiang.module.cms.controller.Test.main(Test.java:38)

进程已结束,退出代码1

```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本
