### ISSUE TITLE
kotlin 在序列化Any类型时报错 [BUG]

### ISSUE THREAD

**Issue by XiaoyuZhann** [alibaba/fastjson2#953]
### 问题描述
*简要描述您碰到的问题。*
kotlin 在序列化Any类型时报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：fastjson2-kotlin:2.0.19]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `.toJSONString()` 方法
2. 序列化如下对象：
 `data class Instruction(
    var send: String = "",
    var receive: String = "",
    var instruct: String = "",
    var content: MutableList<Content> = mutableListOf()
)`
`data class Content(
    var path: String = "",
    var mack: String = "",
    var content: Any = ""
)`  
4. 出现 `java.lang.ExceptionInInitializerError` 错误
```java
//可在此输入示例代码
data class Instruction(
    var send: String = "",
    var receive: String = "",
    var instruct: String = "",
    var content: MutableList<Content> = mutableListOf()
)
data class Content(
    var path: String = "",
    var mack: String = "",
    var content: Any = ""
)
fun(content:Any){
    Instruction().content.add(
            Content().apply {
                path = property.path
                mack = property.mack
                this.content = content
            }
        )
    instruction.toJSONString()
}

```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.sproutapp, PID: 4794
    java.lang.ExceptionInInitializerError
        at com.alibaba.fastjson2.writer.FieldWriterList.<init>(FieldWriterList.java:43)
        at com.alibaba.fastjson2.writer.FieldWriterListMethod.<init>(FieldWriterListMethod.java:26)
        at com.alibaba.fastjson2.writer.ObjectWriterCreator.createFieldWriter(ObjectWriterCreator.java:899)
        at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.lambda$createObjectWriter$2$com-alibaba-fastjson2-writer-ObjectWriterCreatorASM(ObjectWriterCreatorASM.java:332)
        at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM$$ExternalSyntheticLambda2.accept(Unknown Source:19)
        at com.alibaba.fastjson2.util.BeanUtils.getters(BeanUtils.java:838)
        at com.alibaba.fastjson2.writer.ObjectWriterCreatorASM.createObjectWriter(ObjectWriterCreatorASM.java:241)
        at com.alibaba.fastjson2.writer.ObjectWriterProvider.getObjectWriter(ObjectWriterProvider.java:239)
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2182)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by XiaoyuZhann** [comment]
抱歉，我用错包了，我是在Android里面，换成Android的包就行了
