### ISSUE TITLE
[BUG]使用mvn T126 test在fastjson@2.0.19测试失败报错

### ISSUE THREAD

**Issue by Tom-python0121** [alibaba/fastjson2#973]
### 问题描述
*简要描述您碰到的问题。*

使用mvn T126 test在fastjson@2.0.19测试失败报错
### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 4.18.0-193.el8.aarch64]
 - JDK信息： [e.g.：Openjdk 1.8.0_191]
 - 版本信息：[e.g.：Fastjson2 2.0.19]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
[root@localhost src]#mvn -T126 test
……
[INFO]
[ERROR] Failures:
[ERROR]   JSONPathValueConsumerTest2.test_extract_scalar_str_1:173 expected: <)123????> but was: <)123????????????>
[ERROR]   JSONReaderTest1.testDates:1555 expected: <-1600671600000> but was: <-1600675200000>
[ERROR]   JSONReaderTest1.testMillis_shanghai:1849->validate:1904 1991-09-15T00:00 ==> expected: <684864000000> but was: <684860400000>
[ERROR]   StringTest1.test_0:17 expected: <??> but was: <?????>
[ERROR]   IOUtilsTest.encodeUTF8:38 expected: <??????> but was: <?????????????????????>
[ERROR]   Issue1140.test_for_issue:22 expected: <"??"> but was: <"????????">
[INFO]
[ERROR] Tests run: 4794, Failures: 6, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for fastjson2-parent 2.0.19:
[INFO]
[INFO] fastjson2-parent ................................... SUCCESS [  2.154 s]
[INFO] fastjson2 .......................................... FAILURE [01:41 min]
[INFO] fastjson2-benchmark ................................ SKIPPED
[INFO] fastjson2-extension ................................ SKIPPED
[INFO] fastjson1-compatible ............................... SKIPPED
[INFO] fastjson2-kotlin ................................... SKIPPED
[INFO] spring-test ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:44 min (Wall Clock)
[INFO] Finished at: 2022-11-28T16:32:11+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project fastjson2: There are test failures.
[ERROR]
[ERROR] Please refer to /home/stage/root/spack-stage-fastjson-2.0.19-jvgv6ladw4p4s4gjmxfqolcnyi7ho6db/spack-src/core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :fastjson2
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
希望测试通过

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
-T126是测试什么场景啊

**Comment by Tom-python0121** [comment]
@wenshao -T126是多进程，这个是软件移植，就是在centos8_aarch64系统中进行正常的软件安装，然后进行测试，之后就报错了

**Comment by wenshao** [comment]
我在MacOS 13.0.1下执行
```
mvn -T126 test
```
运行是成功的

**Comment by Tom-python0121** [comment]
@wenshao 我这个环境是linux 中的，两者不太一样吧，你那边使用的openjdk版本是啥

**Comment by wenshao** [comment]
我在Linux下重现了这个问题，但还不知道什么原因，哪里文档能看到-T126是什么含义么？

**Comment by Tom-python0121** [comment]
@wenshao  mvn -h就会报-T后面多线程啊

**Comment by wenshao** [comment]
要修复的，只是还没找到原因，我们的build test都是跑在LInux下的，比如 https://github.com/alibaba/fastjson2/actions/runs/3584229800

**Comment by Tom-python0121** [comment]
好的，那我等修复吧

**Comment by wenshao** [comment]
@Tom-python0121 已经修复，是系统缺省编码的问题。兼容包中文的测试类在这个参数下跑不过，这没办法了，为什么要加-T呢？

**Comment by Tom-python0121** [comment]
@wenshao 可是我拉下main版本，然后mvn test还是继续报错
### Steps to reproduce the issue

```console
[root@bigdata src]# uname -a
Linux bigdata 4.18.0-408.el8.aarch64 #1 SMP Mon Jul 18 15:47:44 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
[root@bigdata src]# mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 1.8.0_191, vendor: AdoptOpenJdk, runtime: /home/linux-centos8-aarch64/gcc-8.5.0/openjdk-1.8.0_191-b12-2pvowqoqg3nu7kwaohs6rux7tpwftzwy/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.18.0-408.el8.aarch64", arch: "aarch64", family: "unix"
[root@bigdata src]# mvn test
……
[ERROR] Tests run: 79, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 34.399 s <<< FAILURE! - in com.alibaba.fastjson2.JSONReaderTest1
[ERROR] com.alibaba.fastjson2.JSONReaderTest1.testDates  Time elapsed: 1.998 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <-1600671600000> but was: <-1600675200000>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
……
[ERROR] com.alibaba.fastjson2.JSONReaderTest1.testMillis_shanghai  Time elapsed: 0.367 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 1991-09-15T00:00 ==> expected: <684864000000> but was: <684860400000>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
……
[INFO]
[ERROR] Failures:
[ERROR]   JSONReaderTest1.testDates:1555 expected: <-1600671600000> but was: <-1600675200000>
[ERROR]   JSONReaderTest1.testMillis_shanghai:1849->validate:1904 1991-09-15T00:00 ==> expected: <684864000000> but was: <684860400000>
[INFO]
[ERROR] Tests run: 4985, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for fastjson2-parent 2.0.21-SNAPSHOT:
[INFO]
[INFO] fastjson2-parent ................................... SUCCESS [  2.855 s]
[INFO] fastjson2 .......................................... FAILURE [02:31 min]
[INFO] fastjson2-extension ................................ SKIPPED
[INFO] adapter ............................................ SKIPPED
[INFO] fastjson2-benchmark ................................ SKIPPED
[INFO] fastjson1-compatible ............................... SKIPPED
[INFO] fastjson2-kotlin ................................... SKIPPED
[INFO] spring-test ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:34 min
[INFO] Finished at: 2022-12-02T15:06:46+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project fastjson2: There are test failures.
[ERROR]
[ERROR] Please refer to /home/stage/root/src/core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :fastjson2
```
好像没有效果，修复好像不全

**Comment by wenshao** [comment]
问题已经修复，你再验证下

**Comment by wenshao** [comment]
去掉-T126来跑测试不可以么？

**Comment by Tom-python0121** [comment]
@wenshao 我就是去掉-T126参数的呀，上面显示我只用了mvn test测试

**Comment by wenshao** [comment]
```
Maven home: /root/Install/maven
Java version: 17.0.3.1, vendor: Oracle Corporation, runtime: /root/Install/jdk-17.0.3.1_aarch64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.18.0-348.23.1.an8_5.aarch64", arch: "aarch64", family: "unix"
```
我再上面的环境，和在MacOS下都无法重现问题

**Comment by wenshao** [comment]
@Tom-python0121 我这里没办法重现，你本地如果能重现，可以帮忙调试找问题么？

**Comment by Tom-python0121** [comment]
@wenshao 好的，我用mvn命令调试调试看看

**Comment by Tom-python0121** [comment]
debug log:
[test-suite.log](https://github.com/alibaba/fastjson2/files/10214054/test-suite.log)

**Comment by wenshao** [comment]
在IDE中单跑这个会报错么？如果可以，调试进取看下什么原因

**Comment by Tom-python0121** [comment]
@wenshao 我没有IDE环境

**Comment by Tom-python0121** [comment]
the test have passed,I will close the issuse.
