### ISSUE TITLE
[QUESTION] no problem

### ISSUE THREAD

**Issue by ybbhai** [alibaba/fastjson2#974]

**Comment by ybbhai** [comment]
> redis serializer配置：
> 
> ```
> public class FastJson2JsonRedisSerializer<T> implements RedisSerializer<T> {
>     public static final Charset DEFAULT_CHARSET = StandardCharsets.UTF_8;
> 
>     private Class<T> clazz;
> 
>     public FastJson2JsonRedisSerializer(Class<T> clazz) {
>         super();
>         this.clazz = clazz;
>     }
> 
>     @Override
>     public byte[] serialize(T t) throws SerializationException {
>         if (t == null) {
>             return new byte[0];
>         }
>         return JSON.toJSONString(t, JSONWriter.Feature.WriteClassName).getBytes(DEFAULT_CHARSET);
>     }
> 
>     @Override
>     public T deserialize(byte[] bytes) throws SerializationException {
>         if (bytes == null || bytes.length <= 0) {
>             return null;
>         }
>         String str = new String(bytes, DEFAULT_CHARSET);
> 
>         return JSON.parseObject(str, clazz, JSONReader.Feature.SupportAutoType);
>     }
> }
> 
> 存取对象类定义：
> LoginUser:
> ```
> 
> @DaTa public class LoginUser implements UserDetails { private static final long serialVersionUID = 1L;
> 
> ```
> /**
>  * 用户ID
>  */
> private Long id;
> 
> /**
>  * 部门ID
>  */
> private Long deptId;
> 
> /**
>  * 用户唯一标识
>  */
> private String token;
> 
> /**
>  * 登录时间
>  */
> private Long loginTime;
> 
> /**
>  * 过期时间
>  */
> private Long expireTime;
> 
> /**
>  * 登录IP地址
>  */
> private String ipaddr;
> 
> /**
>  * 登录地点
>  */
> private String loginLocation;
> 
> /**
>  * 浏览器类型
>  */
> private String browser;
> 
> /**
>  * 操作系统
>  */
> private String os;
> 
> /**
>  * 资源列表
>  */
> private Set<String> resources;
> 
> /**
>  * 用户信息
>  */
> private UserEntity user;
> ```
> 
> }`
> 
> UserEntity: `public class UserEntity extends BaseEntity {
> 
> ```
> /**
>  * 邀请人ID
>  */
> @TableField("invitor_id")
> private Long invitorId;
> 
> /**
>  * 用户名
>  */
> @TableField("user_name")
> private String userName;
> ```
> 
> }`
> 
> baseEntity: @DaTa public class BaseEntity implements Serializable { /** * 主键ID */ private Long id;
> 
> ```
> /**
>  * 创建用户
>  */
> @TableField(fill = FieldFill.INSERT)
> private Long createUser;
> 
> /**
>  * 创建时间
>  */
> @TableField(fill = FieldFill.INSERT)
> private LocalDateTime createTime;
> ```
> 
> }
> 
> 报错信息： `com.alibaba.fastjson2.JSONException: set authorities error at com.alibaba.fastjson2.reader.FieldReaderCollectionMethodReadOnly.accept(FieldReaderCollectionMethodReadOnly.java:48) at com.alibaba.fastjson2.reader.FieldReaderCollectionMethodReadOnly.readFieldValue(FieldReaderCollectionMethodReadOnly.java:110) at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:235) at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:87) at com.alibaba.fastjson2.JSON.parseObject(JSON.java:637)`

没问题了，找到原因了
