### ISSUE TITLE
[BUG]Android8.0以下

### ISSUE THREAD

**Issue by wandersnail** [alibaba/fastjson2#988]
### 问题描述
*简要描述您碰到的问题。*
Android8.0以下不支持

 - OS信息： Android7.0
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

```java
JSON.parseObject()
```

### 相关日志输出
2022-12-02 15:11:43.796  5015-5015  art                                I    Rejecting re-init on previously-failed class java.lang.Class<com.alibaba.fastjson.JSON>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalTime;
2022-12-02 15:11:43.796  5015-5015  art                                I    at void com.alibaba.fastjson2.writer.ObjectWriterProvider.<clinit>() (ObjectWriterProvider.java:240)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void com.alibaba.fastjson2.JSONFactory.<clinit>() (JSONFactory.java:352)
2022-12-02 15:11:43.796  5015-5015  art                                I    at com.alibaba.fastjson2.reader.ObjectReaderProvider com.alibaba.fastjson2.JSONFactory.getDefaultObjectReaderProvider() (JSONFactory.java:455)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void com.alibaba.fastjson.JSON.<clinit>() (JSON.java:76)
2022-12-02 15:11:43.796  5015-5015  art                                I    at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
2022-12-02 15:11:43.796  5015-5015  art                                I    at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
2022-12-02 15:11:43.796  5015-5015  art                                I    at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
2022-12-02 15:11:43.796  5015-5015  art                                I    at boolean cn.wandersnail.http.converter.JsonResponseConverter.isFastjsonSupported() (JsonResponseConverter.java:72)
2022-12-02 15:11:43.796  5015-5015  art                                I    at java.lang.Object cn.wandersnail.http.converter.JsonResponseConverter.convert(okhttp3.ResponseBody) (JsonResponseConverter.java:52)
2022-12-02 15:11:43.796  5015-5015  art                                I    at java.lang.Object cn.wandersnail.http.converter.JsonResponseConverter.convert(java.lang.Object) (JsonResponseConverter.java:18)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void cn.wandersnail.http.GeneralRequestTask.lambda$doRequest$0$cn-wandersnail-http-GeneralRequestTask(java.lang.Runnable, cn.wandersnail.http.callback.RequestCallback, retrofit2.Converter, retrofit2.Response) (GeneralRequestTask.java:49)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void cn.wandersnail.http.GeneralRequestTask$$ExternalSyntheticLambda0.accept(java.lang.Object) (D8$$SyntheticClass:-1)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal() (ObservableObserveOn.java:201)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run() (ObservableObserveOn.java:255)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run() (HandlerScheduler.java:124)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
2022-12-02 15:11:43.796  5015-5015  art                                I    at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)

**Comment by wenshao** [comment]
由于使用到java.time api，支持Android低版本需要较大工作量，所以没有做

**Comment by andrewliu1345** [comment]
遇到同样问题~  只能换回1.2.83了。
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalTime;
                                                                                                    	at com.alibaba.fastjson2.writer.ObjectWriterProvider.<clinit>(ObjectWriterProvider.java:155)
                                                                                                    	at com.alibaba.fastjson2.JSONFactory.<clinit>(JSONFactory.java:270)
                                                                                                    	at com.alibaba.fastjson2.JSONFactory.getDefaultObjectReaderProvider(JSONFactory.java:294)
                                                                                                    	at com.alibaba.fastjson.JSON.<clinit>(JSON.java:56)
                                                                                                    	at com.alibaba.fastjson.JSON.parseObject(JSON.java)
