### ISSUE TITLE
时间格式转化问题

### ISSUE THREAD

**Issue by mikePengW** [alibaba/fastjson2#991]
### 问题描述
输入时间字符串为：2022-12-06 10:05:56
反序列化为时间格式时：出现报错源码中是如下
![image](https://user-images.githubusercontent.com/13198764/205792357-55e39f74-f403-4f3e-ba9b-7e487881c861.png)
烦请查看并解决一下谢谢！

**Comment by mikePengW** [comment]
`
public static void main(String[] args) {
        String str = "2022-12-06 10:05:56";
        Date date = DateUtils.parseDate(str);
        System.out.println(date.toString());
}
`
执行以上代码亦然出现同样的报错：
`
Exception in thread "main" java.time.format.DateTimeParseException: illegal input
	at com.alibaba.fastjson2.util.DateUtils.toMillis19(DateUtils.java:2289)
	at com.alibaba.fastjson2.util.DateUtils.parseDate(DateUtils.java:41)	
`
麻烦修复一下谢谢！

**Comment by mikePengW** [comment]
刚刚更新后，最新版已经解决了该问题了。
