### ISSUE TITLE
[BUG] json字符串中的需要反序列化字段是个对象，但是传入值为空字符时候解析出错

### ISSUE THREAD

**Issue by mystox** [alibaba/fastjson2#998]
### 问题描述
json字符串中的需要反序列化字段是个对象，但是传入值为空字符时候解析出错

### 环境信息
 - 版本信息：[e.g.：Fastjson2 2.0.20]
 
### 重现步骤

{"cloudServiceName":"xxx","enterpriseCode":"xxx","enterpriseName":"xxx","serviceCode":"IT_MONITOR_MANAGER_SYSTEM","cloudStyle":""}

```java实体如下
public class EnterpriseCloudServiceVO {

    private String enterpriseCode;
    private String enterpriseName;
    private String serviceCode;
    private String cloudServiceName;
    private CloudStyle cloudStyle;
    ...省略getter setter
}
public class CloudStyle implements Serializable {
    private Integer modelId;
    public Integer getModelId() {
        return modelId;
    }
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }
}
    public static void main(String[] args) {
         String str = "{\"cloudServiceName\":\"xxx\",\"enterpriseCode\":\"xxx\",\"enterpriseName\":\"xxx\",\"serviceCode\":\"IT_MONITOR_MANAGER_SYSTEM\",\"cloudStyle\":\"\"}";
        EnterpriseCloudServiceVO enterpriseCloudServiceVO = JSONObject.parseObject(str, EnterpriseCloudServiceVO.class);
    }
```

### 期待的正确结果
正确解析

### 相关日志输出
Exception in thread "main" com.alibaba.fastjson2.JSONException: expect ':', but }, offset 128, character ", line 1, column 129, fastjson-version 2.0.20 {"cloudServiceName":"xxx","enterpriseCode":"xxx","enterpriseName":"xxx","serviceCode":"IT_MONITOR_MANAGER_SYSTEM","cloudStyle":""}
	at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:1312)
	at com.alibaba.fastjson2.reader.ObjectReader_2.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:807)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1859)
	at com.itime.center.manage.model.vo.EnterpriseCloudServiceVO.main(EnterpriseCloudServiceVO.java:34)

**Comment by TanZhiL** [comment]
> cloudStyle

@mystox 你的问题修复了吗？

**Comment by TanZhiL** [comment]
当处理的字段类型内部带有一个以上的字段时，还是不行哦，比如：
public class CloudStyle implements Serializable {
    private Integer modelId;
    private Integer modelId1;
    public Integer getModelId() {
        return modelId;
    }
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    public Integer getModelId1() {
        return modelId1;
    }

    public void setModelId1(Integer modelId1) {
        this.modelId1 = modelId1;
    }
}

> https://github.com/alibaba/fastjson2/releases/tag/2.0.21 问题已修复，请用新版本
